; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -force-vector-width=4 -S %s | FileCheck %s

; Test that vectorizing the second loop does not crash due to reusing a zext
; instruction from the first loop's preheader that does not dominate the second
; loop's preheader.

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx10.8.0"

@b = common global [2048 x i32] zeroinitializer, align 16
@c = common global [2048 x i32] zeroinitializer, align 16
@a = common global [2048 x i32] zeroinitializer, align 16

define void @scev_reuse_non_dominating(i32 %n, i32 %x) optsize {
; CHECK-LABEL: define void @scev_reuse_non_dominating(
; CHECK-SAME: i32 [[N:%.*]], i32 [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[N]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP1_PREHEADER:.*]], label %[[PREHEADER:.*]]
; CHECK:       [[LOOP1_PREHEADER]]:
; CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[N]] to i64
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_RND_UP:%.*]] = add i64 [[TMP0]], 3
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N_RND_UP]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N_RND_UP]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TRIP_COUNT_MINUS_1:%.*]] = sub i64 [[TMP0]], 1
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TRIP_COUNT_MINUS_1]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE6:.*]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <4 x i64> [ <i64 0, i64 1, i64 2, i64 3>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[PRED_STORE_CONTINUE6]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule <4 x i64> [[VEC_IND]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i1> [[TMP1]], i32 0
; CHECK-NEXT:    br i1 [[TMP2]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE:.*]]
; CHECK:       [[PRED_STORE_IF]]:
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 [[INDEX]]
; CHECK-NEXT:    store i32 [[X]], ptr [[TMP3]], align 4
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE]]
; CHECK:       [[PRED_STORE_CONTINUE]]:
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i1> [[TMP1]], i32 1
; CHECK-NEXT:    br i1 [[TMP4]], label %[[PRED_STORE_IF1:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; CHECK:       [[PRED_STORE_IF1]]:
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 [[TMP5]]
; CHECK-NEXT:    store i32 [[X]], ptr [[TMP6]], align 4
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; CHECK:       [[PRED_STORE_CONTINUE2]]:
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[TMP1]], i32 2
; CHECK-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; CHECK:       [[PRED_STORE_IF3]]:
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 [[TMP8]]
; CHECK-NEXT:    store i32 [[X]], ptr [[TMP9]], align 4
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; CHECK:       [[PRED_STORE_CONTINUE4]]:
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[TMP1]], i32 3
; CHECK-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF5:.*]], label %[[PRED_STORE_CONTINUE6]]
; CHECK:       [[PRED_STORE_IF5]]:
; CHECK-NEXT:    [[TMP11:%.*]] = add i64 [[INDEX]], 3
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 [[TMP11]]
; CHECK-NEXT:    store i32 [[X]], ptr [[TMP12]], align 4
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE6]]
; CHECK:       [[PRED_STORE_CONTINUE6]]:
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add <4 x i64> [[VEC_IND]], splat (i64 4)
; CHECK-NEXT:    [[TMP13:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP13]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[BETWEEN:.*]]
; CHECK:       [[BETWEEN]]:
; CHECK-NEXT:    [[EXT:%.*]] = sext i32 [[N]] to i64
; CHECK-NEXT:    br label %[[PREHEADER]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    [[START:%.*]] = phi i64 [ [[EXT]], %[[BETWEEN]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[N]], 0
; CHECK-NEXT:    br i1 [[CMP2]], label %[[EXIT:.*]], label %[[LOOP2_PREHEADER:.*]]
; CHECK:       [[LOOP2_PREHEADER]]:
; CHECK-NEXT:    [[TMP14:%.*]] = zext i32 [[N]] to i64
; CHECK-NEXT:    br label %[[VECTOR_PH7:.*]]
; CHECK:       [[VECTOR_PH7]]:
; CHECK-NEXT:    [[N_RND_UP8:%.*]] = add i64 [[TMP14]], 3
; CHECK-NEXT:    [[N_MOD_VF9:%.*]] = urem i64 [[N_RND_UP8]], 4
; CHECK-NEXT:    [[N_VEC10:%.*]] = sub i64 [[N_RND_UP8]], [[N_MOD_VF9]]
; CHECK-NEXT:    [[TRIP_COUNT_MINUS_111:%.*]] = sub i64 [[TMP14]], 1
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT12:%.*]] = insertelement <4 x i64> poison, i64 [[TRIP_COUNT_MINUS_111]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT13:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT12]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY14:.*]]
; CHECK:       [[VECTOR_BODY14]]:
; CHECK-NEXT:    [[INDEX15:%.*]] = phi i64 [ 0, %[[VECTOR_PH7]] ], [ [[INDEX_NEXT26:%.*]], %[[PRED_STORE_CONTINUE25:.*]] ]
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = add i64 [[START]], [[INDEX15]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT16:%.*]] = insertelement <4 x i64> poison, i64 [[INDEX15]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT17:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT16]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[VEC_IV:%.*]] = add <4 x i64> [[BROADCAST_SPLAT17]], <i64 0, i64 1, i64 2, i64 3>
; CHECK-NEXT:    [[TMP15:%.*]] = icmp ule <4 x i64> [[VEC_IV]], [[BROADCAST_SPLAT13]]
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <4 x i1> [[TMP15]], i32 0
; CHECK-NEXT:    br i1 [[TMP16]], label %[[PRED_STORE_IF18:.*]], label %[[PRED_STORE_CONTINUE19:.*]]
; CHECK:       [[PRED_STORE_IF18]]:
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP18:%.*]] = load i32, ptr [[TMP17]], align 4
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds [2048 x i32], ptr @c, i64 0, i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP20:%.*]] = load i32, ptr [[TMP19]], align 4
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds [2048 x i32], ptr @a, i64 0, i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP22:%.*]] = and i32 [[TMP20]], [[TMP18]]
; CHECK-NEXT:    store i32 [[TMP22]], ptr [[TMP21]], align 4
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE19]]
; CHECK:       [[PRED_STORE_CONTINUE19]]:
; CHECK-NEXT:    [[TMP23:%.*]] = extractelement <4 x i1> [[TMP15]], i32 1
; CHECK-NEXT:    br i1 [[TMP23]], label %[[PRED_STORE_IF20:.*]], label %[[PRED_STORE_CONTINUE21:.*]]
; CHECK:       [[PRED_STORE_IF20]]:
; CHECK-NEXT:    [[TMP24:%.*]] = add i64 [[OFFSET_IDX]], 1
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 [[TMP24]]
; CHECK-NEXT:    [[TMP26:%.*]] = load i32, ptr [[TMP25]], align 4
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds [2048 x i32], ptr @c, i64 0, i64 [[TMP24]]
; CHECK-NEXT:    [[TMP28:%.*]] = load i32, ptr [[TMP27]], align 4
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds [2048 x i32], ptr @a, i64 0, i64 [[TMP24]]
; CHECK-NEXT:    [[TMP30:%.*]] = and i32 [[TMP28]], [[TMP26]]
; CHECK-NEXT:    store i32 [[TMP30]], ptr [[TMP29]], align 4
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE21]]
; CHECK:       [[PRED_STORE_CONTINUE21]]:
; CHECK-NEXT:    [[TMP31:%.*]] = extractelement <4 x i1> [[TMP15]], i32 2
; CHECK-NEXT:    br i1 [[TMP31]], label %[[PRED_STORE_IF22:.*]], label %[[PRED_STORE_CONTINUE23:.*]]
; CHECK:       [[PRED_STORE_IF22]]:
; CHECK-NEXT:    [[TMP32:%.*]] = add i64 [[OFFSET_IDX]], 2
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 [[TMP32]]
; CHECK-NEXT:    [[TMP34:%.*]] = load i32, ptr [[TMP33]], align 4
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr inbounds [2048 x i32], ptr @c, i64 0, i64 [[TMP32]]
; CHECK-NEXT:    [[TMP36:%.*]] = load i32, ptr [[TMP35]], align 4
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds [2048 x i32], ptr @a, i64 0, i64 [[TMP32]]
; CHECK-NEXT:    [[TMP38:%.*]] = and i32 [[TMP36]], [[TMP34]]
; CHECK-NEXT:    store i32 [[TMP38]], ptr [[TMP37]], align 4
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE23]]
; CHECK:       [[PRED_STORE_CONTINUE23]]:
; CHECK-NEXT:    [[TMP39:%.*]] = extractelement <4 x i1> [[TMP15]], i32 3
; CHECK-NEXT:    br i1 [[TMP39]], label %[[PRED_STORE_IF24:.*]], label %[[PRED_STORE_CONTINUE25]]
; CHECK:       [[PRED_STORE_IF24]]:
; CHECK-NEXT:    [[TMP40:%.*]] = add i64 [[OFFSET_IDX]], 3
; CHECK-NEXT:    [[TMP41:%.*]] = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 [[TMP40]]
; CHECK-NEXT:    [[TMP42:%.*]] = load i32, ptr [[TMP41]], align 4
; CHECK-NEXT:    [[TMP43:%.*]] = getelementptr inbounds [2048 x i32], ptr @c, i64 0, i64 [[TMP40]]
; CHECK-NEXT:    [[TMP44:%.*]] = load i32, ptr [[TMP43]], align 4
; CHECK-NEXT:    [[TMP45:%.*]] = getelementptr inbounds [2048 x i32], ptr @a, i64 0, i64 [[TMP40]]
; CHECK-NEXT:    [[TMP46:%.*]] = and i32 [[TMP44]], [[TMP42]]
; CHECK-NEXT:    store i32 [[TMP46]], ptr [[TMP45]], align 4
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE25]]
; CHECK:       [[PRED_STORE_CONTINUE25]]:
; CHECK-NEXT:    [[INDEX_NEXT26]] = add nuw i64 [[INDEX15]], 4
; CHECK-NEXT:    [[TMP47:%.*]] = icmp eq i64 [[INDEX_NEXT26]], [[N_VEC10]]
; CHECK-NEXT:    br i1 [[TMP47]], label %[[MIDDLE_BLOCK27:.*]], label %[[VECTOR_BODY14]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK27]]:
; CHECK-NEXT:    br label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %loop1, label %preheader

loop1:
  %iv1 = phi i64 [ %iv1.next, %loop1 ], [ 0, %entry ]
  %ptr1 = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 %iv1
  store i32 %x, ptr %ptr1, align 4
  %iv1.next = add i64 %iv1, 1
  %trunc = trunc i64 %iv1.next to i32
  %exit1 = icmp eq i32 %trunc, %n
  br i1 %exit1, label %between, label %loop1

between:
  %ext = sext i32 %n to i64
  br label %preheader

preheader:
  %start = phi i64 [ %ext, %between ], [ 0, %entry ]
  %cmp2 = icmp eq i32 %n, 0
  br i1 %cmp2, label %exit, label %loop2

loop2:
  %iv2 = phi i64 [ %iv2.next, %loop2 ], [ %start, %preheader ]
  %count = phi i32 [ %dec, %loop2 ], [ %n, %preheader ]
  %dec = add nsw i32 %count, -1
  %ptr2 = getelementptr inbounds [2048 x i32], ptr @b, i64 0, i64 %iv2
  %val1 = load i32, ptr %ptr2, align 4
  %ptr3 = getelementptr inbounds [2048 x i32], ptr @c, i64 0, i64 %iv2
  %val2 = load i32, ptr %ptr3, align 4
  %and = and i32 %val2, %val1
  %ptr4 = getelementptr inbounds [2048 x i32], ptr @a, i64 0, i64 %iv2
  store i32 %and, ptr %ptr4, align 4
  %iv2.next = add i64 %iv2, 1
  %exit2 = icmp eq i32 %dec, 0
  br i1 %exit2, label %exit, label %loop2

exit:
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
;.
