; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --include-generated-funcs --version 6
; RUN: opt -p loop-vectorize -force-vector-width=4 -S %s | FileCheck %s

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx15.0.0"

; Test that calls in early-exit loops with speculative loads are handled
; correctly in the oracle. The call to llvm.abs.i8 is used in the exit
; condition and must be executed in the oracle's scalar loop.
define i32 @oracle_with_live_call(ptr %p, i64 %n) {
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %gep = getelementptr inbounds i8, ptr %p, i64 %iv
  %ld = load i8, ptr %gep, align 1
  %abs = call i8 @llvm.abs.i8(i8 %ld, i1 false)
  %ext = zext i8 %abs to i32
  %cmp = icmp sgt i32 %ext, 42
  br i1 %cmp, label %early.exit, label %loop.latch

loop.latch:
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp ne i64 %iv.next, %n
  br i1 %ec, label %loop, label %exit

early.exit:
  ret i32 1

exit:
  ret i32 0
}

; Test that dead calls (constant args, unused result) in early-exit loops
; do not cause crashes. The call to llvm.abs.i8 with constant args is dead
; and should be handled gracefully in the oracle.
define i32 @oracle_with_dead_call(ptr %p, i64 %n) {
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %dead = call i8 @llvm.abs.i8(i8 0, i1 false)
  %gep = getelementptr inbounds i8, ptr %p, i64 %iv
  %ld = load i8, ptr %gep, align 1
  %ext = zext i8 %ld to i32
  %cmp = icmp sgt i32 %ext, 42
  br i1 %cmp, label %early.exit, label %loop.latch

loop.latch:
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp ne i64 %iv.next, %n
  br i1 %ec, label %loop, label %exit

early.exit:
  ret i32 1

exit:
  ret i32 0
}

; Test that fcmp in early-exit loops with speculative loads is handled
; correctly in the oracle. The fcmp is used in the exit condition and must
; be executed as a scalar in the oracle's loop.
define i32 @oracle_with_fcmp(ptr %p, i64 %n) {
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %gep = getelementptr inbounds float, ptr %p, i64 %iv
  %ld = load float, ptr %gep, align 4
  %ext = fpext float %ld to double
  %cmp = fcmp uge double %ext, 0.000000e+00
  br i1 %cmp, label %early.exit, label %loop.latch

loop.latch:
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp ne i64 %iv.next, %n
  br i1 %ec, label %loop, label %exit

early.exit:
  ret i32 1

exit:
  ret i32 0
}

; Test that a dead GEP with constant operands in an early-exit loop with
; speculative loads does not crash during VPlan simplification. The GEP has
; no underlying instruction after oracle cloning, so tryToFoldLiveIns must
; handle the null underlying value.
define i32 @oracle_with_dead_gep(ptr %p, i64 %n) {
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %dead.gep = getelementptr i8, ptr null, i64 8
  %gep = getelementptr inbounds i8, ptr %p, i64 %iv
  %ld = load i8, ptr %gep, align 1
  %ext = zext i8 %ld to i32
  %cmp = icmp sgt i32 %ext, 42
  br i1 %cmp, label %early.exit, label %loop.latch

loop.latch:
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp ne i64 %iv.next, %n
  br i1 %ec, label %loop, label %exit

early.exit:
  ret i32 1

exit:
  ret i32 0
}

declare i8 @llvm.abs.i8(i8, i1 immarg) #0

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK-LABEL: define i32 @oracle_with_live_call(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[SCALAR_PH:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH1:.*]], label %[[SPEC_LOAD_CHECK:.*]]
; CHECK:       [[SPEC_LOAD_CHECK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.can.load.speculatively.p0(ptr [[P]], i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = xor i1 [[TMP0]], true
; CHECK-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH1]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY_SPLIT:.*]]
; CHECK:       [[VECTOR_BODY_SPLIT]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT2:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 [[IV]]
; CHECK-NEXT:    [[TMP11:%.*]] = call <4 x i8> (ptr, ...) @llvm.speculative.load.v4i8.p0(ptr [[GEP]], ptr @speculativeLoadOracle, i64 [[IV]], ptr [[P]])
; CHECK-NEXT:    [[TMP12:%.*]] = call <4 x i8> @llvm.abs.v4i8(<4 x i8> [[TMP11]], i1 false)
; CHECK-NEXT:    [[TMP13:%.*]] = zext <4 x i8> [[TMP12]] to <4 x i32>
; CHECK-NEXT:    [[TMP14:%.*]] = icmp sgt <4 x i32> [[TMP13]], splat (i32 42)
; CHECK-NEXT:    [[INDEX_NEXT2]] = add nuw i64 [[IV]], 4
; CHECK-NEXT:    [[TMP15:%.*]] = freeze <4 x i1> [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP15]])
; CHECK-NEXT:    [[TMP17:%.*]] = icmp eq i64 [[INDEX_NEXT2]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP16]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP17]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY_SPLIT]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH1]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[EARLY_EXIT:.*]]
; CHECK:       [[SCALAR_PH1]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[SCALAR_PH]] ], [ 0, %[[SPEC_LOAD_CHECK]] ]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[IV1:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH1]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 [[IV1]]
; CHECK-NEXT:    [[LD:%.*]] = load i8, ptr [[GEP1]], align 1
; CHECK-NEXT:    [[ABS:%.*]] = call i8 @llvm.abs.i8(i8 [[LD]], i1 false)
; CHECK-NEXT:    [[EXT:%.*]] = zext i8 [[ABS]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[EXT]], 42
; CHECK-NEXT:    br i1 [[CMP]], label %[[EARLY_EXIT]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV1]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP1]], label %[[EXIT]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[EARLY_EXIT]]:
; CHECK-NEXT:    ret i32 1
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
;
; CHECK-LABEL: define i32 @oracle_with_dead_call(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[SCALAR_PH:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH1:.*]], label %[[SPEC_LOAD_CHECK:.*]]
; CHECK:       [[SPEC_LOAD_CHECK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.can.load.speculatively.p0(ptr [[P]], i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = xor i1 [[TMP0]], true
; CHECK-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH1]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY_SPLIT:.*]]
; CHECK:       [[VECTOR_BODY_SPLIT]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT2:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP10:%.*]] = call <4 x i8> (ptr, ...) @llvm.speculative.load.v4i8.p0(ptr [[TMP9]], ptr @speculativeLoadOracle.1, i64 [[INDEX]], ptr [[P]])
; CHECK-NEXT:    [[TMP11:%.*]] = zext <4 x i8> [[TMP10]] to <4 x i32>
; CHECK-NEXT:    [[TMP12:%.*]] = icmp sgt <4 x i32> [[TMP11]], splat (i32 42)
; CHECK-NEXT:    [[INDEX_NEXT2]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP13:%.*]] = freeze <4 x i1> [[TMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP13]])
; CHECK-NEXT:    [[TMP15:%.*]] = icmp eq i64 [[INDEX_NEXT2]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP14]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP15]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY_SPLIT]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH1]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[EARLY_EXIT:.*]]
; CHECK:       [[SCALAR_PH1]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[SCALAR_PH]] ], [ 0, %[[SPEC_LOAD_CHECK]] ]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH1]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[DEAD:%.*]] = call i8 @llvm.abs.i8(i8 0, i1 false)
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 [[IV]]
; CHECK-NEXT:    [[LD:%.*]] = load i8, ptr [[GEP]], align 1
; CHECK-NEXT:    [[EXT:%.*]] = zext i8 [[LD]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[EXT]], 42
; CHECK-NEXT:    br i1 [[CMP]], label %[[EARLY_EXIT]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP1]], label %[[EXIT]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[EARLY_EXIT]]:
; CHECK-NEXT:    ret i32 1
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
;
; CHECK-LABEL: define i32 @oracle_with_fcmp(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[SCALAR_PH:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH1:.*]], label %[[SPEC_LOAD_CHECK:.*]]
; CHECK:       [[SPEC_LOAD_CHECK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.can.load.speculatively.p0(ptr [[P]], i64 16)
; CHECK-NEXT:    [[TMP1:%.*]] = xor i1 [[TMP0]], true
; CHECK-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH1]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY_SPLIT:.*]]
; CHECK:       [[VECTOR_BODY_SPLIT]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT2:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds float, ptr [[P]], i64 [[IV]]
; CHECK-NEXT:    [[TMP11:%.*]] = call <4 x float> (ptr, ...) @llvm.speculative.load.v4f32.p0(ptr [[GEP]], ptr @speculativeLoadOracle.2, i64 [[IV]], ptr [[P]])
; CHECK-NEXT:    [[TMP12:%.*]] = fpext <4 x float> [[TMP11]] to <4 x double>
; CHECK-NEXT:    [[TMP13:%.*]] = fcmp uge <4 x double> [[TMP12]], zeroinitializer
; CHECK-NEXT:    [[INDEX_NEXT2]] = add nuw i64 [[IV]], 4
; CHECK-NEXT:    [[TMP14:%.*]] = freeze <4 x i1> [[TMP13]]
; CHECK-NEXT:    [[TMP15:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP14]])
; CHECK-NEXT:    [[TMP16:%.*]] = icmp eq i64 [[INDEX_NEXT2]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP15]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP16]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY_SPLIT]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH1]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[EARLY_EXIT:.*]]
; CHECK:       [[SCALAR_PH1]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[SCALAR_PH]] ], [ 0, %[[SPEC_LOAD_CHECK]] ]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[IV1:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH1]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds float, ptr [[P]], i64 [[IV1]]
; CHECK-NEXT:    [[LD:%.*]] = load float, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[EXT:%.*]] = fpext float [[LD]] to double
; CHECK-NEXT:    [[CMP:%.*]] = fcmp uge double [[EXT]], 0.000000e+00
; CHECK-NEXT:    br i1 [[CMP]], label %[[EARLY_EXIT]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV1]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP1]], label %[[EXIT]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       [[EARLY_EXIT]]:
; CHECK-NEXT:    ret i32 1
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
;
; CHECK-LABEL: define i32 @oracle_with_dead_gep(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[SCALAR_PH:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH1:.*]], label %[[SPEC_LOAD_CHECK:.*]]
; CHECK:       [[SPEC_LOAD_CHECK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.can.load.speculatively.p0(ptr [[P]], i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = xor i1 [[TMP0]], true
; CHECK-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH1]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY_SPLIT:.*]]
; CHECK:       [[VECTOR_BODY_SPLIT]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT2:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP10:%.*]] = call <4 x i8> (ptr, ...) @llvm.speculative.load.v4i8.p0(ptr [[TMP9]], ptr @speculativeLoadOracle.3, i64 [[INDEX]], ptr [[P]])
; CHECK-NEXT:    [[TMP11:%.*]] = zext <4 x i8> [[TMP10]] to <4 x i32>
; CHECK-NEXT:    [[TMP12:%.*]] = icmp sgt <4 x i32> [[TMP11]], splat (i32 42)
; CHECK-NEXT:    [[INDEX_NEXT2]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP13:%.*]] = freeze <4 x i1> [[TMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP13]])
; CHECK-NEXT:    [[TMP15:%.*]] = icmp eq i64 [[INDEX_NEXT2]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP14]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP15]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY_SPLIT]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH1]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[EARLY_EXIT:.*]]
; CHECK:       [[SCALAR_PH1]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[SCALAR_PH]] ], [ 0, %[[SPEC_LOAD_CHECK]] ]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH1]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[DEAD_GEP:%.*]] = getelementptr i8, ptr null, i64 8
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 [[IV]]
; CHECK-NEXT:    [[LD:%.*]] = load i8, ptr [[GEP]], align 1
; CHECK-NEXT:    [[EXT:%.*]] = zext i8 [[LD]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[EXT]], 42
; CHECK-NEXT:    br i1 [[CMP]], label %[[EARLY_EXIT]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP1]], label %[[EXIT]], !llvm.loop [[LOOP9:![0-9]+]]
; CHECK:       [[EARLY_EXIT]]:
; CHECK-NEXT:    ret i32 1
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
;
; CHECK-LABEL: define internal i64 @speculativeLoadOracle(
; CHECK-SAME: i64 [[CANONIV:%.*]], ptr [[P:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ORACLE_ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i64 [ 0, %[[ORACLE_ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[ADJUSTED_IV:%.*]] = add i64 [[TMP0]], [[CANONIV]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[P]], i64 [[ADJUSTED_IV]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = call i8 @llvm.abs.i8(i8 [[TMP2]], i1 false)
; CHECK-NEXT:    [[TMP4:%.*]] = zext i8 [[TMP3]] to i32
; CHECK-NEXT:    [[TMP5:%.*]] = icmp sgt i32 [[TMP4]], 42
; CHECK-NEXT:    br i1 [[TMP5]], label %[[ORACLE_EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[TMP6:%.*]] = add nuw nsw i64 [[ADJUSTED_IV]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP6]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = xor i1 [[TMP7]], true
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[TMP0]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], 4
; CHECK-NEXT:    br i1 [[TMP9]], label %[[ORACLE_EXIT]], label %[[LOOP]]
; CHECK:       [[ORACLE_EXIT]]:
; CHECK-NEXT:    [[TMP10:%.*]] = add i64 [[TMP0]], 1
; CHECK-NEXT:    ret i64 [[TMP10]]
;
;
; CHECK-LABEL: define internal i64 @speculativeLoadOracle.1(
; CHECK-SAME: i64 [[CANONIV:%.*]], ptr [[P:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ORACLE_ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i64 [ 0, %[[ORACLE_ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[ADJUSTED_IV:%.*]] = add i64 [[TMP0]], [[CANONIV]]
; CHECK-NEXT:    [[TMP1:%.*]] = call i8 @llvm.abs.i8(i8 0, i1 false)
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[P]], i64 [[ADJUSTED_IV]]
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP2]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = zext i8 [[TMP3]] to i32
; CHECK-NEXT:    [[TMP5:%.*]] = icmp sgt i32 [[TMP4]], 42
; CHECK-NEXT:    br i1 [[TMP5]], label %[[ORACLE_EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[TMP6:%.*]] = add nuw nsw i64 [[ADJUSTED_IV]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP6]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = xor i1 [[TMP7]], true
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[TMP0]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], 4
; CHECK-NEXT:    br i1 [[TMP9]], label %[[ORACLE_EXIT]], label %[[LOOP]]
; CHECK:       [[ORACLE_EXIT]]:
; CHECK-NEXT:    [[TMP10:%.*]] = add i64 [[TMP0]], 1
; CHECK-NEXT:    ret i64 [[TMP10]]
;
;
; CHECK-LABEL: define internal i64 @speculativeLoadOracle.2(
; CHECK-SAME: i64 [[CANONIV:%.*]], ptr [[P:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ORACLE_ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i64 [ 0, %[[ORACLE_ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[ADJUSTED_IV:%.*]] = add i64 [[TMP0]], [[CANONIV]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr float, ptr [[P]], i64 [[ADJUSTED_IV]]
; CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = fpext float [[TMP2]] to double
; CHECK-NEXT:    [[TMP4:%.*]] = fcmp uge double [[TMP3]], 0.000000e+00
; CHECK-NEXT:    br i1 [[TMP4]], label %[[ORACLE_EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[TMP5:%.*]] = add nuw nsw i64 [[ADJUSTED_IV]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = xor i1 [[TMP6]], true
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[TMP0]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], 4
; CHECK-NEXT:    br i1 [[TMP8]], label %[[ORACLE_EXIT]], label %[[LOOP]]
; CHECK:       [[ORACLE_EXIT]]:
; CHECK-NEXT:    [[TMP9:%.*]] = add i64 [[TMP0]], 1
; CHECK-NEXT:    ret i64 [[TMP9]]
;
;
; CHECK-LABEL: define internal i64 @speculativeLoadOracle.3(
; CHECK-SAME: i64 [[CANONIV:%.*]], ptr [[P:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ORACLE_ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i64 [ 0, %[[ORACLE_ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[ADJUSTED_IV:%.*]] = add i64 [[TMP0]], [[CANONIV]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[P]], i64 [[ADJUSTED_IV]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = zext i8 [[TMP2]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = icmp sgt i32 [[TMP3]], 42
; CHECK-NEXT:    br i1 [[TMP4]], label %[[ORACLE_EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[TMP5:%.*]] = add nuw nsw i64 [[ADJUSTED_IV]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = xor i1 [[TMP6]], true
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[TMP0]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], 4
; CHECK-NEXT:    br i1 [[TMP8]], label %[[ORACLE_EXIT]], label %[[LOOP]]
; CHECK:       [[ORACLE_EXIT]]:
; CHECK-NEXT:    [[TMP9:%.*]] = add i64 [[TMP0]], 1
; CHECK-NEXT:    ret i64 [[TMP9]]
;
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR1]] = { noinline optnone memory(argmem: read) }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META2]], [[META1]]}
; CHECK: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]]}
; CHECK: [[LOOP7]] = distinct !{[[LOOP7]], [[META2]], [[META1]]}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META1]], [[META2]]}
; CHECK: [[LOOP9]] = distinct !{[[LOOP9]], [[META2]], [[META1]]}
;.
