; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --include-generated-funcs --version 6
; RUN: opt -p loop-vectorize -force-vector-width=4 -S %s | FileCheck %s

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx15.0.0"

; Test that unary ops (fneg) in early-exit loop bodies are handled correctly
; in the oracle plan.
define i1 @early_exit_with_fneg(ptr %v1, i64 %n) {
entry:
  br label %for.body

for.cond:
  %indvars.iv.next = add i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %n
  br i1 %exitcond.not, label %return.loopexit, label %for.body

for.body:
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.cond ]
  %fneg.i = fneg float 0.000000e+00
  %arrayidx = getelementptr [4 x i8], ptr %v1, i64 %indvars.iv
  %0 = load float, ptr %arrayidx, align 4
  %cmp7.i = fcmp ugt float %0, %fneg.i
  br i1 %cmp7.i, label %return.loopexit, label %for.cond

return.loopexit:
  ret i1 false
}
; CHECK-LABEL: define i1 @early_exit_with_fneg(
; CHECK-SAME: ptr [[V1:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[SCALAR_PH:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH1:.*]], label %[[SPEC_LOAD_CHECK:.*]]
; CHECK:       [[SPEC_LOAD_CHECK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.can.load.speculatively.p0(ptr [[V1]], i64 16)
; CHECK-NEXT:    [[TMP1:%.*]] = xor i1 [[TMP0]], true
; CHECK-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH1]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY_SPLIT:.*]]
; CHECK:       [[VECTOR_BODY_SPLIT]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT2:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr [4 x i8], ptr [[V1]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP10:%.*]] = call <4 x float> (ptr, ...) @llvm.speculative.load.v4f32.p0(ptr [[TMP9]], ptr @speculativeLoadOracle, i64 [[INDEX]], ptr [[V1]])
; CHECK-NEXT:    [[TMP11:%.*]] = fcmp ugt <4 x float> [[TMP10]], splat (float -0.000000e+00)
; CHECK-NEXT:    [[INDEX_NEXT2]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP12:%.*]] = freeze <4 x i1> [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP12]])
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT2]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP13]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY_SPLIT]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[RETURN_LOOPEXIT:.*]], label %[[SCALAR_PH1]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[RETURN_LOOPEXIT]]
; CHECK:       [[SCALAR_PH1]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[SCALAR_PH]] ], [ 0, %[[SPEC_LOAD_CHECK]] ]
; CHECK-NEXT:    br label %[[FOR_BODY1:.*]]
; CHECK:       [[FOR_COND:.*]]:
; CHECK-NEXT:    [[INDVARS_IV_NEXT1:%.*]] = add i64 [[INDVARS_IV1:%.*]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT1]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[RETURN_LOOPEXIT]], label %[[FOR_BODY1]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[FOR_BODY1]]:
; CHECK-NEXT:    [[INDVARS_IV1]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH1]] ], [ [[INDVARS_IV_NEXT1]], %[[FOR_COND]] ]
; CHECK-NEXT:    [[FNEG_I:%.*]] = fneg float 0.000000e+00
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [4 x i8], ptr [[V1]], i64 [[INDVARS_IV1]]
; CHECK-NEXT:    [[TMP15:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[CMP7_I:%.*]] = fcmp ugt float [[TMP15]], [[FNEG_I]]
; CHECK-NEXT:    br i1 [[CMP7_I]], label %[[RETURN_LOOPEXIT]], label %[[FOR_COND]]
; CHECK:       [[RETURN_LOOPEXIT]]:
; CHECK-NEXT:    ret i1 false
;
;
; CHECK-LABEL: define internal i64 @speculativeLoadOracle(
; CHECK-SAME: i64 [[CANONIV:%.*]], ptr [[V1:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ORACLE_ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i64 [ 0, %[[ORACLE_ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[FOR_COND:.*]] ]
; CHECK-NEXT:    [[ADJUSTED_IV:%.*]] = add i64 [[TMP1]], [[CANONIV]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [4 x i8], ptr [[V1]], i64 [[ADJUSTED_IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = fcmp ugt float [[TMP4]], -0.000000e+00
; CHECK-NEXT:    br i1 [[TMP5]], label %[[ORACLE_EXIT:.*]], label %[[FOR_COND]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[TMP7:%.*]] = add i64 [[ADJUSTED_IV]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[TMP7]], 0
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], 4
; CHECK-NEXT:    br i1 [[TMP9]], label %[[ORACLE_EXIT]], label %[[FOR_BODY]]
; CHECK:       [[ORACLE_EXIT]]:
; CHECK-NEXT:    [[TMP10:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    ret i64 [[TMP10]]
;
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR1]] = { noinline optnone memory(argmem: read) }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
