; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --include-generated-funcs --version 6
; RUN: opt -p loop-vectorize -force-vector-width=4 -S %s | FileCheck %s

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx15.0.0"

; Test that the oracle expansion preserves correct predecessor ordering for
; phi nodes in multi-block loop bodies. The loop body has a conditional branch
; leading to two blocks that merge at a phi node before the early exit check.
define ptr @oracle_multiblock_phi(i64 %n) {
entry:
  br label %header

latch.exit:
  ret ptr null

header:
  %iv = phi i64 [ %iv.next, %latch ], [ 0, %entry ]
  br i1 false, label %if.true, label %if.false

if.true:
  %gep.i16 = getelementptr [2 x i8], ptr null, i64 %iv
  %ld.i16 = load i16, ptr %gep.i16, align 2
  br label %merge

if.false:
  %gep.i32 = getelementptr [4 x i8], ptr null, i64 %iv
  %ld.i32 = load i32, ptr %gep.i32, align 4
  br label %merge

merge:
  %val = phi i32 [ %ld.i32, %if.false ], [ 1, %if.true ]
  %cmp = icmp eq i32 %val, 0
  br i1 %cmp, label %latch, label %early.exit

latch:
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, %n
  br i1 %ec, label %latch.exit, label %header

early.exit:
  ret ptr null
}
; CHECK-LABEL: define ptr @oracle_multiblock_phi(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[SCALAR_PH:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH1:.*]], label %[[SPEC_LOAD_CHECK:.*]]
; CHECK:       [[SPEC_LOAD_CHECK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.can.load.speculatively.p0(ptr null, i64 16)
; CHECK-NEXT:    [[TMP1:%.*]] = xor i1 [[TMP0]], true
; CHECK-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH1]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY_SPLIT:.*]]
; CHECK:       [[VECTOR_BODY_SPLIT]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT2:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr [4 x i8], ptr null, i64 [[INDEX]]
; CHECK-NEXT:    [[TMP10:%.*]] = call <4 x i32> (ptr, ...) @llvm.speculative.load.v4i32.p0(ptr [[TMP9]], ptr @speculativeLoadOracle, i64 [[INDEX]])
; CHECK-NEXT:    [[TMP11:%.*]] = icmp ne <4 x i32> [[TMP10]], zeroinitializer
; CHECK-NEXT:    [[INDEX_NEXT2]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP12:%.*]] = freeze <4 x i1> [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP12]])
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT2]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP13]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY_SPLIT]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[LATCH_EXIT1:.*]], label %[[SCALAR_PH1]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[EARLY_EXIT:.*]]
; CHECK:       [[SCALAR_PH1]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[SCALAR_PH]] ], [ 0, %[[SPEC_LOAD_CHECK]] ]
; CHECK-NEXT:    br label %[[HEADER1:.*]]
; CHECK:       [[LATCH_EXIT1]]:
; CHECK-NEXT:    ret ptr null
; CHECK:       [[HEADER1]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH1]] ]
; CHECK-NEXT:    br i1 false, label %[[IF_TRUE:.*]], label %[[IF_FALSE:.*]]
; CHECK:       [[IF_TRUE]]:
; CHECK-NEXT:    [[GEP_I16:%.*]] = getelementptr [2 x i8], ptr null, i64 [[IV]]
; CHECK-NEXT:    [[LD_I16:%.*]] = load i16, ptr [[GEP_I16]], align 2
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[IF_FALSE]]:
; CHECK-NEXT:    [[GEP_I32:%.*]] = getelementptr [4 x i8], ptr null, i64 [[IV]]
; CHECK-NEXT:    [[LD_I32:%.*]] = load i32, ptr [[GEP_I32]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[VAL:%.*]] = phi i32 [ [[LD_I32]], %[[IF_FALSE]] ], [ 1, %[[IF_TRUE]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[VAL]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[LATCH]], label %[[EARLY_EXIT]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LATCH_EXIT1]], label %[[HEADER1]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[EARLY_EXIT]]:
; CHECK-NEXT:    ret ptr null
;
;
; CHECK-LABEL: define internal i64 @speculativeLoadOracle(
; CHECK-SAME: i64 [[CANONIV:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ORACLE_ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i64 [ 0, %[[ORACLE_ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[ADJUSTED_IV:%.*]] = add i64 [[TMP0]], [[CANONIV]]
; CHECK-NEXT:    br i1 false, label %[[IF_TRUE:.*]], label %[[IF_FALSE:.*]]
; CHECK:       [[IF_FALSE]]:
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [4 x i8], ptr null, i64 [[ADJUSTED_IV]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[IF_TRUE]]:
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [2 x i8], ptr null, i64 [[ADJUSTED_IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi i32 [ [[TMP2]], %[[IF_FALSE]] ], [ 1, %[[IF_TRUE]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i32 [[VEC_PHI]], 0
; CHECK-NEXT:    br i1 [[TMP5]], label %[[LATCH]], label %[[ORACLE_EXIT:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[TMP6:%.*]] = add i64 [[ADJUSTED_IV]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP6]], 0
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[TMP0]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], 4
; CHECK-NEXT:    br i1 [[TMP8]], label %[[ORACLE_EXIT]], label %[[HEADER]]
; CHECK:       [[ORACLE_EXIT]]:
; CHECK-NEXT:    [[TMP9:%.*]] = add i64 [[TMP0]], 1
; CHECK-NEXT:    ret i64 [[TMP9]]
;
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR1]] = { noinline optnone memory(argmem: read) }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
