; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -S %s | FileCheck %s

; Make sure we don't crash when checking if all loads are dereferenceable
; in a loop with an uncountable early exit containing a unary fneg.

define i1 @early_exit_with_fneg(i1 %cond) {
; CHECK-LABEL: define i1 @early_exit_with_fneg(
; CHECK-SAME: i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[NEG:%.*]] = fneg double 0.000000e+00
; CHECK-NEXT:    br i1 [[COND]], label %[[LATCH]], label %[[EARLY_EXIT:.*]]
; CHECK:       [[EARLY_EXIT]]:
; CHECK-NEXT:    ret i1 false
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i64 [[IV]], 1
; CHECK-NEXT:    [[EXIT_COND:%.*]] = icmp eq i64 [[IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXIT_COND]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 true
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ %iv.next, %latch ], [ 0, %entry ]
  %neg = fneg double 0.000000e+00
  br i1 %cond, label %latch, label %early.exit

early.exit:
  ret i1 false

latch:
  %iv.next = add nuw i64 %iv, 1
  %exit.cond = icmp eq i64 %iv.next, 1024
  br i1 %exit.cond, label %exit, label %loop

exit:
  ret i1 true
}
