; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -p loop-vectorize -S %s | FileCheck %s

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx13.0.0"

; Test 1: Store to limit pointer inside loop.
; The loop modifies *limit_ptr, so the load is NOT invariant.
; This must NOT be vectorized with the invariant-load assumption.
define void @store_to_limit_ptr(ptr %limit_ptr, ptr %dst) {
; CHECK-LABEL: define void @store_to_limit_ptr(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[DST]], %[[ENTRY]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[NEW_LIMIT:%.*]] = add i32 [[IV]], 100
; CHECK-NEXT:    store i32 [[NEW_LIMIT]], ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %entry ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  ; Store a new limit value each iteration - load is NOT invariant
  %new_limit = add i32 %iv, 100
  store i32 %new_limit, ptr %limit_ptr, align 4
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = load i32, ptr %limit_ptr, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Test 2: Store through aliased pointer to limit.
; %alias_ptr and %limit_ptr may alias, so the load may not be invariant.
define void @store_through_alias(ptr %limit_ptr, ptr %alias_ptr, ptr %dst) {
; CHECK-LABEL: define void @store_through_alias(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr [[ALIAS_PTR:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ITER_CHECK:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP0]], i32 1)
; CHECK-NEXT:    [[TMP11:%.*]] = zext nneg i32 [[SMAX]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i32 [[SMAX]], -1
; CHECK-NEXT:    [[TMP3:%.*]] = zext nneg i32 [[TMP2]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP11]], 32
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[VEC_EPILOG_SCALAR_PH:.*]], label %[[VECTOR_MAIN_LOOP_ITER_CHECK1:.*]]
; CHECK:       [[VECTOR_MAIN_LOOP_ITER_CHECK1]]:
; CHECK-NEXT:    [[TMP13:%.*]] = add i64 1, [[TMP3]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[DST]], i64 [[TMP13]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[ALIAS_PTR]], i64 4
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[LIMIT_PTR]], i64 4
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[DST]], [[TMP10]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[ALIAS_PTR]], [[TMP12]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    [[BOUND01:%.*]] = icmp ult ptr [[DST]], [[TMP9]]
; CHECK-NEXT:    [[BOUND12:%.*]] = icmp ult ptr [[LIMIT_PTR]], [[TMP12]]
; CHECK-NEXT:    [[FOUND_CONFLICT3:%.*]] = and i1 [[BOUND01]], [[BOUND12]]
; CHECK-NEXT:    [[CONFLICT_RDX:%.*]] = or i1 [[FOUND_CONFLICT]], [[FOUND_CONFLICT3]]
; CHECK-NEXT:    [[BOUND04:%.*]] = icmp ult ptr [[ALIAS_PTR]], [[TMP9]]
; CHECK-NEXT:    [[BOUND15:%.*]] = icmp ult ptr [[LIMIT_PTR]], [[TMP10]]
; CHECK-NEXT:    [[FOUND_CONFLICT6:%.*]] = and i1 [[BOUND04]], [[BOUND15]]
; CHECK-NEXT:    [[CONFLICT_RDX7:%.*]] = or i1 [[CONFLICT_RDX]], [[FOUND_CONFLICT6]]
; CHECK-NEXT:    br i1 [[CONFLICT_RDX7]], label %[[VEC_EPILOG_SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP11]], 32
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP11]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <16 x i32> [ <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[STEP_ADD:%.*]] = add nuw nsw <16 x i32> [[VEC_IND]], splat (i32 16)
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 16
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[NEXT_GEP]], align 1, !alias.scope [[META0:![0-9]+]], !noalias [[META3:![0-9]+]]
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[TMP5]], align 1, !alias.scope [[META0]], !noalias [[META3]]
; CHECK-NEXT:    [[TMP6:%.*]] = add <16 x i32> [[STEP_ADD]], splat (i32 50)
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <16 x i32> [[TMP6]], i32 15
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[ALIAS_PTR]], align 4, !alias.scope [[META6:![0-9]+]], !noalias [[META7:![0-9]+]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add nuw nsw <16 x i32> [[STEP_ADD]], splat (i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP8]], label %[[VEC_EPILOG_MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       [[VEC_EPILOG_MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N19:%.*]] = icmp eq i64 [[TMP11]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N19]], label %[[EXIT:.*]], label %[[VEC_EPILOG_SCALAR_PH]]
; CHECK:       [[VEC_EPILOG_SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[TMP4]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ 0, %[[ITER_CHECK]] ], [ 0, %[[VECTOR_MAIN_LOOP_ITER_CHECK1]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL8:%.*]] = phi ptr [ [[TMP14]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ [[DST]], %[[ITER_CHECK]] ], [ [[DST]], %[[VECTOR_MAIN_LOOP_ITER_CHECK1]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[BC_RESUME_VAL8]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[VAL:%.*]] = add i32 [[IV]], 50
; CHECK-NEXT:    store i32 [[VAL]], ptr [[ALIAS_PTR]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %entry ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  ; Store through a potentially aliasing pointer
  %val = add i32 %iv, 50
  store i32 %val, ptr %alias_ptr, align 4
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = load i32, ptr %limit_ptr, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Test 3: Load used as trip count with unsigned comparison, limit could be 0.
; When the load returns 0 and start is 1, the loop should not execute.
define void @ult_load_zero_limit(ptr %limit_ptr, ptr %dst) {
; CHECK-LABEL: define void @ult_load_zero_limit(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ITER_CHECK:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-NEXT:    [[UMAX2:%.*]] = call i64 @llvm.umax.i64(i64 [[TMP1]], i64 1)
; CHECK-NEXT:    [[UMAX1:%.*]] = call i32 @llvm.umax.i32(i32 [[TMP0]], i32 1)
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[UMAX1]], -1
; CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMAX2]], 32
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[VEC_EPILOG_SCALAR_PH:.*]], label %[[VECTOR_MAIN_LOOP_ITER_CHECK1:.*]]
; CHECK:       [[VECTOR_MAIN_LOOP_ITER_CHECK1]]:
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 1, [[TMP3]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[DST]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[LIMIT_PTR]], i64 4
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[DST]], [[TMP7]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[LIMIT_PTR]], [[TMP6]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[VEC_EPILOG_SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMAX2]], 32
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMAX2]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP9:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 16
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[NEXT_GEP]], align 1, !alias.scope [[META12:![0-9]+]], !noalias [[META15:![0-9]+]]
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[TMP4]], align 1, !alias.scope [[META12]], !noalias [[META15]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP5]], label %[[VEC_EPILOG_MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP17:![0-9]+]]
; CHECK:       [[VEC_EPILOG_MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N9:%.*]] = icmp eq i64 [[UMAX2]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N9]], label %[[EXIT:.*]], label %[[VEC_EPILOG_SCALAR_PH]]
; CHECK:       [[VEC_EPILOG_SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[TMP9]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ 0, %[[ITER_CHECK]] ], [ 0, %[[VECTOR_MAIN_LOOP_ITER_CHECK1]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL2:%.*]] = phi ptr [ [[TMP10]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ [[DST]], %[[ITER_CHECK]] ], [ [[DST]], %[[VECTOR_MAIN_LOOP_ITER_CHECK1]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[BC_RESUME_VAL2]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP18:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %entry ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw i32 %iv, 1
  %limit = load i32, ptr %limit_ptr, align 4
  %cmp = icmp ult i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Test 4: Signed comparison with load, negative start value.
define void @slt_negative_start(ptr %limit_ptr, ptr %dst) {
; CHECK-LABEL: define void @slt_negative_start(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ITER_CHECK:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[SMAX3:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP0]], i32 -9)
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[SMAX3]], 10
; CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[SMAX3]], 9
; CHECK-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP3]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[TMP1]], 32
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[VEC_EPILOG_SCALAR_PH:.*]], label %[[VECTOR_MAIN_LOOP_ITER_CHECK1:.*]]
; CHECK:       [[VECTOR_MAIN_LOOP_ITER_CHECK1]]:
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[DST]], i64 -10
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 -9, [[TMP2]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[DST]], i64 [[TMP5]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[LIMIT_PTR]], i64 4
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[TMP11]], [[TMP4]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[LIMIT_PTR]], [[TMP10]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[VEC_EPILOG_SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i32 [[TMP1]], 32
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i32 [[TMP1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP13:%.*]] = add i32 -10, [[N_VEC]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = add i32 -10, [[INDEX]]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[DST]], i32 [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP7]], i64 16
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[TMP7]], align 1, !alias.scope [[META19:![0-9]+]], !noalias [[META22:![0-9]+]]
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[TMP8]], align 1, !alias.scope [[META19]], !noalias [[META22]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], 32
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i32 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP9]], label %[[VEC_EPILOG_MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP24:![0-9]+]]
; CHECK:       [[VEC_EPILOG_MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N9:%.*]] = icmp eq i32 [[TMP1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N9]], label %[[EXIT:.*]], label %[[VEC_EPILOG_SCALAR_PH]]
; CHECK:       [[VEC_EPILOG_SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[TMP13]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ -10, %[[ITER_CHECK]] ], [ -10, %[[VECTOR_MAIN_LOOP_ITER_CHECK1]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr i8, ptr [[DST]], i32 [[IV]]
; CHECK-NEXT:    store i8 42, ptr [[P]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP25:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ -10, %entry ], [ %iv.next, %loop ]
  %p = getelementptr i8, ptr %dst, i32 %iv
  store i8 42, ptr %p, align 1
  %iv.next = add nsw i32 %iv, 1
  %limit = load i32, ptr %limit_ptr, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Test 5: Multiple invariant loads from different pointers in exit condition.
; One load as the direct RHS, another used in computation.
define void @two_invariant_load_ptrs(ptr %ptr1, ptr %ptr2, ptr %dst) {
; CHECK-LABEL: define void @two_invariant_load_ptrs(
; CHECK-SAME: ptr [[PTR1:%.*]], ptr [[PTR2:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ITER_CHECK:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PTR1]], align 4
; CHECK-NEXT:    [[SMAX2:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP0]], i32 1)
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i32 [[SMAX2]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i32 [[SMAX2]], -1
; CHECK-NEXT:    [[TMP3:%.*]] = zext nneg i32 [[TMP2]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP1]], 32
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[VEC_EPILOG_SCALAR_PH:.*]], label %[[VECTOR_MAIN_LOOP_ITER_CHECK1:.*]]
; CHECK:       [[VECTOR_MAIN_LOOP_ITER_CHECK1]]:
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 1, [[TMP3]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[DST]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[PTR1]], i64 4
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[DST]], [[TMP7]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[PTR1]], [[TMP6]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[VEC_EPILOG_SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP1]], 32
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP9:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 16
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[NEXT_GEP]], align 1, !alias.scope [[META26:![0-9]+]], !noalias [[META29:![0-9]+]]
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[TMP4]], align 1, !alias.scope [[META26]], !noalias [[META29]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP5]], label %[[VEC_EPILOG_MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP31:![0-9]+]]
; CHECK:       [[VEC_EPILOG_MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N9:%.*]] = icmp eq i64 [[TMP1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N9]], label %[[EXIT:.*]], label %[[VEC_EPILOG_SCALAR_PH]]
; CHECK:       [[VEC_EPILOG_SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[TMP9]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ 0, %[[ITER_CHECK]] ], [ 0, %[[VECTOR_MAIN_LOOP_ITER_CHECK1]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL1:%.*]] = phi ptr [ [[TMP10]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ [[DST]], %[[ITER_CHECK]] ], [ [[DST]], %[[VECTOR_MAIN_LOOP_ITER_CHECK1]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[BC_RESUME_VAL1]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[PTR1]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP32:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %entry ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = load i32, ptr %ptr1, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Test 6: Atomic load as limit (should not get predicated BTC).
define void @atomic_load_limit(ptr %limit_ptr, ptr %dst) {
; CHECK-LABEL: define void @atomic_load_limit(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[DST]], %[[ENTRY]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load atomic i32, ptr [[LIMIT_PTR]] monotonic, align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %entry ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = load atomic i32, ptr %limit_ptr monotonic, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Test 7: Invariant load with noalias dst - no runtime checks generated, so no
; scoped noalias metadata. hoistInvariantLoads cannot hoist the load, but VPlan
; LICM can hoist it using AA (noalias on dst proves no alias with limit_ptr).
; Vectorization succeeds with the invariant load BTC.
define void @invariant_load_noalias_dst(ptr %limit_ptr, ptr noalias %dst) {
; CHECK-LABEL: define void @invariant_load_noalias_dst(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr noalias [[DST:%.*]]) {
; CHECK-NEXT:  [[ITER_CHECK:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP0]], i32 1)
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i32 [[SMAX]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP1]], 8
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[VEC_EPILOG_SCALAR_PH:.*]], label %[[VECTOR_MAIN_LOOP_ITER_CHECK:.*]]
; CHECK:       [[VECTOR_MAIN_LOOP_ITER_CHECK]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK1:%.*]] = icmp ult i64 [[TMP1]], 32
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK1]], label %[[VEC_EPILOG_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP1]], 32
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP2:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 16
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[NEXT_GEP]], align 1
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[TMP4]], align 1
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP33:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[VEC_EPILOG_ITER_CHECK:.*]]
; CHECK:       [[VEC_EPILOG_ITER_CHECK]]:
; CHECK-NEXT:    [[MIN_EPILOG_ITERS_CHECK:%.*]] = icmp ult i64 [[N_MOD_VF]], 8
; CHECK-NEXT:    br i1 [[MIN_EPILOG_ITERS_CHECK]], label %[[VEC_EPILOG_SCALAR_PH]], label %[[VEC_EPILOG_PH]], !prof [[PROF34:![0-9]+]]
; CHECK:       [[VEC_EPILOG_PH]]:
; CHECK-NEXT:    [[VEC_EPILOG_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[VEC_EPILOG_ITER_CHECK]] ], [ 0, %[[VECTOR_MAIN_LOOP_ITER_CHECK]] ]
; CHECK-NEXT:    [[N_MOD_VF3:%.*]] = urem i64 [[TMP1]], 8
; CHECK-NEXT:    [[N_VEC4:%.*]] = sub i64 [[TMP1]], [[N_MOD_VF3]]
; CHECK-NEXT:    [[TMP6:%.*]] = trunc i64 [[N_VEC4]] to i32
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC4]]
; CHECK-NEXT:    br label %[[VEC_EPILOG_VECTOR_BODY:.*]]
; CHECK:       [[VEC_EPILOG_VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX5:%.*]] = phi i64 [ [[VEC_EPILOG_RESUME_VAL]], %[[VEC_EPILOG_PH]] ], [ [[INDEX_NEXT7:%.*]], %[[VEC_EPILOG_VECTOR_BODY]] ]
; CHECK-NEXT:    [[NEXT_GEP6:%.*]] = getelementptr i8, ptr [[DST]], i64 [[INDEX5]]
; CHECK-NEXT:    store <8 x i8> splat (i8 42), ptr [[NEXT_GEP6]], align 1
; CHECK-NEXT:    [[INDEX_NEXT7]] = add nuw i64 [[INDEX5]], 8
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT7]], [[N_VEC4]]
; CHECK-NEXT:    br i1 [[TMP8]], label %[[VEC_EPILOG_MIDDLE_BLOCK:.*]], label %[[VEC_EPILOG_VECTOR_BODY]], !llvm.loop [[LOOP35:![0-9]+]]
; CHECK:       [[VEC_EPILOG_MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N8:%.*]] = icmp eq i64 [[TMP1]], [[N_VEC4]]
; CHECK-NEXT:    br i1 [[CMP_N8]], label %[[EXIT]], label %[[VEC_EPILOG_SCALAR_PH]]
; CHECK:       [[VEC_EPILOG_SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL9:%.*]] = phi i32 [ [[TMP6]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ [[TMP2]], %[[VEC_EPILOG_ITER_CHECK]] ], [ 0, %[[ITER_CHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL10:%.*]] = phi ptr [ [[TMP7]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ [[TMP3]], %[[VEC_EPILOG_ITER_CHECK]] ], [ [[DST]], %[[ITER_CHECK]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL9]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[BC_RESUME_VAL10]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP36:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %entry ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = load i32, ptr %limit_ptr, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}
;.
; CHECK: [[META0]] = !{[[META1:![0-9]+]]}
; CHECK: [[META1]] = distinct !{[[META1]], [[META2:![0-9]+]]}
; CHECK: [[META2]] = distinct !{[[META2]], !"LVerDomain"}
; CHECK: [[META3]] = !{[[META4:![0-9]+]], [[META5:![0-9]+]]}
; CHECK: [[META4]] = distinct !{[[META4]], [[META2]]}
; CHECK: [[META5]] = distinct !{[[META5]], [[META2]]}
; CHECK: [[META6]] = !{[[META4]]}
; CHECK: [[META7]] = !{[[META5]]}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META9:![0-9]+]], [[META10:![0-9]+]]}
; CHECK: [[META9]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META10]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META10]], [[META9]]}
; CHECK: [[META12]] = !{[[META13:![0-9]+]]}
; CHECK: [[META13]] = distinct !{[[META13]], [[META14:![0-9]+]]}
; CHECK: [[META14]] = distinct !{[[META14]], !"LVerDomain"}
; CHECK: [[META15]] = !{[[META16:![0-9]+]]}
; CHECK: [[META16]] = distinct !{[[META16]], [[META14]]}
; CHECK: [[LOOP17]] = distinct !{[[LOOP17]], [[META9]], [[META10]]}
; CHECK: [[LOOP18]] = distinct !{[[LOOP18]], [[META10]], [[META9]]}
; CHECK: [[META19]] = !{[[META20:![0-9]+]]}
; CHECK: [[META20]] = distinct !{[[META20]], [[META21:![0-9]+]]}
; CHECK: [[META21]] = distinct !{[[META21]], !"LVerDomain"}
; CHECK: [[META22]] = !{[[META23:![0-9]+]]}
; CHECK: [[META23]] = distinct !{[[META23]], [[META21]]}
; CHECK: [[LOOP24]] = distinct !{[[LOOP24]], [[META9]], [[META10]]}
; CHECK: [[LOOP25]] = distinct !{[[LOOP25]], [[META10]], [[META9]]}
; CHECK: [[META26]] = !{[[META27:![0-9]+]]}
; CHECK: [[META27]] = distinct !{[[META27]], [[META28:![0-9]+]]}
; CHECK: [[META28]] = distinct !{[[META28]], !"LVerDomain"}
; CHECK: [[META29]] = !{[[META30:![0-9]+]]}
; CHECK: [[META30]] = distinct !{[[META30]], [[META28]]}
; CHECK: [[LOOP31]] = distinct !{[[LOOP31]], [[META9]], [[META10]]}
; CHECK: [[LOOP32]] = distinct !{[[LOOP32]], [[META10]], [[META9]]}
; CHECK: [[LOOP33]] = distinct !{[[LOOP33]], [[META9]], [[META10]]}
; CHECK: [[PROF34]] = !{!"branch_weights", i32 8, i32 24}
; CHECK: [[LOOP35]] = distinct !{[[LOOP35]], [[META9]], [[META10]]}
; CHECK: [[LOOP36]] = distinct !{[[LOOP36]], [[META10]], [[META9]]}
;.
