; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=loop-vectorize,verify -force-vector-width=4 -enable-vplan-native-path < %s | FileCheck %s

; The annotation promises independence between accesses it covers.
define void @parallel_accesses(ptr %a, ptr %b) {
; CHECK-LABEL: define void @parallel_accesses(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x ptr> poison, ptr [[A]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x ptr> [[BROADCAST_SPLATINSERT]], <4 x ptr> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    br label %[[INNER1:.*]]
; CHECK:       [[INNER1]]:
; CHECK-NEXT:    [[J2:%.*]] = phi <4 x i64> [ zeroinitializer, %[[VECTOR_BODY]] ], [ [[TMP0:%.*]], %[[INNER1]] ]
; CHECK-NEXT:    [[WIDE_MASKED_GATHER:%.*]] = call <4 x i32> @llvm.masked.gather.v4i32.v4p0(<4 x ptr> align 4 [[BROADCAST_SPLAT]], <4 x i1> splat (i1 true), <4 x i32> poison), !llvm.access.group [[ACC_GRP0:![0-9]+]]
; CHECK-NEXT:    [[TMP0]] = add nuw nsw <4 x i64> [[J2]], splat (i64 1)
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <4 x i64> [[TMP0]], splat (i64 2)
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i1> [[TMP1]], i64 0
; CHECK-NEXT:    br i1 [[TMP2]], label %[[LATCH3:.*]], label %[[INNER1]], !llvm.loop [[LOOP1:![0-9]+]]
; CHECK:       [[LATCH3]]:
; CHECK-NEXT:    store <4 x i32> [[WIDE_MASKED_GATHER]], ptr [[B]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    br label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @parallel_access_group_list(ptr %a, ptr %b) {
; CHECK-LABEL: define void @parallel_access_group_list(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x ptr> poison, ptr [[A]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x ptr> [[BROADCAST_SPLATINSERT]], <4 x ptr> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    br label %[[INNER1:.*]]
; CHECK:       [[INNER1]]:
; CHECK-NEXT:    [[J2:%.*]] = phi <4 x i64> [ zeroinitializer, %[[VECTOR_BODY]] ], [ [[TMP0:%.*]], %[[INNER1]] ]
; CHECK-NEXT:    [[WIDE_MASKED_GATHER:%.*]] = call <4 x i32> @llvm.masked.gather.v4i32.v4p0(<4 x ptr> align 4 [[BROADCAST_SPLAT]], <4 x i1> splat (i1 true), <4 x i32> poison), !llvm.access.group [[ACC_GRP5:![0-9]+]]
; CHECK-NEXT:    [[TMP0]] = add nuw nsw <4 x i64> [[J2]], splat (i64 1)
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <4 x i64> [[TMP0]], splat (i64 2)
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i1> [[TMP1]], i64 0
; CHECK-NEXT:    br i1 [[TMP2]], label %[[LATCH3:.*]], label %[[INNER1]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       [[LATCH3]]:
; CHECK-NEXT:    store <4 x i32> [[WIDE_MASKED_GATHER]], ptr [[B]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    br label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4, !llvm.access.group !5
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @unrelated_access_group(ptr %a, ptr %b) {
; CHECK-LABEL: define void @unrelated_access_group(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[A]], align 4, !llvm.access.group [[ACC_GRP6:![0-9]+]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store i32 [[V_LCSSA]], ptr [[P]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4, !llvm.access.group !4
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @missing_access_group(ptr %a, ptr %b) {
; CHECK-LABEL: define void @missing_access_group(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[A]], align 4
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store i32 [[V_LCSSA]], ptr [[P]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP8]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

; Disjoint stores may advance in either direction.
define void @negative_stride(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @negative_stride(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x ptr> poison, ptr [[A]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x ptr> [[BROADCAST_SPLATINSERT]], <4 x ptr> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    br label %[[INNER1:.*]]
; CHECK:       [[INNER1]]:
; CHECK-NEXT:    [[J2:%.*]] = phi <4 x i64> [ zeroinitializer, %[[VECTOR_BODY]] ], [ [[TMP0:%.*]], %[[INNER1]] ]
; CHECK-NEXT:    [[WIDE_MASKED_GATHER:%.*]] = call <4 x i32> @llvm.masked.gather.v4i32.v4p0(<4 x ptr> align 4 [[BROADCAST_SPLAT]], <4 x i1> splat (i1 true), <4 x i32> poison)
; CHECK-NEXT:    [[TMP0]] = add nuw nsw <4 x i64> [[J2]], splat (i64 1)
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <4 x i64> [[TMP0]], splat (i64 2)
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i1> [[TMP1]], i64 0
; CHECK-NEXT:    br i1 [[TMP2]], label %[[LATCH3:.*]], label %[[INNER1]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       [[LATCH3]]:
; CHECK-NEXT:    [[WIDE_GEP:%.*]] = getelementptr inbounds i32, ptr [[B]], <4 x i64> <i64 0, i64 -1, i64 -2, i64 -3>
; CHECK-NEXT:    call void @llvm.masked.scatter.v4i32.v4p0(<4 x i32> [[WIDE_MASKED_GATHER]], <4 x ptr> align 4 [[WIDE_GEP]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    br label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %offset = sub nsw i64 0, %i
  %p = getelementptr inbounds i32, ptr %b, i64 %offset
  store i32 %v, ptr %p, align 4
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !6
exit:
  ret void
}
!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.vectorize.enable"}
!2 = !{!"llvm.loop.parallel_accesses", !3}
!3 = distinct !{}
!4 = distinct !{}
!5 = !{!4, !3}
!6 = distinct !{!6, !1}

; Static disambiguation complements the annotated inner store.
define void @partial_noalias(ptr %a, ptr noalias %b) {
; CHECK-LABEL: define void @partial_noalias(
; CHECK-SAME: ptr [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    br label %[[INNER1:.*]]
; CHECK:       [[INNER1]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i64> [ zeroinitializer, %[[VECTOR_BODY]] ], [ [[TMP3:%.*]], %[[INNER1]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[VEC_PHI]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = shl nuw nsw i64 [[TMP0]], 6
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[TMP1]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[B]], align 4
; CHECK-NEXT:    store <4 x i32> [[WIDE_LOAD]], ptr [[TMP2]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[TMP3]] = add nuw nsw <4 x i64> [[VEC_PHI]], splat (i64 1)
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq <4 x i64> [[TMP3]], splat (i64 2)
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x i1> [[TMP4]], i64 0
; CHECK-NEXT:    br i1 [[TMP5]], label %[[LATCH2:.*]], label %[[INNER1]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       [[LATCH2]]:
; CHECK-NEXT:    br label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [0, %entry], [%in, %latch]
  br label %inner
inner:
  %j = phi i64 [0, %outer], [%jn, %inner]
  %row = mul nuw nsw i64 %j, 64
  %idx = add nuw nsw i64 %row, %i
  %ap = getelementptr inbounds i32, ptr %a, i64 %idx
  %bp = getelementptr inbounds i32, ptr %b, i64 %i
  %v = load i32, ptr %bp, align 4
  store i32 %v, ptr %ap, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

; An uncovered potentially aliasing load still needs a runtime check.
define void @partial_checked(ptr %a, ptr %b) {
; CHECK-LABEL: define void @partial_checked(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_MEMCHECK:.*]]
; CHECK:       [[VECTOR_MEMCHECK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[A]], i64 272
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i64 16
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[A]], [[TMP1]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[B]], [[TMP0]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    br label %[[INNER1:.*]]
; CHECK:       [[INNER1]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i64> [ zeroinitializer, %[[VECTOR_BODY]] ], [ [[TMP5:%.*]], %[[INNER1]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i64> [[VEC_PHI]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = shl nuw nsw i64 [[TMP2]], 6
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[TMP3]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[B]], align 4
; CHECK-NEXT:    store <4 x i32> [[WIDE_LOAD]], ptr [[TMP4]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[TMP5]] = add nuw nsw <4 x i64> [[VEC_PHI]], splat (i64 1)
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq <4 x i64> [[TMP5]], splat (i64 2)
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[TMP6]], i64 0
; CHECK-NEXT:    br i1 [[TMP7]], label %[[LATCH2:.*]], label %[[INNER1]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       [[LATCH2]]:
; CHECK-NEXT:    br label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[SCALAR_PH]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[ROW:%.*]] = mul nuw nsw i64 [[J]], 64
; CHECK-NEXT:    [[IDX:%.*]] = add nuw nsw i64 [[ROW]], [[I]]
; CHECK-NEXT:    [[AP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[IDX]]
; CHECK-NEXT:    [[BP:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[BP]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr [[AP]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT]], label %[[OUTER]], !llvm.loop [[LOOP13:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [0, %entry], [%in, %latch]
  br label %inner
inner:
  %j = phi i64 [0, %outer], [%jn, %inner]
  %row = mul nuw nsw i64 %j, 64
  %idx = add nuw nsw i64 %row, %i
  %ap = getelementptr inbounds i32, ptr %a, i64 %idx
  %bp = getelementptr inbounds i32, ptr %b, i64 %i
  %v = load i32, ptr %bp, align 4
  store i32 %v, ptr %ap, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

; An uncovered load without a provable range must keep the loop scalar.
define void @partial_unbounded(ptr %a, ptr %b) {
; CHECK-LABEL: define void @partial_unbounded(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[ROW:%.*]] = mul nuw nsw i64 [[J]], 64
; CHECK-NEXT:    [[IDX:%.*]] = add nuw nsw i64 [[ROW]], [[I]]
; CHECK-NEXT:    [[AP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[IDX]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr [[AP]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP8]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [0, %entry], [%in, %latch]
  br label %inner
inner:
  %j = phi i64 [0, %outer], [%jn, %inner]
  %row = mul nuw nsw i64 %j, 64
  %idx = add nuw nsw i64 %row, %i
  %ap = getelementptr inbounds i32, ptr %a, i64 %idx
  %v = load i32, ptr %b, align 4
  store i32 %v, ptr %ap, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

; Different groups listed by the loop also discharge the pair.
define void @different_parallel_groups(ptr %a, ptr %b) {
; CHECK-LABEL: define void @different_parallel_groups(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x ptr> poison, ptr [[B]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x ptr> [[BROADCAST_SPLATINSERT]], <4 x ptr> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    br label %[[INNER1:.*]]
; CHECK:       [[INNER1]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i64> [ zeroinitializer, %[[VECTOR_BODY]] ], [ [[TMP3:%.*]], %[[INNER1]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[VEC_PHI]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = shl nuw nsw i64 [[TMP0]], 6
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[TMP1]]
; CHECK-NEXT:    [[WIDE_MASKED_GATHER:%.*]] = call <4 x i32> @llvm.masked.gather.v4i32.v4p0(<4 x ptr> align 4 [[BROADCAST_SPLAT]], <4 x i1> splat (i1 true), <4 x i32> poison), !llvm.access.group [[ACC_GRP6]]
; CHECK-NEXT:    store <4 x i32> [[WIDE_MASKED_GATHER]], ptr [[TMP2]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[TMP3]] = add nuw nsw <4 x i64> [[VEC_PHI]], splat (i64 1)
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq <4 x i64> [[TMP3]], splat (i64 2)
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x i1> [[TMP4]], i64 0
; CHECK-NEXT:    br i1 [[TMP5]], label %[[LATCH2:.*]], label %[[INNER1]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       [[LATCH2]]:
; CHECK-NEXT:    br label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [0, %entry], [%in, %latch]
  br label %inner
inner:
  %j = phi i64 [0, %outer], [%jn, %inner]
  %row = mul nuw nsw i64 %j, 64
  %idx = add nuw nsw i64 %row, %i
  %ap = getelementptr inbounds i32, ptr %a, i64 %idx
  %v = load i32, ptr %b, align 4, !llvm.access.group !4
  store i32 %v, ptr %ap, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !8
exit:
  ret void
}

!8 = distinct !{!8, !1, !7}
!7 = !{!"llvm.loop.parallel_accesses", !3, !4}

;.
; CHECK: [[ACC_GRP0]] = distinct !{}
; CHECK: [[LOOP1]] = distinct !{[[LOOP1]], [[META2:![0-9]+]], [[META3:![0-9]+]], [[META4:![0-9]+]]}
; CHECK: [[META2]] = !{!"llvm.loop.parallel_accesses", [[ACC_GRP0]]}
; CHECK: [[META3]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META4]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[ACC_GRP5]] = !{[[ACC_GRP6]], [[ACC_GRP0]]}
; CHECK: [[ACC_GRP6]] = distinct !{}
; CHECK: [[LOOP7]] = distinct !{[[LOOP7]], [[META2]], [[META3]], [[META4]]}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META9:![0-9]+]], [[META2]]}
; CHECK: [[META9]] = !{!"llvm.loop.vectorize.enable"}
; CHECK: [[LOOP10]] = distinct !{[[LOOP10]], [[META3]], [[META4]]}
; CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META2]], [[META3]], [[META4]]}
; CHECK: [[LOOP12]] = distinct !{[[LOOP12]], [[META2]], [[META3]], [[META4]]}
; CHECK: [[LOOP13]] = distinct !{[[LOOP13]], [[META2]], [[META3]]}
; CHECK: [[LOOP14]] = distinct !{[[LOOP14]], [[META15:![0-9]+]], [[META3]], [[META4]]}
; CHECK: [[META15]] = !{!"llvm.loop.parallel_accesses", [[ACC_GRP0]], [[ACC_GRP6]]}
;.
