; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=loop-vectorize,verify -force-vector-width=4 -enable-vplan-native-path < %s | FileCheck %s

; Parallel annotations do not make volatile or atomic operations widenable.
define void @volatile_load(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @volatile_load(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load volatile i32, ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0:![0-9]+]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store i32 [[V_LCSSA]], ptr [[P]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load volatile i32, ptr %a, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @volatile_store(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @volatile_store(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store volatile i32 [[V_LCSSA]], ptr [[P]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store volatile i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @atomic_load_unordered(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @atomic_load_unordered(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load atomic i32, ptr [[A]] unordered, align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store i32 [[V_LCSSA]], ptr [[P]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load atomic i32, ptr %a unordered, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @atomic_load_monotonic(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @atomic_load_monotonic(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load atomic i32, ptr [[A]] monotonic, align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store i32 [[V_LCSSA]], ptr [[P]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load atomic i32, ptr %a monotonic, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @atomic_load_acquire(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @atomic_load_acquire(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load atomic i32, ptr [[A]] acquire, align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store i32 [[V_LCSSA]], ptr [[P]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load atomic i32, ptr %a acquire, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @atomic_load_seq_cst(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @atomic_load_seq_cst(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load atomic i32, ptr [[A]] seq_cst, align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store i32 [[V_LCSSA]], ptr [[P]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load atomic i32, ptr %a seq_cst, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store i32 %v, ptr %p, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @atomic_store_unordered(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @atomic_store_unordered(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store atomic i32 [[V_LCSSA]], ptr [[P]] unordered, align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store atomic i32 %v, ptr %p unordered, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @atomic_store_monotonic(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @atomic_store_monotonic(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store atomic i32 [[V_LCSSA]], ptr [[P]] monotonic, align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store atomic i32 %v, ptr %p monotonic, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @atomic_store_release(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @atomic_store_release(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store atomic i32 [[V_LCSSA]], ptr [[P]] release, align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store atomic i32 %v, ptr %p release, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

define void @atomic_store_seq_cst(ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: define void @atomic_store_seq_cst(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IN:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[JN:%.*]], %[[INNER]] ]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[JN]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[JC:%.*]] = icmp eq i64 [[JN]], 2
; CHECK-NEXT:    br i1 [[JC]], label %[[LATCH]], label %[[INNER]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[INNER]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store atomic i32 [[V_LCSSA]], ptr [[P]] seq_cst, align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[IN]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[IC:%.*]] = icmp eq i64 [[IN]], 4
; CHECK-NEXT:    br i1 [[IC]], label %[[EXIT:.*]], label %[[OUTER]], !llvm.loop [[LOOP1]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer
outer:
  %i = phi i64 [ 0, %entry ], [ %in, %latch ]
  br label %inner
inner:
  %j = phi i64 [ 0, %outer ], [ %jn, %inner ]
  %v = load i32, ptr %a, align 4, !llvm.access.group !3
  %jn = add nuw nsw i64 %j, 1
  %jc = icmp eq i64 %jn, 2
  br i1 %jc, label %latch, label %inner
latch:
  %p = getelementptr inbounds i32, ptr %b, i64 %i
  store atomic i32 %v, ptr %p seq_cst, align 4, !llvm.access.group !3
  %in = add nuw nsw i64 %i, 1
  %ic = icmp eq i64 %in, 4
  br i1 %ic, label %exit, label %outer, !llvm.loop !0
exit:
  ret void
}

!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.vectorize.enable"}
!2 = !{!"llvm.loop.parallel_accesses", !3}
!3 = distinct !{}
!4 = distinct !{}
!5 = !{!4, !3}
;.
; CHECK: [[ACC_GRP0]] = distinct !{}
; CHECK: [[LOOP1]] = distinct !{[[LOOP1]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META2]] = !{!"llvm.loop.vectorize.enable"}
; CHECK: [[META3]] = !{!"llvm.loop.parallel_accesses", [[ACC_GRP0]]}
;.
