; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=loop-vectorize -force-vector-width=2 -S %s | FileCheck %s

; Tests for Loop::isAnnotatedParallel end-to-end through the loop vectorizer.
; All loops below use indirect (gather/scatter) accesses, so they can only be
; proven dependence-free - and thus vectorized - via the
; !llvm.loop.parallel_accesses annotation, making the annotation load-bearing.

; A loop tagged llvm.loop.parallel_accesses is parallel when every memory
; accessing instruction carries the loop's access group, so it vectorizes.
define void @parallel(ptr noalias %a, ptr noalias %idx, i64 %n) {
; CHECK-LABEL: define void @parallel(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i64, ptr [[IDX]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x i64>, ptr [[TMP0]], align 4, !llvm.access.group [[ACC_GRP0:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i64> [[WIDE_LOAD]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i64> [[WIDE_LOAD]], i64 1
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr double, ptr [[A]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr double, ptr [[A]], i64 [[TMP2]]
; CHECK-NEXT:    [[TMP5:%.*]] = load double, ptr [[TMP3]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[TMP6:%.*]] = load double, ptr [[TMP4]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x double> poison, double [[TMP5]], i32 0
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x double> [[TMP7]], double [[TMP6]], i32 1
; CHECK-NEXT:    [[TMP9:%.*]] = fadd <2 x double> [[TMP8]], splat (double 1.000000e+00)
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <2 x double> [[TMP9]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x double> [[TMP9]], i64 1
; CHECK-NEXT:    store double [[TMP10]], ptr [[TMP3]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    store double [[TMP11]], ptr [[TMP4]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP12]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP1:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GIDX:%.*]] = getelementptr i64, ptr [[IDX]], i64 [[I]]
; CHECK-NEXT:    [[J:%.*]] = load i64, ptr [[GIDX]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[GA:%.*]] = getelementptr double, ptr [[A]], i64 [[J]]
; CHECK-NEXT:    [[V:%.*]] = load double, ptr [[GA]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[V2:%.*]] = fadd double [[V]], 1.000000e+00
; CHECK-NEXT:    store double [[V2]], ptr [[GA]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; CHECK-NEXT:    [[C:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT]], label %[[LOOP]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %gidx = getelementptr i64, ptr %idx, i64 %i
  %j = load i64, ptr %gidx, !llvm.access.group !1
  %ga = getelementptr double, ptr %a, i64 %j
  %v = load double, ptr %ga, !llvm.access.group !1
  %v2 = fadd double %v, 1.0
  store double %v2, ptr %ga, !llvm.access.group !1
  %i.next = add i64 %i, 1
  %c = icmp eq i64 %i.next, %n
  br i1 %c, label %exit, label %loop, !llvm.loop !0

exit:
  ret void
}

; A memory accessing instruction without the loop's access group (the load of
; %v) makes the loop non-parallel even though it is tagged parallel_accesses, so
; the indirect accesses cannot be proven independent and it does not vectorize.
define void @missing_access_group(ptr noalias %a, ptr noalias %idx, i64 %n) {
; CHECK-LABEL: define void @missing_access_group(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GIDX:%.*]] = getelementptr i64, ptr [[IDX]], i64 [[I]]
; CHECK-NEXT:    [[J:%.*]] = load i64, ptr [[GIDX]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[GA:%.*]] = getelementptr double, ptr [[A]], i64 [[J]]
; CHECK-NEXT:    [[V:%.*]] = load double, ptr [[GA]], align 8
; CHECK-NEXT:    [[V2:%.*]] = fadd double [[V]], 1.000000e+00
; CHECK-NEXT:    store double [[V2]], ptr [[GA]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; CHECK-NEXT:    [[C:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %gidx = getelementptr i64, ptr %idx, i64 %i
  %j = load i64, ptr %gidx, !llvm.access.group !1
  %ga = getelementptr double, ptr %a, i64 %j
  %v = load double, ptr %ga
  %v2 = fadd double %v, 1.0
  store double %v2, ptr %ga, !llvm.access.group !1
  %i.next = add i64 %i, 1
  %c = icmp eq i64 %i.next, %n
  br i1 %c, label %exit, label %loop, !llvm.loop !0

exit:
  ret void
}

; An llvm.assume inside a loop annotated with !llvm.loop.parallel_accesses must
; not make the loop appear non-parallel, even though the assume does not carry
; the loop's !llvm.access.group. The assume only writes inaccessible memory, so
; it can never introduce a loop-carried dependence; Loop::isAnnotatedParallel
; ignores it for this reason. Without that, the indirect (gather/scatter)
; accesses below could not be proven independent and the loop would fail to
; vectorize (PR115595).
define void @parallel_with_assume(ptr noalias %a, ptr noalias %idx, i64 %n) {
; CHECK-LABEL: define void @parallel_with_assume(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GIDX:%.*]] = getelementptr i64, ptr [[IDX]], i64 [[I]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x i64>, ptr [[GIDX]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[WIDE_GEP:%.*]] = getelementptr double, ptr [[A]], <2 x i64> [[WIDE_LOAD]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x ptr> [[WIDE_GEP]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x ptr> [[WIDE_GEP]], i64 1
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[TMP1]], i64 8) ]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[TMP2]], i64 8) ]
; CHECK-NEXT:    [[TMP3:%.*]] = load double, ptr [[TMP1]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[TMP4:%.*]] = load double, ptr [[TMP2]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x double> poison, double [[TMP3]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x double> [[TMP5]], double [[TMP4]], i32 1
; CHECK-NEXT:    [[TMP7:%.*]] = fadd <2 x double> [[TMP6]], splat (double 1.000000e+00)
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <2 x double> [[TMP7]], i64 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <2 x double> [[TMP7]], i64 1
; CHECK-NEXT:    store double [[TMP8]], ptr [[TMP1]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    store double [[TMP9]], ptr [[TMP2]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[I]], 2
; CHECK-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_BLOCK:.*]], label %[[LOOP]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP2:.*]]
; CHECK:       [[LOOP2]]:
; CHECK-NEXT:    [[I1:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[I_NEXT:%.*]], %[[LOOP2]] ]
; CHECK-NEXT:    [[GIDX1:%.*]] = getelementptr i64, ptr [[IDX]], i64 [[I1]]
; CHECK-NEXT:    [[J:%.*]] = load i64, ptr [[GIDX1]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[GA:%.*]] = getelementptr double, ptr [[A]], i64 [[J]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[GA]], i64 8) ]
; CHECK-NEXT:    [[V:%.*]] = load double, ptr [[GA]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[V2:%.*]] = fadd double [[V]], 1.000000e+00
; CHECK-NEXT:    store double [[V2]], ptr [[GA]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I1]], 1
; CHECK-NEXT:    [[C:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT]], label %[[LOOP2]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %gidx = getelementptr i64, ptr %idx, i64 %i
  %j = load i64, ptr %gidx, !llvm.access.group !1
  %ga = getelementptr double, ptr %a, i64 %j
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %ga, i64 8) ]
  %v = load double, ptr %ga, !llvm.access.group !1
  %v2 = fadd double %v, 1.0
  store double %v2, ptr %ga, !llvm.access.group !1
  %i.next = add i64 %i, 1
  %c = icmp eq i64 %i.next, %n
  br i1 %c, label %exit, label %loop, !llvm.loop !0

exit:
  ret void
}

declare void @llvm.assume(i1)

; A non-assume call that accesses inaccessible memory (readwrite) can carry
; hidden state across iterations, so unlike llvm.assume it is NOT ignored by
; Loop::isAnnotatedParallel: an un-annotated such call makes the loop
; non-parallel, so the indirect accesses cannot be proven independent and the
; loop does not vectorize. The call has a vector variant so that it clears the
; "call cannot be vectorized" legality check; that makes the parallel gate (and
; thus this case) actually load-bearing here. Note isAnnotatedParallel must
; check for llvm.assume specifically rather than onlyAccessesInaccessibleMemory:
; the latter is also true for this readwrite call and would wrongly vectorize.
define void @inaccessible_mem_call(ptr noalias %a, ptr noalias %idx, i64 %n) {
; CHECK-LABEL: define void @inaccessible_mem_call(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GIDX:%.*]] = getelementptr i64, ptr [[IDX]], i64 [[I]]
; CHECK-NEXT:    [[J:%.*]] = load i64, ptr [[GIDX]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[GA:%.*]] = getelementptr double, ptr [[A]], i64 [[J]]
; CHECK-NEXT:    [[V:%.*]] = load double, ptr [[GA]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[R:%.*]] = call double @foo(double [[V]]) #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    store double [[R]], ptr [[GA]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; CHECK-NEXT:    [[C:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP6]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %gidx = getelementptr i64, ptr %idx, i64 %i
  %j = load i64, ptr %gidx, !llvm.access.group !1
  %ga = getelementptr double, ptr %a, i64 %j
  %v = load double, ptr %ga, !llvm.access.group !1
  %r = call double @foo(double %v) #0
  store double %r, ptr %ga, !llvm.access.group !1
  %i.next = add i64 %i, 1
  %c = icmp eq i64 %i.next, %n
  br i1 %c, label %exit, label %loop, !llvm.loop !0

exit:
  ret void
}

declare double @foo(double) memory(inaccessiblemem: readwrite)
declare <2 x double> @foo_vec(<2 x double>)

attributes #0 = { nounwind "vector-function-abi-variant"="_ZGV_LLVM_N2v_foo(foo_vec)" }

!0 = distinct !{!0, !2}
!1 = distinct !{}
!2 = !{!"llvm.loop.parallel_accesses", !1}
;.
; CHECK: [[ACC_GRP0]] = distinct !{}
; CHECK: [[LOOP1]] = distinct !{[[LOOP1]], [[META2:![0-9]+]], [[META3:![0-9]+]], [[META4:![0-9]+]]}
; CHECK: [[META2]] = !{!"llvm.loop.parallel_accesses", [[ACC_GRP0]]}
; CHECK: [[META3]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META4]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META2]], [[META4]], [[META3]]}
; CHECK: [[LOOP6]] = distinct !{[[LOOP6]], [[META2]]}
; CHECK: [[LOOP7]] = distinct !{[[LOOP7]], [[META2]], [[META3]], [[META4]]}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META2]], [[META4]], [[META3]]}
;.
