; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=loop-vectorize -force-vector-interleave=4 -force-vector-width=4 -vplan-try-to-realign-loop -S %s | FileCheck %s

; The body's load/store carry align 32, larger than VF*EltSize = 16. After
; unrolling to UF=4 the per-part recipes retain align 32, but for parts
; whose offset (part*VF*EltSize) is not a multiple of 32 the actual
; alignment is only 16.
;
; The realign body executes the body once with a shifted index. With
; TC=45, Stride=16, VF=4, RestartIdx=29, the part offsets (in bytes
; relative to the live-in base) are 116, 132, 148, 164. gcd(32, 116)=4,
; so claiming align 32 for every part would be unsound.
;
; tryToRealignLoop intersects the downgraded alignment with VF*EltSize
; (=16) AND with the runtime base shift (RestartIdx * EltSize = 116).
; gcd(commonAlignment(32, 116), 16) = gcd(4, 16) = 4, giving a uniform
; align 4 claim that is sound for every part.
define void @realign_overaligned_uf4(ptr noalias %dst, ptr noalias %src) {
; CHECK-LABEL: define void @realign_overaligned_uf4(
; CHECK-SAME: ptr noalias [[DST:%.*]], ptr noalias [[SRC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 12
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[TMP0]], align 32
; CHECK-NEXT:    [[WIDE_LOAD1:%.*]] = load <4 x i32>, ptr [[TMP1]], align 32
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i32>, ptr [[TMP2]], align 32
; CHECK-NEXT:    [[WIDE_LOAD3:%.*]] = load <4 x i32>, ptr [[TMP3]], align 32
; CHECK-NEXT:    [[TMP4:%.*]] = add <4 x i32> [[WIDE_LOAD]], splat (i32 1)
; CHECK-NEXT:    [[TMP5:%.*]] = add <4 x i32> [[WIDE_LOAD1]], splat (i32 1)
; CHECK-NEXT:    [[TMP6:%.*]] = add <4 x i32> [[WIDE_LOAD2]], splat (i32 1)
; CHECK-NEXT:    [[TMP7:%.*]] = add <4 x i32> [[WIDE_LOAD3]], splat (i32 1)
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i32, ptr [[TMP8]], i64 4
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[TMP8]], i64 8
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i32, ptr [[TMP8]], i64 12
; CHECK-NEXT:    store <4 x i32> [[TMP4]], ptr [[TMP8]], align 32
; CHECK-NEXT:    store <4 x i32> [[TMP5]], ptr [[TMP9]], align 32
; CHECK-NEXT:    store <4 x i32> [[TMP6]], ptr [[TMP10]], align 32
; CHECK-NEXT:    store <4 x i32> [[TMP7]], ptr [[TMP11]], align 32
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 16
; CHECK-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 32
; CHECK-NEXT:    br i1 [[TMP12]], label %[[VECTOR_REALIGN_PH:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[VECTOR_REALIGN_PH]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_REALIGN_PH1:.*]]
; CHECK:       [[VECTOR_REALIGN_PH1]]:
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[IV1:%.*]] = phi i64 [ 29, %[[VECTOR_REALIGN_PH1]] ], [ [[INDEX_NEXT7:%.*]], %[[LOOP1]] ]
; CHECK-NEXT:    [[GEP_SRC1:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[IV1]]
; CHECK-NEXT:    [[WIDE_LOAD5:%.*]] = load <4 x i32>, ptr [[GEP_SRC1]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = add <4 x i32> [[WIDE_LOAD5]], splat (i32 1)
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[IV1]]
; CHECK-NEXT:    store <4 x i32> [[TMP14]], ptr [[TMP15]], align 4
; CHECK-NEXT:    [[INDEX_NEXT7]] = add nuw i64 [[IV1]], 4
; CHECK-NEXT:    [[REALIGN_CMP:%.*]] = icmp eq i64 [[INDEX_NEXT7]], 45
; CHECK-NEXT:    br i1 [[REALIGN_CMP]], label %[[EXIT1:.*]], label %[[LOOP1]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[LOOP2:.*]]
; CHECK:       [[LOOP2]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 32, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP2]] ]
; CHECK-NEXT:    [[GEP_SRC:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[IV]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[GEP_SRC]], align 32
; CHECK-NEXT:    [[INC:%.*]] = add i32 [[V]], 1
; CHECK-NEXT:    [[GEP_DST:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[IV]]
; CHECK-NEXT:    store i32 [[INC]], ptr [[GEP_DST]], align 32
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[IV_NEXT]], 45
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT1]], label %[[LOOP2]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.src = getelementptr inbounds i32, ptr %src, i64 %iv
  %v = load i32, ptr %gep.src, align 32
  %inc = add i32 %v, 1
  %gep.dst = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 %inc, ptr %gep.dst, align 32
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 45
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
