; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S < %s -p loop-vectorize -force-vector-width=4 -enable-early-exit-vectorization | FileCheck %s

declare void @init_mem(ptr, i64)

; Test that rotated early exit loops (where the latch has the uncountable exit)
; are properly vectorized. The loads in the latch block should be widened and
; the early exit condition should use vector operations.
define i64 @rotated_early_exit_vectorized_loads() {
; CHECK-LABEL: define i64 @rotated_early_exit_vectorized_loads() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[P1:%.*]] = alloca [1024 x i8], align 1
; CHECK-NEXT:    [[P2:%.*]] = alloca [1024 x i8], align 1
; CHECK-NEXT:    call void @init_mem(ptr [[P1]], i64 1024)
; CHECK-NEXT:    call void @init_mem(ptr [[P2]], i64 1024)
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    br label [[VECTOR_BODY1:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX1:%.*]] = phi i64 [ 0, [[VECTOR_BODY]] ], [ [[INDEX_NEXT3:%.*]], [[LOOP_END:%.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P1]], i64 [[INDEX1]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[P2]], i64 [[INDEX1]]
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i8>, ptr [[TMP1]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], [[WIDE_LOAD2]]
; CHECK-NEXT:    [[INDEX_NEXT3]] = add nuw i64 [[INDEX1]], 4
; CHECK-NEXT:    [[TMP3:%.*]] = freeze <4 x i1> [[TMP2]]
; CHECK-NEXT:    [[EXITCOND:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT3]], 64
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[LOOP_BODY:%.*]], label [[LOOP_END]]
; CHECK:       vector.body.interim:
; CHECK-NEXT:    br i1 [[TMP5]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY1]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[LOOP_END1:%.*]]
; CHECK:       vector.early.exit:
; CHECK-NEXT:    [[TMP6:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP2]], i1 false)
; CHECK-NEXT:    [[TMP7:%.*]] = add i64 [[INDEX1]], [[TMP6]]
; CHECK-NEXT:    br label [[LOOP_END1]]
; CHECK:       loop.end:
; CHECK-NEXT:    [[RETVAL1:%.*]] = phi i64 [ [[TMP7]], [[LOOP_BODY]] ], [ 64, [[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    ret i64 [[RETVAL1]]
;
entry:
  %p1 = alloca [1024 x i8]
  %p2 = alloca [1024 x i8]
  call void @init_mem(ptr %p1, i64 1024)
  call void @init_mem(ptr %p2, i64 1024)
  br label %loop.header

; The header has the countable exit
loop.header:
  %index = phi i64 [ %index.next, %loop.body ], [ 0, %entry ]
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 64
  br i1 %exitcond, label %loop.body, label %loop.end

; The latch has the uncountable (early) exit - this is the "rotated" case
loop.body:
  %gep1 = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %gep1, align 1
  %gep2 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %gep2, align 1
  %cmp = icmp eq i8 %ld1, %ld2
  br i1 %cmp, label %loop.end, label %loop.header

loop.end:
  %retval = phi i64 [ 64, %loop.header ], [ %index, %loop.body ]
  ret i64 %retval
}

; Rotated early exit with i32 data type
define i64 @rotated_early_exit_i32() {
; CHECK-LABEL: define i64 @rotated_early_exit_i32() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[P1:%.*]] = alloca [1024 x i32], align 4
; CHECK-NEXT:    [[P2:%.*]] = alloca [1024 x i32], align 4
; CHECK-NEXT:    call void @init_mem(ptr [[P1]], i64 4096)
; CHECK-NEXT:    call void @init_mem(ptr [[P2]], i64 4096)
; CHECK-NEXT:    br label [[VECTOR_BODY1:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX1:%.*]] = phi i64 [ 0, [[VECTOR_BODY1]] ], [ [[INDEX_NEXT3:%.*]], [[LOOP_END:%.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i32, ptr [[P1]], i64 [[INDEX1]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[TMP0]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[P2]], i64 [[INDEX1]]
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i32>, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq <4 x i32> [[WIDE_LOAD]], [[WIDE_LOAD2]]
; CHECK-NEXT:    [[INDEX_NEXT3]] = add nuw i64 [[INDEX1]], 4
; CHECK-NEXT:    [[TMP3:%.*]] = freeze <4 x i1> [[TMP2]]
; CHECK-NEXT:    [[EXITCOND:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT3]], 128
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[LOOP_BODY:%.*]], label [[LOOP_END]]
; CHECK:       vector.body.interim:
; CHECK-NEXT:    br i1 [[TMP5]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[LOOP_END1:%.*]]
; CHECK:       vector.early.exit:
; CHECK-NEXT:    [[TMP6:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP2]], i1 false)
; CHECK-NEXT:    [[TMP7:%.*]] = add i64 [[INDEX1]], [[TMP6]]
; CHECK-NEXT:    br label [[LOOP_END1]]
; CHECK:       loop.end:
; CHECK-NEXT:    [[RETVAL1:%.*]] = phi i64 [ [[TMP7]], [[LOOP_BODY]] ], [ 128, [[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    ret i64 [[RETVAL1]]
;
entry:
  %p1 = alloca [1024 x i32]
  %p2 = alloca [1024 x i32]
  call void @init_mem(ptr %p1, i64 4096)
  call void @init_mem(ptr %p2, i64 4096)
  br label %loop.header

loop.header:
  %index = phi i64 [ %index.next, %loop.body ], [ 0, %entry ]
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 128
  br i1 %exitcond, label %loop.body, label %loop.end

loop.body:
  %gep1 = getelementptr inbounds i32, ptr %p1, i64 %index
  %ld1 = load i32, ptr %gep1, align 4
  %gep2 = getelementptr inbounds i32, ptr %p2, i64 %index
  %ld2 = load i32, ptr %gep2, align 4
  %cmp = icmp eq i32 %ld1, %ld2
  br i1 %cmp, label %loop.end, label %loop.header

loop.end:
  %retval = phi i64 [ 128, %loop.header ], [ %index, %loop.body ]
  ret i64 %retval
}

; Rotated early exit with non-zero start index
define i64 @rotated_early_exit_with_offset() {
; CHECK-LABEL: define i64 @rotated_early_exit_with_offset() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[P1:%.*]] = alloca [1024 x i8], align 1
; CHECK-NEXT:    [[P2:%.*]] = alloca [1024 x i8], align 1
; CHECK-NEXT:    call void @init_mem(ptr [[P1]], i64 1024)
; CHECK-NEXT:    call void @init_mem(ptr [[P2]], i64 1024)
; CHECK-NEXT:    br label [[VECTOR_BODY1:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX1:%.*]] = phi i64 [ 0, [[VECTOR_BODY1]] ], [ [[INDEX_NEXT3:%.*]], [[LOOP_END:%.*]] ]
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = add i64 10, [[INDEX1]]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P1]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[P2]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i8>, ptr [[TMP1]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], [[WIDE_LOAD2]]
; CHECK-NEXT:    [[INDEX_NEXT3]] = add nuw i64 [[INDEX1]], 4
; CHECK-NEXT:    [[TMP3:%.*]] = freeze <4 x i1> [[TMP2]]
; CHECK-NEXT:    [[EXITCOND:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT3]], 64
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[LOOP_BODY:%.*]], label [[LOOP_END]]
; CHECK:       vector.body.interim:
; CHECK-NEXT:    br i1 [[TMP5]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[LOOP_END1:%.*]]
; CHECK:       vector.early.exit:
; CHECK-NEXT:    [[TMP6:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP2]], i1 false)
; CHECK-NEXT:    [[TMP7:%.*]] = add i64 [[INDEX1]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 10, [[TMP7]]
; CHECK-NEXT:    br label [[LOOP_END1]]
; CHECK:       loop.end:
; CHECK-NEXT:    [[RETVAL1:%.*]] = phi i64 [ [[TMP8]], [[LOOP_BODY]] ], [ 74, [[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    ret i64 [[RETVAL1]]
;
entry:
  %p1 = alloca [1024 x i8]
  %p2 = alloca [1024 x i8]
  call void @init_mem(ptr %p1, i64 1024)
  call void @init_mem(ptr %p2, i64 1024)
  br label %loop.header

loop.header:
  %index = phi i64 [ %index.next, %loop.body ], [ 10, %entry ]
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 74
  br i1 %exitcond, label %loop.body, label %loop.end

loop.body:
  %gep1 = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %gep1, align 1
  %gep2 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %gep2, align 1
  %cmp = icmp eq i8 %ld1, %ld2
  br i1 %cmp, label %loop.end, label %loop.header

loop.end:
  %retval = phi i64 [ 74, %loop.header ], [ %index, %loop.body ]
  ret i64 %retval
}

; Rotated early exit where exit returns a constant (no live-out)
define i64 @rotated_early_exit_constant_return() {
; CHECK-LABEL: define i64 @rotated_early_exit_constant_return() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[P1:%.*]] = alloca [1024 x i8], align 1
; CHECK-NEXT:    [[P2:%.*]] = alloca [1024 x i8], align 1
; CHECK-NEXT:    call void @init_mem(ptr [[P1]], i64 1024)
; CHECK-NEXT:    call void @init_mem(ptr [[P2]], i64 1024)
; CHECK-NEXT:    br label [[VECTOR_BODY1:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX1:%.*]] = phi i64 [ 0, [[VECTOR_BODY1]] ], [ [[INDEX_NEXT3:%.*]], [[LOOP_END:%.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P1]], i64 [[INDEX1]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[P2]], i64 [[INDEX1]]
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <4 x i8>, ptr [[TMP1]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], [[WIDE_LOAD2]]
; CHECK-NEXT:    [[INDEX_NEXT3]] = add nuw i64 [[INDEX1]], 4
; CHECK-NEXT:    [[TMP3:%.*]] = freeze <4 x i1> [[TMP2]]
; CHECK-NEXT:    [[EXITCOND:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT3]], 64
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[LOOP_BODY:%.*]], label [[LOOP_END]]
; CHECK:       vector.body.interim:
; CHECK-NEXT:    br i1 [[TMP5]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[LOOP_END1:%.*]]
; CHECK:       vector.early.exit:
; CHECK-NEXT:    br label [[LOOP_END1]]
; CHECK:       loop.end:
; CHECK-NEXT:    [[RETVAL:%.*]] = phi i64 [ 1, [[LOOP_BODY]] ], [ 0, [[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    ret i64 [[RETVAL]]
;
entry:
  %p1 = alloca [1024 x i8]
  %p2 = alloca [1024 x i8]
  call void @init_mem(ptr %p1, i64 1024)
  call void @init_mem(ptr %p2, i64 1024)
  br label %loop.header

loop.header:
  %index = phi i64 [ %index.next, %loop.body ], [ 0, %entry ]
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 64
  br i1 %exitcond, label %loop.body, label %loop.end

loop.body:
  %gep1 = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %gep1, align 1
  %gep2 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %gep2, align 1
  %cmp = icmp eq i8 %ld1, %ld2
  br i1 %cmp, label %loop.end, label %loop.header

loop.end:
  ; Both exits return constants, no data-dependent live-out
  %retval = phi i64 [ 0, %loop.header ], [ 1, %loop.body ]
  ret i64 %retval
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]], [[META2]]}
;.
