; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --filter "br i1|!prof" --version 6
; RUN: opt -passes=loop-vectorize -tail-folding-policy=must-fold-tail -force-vector-width=4 -force-vector-interleave=1 -S %s | FileCheck %s --check-prefix=VF4IC1
; RUN: opt -passes=loop-vectorize -tail-folding-policy=must-fold-tail -force-vector-width=2 -force-vector-interleave=2 -S %s | FileCheck %s --check-prefix=VF2IC2

; Folding the tail masks the body on the header mask, on a branch VPlan
; introduces itself. Its weights are known - a vector iteration only executes if
; it has an active lane - and recording them keeps the probabilities of the
; blocks below it derivable: the guards of the replicate region for the store
; predicated on %c keep the weights of %c, rather than coming out unknown
; because the header mask branch above them has no probability.
;
; The load of %i executes on every iteration and is guarded only because the tail
; is folded and it is scalarized, so its guards are conditioned on the lane mask,
; for which there is no probability to record.
define void @tail_folded_predicated_scatter(ptr noalias %A, ptr noalias %idx, i32 %n) !prof !0 {
;
;
; VF4IC1-LABEL: define void @tail_folded_predicated_scatter(
; VF4IC1-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]], i32 [[N:%.*]]) !prof [[PROF0:![0-9]+]] {
; VF4IC1:    br i1 [[TMP2:%.*]], [[PRED_LOAD_IF:label %.*]], [[PRED_LOAD_CONTINUE:label %.*]], !prof [[PROF1:![0-9]+]]
; VF4IC1:    br i1 [[TMP7:%.*]], [[PRED_LOAD_IF1:label %.*]], [[PRED_LOAD_CONTINUE2:label %.*]], !prof [[PROF1]]
; VF4IC1:    br i1 [[TMP13:%.*]], [[PRED_LOAD_IF3:label %.*]], [[PRED_LOAD_CONTINUE4:label %.*]], !prof [[PROF1]]
; VF4IC1:    br i1 [[TMP19:%.*]], [[PRED_LOAD_IF5:label %.*]], [[PRED_LOAD_CONTINUE6:label %.*]], !prof [[PROF1]]
; VF4IC1:    br i1 [[TMP27:%.*]], [[PRED_STORE_IF:label %.*]], [[PRED_STORE_CONTINUE:label %.*]], !prof [[PROF2:![0-9]+]]
; VF4IC1:    br i1 [[TMP30:%.*]], [[PRED_STORE_IF7:label %.*]], [[PRED_STORE_CONTINUE8:label %.*]], !prof [[PROF2]]
; VF4IC1:    br i1 [[TMP33:%.*]], [[PRED_STORE_IF9:label %.*]], [[PRED_STORE_CONTINUE10:label %.*]], !prof [[PROF2]]
; VF4IC1:    br i1 [[TMP36:%.*]], [[PRED_STORE_IF11:label %.*]], [[PRED_STORE_CONTINUE12:label %.*]], !prof [[PROF2]]
; VF4IC1:    br i1 [[TMP39:%.*]], [[MIDDLE_BLOCK:label %.*]], [[VECTOR_BODY:label %.*]], !prof [[PROF3:![0-9]+]], !llvm.loop [[LOOP4:![0-9]+]]
;
; VF2IC2-LABEL: define void @tail_folded_predicated_scatter(
; VF2IC2-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]], i32 [[N:%.*]]) !prof [[PROF0:![0-9]+]] {
; VF2IC2:    br i1 [[TMP3:%.*]], [[PRED_LOAD_IF:label %.*]], [[PRED_LOAD_CONTINUE:label %.*]], !prof [[PROF1:![0-9]+]]
; VF2IC2:    br i1 [[TMP8:%.*]], [[PRED_LOAD_IF1:label %.*]], [[PRED_LOAD_CONTINUE2:label %.*]], !prof [[PROF1]]
; VF2IC2:    br i1 [[TMP14:%.*]], [[PRED_LOAD_IF3:label %.*]], [[PRED_LOAD_CONTINUE4:label %.*]], !prof [[PROF1]]
; VF2IC2:    br i1 [[TMP20:%.*]], [[PRED_LOAD_IF5:label %.*]], [[PRED_LOAD_CONTINUE6:label %.*]], !prof [[PROF1]]
; VF2IC2:    br i1 [[TMP30:%.*]], [[PRED_STORE_IF:label %.*]], [[PRED_STORE_CONTINUE:label %.*]], !prof [[PROF2:![0-9]+]]
; VF2IC2:    br i1 [[TMP33:%.*]], [[PRED_STORE_IF7:label %.*]], [[PRED_STORE_CONTINUE8:label %.*]], !prof [[PROF2]]
; VF2IC2:    br i1 [[TMP36:%.*]], [[PRED_STORE_IF9:label %.*]], [[PRED_STORE_CONTINUE10:label %.*]], !prof [[PROF2]]
; VF2IC2:    br i1 [[TMP39:%.*]], [[PRED_STORE_IF11:label %.*]], [[PRED_STORE_CONTINUE12:label %.*]], !prof [[PROF2]]
; VF2IC2:    br i1 [[TMP42:%.*]], [[MIDDLE_BLOCK:label %.*]], [[VECTOR_BODY:label %.*]], !prof [[PROF3:![0-9]+]], !llvm.loop [[LOOP4:![0-9]+]]
;
entry:
  br label %loop.header

loop.header:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep.i = getelementptr inbounds i32, ptr %idx, i32 %iv
  %i = load i32, ptr %gep.i, align 4
  %c = icmp sgt i32 %i, 0
  br i1 %c, label %if.then, label %latch, !prof !1

if.then:
  %gep.a = getelementptr inbounds i32, ptr %A, i32 %i
  store i32 42, ptr %gep.a, align 4
  br label %latch

latch:
  %iv.next = add nuw nsw i32 %iv, 1
  %ec = icmp eq i32 %iv.next, %n
  br i1 %ec, label %exit, label %loop.header, !prof !2

exit:
  ret void
}


; The trip count of 64 is a multiple of the step, so every lane slot is active and
; the guards conditioned on the lane mask alone are taken essentially always; the
; unlikely side is kept at 1 rather than 0.
define void @tail_folded_exact_multiple(ptr noalias %A, ptr noalias %idx) !prof !0 {
; VF4IC1-LABEL: define void @tail_folded_exact_multiple(
; VF4IC1-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]]) !prof [[PROF0]] {
; VF4IC1:    br i1 [[TMP9:%.*]], [[MIDDLE_BLOCK:label %.*]], [[VECTOR_BODY:label %.*]], !prof [[PROF3]], !llvm.loop [[LOOP8:![0-9]+]]
;
; VF2IC2-LABEL: define void @tail_folded_exact_multiple(
; VF2IC2-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]]) !prof [[PROF0]] {
; VF2IC2:    br i1 [[TMP10:%.*]], [[MIDDLE_BLOCK:label %.*]], [[VECTOR_BODY:label %.*]], !prof [[PROF3]], !llvm.loop [[LOOP8:![0-9]+]]
;
entry:
  br label %loop.header

loop.header:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep.i = getelementptr inbounds i32, ptr %idx, i32 %iv
  %i = load i32, ptr %gep.i, align 4
  %gep.a = getelementptr inbounds i32, ptr %A, i32 %i
  store i32 42, ptr %gep.a, align 4
  br label %latch

latch:
  %iv.next = add nuw nsw i32 %iv, 1
  %ec = icmp eq i32 %iv.next, 64
  br i1 %ec, label %exit, label %loop.header, !prof !2

exit:
  ret void
}

; Without weights on the latch there is no estimated trip count, so the fraction
; of active lane slots is unknown and the guards must stay marked unknown rather
; than be scaled by a guessed one.
define void @tail_folded_no_estimate(ptr noalias %A, ptr noalias %idx, i32 %n) !prof !0 {
; VF4IC1-LABEL: define void @tail_folded_no_estimate(
; VF4IC1-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]], i32 [[N:%.*]]) !prof [[PROF0]] {
; VF4IC1:    br i1 [[TMP2:%.*]], [[PRED_STORE_IF:label %.*]], [[PRED_STORE_CONTINUE:label %.*]], !prof [[PROF9:![0-9]+]]
; VF4IC1:    br i1 [[TMP6:%.*]], [[PRED_STORE_IF1:label %.*]], [[PRED_STORE_CONTINUE2:label %.*]], !prof [[PROF9]]
; VF4IC1:    br i1 [[TMP11:%.*]], [[PRED_STORE_IF3:label %.*]], [[PRED_STORE_CONTINUE4:label %.*]], !prof [[PROF9]]
; VF4IC1:    br i1 [[TMP16:%.*]], [[PRED_STORE_IF5:label %.*]], [[PRED_STORE_CONTINUE6:label %.*]], !prof [[PROF9]]
; VF4IC1:    br i1 [[TMP21:%.*]], [[MIDDLE_BLOCK:label %.*]], [[VECTOR_BODY:label %.*]], !prof [[PROF9]], !llvm.loop [[LOOP10:![0-9]+]]
;
; VF2IC2-LABEL: define void @tail_folded_no_estimate(
; VF2IC2-SAME: ptr noalias [[A:%.*]], ptr noalias [[IDX:%.*]], i32 [[N:%.*]]) !prof [[PROF0]] {
; VF2IC2:    br i1 [[TMP3:%.*]], [[PRED_STORE_IF:label %.*]], [[PRED_STORE_CONTINUE:label %.*]], !prof [[PROF9:![0-9]+]]
; VF2IC2:    br i1 [[TMP7:%.*]], [[PRED_STORE_IF1:label %.*]], [[PRED_STORE_CONTINUE2:label %.*]], !prof [[PROF9]]
; VF2IC2:    br i1 [[TMP12:%.*]], [[PRED_STORE_IF3:label %.*]], [[PRED_STORE_CONTINUE4:label %.*]], !prof [[PROF9]]
; VF2IC2:    br i1 [[TMP17:%.*]], [[PRED_STORE_IF5:label %.*]], [[PRED_STORE_CONTINUE6:label %.*]], !prof [[PROF9]]
; VF2IC2:    br i1 [[TMP22:%.*]], [[MIDDLE_BLOCK:label %.*]], [[VECTOR_BODY:label %.*]], !prof [[PROF9]], !llvm.loop [[LOOP10:![0-9]+]]
;
entry:
  br label %loop.header

loop.header:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep.i = getelementptr inbounds i32, ptr %idx, i32 %iv
  %i = load i32, ptr %gep.i, align 4
  %gep.a = getelementptr inbounds i32, ptr %A, i32 %i
  store i32 42, ptr %gep.a, align 4
  br label %latch

latch:
  %iv.next = add nuw nsw i32 %iv, 1
  %ec = icmp eq i32 %iv.next, %n
  br i1 %ec, label %exit, label %loop.header

exit:
  ret void
}

!0 = !{!"function_entry_count", i64 1000}
!1 = !{!"branch_weights", i32 1, i32 3}
!2 = !{!"branch_weights", i32 1, i32 63}
;.
; VF4IC1: [[PROF0]] = !{!"function_entry_count", i64 1000}
; VF4IC1: [[PROF1]] = !{!"branch_weights", i32 64, i32 1}
; VF4IC1: [[PROF2]] = !{!"branch_weights", i32 1, i32 3}
; VF4IC1: [[PROF3]] = !{!"branch_weights", i32 1, i32 15}
; VF4IC1: [[LOOP4]] = distinct !{[[LOOP4]], [[META5:![0-9]+]], [[META6:![0-9]+]], [[META7:![0-9]+]]}
; VF4IC1: [[META5]] = !{!"llvm.loop.isvectorized", i32 1}
; VF4IC1: [[META6]] = !{!"llvm.loop.unroll.runtime.disable"}
; VF4IC1: [[META7]] = !{!"llvm.loop.estimated_trip_count", i32 16}
; VF4IC1: [[LOOP8]] = distinct !{[[LOOP8]], [[META5]], [[META6]], [[META7]]}
; VF4IC1: [[PROF9]] = !{!"unknown", !"loop-vectorize"}
; VF4IC1: [[LOOP10]] = distinct !{[[LOOP10]], [[META5]], [[META6]]}
;.
; VF2IC2: [[PROF0]] = !{!"function_entry_count", i64 1000}
; VF2IC2: [[PROF1]] = !{!"branch_weights", i32 64, i32 1}
; VF2IC2: [[PROF2]] = !{!"branch_weights", i32 1, i32 3}
; VF2IC2: [[PROF3]] = !{!"branch_weights", i32 1, i32 15}
; VF2IC2: [[LOOP4]] = distinct !{[[LOOP4]], [[META5:![0-9]+]], [[META6:![0-9]+]], [[META7:![0-9]+]]}
; VF2IC2: [[META5]] = !{!"llvm.loop.isvectorized", i32 1}
; VF2IC2: [[META6]] = !{!"llvm.loop.unroll.runtime.disable"}
; VF2IC2: [[META7]] = !{!"llvm.loop.estimated_trip_count", i32 16}
; VF2IC2: [[LOOP8]] = distinct !{[[LOOP8]], [[META5]], [[META6]], [[META7]]}
; VF2IC2: [[PROF9]] = !{!"unknown", !"loop-vectorize"}
; VF2IC2: [[LOOP10]] = distinct !{[[LOOP10]], [[META5]], [[META6]]}
;.
