; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; REQUIRES: aarch64-registered-target
; RUN: opt -p loop-vectorize -S %s | FileCheck %s

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx13.0.0"

define void @invariant_load_exit_basic1(ptr %limit_ptr, ptr %dst) {
; CHECK-LABEL: define void @invariant_load_exit_basic1(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[VEC_EPILOG_SCALAR_PH:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP0]], i32 1)
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i32 [[SMAX]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i32 [[SMAX]], -1
; CHECK-NEXT:    [[TMP3:%.*]] = zext nneg i32 [[TMP2]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP1]], 32
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_MEMCHECK:.*]]
; CHECK:       [[VECTOR_MEMCHECK]]:
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 1, [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[DST]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[LIMIT_PTR]], i64 4
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[DST]], [[TMP6]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[LIMIT_PTR]], [[TMP5]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP1]], 32
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP7:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 16
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[NEXT_GEP]], align 1, !alias.scope [[META0:![0-9]+]], !noalias [[META3:![0-9]+]]
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[TMP9]], align 1, !alias.scope [[META0]], !noalias [[META3]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; CHECK-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_BLOCK:.*]], label %[[LOOP]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[TMP7]], %[[MIDDLE_BLOCK]] ], [ 0, %[[VEC_EPILOG_SCALAR_PH]] ], [ 0, %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL1:%.*]] = phi ptr [ [[TMP8]], %[[MIDDLE_BLOCK]] ], [ [[DST]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[DST]], %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP1]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[BC_RESUME_VAL1]], %[[SCALAR_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP1]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP1]], label %[[EXIT]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %entry ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = load i32, ptr %limit_ptr, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}


; Positive: basic loop with invariant-address load in exit condition.
; The pre-loop load of %limit_ptr should be used as the trip count.

define void @invariant_load_exit_basic(ptr %limit_ptr, ptr %dst) {
; CHECK-LABEL: define void @invariant_load_exit_basic(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LIMIT_INIT:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP_INIT:%.*]] = icmp sgt i32 [[LIMIT_INIT]], 0
; CHECK-NEXT:    br i1 [[CMP_INIT]], label %[[VEC_EPILOG_SCALAR_PH:.*]], label %[[EXIT:.*]]
; CHECK:       [[VEC_EPILOG_SCALAR_PH]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP0]], i32 1)
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i32 [[SMAX]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i32 [[SMAX]], -1
; CHECK-NEXT:    [[TMP3:%.*]] = zext nneg i32 [[TMP2]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP1]], 32
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_MEMCHECK:.*]]
; CHECK:       [[VECTOR_MEMCHECK]]:
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 1, [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[DST]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[LIMIT_PTR]], i64 4
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[DST]], [[TMP6]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[LIMIT_PTR]], [[TMP5]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP1]], 32
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP7:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC]]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP1]] ]
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 16
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[NEXT_GEP]], align 1, !alias.scope [[META9:![0-9]+]], !noalias [[META12:![0-9]+]]
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[TMP9]], align 1, !alias.scope [[META9]], !noalias [[META12]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; CHECK-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_BLOCK:.*]], label %[[LOOP1]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT_LOOPEXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[TMP7]], %[[MIDDLE_BLOCK]] ], [ 0, %[[VEC_EPILOG_SCALAR_PH]] ], [ 0, %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL1:%.*]] = phi ptr [ [[TMP8]], %[[MIDDLE_BLOCK]] ], [ [[DST]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[DST]], %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[BC_RESUME_VAL1]], %[[SCALAR_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]], !llvm.loop [[LOOP15:![0-9]+]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %limit_init = load i32, ptr %limit_ptr, align 4
  %cmp_init = icmp sgt i32 %limit_init, 0
  br i1 %cmp_init, label %loop.ph, label %exit

loop.ph:
  br label %loop

loop:
  %iv = phi i32 [ 0, %loop.ph ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %loop.ph ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = load i32, ptr %limit_ptr, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Positive: two-channel float-to-u8 pixel export with invariant load trip count.

define void @invariant_load_exit_multichannel(ptr %image_row, ptr %src, ptr %dst_base) {
; CHECK-LABEL: define void @invariant_load_exit_multichannel(
; CHECK-SAME: ptr [[IMAGE_ROW:%.*]], ptr [[SRC:%.*]], ptr [[DST_BASE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[WIDTH_INIT:%.*]] = load i32, ptr [[IMAGE_ROW]], align 8, !tbaa [[INT_TBAA16:![0-9]+]]
; CHECK-NEXT:    [[CMP_INIT:%.*]] = icmp sgt i32 [[WIDTH_INIT]], 0
; CHECK-NEXT:    br i1 [[CMP_INIT]], label %[[VEC_EPILOG_SCALAR_PH:.*]], label %[[EXIT:.*]]
; CHECK:       [[VEC_EPILOG_SCALAR_PH]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[IMAGE_ROW]], align 4
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP0]], i32 1)
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i32 [[SMAX]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = shl nuw i32 [[SMAX]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[TMP2]], -2
; CHECK-NEXT:    [[TMP4:%.*]] = zext i32 [[TMP3]] to i64
; CHECK-NEXT:    [[TMP5:%.*]] = add nsw i32 [[SMAX]], -1
; CHECK-NEXT:    [[TMP6:%.*]] = zext nneg i32 [[TMP5]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP1]], 16
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_MEMCHECK:.*]]
; CHECK:       [[VECTOR_MEMCHECK]]:
; CHECK-NEXT:    [[TMP7:%.*]] = add i64 2, [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[DST_BASE]], i64 [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = shl nuw nsw i64 [[TMP6]], 3
; CHECK-NEXT:    [[TMP10:%.*]] = add i64 8, [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[SRC]], i64 [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[IMAGE_ROW]], i64 4
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[DST_BASE]], [[TMP11]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[SRC]], [[TMP8]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    [[BOUND01:%.*]] = icmp ult ptr [[DST_BASE]], [[TMP12]]
; CHECK-NEXT:    [[BOUND12:%.*]] = icmp ult ptr [[IMAGE_ROW]], [[TMP8]]
; CHECK-NEXT:    [[FOUND_CONFLICT3:%.*]] = and i1 [[BOUND01]], [[BOUND12]]
; CHECK-NEXT:    [[CONFLICT_RDX:%.*]] = or i1 [[FOUND_CONFLICT]], [[FOUND_CONFLICT3]]
; CHECK-NEXT:    br i1 [[CONFLICT_RDX]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP1]], 16
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP13:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[TMP14:%.*]] = mul i64 [[N_VEC]], 8
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[SRC]], i64 [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = mul i64 [[N_VEC]], 2
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr i8, ptr [[DST_BASE]], i64 [[TMP16]]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP1]] ]
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[INDEX]], 8
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[SRC]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[OFFSET_IDX4:%.*]] = mul i64 [[INDEX]], 2
; CHECK-NEXT:    [[NEXT_GEP5:%.*]] = getelementptr i8, ptr [[DST_BASE]], i64 [[OFFSET_IDX4]]
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <32 x float>, ptr [[NEXT_GEP]], align 4, !tbaa [[FLOAT_TBAA20:![0-9]+]], !alias.scope [[META22:![0-9]+]]
; CHECK-NEXT:    [[STRIDED_VEC:%.*]] = shufflevector <32 x float> [[WIDE_VEC]], <32 x float> poison, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
; CHECK-NEXT:    [[STRIDED_VEC6:%.*]] = shufflevector <32 x float> [[WIDE_VEC]], <32 x float> poison, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
; CHECK-NEXT:    [[TMP18:%.*]] = call <16 x float> @llvm.minnum.v16f32(<16 x float> [[STRIDED_VEC]], <16 x float> splat (float 2.550000e+02))
; CHECK-NEXT:    [[TMP19:%.*]] = call <16 x float> @llvm.maxnum.v16f32(<16 x float> [[TMP18]], <16 x float> zeroinitializer)
; CHECK-NEXT:    [[TMP20:%.*]] = fptoui <16 x float> [[TMP19]] to <16 x i8>
; CHECK-NEXT:    [[TMP21:%.*]] = call <16 x float> @llvm.minnum.v16f32(<16 x float> [[STRIDED_VEC6]], <16 x float> splat (float 2.550000e+02))
; CHECK-NEXT:    [[TMP22:%.*]] = call <16 x float> @llvm.maxnum.v16f32(<16 x float> [[TMP21]], <16 x float> zeroinitializer)
; CHECK-NEXT:    [[TMP23:%.*]] = fptoui <16 x float> [[TMP22]] to <16 x i8>
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP20]], <16 x i8> [[TMP23]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = shufflevector <32 x i8> [[TMP24]], <32 x i8> poison, <32 x i32> <i32 0, i32 16, i32 1, i32 17, i32 2, i32 18, i32 3, i32 19, i32 4, i32 20, i32 5, i32 21, i32 6, i32 22, i32 7, i32 23, i32 8, i32 24, i32 9, i32 25, i32 10, i32 26, i32 11, i32 27, i32 12, i32 28, i32 13, i32 29, i32 14, i32 30, i32 15, i32 31>
; CHECK-NEXT:    store <32 x i8> [[INTERLEAVED_VEC]], ptr [[NEXT_GEP5]], align 1, !tbaa [[CHAR_TBAA25:![0-9]+]], !alias.scope [[META26:![0-9]+]], !noalias [[META28:![0-9]+]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 16
; CHECK-NEXT:    [[TMP25:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP25]], label %[[MIDDLE_BLOCK:.*]], label %[[LOOP1]], !llvm.loop [[LOOP30:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT_LOOPEXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[TMP13]], %[[MIDDLE_BLOCK]] ], [ 0, %[[VEC_EPILOG_SCALAR_PH]] ], [ 0, %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL7:%.*]] = phi ptr [ [[TMP15]], %[[MIDDLE_BLOCK]] ], [ [[SRC]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[SRC]], %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL8:%.*]] = phi ptr [ [[TMP17]], %[[MIDDLE_BLOCK]] ], [ [[DST_BASE]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[DST_BASE]], %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[SRC_PTR:%.*]] = phi ptr [ [[BC_RESUME_VAL7]], %[[SCALAR_PH]] ], [ [[SRC2:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[BC_RESUME_VAL8]], %[[SCALAR_PH]] ], [ [[DST2:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[VAL0:%.*]] = load float, ptr [[SRC_PTR]], align 4, !tbaa [[FLOAT_TBAA20]]
; CHECK-NEXT:    [[CLAMP0_HI:%.*]] = call float @llvm.minnum.f32(float [[VAL0]], float 2.550000e+02)
; CHECK-NEXT:    [[CLAMP0:%.*]] = call float @llvm.maxnum.f32(float [[CLAMP0_HI]], float 0.000000e+00)
; CHECK-NEXT:    [[BYTE0:%.*]] = fptoui float [[CLAMP0]] to i8
; CHECK-NEXT:    store i8 [[BYTE0]], ptr [[DST_PTR]], align 1, !tbaa [[CHAR_TBAA25]]
; CHECK-NEXT:    [[SRC1:%.*]] = getelementptr inbounds i8, ptr [[SRC_PTR]], i64 4
; CHECK-NEXT:    [[VAL1:%.*]] = load float, ptr [[SRC1]], align 4, !tbaa [[FLOAT_TBAA20]]
; CHECK-NEXT:    [[CLAMP1_HI:%.*]] = call float @llvm.minnum.f32(float [[VAL1]], float 2.550000e+02)
; CHECK-NEXT:    [[CLAMP1:%.*]] = call float @llvm.maxnum.f32(float [[CLAMP1_HI]], float 0.000000e+00)
; CHECK-NEXT:    [[BYTE1:%.*]] = fptoui float [[CLAMP1]] to i8
; CHECK-NEXT:    [[DST1:%.*]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    store i8 [[BYTE1]], ptr [[DST1]], align 1, !tbaa [[CHAR_TBAA25]]
; CHECK-NEXT:    [[SRC2]] = getelementptr inbounds i8, ptr [[SRC_PTR]], i64 8
; CHECK-NEXT:    [[DST2]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 2
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[WIDTH:%.*]] = load i32, ptr [[IMAGE_ROW]], align 8, !tbaa [[INT_TBAA16]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[WIDTH]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]], !llvm.loop [[LOOP31:![0-9]+]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %width_init = load i32, ptr %image_row, align 8, !tbaa !3
  %cmp_init = icmp sgt i32 %width_init, 0
  br i1 %cmp_init, label %loop.ph, label %exit

loop.ph:
  br label %loop

loop:
  %iv = phi i32 [ 0, %loop.ph ], [ %iv.next, %loop ]
  %src.ptr = phi ptr [ %src, %loop.ph ], [ %src.next, %loop ]
  %dst.ptr = phi ptr [ %dst_base, %loop.ph ], [ %dst.next, %loop ]

  ; Channel 0
  %val0 = load float, ptr %src.ptr, align 4, !tbaa !7
  %clamp0_hi = call float @llvm.minnum.f32(float %val0, float 2.550000e+02)
  %clamp0 = call float @llvm.maxnum.f32(float %clamp0_hi, float 0.000000e+00)
  %byte0 = fptoui float %clamp0 to i8
  store i8 %byte0, ptr %dst.ptr, align 1, !tbaa !9

  ; Channel 1
  %src1 = getelementptr inbounds i8, ptr %src.ptr, i64 4
  %val1 = load float, ptr %src1, align 4, !tbaa !7
  %clamp1_hi = call float @llvm.minnum.f32(float %val1, float 2.550000e+02)
  %clamp1 = call float @llvm.maxnum.f32(float %clamp1_hi, float 0.000000e+00)
  %byte1 = fptoui float %clamp1 to i8
  %dst1 = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  store i8 %byte1, ptr %dst1, align 1, !tbaa !9

  ; Advance pointers
  %src.next = getelementptr inbounds i8, ptr %src.ptr, i64 8
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 2
  %iv.next = add nuw nsw i32 %iv, 1

  ; Trip count reloaded every iteration
  %width = load i32, ptr %image_row, align 8, !tbaa !3
  %cmp = icmp slt i32 %iv.next, %width
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: load address is IV-dependent (not loop-invariant).

define void @variant_load_addr_exit(ptr %base, ptr %dst) {
; CHECK-LABEL: define void @variant_load_addr_exit(
; CHECK-SAME: ptr [[BASE:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LIMIT_INIT:%.*]] = load i32, ptr [[BASE]], align 4
; CHECK-NEXT:    [[CMP_INIT:%.*]] = icmp sgt i32 [[LIMIT_INIT]], 0
; CHECK-NEXT:    br i1 [[CMP_INIT]], label %[[LOOP_PH:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_PH]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[DST]], %[[LOOP_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[IV_EXT:%.*]] = sext i32 [[IV]] to i64
; CHECK-NEXT:    [[ADDR:%.*]] = getelementptr i32, ptr [[BASE]], i64 [[IV_EXT]]
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[ADDR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %limit_init = load i32, ptr %base, align 4
  %cmp_init = icmp sgt i32 %limit_init, 0
  br i1 %cmp_init, label %loop.ph, label %exit

loop.ph:
  br label %loop

loop:
  %iv = phi i32 [ 0, %loop.ph ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %loop.ph ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw nsw i32 %iv, 1
  ; Load from IV-dependent address
  %iv.ext = sext i32 %iv to i64
  %addr = getelementptr i32, ptr %base, i64 %iv.ext
  %limit = load i32, ptr %addr, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: volatile load (not simple).

define void @volatile_load_exit(ptr %limit_ptr, ptr %dst) {
; CHECK-LABEL: define void @volatile_load_exit(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LIMIT_INIT:%.*]] = load volatile i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP_INIT:%.*]] = icmp sgt i32 [[LIMIT_INIT]], 0
; CHECK-NEXT:    br i1 [[CMP_INIT]], label %[[LOOP_PH:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_PH]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[DST]], %[[LOOP_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load volatile i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %limit_init = load volatile i32, ptr %limit_ptr, align 4
  %cmp_init = icmp sgt i32 %limit_init, 0
  br i1 %cmp_init, label %loop.ph, label %exit

loop.ph:
  br label %loop

loop:
  %iv = phi i32 [ 0, %loop.ph ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %loop.ph ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = load volatile i32, ptr %limit_ptr, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: no pre-loop load from same address. Legality passes (detects
; invariant-address load), but VPlan transform cannot fire because the
; pre-loop blocks do not contain a load from %limit_ptr.
; The loop still vectorizes using the conservative symbolic max BTC.

define void @no_preloop_load_from_same_addr(ptr %limit_ptr, ptr %other_ptr, ptr %dst) {
; CHECK-LABEL: define void @no_preloop_load_from_same_addr(
; CHECK-SAME: ptr [[LIMIT_PTR:%.*]], ptr [[OTHER_PTR:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[OTHER_INIT:%.*]] = load i32, ptr [[OTHER_PTR]], align 4
; CHECK-NEXT:    [[CMP_INIT:%.*]] = icmp sgt i32 [[OTHER_INIT]], 0
; CHECK-NEXT:    br i1 [[CMP_INIT]], label %[[VEC_EPILOG_SCALAR_PH:.*]], label %[[EXIT:.*]]
; CHECK:       [[VEC_EPILOG_SCALAR_PH]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP0]], i32 1)
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i32 [[SMAX]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i32 [[SMAX]], -1
; CHECK-NEXT:    [[TMP3:%.*]] = zext nneg i32 [[TMP2]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP1]], 32
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_MEMCHECK:.*]]
; CHECK:       [[VECTOR_MEMCHECK]]:
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 1, [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[DST]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[LIMIT_PTR]], i64 4
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[DST]], [[TMP6]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[LIMIT_PTR]], [[TMP5]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP1]], 32
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP7:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[DST]], i64 [[N_VEC]]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP1]] ]
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 16
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[NEXT_GEP]], align 1, !alias.scope [[META32:![0-9]+]], !noalias [[META35:![0-9]+]]
; CHECK-NEXT:    store <16 x i8> splat (i8 42), ptr [[TMP9]], align 1, !alias.scope [[META32]], !noalias [[META35]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 32
; CHECK-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_BLOCK:.*]], label %[[LOOP1]], !llvm.loop [[LOOP37:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT_LOOPEXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[TMP7]], %[[MIDDLE_BLOCK]] ], [ 0, %[[VEC_EPILOG_SCALAR_PH]] ], [ 0, %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL1:%.*]] = phi ptr [ [[TMP8]], %[[MIDDLE_BLOCK]] ], [ [[DST]], %[[VEC_EPILOG_SCALAR_PH]] ], [ [[DST]], %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[BC_RESUME_VAL1]], %[[SCALAR_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = load i32, ptr [[LIMIT_PTR]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]], !llvm.loop [[LOOP38:![0-9]+]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  ; Pre-loop load from a DIFFERENT address
  %other_init = load i32, ptr %other_ptr, align 4
  %cmp_init = icmp sgt i32 %other_init, 0
  br i1 %cmp_init, label %loop.ph, label %exit

loop.ph:
  br label %loop

loop:
  %iv = phi i32 [ 0, %loop.ph ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %loop.ph ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = load i32, ptr %limit_ptr, align 4
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: exit condition uses non-load variant value (function call).

define void @non_load_variant_exit(ptr %dst, i32 %n) {
; CHECK-LABEL: define void @non_load_variant_exit(
; CHECK-SAME: ptr [[DST:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP_INIT:%.*]] = icmp sgt i32 [[N]], 0
; CHECK-NEXT:    br i1 [[CMP_INIT]], label %[[LOOP_PH:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_PH]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[DST_PTR:%.*]] = phi ptr [ [[DST]], %[[LOOP_PH]] ], [ [[DST_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    store i8 42, ptr [[DST_PTR]], align 1
; CHECK-NEXT:    [[DST_NEXT]] = getelementptr inbounds i8, ptr [[DST_PTR]], i64 1
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[LIMIT:%.*]] = call i32 @get_limit()
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[IV_NEXT]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %cmp_init = icmp sgt i32 %n, 0
  br i1 %cmp_init, label %loop.ph, label %exit

loop.ph:
  br label %loop

loop:
  %iv = phi i32 [ 0, %loop.ph ], [ %iv.next, %loop ]
  %dst.ptr = phi ptr [ %dst, %loop.ph ], [ %dst.next, %loop ]
  store i8 42, ptr %dst.ptr, align 1
  %dst.next = getelementptr inbounds i8, ptr %dst.ptr, i64 1
  %iv.next = add nuw nsw i32 %iv, 1
  %limit = call i32 @get_limit()
  %cmp = icmp slt i32 %iv.next, %limit
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

declare i32 @get_limit()
declare float @llvm.minnum.f32(float, float)
declare float @llvm.maxnum.f32(float, float)

!0 = !{!"root"}
!1 = !{!"omnipotent char", !0, i64 0}
!2 = !{!"int", !1, i64 0}
!3 = !{!2, !2, i64 0}
!7 = !{!"float", !1, i64 0}
!9 = !{!1, !1, i64 0}
;.
; CHECK: [[META0]] = !{[[META1:![0-9]+]]}
; CHECK: [[META1]] = distinct !{[[META1]], [[META2:![0-9]+]]}
; CHECK: [[META2]] = distinct !{[[META2]], !"LVerDomain"}
; CHECK: [[META3]] = !{[[META4:![0-9]+]]}
; CHECK: [[META4]] = distinct !{[[META4]], [[META2]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]], [[META7:![0-9]+]]}
; CHECK: [[META6]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META7]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META7]], [[META6]]}
; CHECK: [[META9]] = !{[[META10:![0-9]+]]}
; CHECK: [[META10]] = distinct !{[[META10]], [[META11:![0-9]+]]}
; CHECK: [[META11]] = distinct !{[[META11]], !"LVerDomain"}
; CHECK: [[META12]] = !{[[META13:![0-9]+]]}
; CHECK: [[META13]] = distinct !{[[META13]], [[META11]]}
; CHECK: [[LOOP14]] = distinct !{[[LOOP14]], [[META6]], [[META7]]}
; CHECK: [[LOOP15]] = distinct !{[[LOOP15]], [[META7]], [[META6]]}
; CHECK: [[INT_TBAA16]] = !{[[META17:![0-9]+]], [[META17]], i64 0}
; CHECK: [[META17]] = !{!"int", [[META18:![0-9]+]], i64 0}
; CHECK: [[META18]] = !{!"omnipotent char", [[META19:![0-9]+]], i64 0}
; CHECK: [[META19]] = !{!"root"}
; CHECK: [[FLOAT_TBAA20]] = !{[[META21:![0-9]+]], [[META21]], i64 0, i64 0}
; CHECK: [[META21]] = !{!"float", [[META18]]}
; CHECK: [[META22]] = !{[[META23:![0-9]+]]}
; CHECK: [[META23]] = distinct !{[[META23]], [[META24:![0-9]+]]}
; CHECK: [[META24]] = distinct !{[[META24]], !"LVerDomain"}
; CHECK: [[CHAR_TBAA25]] = !{[[META18]], [[META18]], i64 0}
; CHECK: [[META26]] = !{[[META27:![0-9]+]]}
; CHECK: [[META27]] = distinct !{[[META27]], [[META24]]}
; CHECK: [[META28]] = !{[[META23]], [[META29:![0-9]+]]}
; CHECK: [[META29]] = distinct !{[[META29]], [[META24]]}
; CHECK: [[LOOP30]] = distinct !{[[LOOP30]], [[META6]], [[META7]]}
; CHECK: [[LOOP31]] = distinct !{[[LOOP31]], [[META7]], [[META6]]}
; CHECK: [[META32]] = !{[[META33:![0-9]+]]}
; CHECK: [[META33]] = distinct !{[[META33]], [[META34:![0-9]+]]}
; CHECK: [[META34]] = distinct !{[[META34]], !"LVerDomain"}
; CHECK: [[META35]] = !{[[META36:![0-9]+]]}
; CHECK: [[META36]] = distinct !{[[META36]], [[META34]]}
; CHECK: [[LOOP37]] = distinct !{[[LOOP37]], [[META6]], [[META7]]}
; CHECK: [[LOOP38]] = distinct !{[[LOOP38]], [[META7]], [[META6]]}
;.
