; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes='default<O3>' -S < %s | FileCheck %s

; Verify that deferring full unrolling until after the vectorizer allows
; vectorization of small fixed-trip-count loops, while still preserving
; scalar optimizations enabled by full unrolling.

target triple = "arm64-apple-macosx"

; A loop with trip count 8 on arrays. With deferred unrolling, this is
; vectorized with VF=4 and unrolled 2x, producing 2 vector iterations.
define void @add_arrays(ptr noalias %dst, ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: @add_arrays(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[A:%.*]], align 4
; CHECK-NEXT:    [[WIDE_LOAD1:%.*]] = load <4 x i32>, ptr [[B:%.*]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw <4 x i32> [[WIDE_LOAD1]], [[WIDE_LOAD]]
; CHECK-NEXT:    store <4 x i32> [[TMP0]], ptr [[DST:%.*]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i64 16
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 16
; CHECK-NEXT:    [[WIDE_LOAD_1:%.*]] = load <4 x i32>, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[WIDE_LOAD1_1:%.*]] = load <4 x i32>, ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = add nsw <4 x i32> [[WIDE_LOAD1_1]], [[WIDE_LOAD_1]]
; CHECK-NEXT:    store <4 x i32> [[TMP4]], ptr [[TMP3]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.a = getelementptr inbounds i32, ptr %a, i64 %iv
  %gep.b = getelementptr inbounds i32, ptr %b, i64 %iv
  %gep.dst = getelementptr inbounds i32, ptr %dst, i64 %iv
  %va = load i32, ptr %gep.a, align 4
  %vb = load i32, ptr %gep.b, align 4
  %add = add nsw i32 %va, %vb
  store i32 %add, ptr %gep.dst, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 8
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Same loop but with vectorization explicitly disabled. The loop should still
; be fully unrolled.
define void @add_arrays_no_vec(ptr noalias %dst, ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: @add_arrays_no_vec(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i32>, ptr [[A:%.*]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[B:%.*]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[TMP1]], [[TMP0]]
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[DST:%.*]], align 4
; CHECK-NEXT:    [[GEP_A_4:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    [[GEP_B_4:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i64 16
; CHECK-NEXT:    [[GEP_DST_4:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 16
; CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr [[GEP_A_4]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = load <4 x i32>, ptr [[GEP_B_4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = add nsw <4 x i32> [[TMP4]], [[TMP3]]
; CHECK-NEXT:    store <4 x i32> [[TMP5]], ptr [[GEP_DST_4]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.a = getelementptr inbounds i32, ptr %a, i64 %iv
  %gep.b = getelementptr inbounds i32, ptr %b, i64 %iv
  %gep.dst = getelementptr inbounds i32, ptr %dst, i64 %iv
  %va = load i32, ptr %gep.a, align 4
  %vb = load i32, ptr %gep.b, align 4
  %add = add nsw i32 %va, %vb
  store i32 %add, ptr %gep.dst, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 8
  br i1 %cmp, label %loop, label %exit, !llvm.loop !0

exit:
  ret void
}

; A find_if-style early-exit loop with a constant latch trip count and a
; read-only body. Without deferral the early full unroller would tear it
; into ~26 scalar branches (its per-exiting-block trip count query sees
; the latch's bound), and SLP cannot rebuild that into a vector reduction.
; With deferral LV's early-exit vectorization handles it as a sequence of
; <8 x i8> compares with a cttz-elts first-active-lane reduction.
@arr = external global [32 x i8]

define ptr @find_if_arr(i8 %c) {
; CHECK-LABEL: @find_if_arr(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <8 x i8> poison, i8 [[C:%.*]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <8 x i8> [[BROADCAST_SPLATINSERT]], <8 x i8> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i8>, ptr @arr, align 1
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq <8 x i8> [[WIDE_LOAD]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP1:%.*]] = freeze <8 x i1> [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i1> [[TMP1]] to i8
; CHECK-NEXT:    [[IS_MATCH_21:%.*]] = icmp eq i8 [[TMP2]], 0
; CHECK-NEXT:    br i1 [[IS_MATCH_21]], label [[VECTOR_BODY_INTERIM:%.*]], label [[LOOP_LATCH_21:%.*]]
; CHECK:       vector.body.interim:
; CHECK-NEXT:    [[WIDE_LOAD_1:%.*]] = load <8 x i8>, ptr getelementptr inbounds nuw (i8, ptr @arr, i64 8), align 1
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <8 x i8> [[WIDE_LOAD_1]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP4:%.*]] = freeze <8 x i1> [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast <8 x i1> [[TMP4]] to i8
; CHECK-NEXT:    [[DOTNOT_1:%.*]] = icmp eq i8 [[TMP5]], 0
; CHECK-NEXT:    br i1 [[DOTNOT_1]], label [[VECTOR_BODY_INTERIM_1:%.*]], label [[LOOP_LATCH_21]]
; CHECK:       vector.body.interim.1:
; CHECK-NEXT:    [[WIDE_LOAD_2:%.*]] = load <8 x i8>, ptr getelementptr inbounds nuw (i8, ptr @arr, i64 16), align 1
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq <8 x i8> [[WIDE_LOAD_2]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP7:%.*]] = freeze <8 x i1> [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = bitcast <8 x i1> [[TMP7]] to i8
; CHECK-NEXT:    [[DOTNOT_2:%.*]] = icmp eq i8 [[TMP8]], 0
; CHECK-NEXT:    br i1 [[DOTNOT_2]], label [[LOOP:%.*]], label [[LOOP_LATCH_21]]
; CHECK:       vector.early.exit:
; CHECK-NEXT:    [[INDEX_LCSSA:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ 8, [[VECTOR_BODY_INTERIM]] ], [ 16, [[VECTOR_BODY_INTERIM_1]] ]
; CHECK-NEXT:    [[DOTLCSSA6:%.*]] = phi ptr [ @arr, [[ENTRY]] ], [ getelementptr inbounds nuw (i8, ptr @arr, i64 8), [[VECTOR_BODY_INTERIM]] ], [ getelementptr inbounds nuw (i8, ptr @arr, i64 16), [[VECTOR_BODY_INTERIM_1]] ]
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi <8 x i1> [ [[TMP1]], [[ENTRY]] ], [ [[TMP4]], [[VECTOR_BODY_INTERIM]] ], [ [[TMP7]], [[VECTOR_BODY_INTERIM_1]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <8 x ptr> poison, ptr [[DOTLCSSA6]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw i8, ptr @arr, i64 [[INDEX_LCSSA]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP10]], i64 1
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <8 x ptr> [[TMP9]], ptr [[TMP11]], i64 1
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw i8, ptr @arr, i64 [[INDEX_LCSSA]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP13]], i64 2
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <8 x ptr> [[TMP12]], ptr [[TMP14]], i64 2
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw i8, ptr @arr, i64 [[INDEX_LCSSA]]
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP16]], i64 3
; CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x ptr> [[TMP15]], ptr [[TMP17]], i64 3
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw i8, ptr @arr, i64 [[INDEX_LCSSA]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP19]], i64 4
; CHECK-NEXT:    [[TMP21:%.*]] = insertelement <8 x ptr> [[TMP18]], ptr [[TMP20]], i64 4
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw i8, ptr @arr, i64 [[INDEX_LCSSA]]
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP22]], i64 5
; CHECK-NEXT:    [[TMP24:%.*]] = insertelement <8 x ptr> [[TMP21]], ptr [[TMP23]], i64 5
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw i8, ptr @arr, i64 [[INDEX_LCSSA]]
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP25]], i64 6
; CHECK-NEXT:    [[TMP27:%.*]] = insertelement <8 x ptr> [[TMP24]], ptr [[TMP26]], i64 6
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds nuw i8, ptr @arr, i64 [[INDEX_LCSSA]]
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP28]], i64 7
; CHECK-NEXT:    [[TMP30:%.*]] = insertelement <8 x ptr> [[TMP27]], ptr [[TMP29]], i64 7
; CHECK-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = tail call i64 @llvm.experimental.cttz.elts.i64.v8i1(<8 x i1> [[DOTLCSSA]], i1 false)
; CHECK-NEXT:    [[TMP31:%.*]] = extractelement <8 x ptr> [[TMP30]], i64 [[FIRST_ACTIVE_LANE]]
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[V:%.*]] = load i8, ptr getelementptr inbounds nuw (i8, ptr @arr, i64 24), align 1
; CHECK-NEXT:    [[IS_MATCH:%.*]] = icmp eq i8 [[V]], [[C]]
; CHECK-NEXT:    br i1 [[IS_MATCH]], label [[EXIT]], label [[LOOP_LATCH:%.*]]
; CHECK:       loop.latch:
; CHECK-NEXT:    [[V_1:%.*]] = load i8, ptr getelementptr inbounds nuw (i8, ptr @arr, i64 25), align 1
; CHECK-NEXT:    [[IS_MATCH_1:%.*]] = icmp eq i8 [[V_1]], [[C]]
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[IS_MATCH_1]], ptr getelementptr inbounds nuw (i8, ptr @arr, i64 25), ptr getelementptr inbounds nuw (i8, ptr @arr, i64 26)
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[RES:%.*]] = phi ptr [ [[TMP31]], [[LOOP_LATCH_21]] ], [ [[SPEC_SELECT]], [[LOOP_LATCH]] ], [ getelementptr inbounds nuw (i8, ptr @arr, i64 24), [[LOOP]] ]
; CHECK-NEXT:    ret ptr [[RES]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %gep = getelementptr inbounds [32 x i8], ptr @arr, i64 0, i64 %iv
  %v = load i8, ptr %gep, align 1
  %is.match = icmp eq i8 %v, %c
  br i1 %is.match, label %exit, label %loop.latch

loop.latch:
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 26
  br i1 %cmp, label %loop, label %end

end:
  br label %exit

exit:
  %res = phi ptr [ %gep, %loop ], [ getelementptr inbounds ([32 x i8], ptr @arr, i64 0, i64 26), %end ]
  ret ptr %res
}

; Trip-count 32 array copy with may-aliasing pointers. The early full
; unroller would unroll TC=32 to a long scalar chain, and SLP cannot fix
; that up because it needs runtime alias checks the loop form provides
; for free. With deferral LV emits a runtime alias check that diverts to
; a <4 x i32> vector body when the pointers don't overlap.
define void @rt_check_needed(ptr %dst, ptr %a) {
; CHECK-LABEL: @rt_check_needed(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[DST1:%.*]] = ptrtoaddr ptr [[DST:%.*]] to i64
; CHECK-NEXT:    [[A2:%.*]] = ptrtoaddr ptr [[A:%.*]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = sub i64 [[DST1]], [[A2]]
; CHECK-NEXT:    [[DIFF_CHECK:%.*]] = icmp ult i64 [[TMP0]], 32
; CHECK-NEXT:    br i1 [[DIFF_CHECK]], label [[LOOP:%.*]], label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[A]], align 4
; CHECK-NEXT:    [[WIDE_LOAD3:%.*]] = load <4 x i32>, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw <4 x i32> [[WIDE_LOAD]], splat (i32 1)
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw <4 x i32> [[WIDE_LOAD3]], splat (i32 1)
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 16
; CHECK-NEXT:    store <4 x i32> [[TMP2]], ptr [[DST]], align 4
; CHECK-NEXT:    store <4 x i32> [[TMP3]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 32
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 48
; CHECK-NEXT:    [[WIDE_LOAD_1:%.*]] = load <4 x i32>, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[WIDE_LOAD3_1:%.*]] = load <4 x i32>, ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = add nsw <4 x i32> [[WIDE_LOAD_1]], splat (i32 1)
; CHECK-NEXT:    [[TMP8:%.*]] = add nsw <4 x i32> [[WIDE_LOAD3_1]], splat (i32 1)
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 32
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 48
; CHECK-NEXT:    store <4 x i32> [[TMP7]], ptr [[TMP9]], align 4
; CHECK-NEXT:    store <4 x i32> [[TMP8]], ptr [[TMP10]], align 4
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 64
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 80
; CHECK-NEXT:    [[WIDE_LOAD_2:%.*]] = load <4 x i32>, ptr [[TMP11]], align 4
; CHECK-NEXT:    [[WIDE_LOAD3_2:%.*]] = load <4 x i32>, ptr [[TMP12]], align 4
; CHECK-NEXT:    [[TMP13:%.*]] = add nsw <4 x i32> [[WIDE_LOAD_2]], splat (i32 1)
; CHECK-NEXT:    [[TMP14:%.*]] = add nsw <4 x i32> [[WIDE_LOAD3_2]], splat (i32 1)
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 64
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 80
; CHECK-NEXT:    store <4 x i32> [[TMP13]], ptr [[TMP15]], align 4
; CHECK-NEXT:    store <4 x i32> [[TMP14]], ptr [[TMP16]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 96
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 112
; CHECK-NEXT:    [[WIDE_LOAD_3:%.*]] = load <4 x i32>, ptr [[TMP17]], align 4
; CHECK-NEXT:    [[WIDE_LOAD3_3:%.*]] = load <4 x i32>, ptr [[TMP18]], align 4
; CHECK-NEXT:    [[TMP19:%.*]] = add nsw <4 x i32> [[WIDE_LOAD_3]], splat (i32 1)
; CHECK-NEXT:    [[TMP20:%.*]] = add nsw <4 x i32> [[WIDE_LOAD3_3]], splat (i32 1)
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 96
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 112
; CHECK-NEXT:    store <4 x i32> [[TMP19]], ptr [[TMP21]], align 4
; CHECK-NEXT:    store <4 x i32> [[TMP20]], ptr [[TMP22]], align 4
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[VA:%.*]] = load i32, ptr [[A]], align 4
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[VA]], 1
; CHECK-NEXT:    store i32 [[ADD]], ptr [[DST]], align 4
; CHECK-NEXT:    [[GEP_A_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 4
; CHECK-NEXT:    [[VA_1:%.*]] = load i32, ptr [[GEP_A_1]], align 4
; CHECK-NEXT:    [[ADD_1:%.*]] = add nsw i32 [[VA_1]], 1
; CHECK-NEXT:    [[GEP_DST_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 4
; CHECK-NEXT:    store i32 [[ADD_1]], ptr [[GEP_DST_1]], align 4
; CHECK-NEXT:    [[GEP_A_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 8
; CHECK-NEXT:    [[VA_2:%.*]] = load i32, ptr [[GEP_A_2]], align 4
; CHECK-NEXT:    [[ADD_2:%.*]] = add nsw i32 [[VA_2]], 1
; CHECK-NEXT:    [[GEP_DST_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 8
; CHECK-NEXT:    store i32 [[ADD_2]], ptr [[GEP_DST_2]], align 4
; CHECK-NEXT:    [[GEP_A_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 12
; CHECK-NEXT:    [[VA_3:%.*]] = load i32, ptr [[GEP_A_3]], align 4
; CHECK-NEXT:    [[ADD_3:%.*]] = add nsw i32 [[VA_3]], 1
; CHECK-NEXT:    [[GEP_DST_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 12
; CHECK-NEXT:    store i32 [[ADD_3]], ptr [[GEP_DST_3]], align 4
; CHECK-NEXT:    [[GEP_A_4:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    [[VA_4:%.*]] = load i32, ptr [[GEP_A_4]], align 4
; CHECK-NEXT:    [[ADD_4:%.*]] = add nsw i32 [[VA_4]], 1
; CHECK-NEXT:    [[GEP_DST_4:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 16
; CHECK-NEXT:    store i32 [[ADD_4]], ptr [[GEP_DST_4]], align 4
; CHECK-NEXT:    [[GEP_A_5:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 20
; CHECK-NEXT:    [[VA_5:%.*]] = load i32, ptr [[GEP_A_5]], align 4
; CHECK-NEXT:    [[ADD_5:%.*]] = add nsw i32 [[VA_5]], 1
; CHECK-NEXT:    [[GEP_DST_5:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 20
; CHECK-NEXT:    store i32 [[ADD_5]], ptr [[GEP_DST_5]], align 4
; CHECK-NEXT:    [[GEP_A_6:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 24
; CHECK-NEXT:    [[VA_6:%.*]] = load i32, ptr [[GEP_A_6]], align 4
; CHECK-NEXT:    [[ADD_6:%.*]] = add nsw i32 [[VA_6]], 1
; CHECK-NEXT:    [[GEP_DST_6:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 24
; CHECK-NEXT:    store i32 [[ADD_6]], ptr [[GEP_DST_6]], align 4
; CHECK-NEXT:    [[GEP_A_7:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 28
; CHECK-NEXT:    [[VA_7:%.*]] = load i32, ptr [[GEP_A_7]], align 4
; CHECK-NEXT:    [[ADD_7:%.*]] = add nsw i32 [[VA_7]], 1
; CHECK-NEXT:    [[GEP_DST_7:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 28
; CHECK-NEXT:    store i32 [[ADD_7]], ptr [[GEP_DST_7]], align 4
; CHECK-NEXT:    [[GEP_A_8:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 32
; CHECK-NEXT:    [[VA_8:%.*]] = load i32, ptr [[GEP_A_8]], align 4
; CHECK-NEXT:    [[ADD_8:%.*]] = add nsw i32 [[VA_8]], 1
; CHECK-NEXT:    [[GEP_DST_8:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 32
; CHECK-NEXT:    store i32 [[ADD_8]], ptr [[GEP_DST_8]], align 4
; CHECK-NEXT:    [[GEP_A_9:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 36
; CHECK-NEXT:    [[VA_9:%.*]] = load i32, ptr [[GEP_A_9]], align 4
; CHECK-NEXT:    [[ADD_9:%.*]] = add nsw i32 [[VA_9]], 1
; CHECK-NEXT:    [[GEP_DST_9:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 36
; CHECK-NEXT:    store i32 [[ADD_9]], ptr [[GEP_DST_9]], align 4
; CHECK-NEXT:    [[GEP_A_10:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 40
; CHECK-NEXT:    [[VA_10:%.*]] = load i32, ptr [[GEP_A_10]], align 4
; CHECK-NEXT:    [[ADD_10:%.*]] = add nsw i32 [[VA_10]], 1
; CHECK-NEXT:    [[GEP_DST_10:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 40
; CHECK-NEXT:    store i32 [[ADD_10]], ptr [[GEP_DST_10]], align 4
; CHECK-NEXT:    [[GEP_A_11:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 44
; CHECK-NEXT:    [[VA_11:%.*]] = load i32, ptr [[GEP_A_11]], align 4
; CHECK-NEXT:    [[ADD_11:%.*]] = add nsw i32 [[VA_11]], 1
; CHECK-NEXT:    [[GEP_DST_11:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 44
; CHECK-NEXT:    store i32 [[ADD_11]], ptr [[GEP_DST_11]], align 4
; CHECK-NEXT:    [[GEP_A_12:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 48
; CHECK-NEXT:    [[VA_12:%.*]] = load i32, ptr [[GEP_A_12]], align 4
; CHECK-NEXT:    [[ADD_12:%.*]] = add nsw i32 [[VA_12]], 1
; CHECK-NEXT:    [[GEP_DST_12:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 48
; CHECK-NEXT:    store i32 [[ADD_12]], ptr [[GEP_DST_12]], align 4
; CHECK-NEXT:    [[GEP_A_13:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 52
; CHECK-NEXT:    [[VA_13:%.*]] = load i32, ptr [[GEP_A_13]], align 4
; CHECK-NEXT:    [[ADD_13:%.*]] = add nsw i32 [[VA_13]], 1
; CHECK-NEXT:    [[GEP_DST_13:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 52
; CHECK-NEXT:    store i32 [[ADD_13]], ptr [[GEP_DST_13]], align 4
; CHECK-NEXT:    [[GEP_A_14:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 56
; CHECK-NEXT:    [[VA_14:%.*]] = load i32, ptr [[GEP_A_14]], align 4
; CHECK-NEXT:    [[ADD_14:%.*]] = add nsw i32 [[VA_14]], 1
; CHECK-NEXT:    [[GEP_DST_14:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 56
; CHECK-NEXT:    store i32 [[ADD_14]], ptr [[GEP_DST_14]], align 4
; CHECK-NEXT:    [[GEP_A_15:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 60
; CHECK-NEXT:    [[VA_15:%.*]] = load i32, ptr [[GEP_A_15]], align 4
; CHECK-NEXT:    [[ADD_15:%.*]] = add nsw i32 [[VA_15]], 1
; CHECK-NEXT:    [[GEP_DST_15:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 60
; CHECK-NEXT:    store i32 [[ADD_15]], ptr [[GEP_DST_15]], align 4
; CHECK-NEXT:    [[GEP_A_16:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 64
; CHECK-NEXT:    [[VA_16:%.*]] = load i32, ptr [[GEP_A_16]], align 4
; CHECK-NEXT:    [[ADD_16:%.*]] = add nsw i32 [[VA_16]], 1
; CHECK-NEXT:    [[GEP_DST_16:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 64
; CHECK-NEXT:    store i32 [[ADD_16]], ptr [[GEP_DST_16]], align 4
; CHECK-NEXT:    [[GEP_A_17:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 68
; CHECK-NEXT:    [[VA_17:%.*]] = load i32, ptr [[GEP_A_17]], align 4
; CHECK-NEXT:    [[ADD_17:%.*]] = add nsw i32 [[VA_17]], 1
; CHECK-NEXT:    [[GEP_DST_17:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 68
; CHECK-NEXT:    store i32 [[ADD_17]], ptr [[GEP_DST_17]], align 4
; CHECK-NEXT:    [[GEP_A_18:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 72
; CHECK-NEXT:    [[VA_18:%.*]] = load i32, ptr [[GEP_A_18]], align 4
; CHECK-NEXT:    [[ADD_18:%.*]] = add nsw i32 [[VA_18]], 1
; CHECK-NEXT:    [[GEP_DST_18:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 72
; CHECK-NEXT:    store i32 [[ADD_18]], ptr [[GEP_DST_18]], align 4
; CHECK-NEXT:    [[GEP_A_19:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 76
; CHECK-NEXT:    [[VA_19:%.*]] = load i32, ptr [[GEP_A_19]], align 4
; CHECK-NEXT:    [[ADD_19:%.*]] = add nsw i32 [[VA_19]], 1
; CHECK-NEXT:    [[GEP_DST_19:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 76
; CHECK-NEXT:    store i32 [[ADD_19]], ptr [[GEP_DST_19]], align 4
; CHECK-NEXT:    [[GEP_A_20:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 80
; CHECK-NEXT:    [[VA_20:%.*]] = load i32, ptr [[GEP_A_20]], align 4
; CHECK-NEXT:    [[ADD_20:%.*]] = add nsw i32 [[VA_20]], 1
; CHECK-NEXT:    [[GEP_DST_20:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 80
; CHECK-NEXT:    store i32 [[ADD_20]], ptr [[GEP_DST_20]], align 4
; CHECK-NEXT:    [[GEP_A_21:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 84
; CHECK-NEXT:    [[VA_21:%.*]] = load i32, ptr [[GEP_A_21]], align 4
; CHECK-NEXT:    [[ADD_21:%.*]] = add nsw i32 [[VA_21]], 1
; CHECK-NEXT:    [[GEP_DST_21:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 84
; CHECK-NEXT:    store i32 [[ADD_21]], ptr [[GEP_DST_21]], align 4
; CHECK-NEXT:    [[GEP_A_22:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 88
; CHECK-NEXT:    [[VA_22:%.*]] = load i32, ptr [[GEP_A_22]], align 4
; CHECK-NEXT:    [[ADD_22:%.*]] = add nsw i32 [[VA_22]], 1
; CHECK-NEXT:    [[GEP_DST_22:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 88
; CHECK-NEXT:    store i32 [[ADD_22]], ptr [[GEP_DST_22]], align 4
; CHECK-NEXT:    [[GEP_A_23:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 92
; CHECK-NEXT:    [[VA_23:%.*]] = load i32, ptr [[GEP_A_23]], align 4
; CHECK-NEXT:    [[ADD_23:%.*]] = add nsw i32 [[VA_23]], 1
; CHECK-NEXT:    [[GEP_DST_23:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 92
; CHECK-NEXT:    store i32 [[ADD_23]], ptr [[GEP_DST_23]], align 4
; CHECK-NEXT:    [[GEP_A_24:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 96
; CHECK-NEXT:    [[VA_24:%.*]] = load i32, ptr [[GEP_A_24]], align 4
; CHECK-NEXT:    [[ADD_24:%.*]] = add nsw i32 [[VA_24]], 1
; CHECK-NEXT:    [[GEP_DST_24:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 96
; CHECK-NEXT:    store i32 [[ADD_24]], ptr [[GEP_DST_24]], align 4
; CHECK-NEXT:    [[GEP_A_25:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 100
; CHECK-NEXT:    [[VA_25:%.*]] = load i32, ptr [[GEP_A_25]], align 4
; CHECK-NEXT:    [[ADD_25:%.*]] = add nsw i32 [[VA_25]], 1
; CHECK-NEXT:    [[GEP_DST_25:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 100
; CHECK-NEXT:    store i32 [[ADD_25]], ptr [[GEP_DST_25]], align 4
; CHECK-NEXT:    [[GEP_A_26:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 104
; CHECK-NEXT:    [[VA_26:%.*]] = load i32, ptr [[GEP_A_26]], align 4
; CHECK-NEXT:    [[ADD_26:%.*]] = add nsw i32 [[VA_26]], 1
; CHECK-NEXT:    [[GEP_DST_26:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 104
; CHECK-NEXT:    store i32 [[ADD_26]], ptr [[GEP_DST_26]], align 4
; CHECK-NEXT:    [[GEP_A_27:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 108
; CHECK-NEXT:    [[VA_27:%.*]] = load i32, ptr [[GEP_A_27]], align 4
; CHECK-NEXT:    [[ADD_27:%.*]] = add nsw i32 [[VA_27]], 1
; CHECK-NEXT:    [[GEP_DST_27:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 108
; CHECK-NEXT:    store i32 [[ADD_27]], ptr [[GEP_DST_27]], align 4
; CHECK-NEXT:    [[GEP_A_28:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 112
; CHECK-NEXT:    [[VA_28:%.*]] = load i32, ptr [[GEP_A_28]], align 4
; CHECK-NEXT:    [[ADD_28:%.*]] = add nsw i32 [[VA_28]], 1
; CHECK-NEXT:    [[GEP_DST_28:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 112
; CHECK-NEXT:    store i32 [[ADD_28]], ptr [[GEP_DST_28]], align 4
; CHECK-NEXT:    [[GEP_A_29:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 116
; CHECK-NEXT:    [[VA_29:%.*]] = load i32, ptr [[GEP_A_29]], align 4
; CHECK-NEXT:    [[ADD_29:%.*]] = add nsw i32 [[VA_29]], 1
; CHECK-NEXT:    [[GEP_DST_29:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 116
; CHECK-NEXT:    store i32 [[ADD_29]], ptr [[GEP_DST_29]], align 4
; CHECK-NEXT:    [[GEP_A_30:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 120
; CHECK-NEXT:    [[VA_30:%.*]] = load i32, ptr [[GEP_A_30]], align 4
; CHECK-NEXT:    [[ADD_30:%.*]] = add nsw i32 [[VA_30]], 1
; CHECK-NEXT:    [[GEP_DST_30:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 120
; CHECK-NEXT:    store i32 [[ADD_30]], ptr [[GEP_DST_30]], align 4
; CHECK-NEXT:    [[GEP_A_31:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 124
; CHECK-NEXT:    [[VA_31:%.*]] = load i32, ptr [[GEP_A_31]], align 4
; CHECK-NEXT:    [[ADD_31:%.*]] = add nsw i32 [[VA_31]], 1
; CHECK-NEXT:    [[GEP_DST_31:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 124
; CHECK-NEXT:    store i32 [[ADD_31]], ptr [[GEP_DST_31]], align 4
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.a = getelementptr inbounds i32, ptr %a, i64 %iv
  %va = load i32, ptr %gep.a, align 4
  %add = add nsw i32 %va, 1
  %gep.dst = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 %add, ptr %gep.dst, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 32
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; A loop with a true loop-carried dependency (recurrence) that the vectorizer
; cannot handle. Verify it still gets fully unrolled after the vectorizer.
define i32 @recurrence_loop(ptr %arr) {
; CHECK-LABEL: @recurrence_loop(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[ARR:%.*]], align 4
; CHECK-NEXT:    [[GEP_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 4
; CHECK-NEXT:    [[VAL_1:%.*]] = load i32, ptr [[GEP_1]], align 4
; CHECK-NEXT:    [[MUL1_1:%.*]] = add i32 [[VAL]], 1
; CHECK-NEXT:    [[NEXT_ACC_1:%.*]] = mul i32 [[MUL1_1]], [[VAL_1]]
; CHECK-NEXT:    [[GEP_2:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 8
; CHECK-NEXT:    [[VAL_2:%.*]] = load i32, ptr [[GEP_2]], align 4
; CHECK-NEXT:    [[MUL1_2:%.*]] = add i32 [[NEXT_ACC_1]], 1
; CHECK-NEXT:    [[NEXT_ACC_2:%.*]] = mul i32 [[MUL1_2]], [[VAL_2]]
; CHECK-NEXT:    [[GEP_3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 12
; CHECK-NEXT:    [[VAL_3:%.*]] = load i32, ptr [[GEP_3]], align 4
; CHECK-NEXT:    [[MUL1_3:%.*]] = add i32 [[NEXT_ACC_2]], 1
; CHECK-NEXT:    [[NEXT_ACC_3:%.*]] = mul i32 [[MUL1_3]], [[VAL_3]]
; CHECK-NEXT:    ret i32 [[NEXT_ACC_3]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %next.acc, %loop ]
  %gep = getelementptr inbounds i32, ptr %arr, i64 %iv
  %val = load i32, ptr %gep, align 4
  %mul = mul nsw i32 %acc, %val
  %next.acc = add nsw i32 %mul, %val
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 4
  br i1 %cmp, label %loop, label %exit

exit:
  ret i32 %next.acc
}

; Verify that full unrolling + scalar optimizations (like DSE) still work
; when unrolling is deferred. The first loop stores zeros and the second
; overwrites them, so DSE should eliminate the dead stores.
define void @unroll_enables_dse(ptr noalias %dst) {
; CHECK-LABEL: @unroll_enables_dse(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store <4 x i32> <i32 1, i32 2, i32 3, i32 4>, ptr [[DST:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.init

loop.init:
  %iv0 = phi i64 [ 0, %entry ], [ %iv0.next, %loop.init ]
  %gep0 = getelementptr inbounds i32, ptr %dst, i64 %iv0
  store i32 0, ptr %gep0, align 4
  %iv0.next = add nuw nsw i64 %iv0, 1
  %cmp0 = icmp ult i64 %iv0.next, 4
  br i1 %cmp0, label %loop.init, label %mid

mid:
  br label %loop.overwrite

loop.overwrite:
  %iv1 = phi i64 [ 0, %mid ], [ %iv1.next, %loop.overwrite ]
  %gep1 = getelementptr inbounds i32, ptr %dst, i64 %iv1
  %iv1.trunc = trunc i64 %iv1 to i32
  %val = add nsw i32 %iv1.trunc, 1
  store i32 %val, ptr %gep1, align 4
  %iv1.next = add nuw nsw i64 %iv1, 1
  %cmp1 = icmp ult i64 %iv1.next, 4
  br i1 %cmp1, label %loop.overwrite, label %exit

exit:
  ret void
}

; Verify that a purely scalar loop (no strided memory accesses) is still
; fully unrolled early and not deferred. The structural heuristic should
; only defer loops with AddRec pointer accesses.
define i32 @scalar_loop_no_defer(i32 %x) {
; CHECK-LABEL: @scalar_loop_no_defer(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[X:%.*]], 12
; CHECK-NEXT:    ret i32 [[TMP0]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %acc = phi i32 [ %x, %entry ], [ %next, %loop ]
  %next = add nsw i32 %acc, 3
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 4
  br i1 %cmp, label %loop, label %exit

exit:
  ret i32 %next
}

; Regression: a 16x16 nested SAD-style pattern. The TC=16 inner loop must
; not be deferred when its parent has TC=16. Without this exclusion:
;   * Inner deferred -> outer skipped from early full-unroll.
;   * LoopVectorize processes the inner with VF=16 + reduction. The
;     resulting per-iteration body is ~3x more costly in the unroll cost
;     model than the unroll-then-SLP equivalent: LV emits a partial-reduce
;     bridge intrinsic (because the chosen VF differs from the natural
;     reduction width), an umax/umin/sub chain for the absolute difference
;     (instead of sub-nsw + llvm.abs), and a freeze on each speculatively
;     vectorized load. The cleanup chain has no pass that re-canonicalizes
;     these shapes back, so the outer's per-iteration cost stays inflated
;     and the late LoopUnrollPass rejects full-unroll.
; With the predicate excluding inners whose ancestor has TC <= 16 the
; outer fully unrolls and the inner becomes a single <16 x i16> chain per
; iteration.
define i32 @nested_sad_16x16(ptr noundef %p1, i32 noundef %s_p1, ptr noundef %p2, i32 noundef %s_p2) {
; CHECK-LABEL: @nested_sad_16x16(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[S_P1:%.*]] to i64
; CHECK-NEXT:    [[IDX_EXT8:%.*]] = sext i32 [[S_P2:%.*]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = load <16 x i8>, ptr [[P1:%.*]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = zext <16 x i8> [[TMP0]] to <16 x i16>
; CHECK-NEXT:    [[TMP2:%.*]] = load <16 x i8>, ptr [[P2:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = zext <16 x i8> [[TMP2]] to <16 x i16>
; CHECK-NEXT:    [[TMP4:%.*]] = sub nsw <16 x i16> [[TMP1]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP4]], i1 false)
; CHECK-NEXT:    [[TMP6:%.*]] = zext <16 x i16> [[TMP5]] to <16 x i32>
; CHECK-NEXT:    [[TMP7:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP6]])
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[ADD_PTR9:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP8:%.*]] = load <16 x i8>, ptr [[ADD_PTR]], align 1
; CHECK-NEXT:    [[TMP9:%.*]] = zext <16 x i8> [[TMP8]] to <16 x i16>
; CHECK-NEXT:    [[TMP10:%.*]] = load <16 x i8>, ptr [[ADD_PTR9]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = zext <16 x i8> [[TMP10]] to <16 x i16>
; CHECK-NEXT:    [[TMP12:%.*]] = sub nsw <16 x i16> [[TMP9]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP12]], i1 false)
; CHECK-NEXT:    [[TMP14:%.*]] = zext <16 x i16> [[TMP13]] to <16 x i32>
; CHECK-NEXT:    [[TMP15:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP14]])
; CHECK-NEXT:    [[OP_RDX_1:%.*]] = add nuw nsw i32 [[TMP15]], [[TMP7]]
; CHECK-NEXT:    [[P1_NEXT_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP16:%.*]] = load <16 x i8>, ptr [[P1_NEXT_1]], align 1
; CHECK-NEXT:    [[TMP17:%.*]] = zext <16 x i8> [[TMP16]] to <16 x i16>
; CHECK-NEXT:    [[TMP18:%.*]] = load <16 x i8>, ptr [[P2_NEXT_1]], align 1
; CHECK-NEXT:    [[TMP19:%.*]] = zext <16 x i8> [[TMP18]] to <16 x i16>
; CHECK-NEXT:    [[TMP20:%.*]] = sub nsw <16 x i16> [[TMP17]], [[TMP19]]
; CHECK-NEXT:    [[TMP21:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP20]], i1 false)
; CHECK-NEXT:    [[TMP22:%.*]] = zext <16 x i16> [[TMP21]] to <16 x i32>
; CHECK-NEXT:    [[TMP23:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP22]])
; CHECK-NEXT:    [[OP_RDX_2:%.*]] = add nuw nsw i32 [[TMP23]], [[OP_RDX_1]]
; CHECK-NEXT:    [[P1_NEXT_2:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_1]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_2:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_1]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP24:%.*]] = load <16 x i8>, ptr [[P1_NEXT_2]], align 1
; CHECK-NEXT:    [[TMP25:%.*]] = zext <16 x i8> [[TMP24]] to <16 x i16>
; CHECK-NEXT:    [[TMP26:%.*]] = load <16 x i8>, ptr [[P2_NEXT_2]], align 1
; CHECK-NEXT:    [[TMP27:%.*]] = zext <16 x i8> [[TMP26]] to <16 x i16>
; CHECK-NEXT:    [[TMP28:%.*]] = sub nsw <16 x i16> [[TMP25]], [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP28]], i1 false)
; CHECK-NEXT:    [[TMP30:%.*]] = zext <16 x i16> [[TMP29]] to <16 x i32>
; CHECK-NEXT:    [[TMP31:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP30]])
; CHECK-NEXT:    [[OP_RDX_3:%.*]] = add nuw nsw i32 [[TMP31]], [[OP_RDX_2]]
; CHECK-NEXT:    [[P1_NEXT_3:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_2]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_3:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_2]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP32:%.*]] = load <16 x i8>, ptr [[P1_NEXT_3]], align 1
; CHECK-NEXT:    [[TMP33:%.*]] = zext <16 x i8> [[TMP32]] to <16 x i16>
; CHECK-NEXT:    [[TMP34:%.*]] = load <16 x i8>, ptr [[P2_NEXT_3]], align 1
; CHECK-NEXT:    [[TMP35:%.*]] = zext <16 x i8> [[TMP34]] to <16 x i16>
; CHECK-NEXT:    [[TMP36:%.*]] = sub nsw <16 x i16> [[TMP33]], [[TMP35]]
; CHECK-NEXT:    [[TMP37:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP36]], i1 false)
; CHECK-NEXT:    [[TMP38:%.*]] = zext <16 x i16> [[TMP37]] to <16 x i32>
; CHECK-NEXT:    [[TMP39:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP38]])
; CHECK-NEXT:    [[OP_RDX_4:%.*]] = add nuw nsw i32 [[TMP39]], [[OP_RDX_3]]
; CHECK-NEXT:    [[P1_NEXT_4:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_3]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_4:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_3]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP40:%.*]] = load <16 x i8>, ptr [[P1_NEXT_4]], align 1
; CHECK-NEXT:    [[TMP41:%.*]] = zext <16 x i8> [[TMP40]] to <16 x i16>
; CHECK-NEXT:    [[TMP42:%.*]] = load <16 x i8>, ptr [[P2_NEXT_4]], align 1
; CHECK-NEXT:    [[TMP43:%.*]] = zext <16 x i8> [[TMP42]] to <16 x i16>
; CHECK-NEXT:    [[TMP44:%.*]] = sub nsw <16 x i16> [[TMP41]], [[TMP43]]
; CHECK-NEXT:    [[TMP45:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP44]], i1 false)
; CHECK-NEXT:    [[TMP46:%.*]] = zext <16 x i16> [[TMP45]] to <16 x i32>
; CHECK-NEXT:    [[TMP47:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP46]])
; CHECK-NEXT:    [[OP_RDX_5:%.*]] = add nuw nsw i32 [[TMP47]], [[OP_RDX_4]]
; CHECK-NEXT:    [[P1_NEXT_5:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_4]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_5:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_4]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP48:%.*]] = load <16 x i8>, ptr [[P1_NEXT_5]], align 1
; CHECK-NEXT:    [[TMP49:%.*]] = zext <16 x i8> [[TMP48]] to <16 x i16>
; CHECK-NEXT:    [[TMP50:%.*]] = load <16 x i8>, ptr [[P2_NEXT_5]], align 1
; CHECK-NEXT:    [[TMP51:%.*]] = zext <16 x i8> [[TMP50]] to <16 x i16>
; CHECK-NEXT:    [[TMP52:%.*]] = sub nsw <16 x i16> [[TMP49]], [[TMP51]]
; CHECK-NEXT:    [[TMP53:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP52]], i1 false)
; CHECK-NEXT:    [[TMP54:%.*]] = zext <16 x i16> [[TMP53]] to <16 x i32>
; CHECK-NEXT:    [[TMP55:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP54]])
; CHECK-NEXT:    [[OP_RDX_6:%.*]] = add i32 [[TMP55]], [[OP_RDX_5]]
; CHECK-NEXT:    [[P1_NEXT_6:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_5]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_6:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_5]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP56:%.*]] = load <16 x i8>, ptr [[P1_NEXT_6]], align 1
; CHECK-NEXT:    [[TMP57:%.*]] = zext <16 x i8> [[TMP56]] to <16 x i16>
; CHECK-NEXT:    [[TMP58:%.*]] = load <16 x i8>, ptr [[P2_NEXT_6]], align 1
; CHECK-NEXT:    [[TMP59:%.*]] = zext <16 x i8> [[TMP58]] to <16 x i16>
; CHECK-NEXT:    [[TMP60:%.*]] = sub nsw <16 x i16> [[TMP57]], [[TMP59]]
; CHECK-NEXT:    [[TMP61:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP60]], i1 false)
; CHECK-NEXT:    [[TMP62:%.*]] = zext <16 x i16> [[TMP61]] to <16 x i32>
; CHECK-NEXT:    [[TMP63:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP62]])
; CHECK-NEXT:    [[OP_RDX_7:%.*]] = add i32 [[TMP63]], [[OP_RDX_6]]
; CHECK-NEXT:    [[P1_NEXT_7:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_6]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_7:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_6]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP64:%.*]] = load <16 x i8>, ptr [[P1_NEXT_7]], align 1
; CHECK-NEXT:    [[TMP65:%.*]] = zext <16 x i8> [[TMP64]] to <16 x i16>
; CHECK-NEXT:    [[TMP66:%.*]] = load <16 x i8>, ptr [[P2_NEXT_7]], align 1
; CHECK-NEXT:    [[TMP67:%.*]] = zext <16 x i8> [[TMP66]] to <16 x i16>
; CHECK-NEXT:    [[TMP68:%.*]] = sub nsw <16 x i16> [[TMP65]], [[TMP67]]
; CHECK-NEXT:    [[TMP69:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP68]], i1 false)
; CHECK-NEXT:    [[TMP70:%.*]] = zext <16 x i16> [[TMP69]] to <16 x i32>
; CHECK-NEXT:    [[TMP71:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP70]])
; CHECK-NEXT:    [[OP_RDX_8:%.*]] = add i32 [[TMP71]], [[OP_RDX_7]]
; CHECK-NEXT:    [[P1_NEXT_8:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_7]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_8:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_7]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP72:%.*]] = load <16 x i8>, ptr [[P1_NEXT_8]], align 1
; CHECK-NEXT:    [[TMP73:%.*]] = zext <16 x i8> [[TMP72]] to <16 x i16>
; CHECK-NEXT:    [[TMP74:%.*]] = load <16 x i8>, ptr [[P2_NEXT_8]], align 1
; CHECK-NEXT:    [[TMP75:%.*]] = zext <16 x i8> [[TMP74]] to <16 x i16>
; CHECK-NEXT:    [[TMP76:%.*]] = sub nsw <16 x i16> [[TMP73]], [[TMP75]]
; CHECK-NEXT:    [[TMP77:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP76]], i1 false)
; CHECK-NEXT:    [[TMP78:%.*]] = zext <16 x i16> [[TMP77]] to <16 x i32>
; CHECK-NEXT:    [[TMP79:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP78]])
; CHECK-NEXT:    [[OP_RDX_9:%.*]] = add i32 [[TMP79]], [[OP_RDX_8]]
; CHECK-NEXT:    [[P1_NEXT_9:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_8]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_9:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_8]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP80:%.*]] = load <16 x i8>, ptr [[P1_NEXT_9]], align 1
; CHECK-NEXT:    [[TMP81:%.*]] = zext <16 x i8> [[TMP80]] to <16 x i16>
; CHECK-NEXT:    [[TMP82:%.*]] = load <16 x i8>, ptr [[P2_NEXT_9]], align 1
; CHECK-NEXT:    [[TMP83:%.*]] = zext <16 x i8> [[TMP82]] to <16 x i16>
; CHECK-NEXT:    [[TMP84:%.*]] = sub nsw <16 x i16> [[TMP81]], [[TMP83]]
; CHECK-NEXT:    [[TMP85:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP84]], i1 false)
; CHECK-NEXT:    [[TMP86:%.*]] = zext <16 x i16> [[TMP85]] to <16 x i32>
; CHECK-NEXT:    [[TMP87:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP86]])
; CHECK-NEXT:    [[OP_RDX_10:%.*]] = add i32 [[TMP87]], [[OP_RDX_9]]
; CHECK-NEXT:    [[P1_NEXT_10:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_9]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_10:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_9]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP88:%.*]] = load <16 x i8>, ptr [[P1_NEXT_10]], align 1
; CHECK-NEXT:    [[TMP89:%.*]] = zext <16 x i8> [[TMP88]] to <16 x i16>
; CHECK-NEXT:    [[TMP90:%.*]] = load <16 x i8>, ptr [[P2_NEXT_10]], align 1
; CHECK-NEXT:    [[TMP91:%.*]] = zext <16 x i8> [[TMP90]] to <16 x i16>
; CHECK-NEXT:    [[TMP92:%.*]] = sub nsw <16 x i16> [[TMP89]], [[TMP91]]
; CHECK-NEXT:    [[TMP93:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP92]], i1 false)
; CHECK-NEXT:    [[TMP94:%.*]] = zext <16 x i16> [[TMP93]] to <16 x i32>
; CHECK-NEXT:    [[TMP95:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP94]])
; CHECK-NEXT:    [[OP_RDX_11:%.*]] = add i32 [[TMP95]], [[OP_RDX_10]]
; CHECK-NEXT:    [[P1_NEXT_11:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_10]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_11:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_10]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP96:%.*]] = load <16 x i8>, ptr [[P1_NEXT_11]], align 1
; CHECK-NEXT:    [[TMP97:%.*]] = zext <16 x i8> [[TMP96]] to <16 x i16>
; CHECK-NEXT:    [[TMP98:%.*]] = load <16 x i8>, ptr [[P2_NEXT_11]], align 1
; CHECK-NEXT:    [[TMP99:%.*]] = zext <16 x i8> [[TMP98]] to <16 x i16>
; CHECK-NEXT:    [[TMP100:%.*]] = sub nsw <16 x i16> [[TMP97]], [[TMP99]]
; CHECK-NEXT:    [[TMP101:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP100]], i1 false)
; CHECK-NEXT:    [[TMP102:%.*]] = zext <16 x i16> [[TMP101]] to <16 x i32>
; CHECK-NEXT:    [[TMP103:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP102]])
; CHECK-NEXT:    [[OP_RDX_12:%.*]] = add i32 [[TMP103]], [[OP_RDX_11]]
; CHECK-NEXT:    [[P1_NEXT_12:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_11]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_12:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_11]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP104:%.*]] = load <16 x i8>, ptr [[P1_NEXT_12]], align 1
; CHECK-NEXT:    [[TMP105:%.*]] = zext <16 x i8> [[TMP104]] to <16 x i16>
; CHECK-NEXT:    [[TMP106:%.*]] = load <16 x i8>, ptr [[P2_NEXT_12]], align 1
; CHECK-NEXT:    [[TMP107:%.*]] = zext <16 x i8> [[TMP106]] to <16 x i16>
; CHECK-NEXT:    [[TMP108:%.*]] = sub nsw <16 x i16> [[TMP105]], [[TMP107]]
; CHECK-NEXT:    [[TMP109:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP108]], i1 false)
; CHECK-NEXT:    [[TMP110:%.*]] = zext <16 x i16> [[TMP109]] to <16 x i32>
; CHECK-NEXT:    [[TMP111:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP110]])
; CHECK-NEXT:    [[OP_RDX_13:%.*]] = add i32 [[TMP111]], [[OP_RDX_12]]
; CHECK-NEXT:    [[P1_NEXT_13:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_12]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_13:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_12]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP112:%.*]] = load <16 x i8>, ptr [[P1_NEXT_13]], align 1
; CHECK-NEXT:    [[TMP113:%.*]] = zext <16 x i8> [[TMP112]] to <16 x i16>
; CHECK-NEXT:    [[TMP114:%.*]] = load <16 x i8>, ptr [[P2_NEXT_13]], align 1
; CHECK-NEXT:    [[TMP115:%.*]] = zext <16 x i8> [[TMP114]] to <16 x i16>
; CHECK-NEXT:    [[TMP116:%.*]] = sub nsw <16 x i16> [[TMP113]], [[TMP115]]
; CHECK-NEXT:    [[TMP117:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP116]], i1 false)
; CHECK-NEXT:    [[TMP118:%.*]] = zext <16 x i16> [[TMP117]] to <16 x i32>
; CHECK-NEXT:    [[TMP119:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP118]])
; CHECK-NEXT:    [[OP_RDX_14:%.*]] = add i32 [[TMP119]], [[OP_RDX_13]]
; CHECK-NEXT:    [[P1_NEXT_14:%.*]] = getelementptr inbounds i8, ptr [[P1_NEXT_13]], i64 [[IDX_EXT8]]
; CHECK-NEXT:    [[P2_NEXT_14:%.*]] = getelementptr inbounds i8, ptr [[P2_NEXT_13]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[TMP120:%.*]] = load <16 x i8>, ptr [[P1_NEXT_14]], align 1
; CHECK-NEXT:    [[TMP121:%.*]] = zext <16 x i8> [[TMP120]] to <16 x i16>
; CHECK-NEXT:    [[TMP122:%.*]] = load <16 x i8>, ptr [[P2_NEXT_14]], align 1
; CHECK-NEXT:    [[TMP123:%.*]] = zext <16 x i8> [[TMP122]] to <16 x i16>
; CHECK-NEXT:    [[TMP124:%.*]] = sub nsw <16 x i16> [[TMP121]], [[TMP123]]
; CHECK-NEXT:    [[TMP125:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP124]], i1 false)
; CHECK-NEXT:    [[TMP126:%.*]] = zext <16 x i16> [[TMP125]] to <16 x i32>
; CHECK-NEXT:    [[TMP127:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP126]])
; CHECK-NEXT:    [[OP_RDX_15:%.*]] = add i32 [[TMP127]], [[OP_RDX_14]]
; CHECK-NEXT:    ret i32 [[OP_RDX_15]]
;
; The pattern repeats 14 more times for the remaining outer iterations.
entry:
  br label %outer

outer:
  %y = phi i32 [ 0, %entry ], [ %y.next, %inner.exit ]
  %sum = phi i32 [ 0, %entry ], [ %sum.next, %inner.exit ]
  %p1.cur = phi ptr [ %p1, %entry ], [ %p1.next, %inner.exit ]
  %p2.cur = phi ptr [ %p2, %entry ], [ %p2.next, %inner.exit ]
  br label %inner

inner:
  %x = phi i32 [ 0, %outer ], [ %x.next, %inner ]
  %row = phi i32 [ %sum, %outer ], [ %row.next, %inner ]
  %x64 = sext i32 %x to i64
  %p1.x = getelementptr inbounds i8, ptr %p1.cur, i64 %x64
  %v1 = load i8, ptr %p1.x, align 1
  %v1.z = zext i8 %v1 to i32
  %p2.x = getelementptr inbounds i8, ptr %p2.cur, i64 %x64
  %v2 = load i8, ptr %p2.x, align 1
  %v2.z = zext i8 %v2 to i32
  %diff = sub nsw i32 %v1.z, %v2.z
  %abs = tail call i32 @llvm.abs.i32(i32 %diff, i1 true)
  %row.next = add i32 %row, %abs
  %x.next = add nuw nsw i32 %x, 1
  %x.cmp = icmp eq i32 %x.next, 16
  br i1 %x.cmp, label %inner.exit, label %inner

inner.exit:
  %sum.next = phi i32 [ %row.next, %inner ]
  %p1.idx = sext i32 %s_p1 to i64
  %p1.next = getelementptr inbounds i8, ptr %p1.cur, i64 %p1.idx
  %p2.idx = sext i32 %s_p2 to i64
  %p2.next = getelementptr inbounds i8, ptr %p2.cur, i64 %p2.idx
  %y.next = add nuw nsw i32 %y, 1
  %y.cmp = icmp eq i32 %y.next, 16
  br i1 %y.cmp, label %exit, label %outer

exit:
  ret i32 %sum.next
}

declare i32 @llvm.abs.i32(i32, i1)

; Regression: an inner loop with TC=10 (constant, > 8) inside an outer
; loop with TC=4 (constant). With the original deferral predicate, the
; inner is deferred (parent && TC > 8 satisfied), the outer is skipped
; from full-unroll (because inner is deferred), the inner is then
; LV-vectorized, and the outer's body is too costly to fully unroll
; afterwards. With the ancestor-TC check, the inner is not deferred and
; the outer fully unrolls.
define void @nested_outer_tc4_inner_tc10(ptr noalias %dst, ptr noalias %a) {
; CHECK-LABEL: @nested_outer_tc4_inner_tc10(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i32>, ptr [[A:%.*]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = add nsw <4 x i32> [[TMP0]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP1]], ptr [[DST:%.*]], align 4
; CHECK-NEXT:    [[SRC_4:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    [[DST_GEP_4:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 16
; CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr [[SRC_4]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw <4 x i32> [[TMP2]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP3]], ptr [[DST_GEP_4]], align 4
; CHECK-NEXT:    [[SRC_8:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 32
; CHECK-NEXT:    [[DST_GEP_8:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 32
; CHECK-NEXT:    [[TMP4:%.*]] = load <4 x i32>, ptr [[SRC_8]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = add nsw <4 x i32> [[TMP4]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP5]], ptr [[DST_GEP_8]], align 4
; CHECK-NEXT:    [[SRC_2_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 48
; CHECK-NEXT:    [[DST_GEP_2_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 48
; CHECK-NEXT:    [[TMP6:%.*]] = load <4 x i32>, ptr [[SRC_2_1]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = add nsw <4 x i32> [[TMP6]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP7]], ptr [[DST_GEP_2_1]], align 4
; CHECK-NEXT:    [[SRC_6_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 64
; CHECK-NEXT:    [[DST_GEP_6_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 64
; CHECK-NEXT:    [[TMP8:%.*]] = load <4 x i32>, ptr [[SRC_6_1]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = add nsw <4 x i32> [[TMP8]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP9]], ptr [[DST_GEP_6_1]], align 4
; CHECK-NEXT:    [[SRC_25:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 80
; CHECK-NEXT:    [[DST_GEP_28:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 80
; CHECK-NEXT:    [[TMP10:%.*]] = load <4 x i32>, ptr [[SRC_25]], align 4
; CHECK-NEXT:    [[TMP11:%.*]] = add nsw <4 x i32> [[TMP10]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP11]], ptr [[DST_GEP_28]], align 4
; CHECK-NEXT:    [[SRC_4_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 96
; CHECK-NEXT:    [[DST_GEP_4_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 96
; CHECK-NEXT:    [[TMP12:%.*]] = load <4 x i32>, ptr [[SRC_4_2]], align 4
; CHECK-NEXT:    [[TMP13:%.*]] = add nsw <4 x i32> [[TMP12]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP13]], ptr [[DST_GEP_4_2]], align 4
; CHECK-NEXT:    [[SRC_8_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 112
; CHECK-NEXT:    [[DST_GEP_8_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 112
; CHECK-NEXT:    [[TMP14:%.*]] = load <4 x i32>, ptr [[SRC_8_2]], align 4
; CHECK-NEXT:    [[TMP15:%.*]] = add nsw <4 x i32> [[TMP14]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP15]], ptr [[DST_GEP_8_2]], align 4
; CHECK-NEXT:    [[SRC_2_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 128
; CHECK-NEXT:    [[DST_GEP_2_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 128
; CHECK-NEXT:    [[TMP16:%.*]] = load <4 x i32>, ptr [[SRC_2_3]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = add nsw <4 x i32> [[TMP16]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP17]], ptr [[DST_GEP_2_3]], align 4
; CHECK-NEXT:    [[SRC_6_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 144
; CHECK-NEXT:    [[DST_GEP_6_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 144
; CHECK-NEXT:    [[TMP18:%.*]] = load <4 x i32>, ptr [[SRC_6_3]], align 4
; CHECK-NEXT:    [[TMP19:%.*]] = add nsw <4 x i32> [[TMP18]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP19]], ptr [[DST_GEP_6_3]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %outer

outer:
  %i = phi i64 [ 0, %entry ], [ %i.next, %outer.latch ]
  br label %inner

inner:
  %j = phi i64 [ 0, %outer ], [ %j.next, %inner ]
  %off = mul i64 %i, 10
  %idx = add i64 %off, %j
  %src = getelementptr inbounds i32, ptr %a, i64 %idx
  %val = load i32, ptr %src, align 4
  %add = add nsw i32 %val, 1
  %dst.gep = getelementptr inbounds i32, ptr %dst, i64 %idx
  store i32 %add, ptr %dst.gep, align 4
  %j.next = add nuw nsw i64 %j, 1
  %j.cmp = icmp ult i64 %j.next, 10
  br i1 %j.cmp, label %inner, label %outer.latch

outer.latch:
  %i.next = add nuw nsw i64 %i, 1
  %i.cmp = icmp ult i64 %i.next, 4
  br i1 %i.cmp, label %outer, label %exit

exit:
  ret void
}

; Loops with early exits ("break") have unknown SCEV trip count and are
; never deferred (the TripCount <= 1 guard catches this). Verify the
; predicate's behavior on this shape: full unrolling cannot complete it
; either, so the loop must remain a loop -- the predicate must not
; emit a stale deferred marker that would gate the surrounding nest.
define i32 @inner_with_break(ptr noalias %a, ptr noalias %cond, i32 %limit) {
; CHECK-LABEL: @inner_with_break(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[C:%.*]] = load i32, ptr [[COND:%.*]], align 4
; CHECK-NEXT:    [[BRK:%.*]] = icmp eq i32 [[C]], 0
; CHECK-NEXT:    br i1 [[BRK]], label [[OUTER_LATCH:%.*]], label [[INNER_CONT:%.*]]
; CHECK:       inner.cont:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[A:%.*]], align 4
; CHECK-NEXT:    [[CGEP_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 4
; CHECK-NEXT:    [[C_1:%.*]] = load i32, ptr [[CGEP_1]], align 4
; CHECK-NEXT:    [[BRK_1:%.*]] = icmp eq i32 [[C_1]], 0
; CHECK-NEXT:    br i1 [[BRK_1]], label [[OUTER_LATCH]], label [[INNER_CONT_1:%.*]]
; CHECK:       inner.cont.1:
; CHECK-NEXT:    [[VGEP_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 4
; CHECK-NEXT:    [[V_1:%.*]] = load i32, ptr [[VGEP_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_1:%.*]] = add i32 [[V_1]], [[V]]
; CHECK-NEXT:    [[CGEP_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 8
; CHECK-NEXT:    [[C_2:%.*]] = load i32, ptr [[CGEP_2]], align 4
; CHECK-NEXT:    [[BRK_2:%.*]] = icmp eq i32 [[C_2]], 0
; CHECK-NEXT:    br i1 [[BRK_2]], label [[OUTER_LATCH]], label [[INNER_CONT_2:%.*]]
; CHECK:       inner.cont.2:
; CHECK-NEXT:    [[VGEP_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 8
; CHECK-NEXT:    [[V_2:%.*]] = load i32, ptr [[VGEP_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_2:%.*]] = add i32 [[V_2]], [[SUM_NEXT_1]]
; CHECK-NEXT:    [[CGEP_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 12
; CHECK-NEXT:    [[C_3:%.*]] = load i32, ptr [[CGEP_3]], align 4
; CHECK-NEXT:    [[BRK_3:%.*]] = icmp eq i32 [[C_3]], 0
; CHECK-NEXT:    br i1 [[BRK_3]], label [[OUTER_LATCH]], label [[INNER_CONT_3:%.*]]
; CHECK:       inner.cont.3:
; CHECK-NEXT:    [[VGEP_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 12
; CHECK-NEXT:    [[V_3:%.*]] = load i32, ptr [[VGEP_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_3:%.*]] = add i32 [[V_3]], [[SUM_NEXT_2]]
; CHECK-NEXT:    [[CGEP_4:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 16
; CHECK-NEXT:    [[C_4:%.*]] = load i32, ptr [[CGEP_4]], align 4
; CHECK-NEXT:    [[BRK_4:%.*]] = icmp eq i32 [[C_4]], 0
; CHECK-NEXT:    br i1 [[BRK_4]], label [[OUTER_LATCH]], label [[INNER_CONT_4:%.*]]
; CHECK:       inner.cont.4:
; CHECK-NEXT:    [[VGEP_4:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    [[V_4:%.*]] = load i32, ptr [[VGEP_4]], align 4
; CHECK-NEXT:    [[SUM_NEXT_4:%.*]] = add i32 [[V_4]], [[SUM_NEXT_3]]
; CHECK-NEXT:    [[CGEP_5:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 20
; CHECK-NEXT:    [[C_5:%.*]] = load i32, ptr [[CGEP_5]], align 4
; CHECK-NEXT:    [[BRK_5:%.*]] = icmp eq i32 [[C_5]], 0
; CHECK-NEXT:    br i1 [[BRK_5]], label [[OUTER_LATCH]], label [[INNER_CONT_5:%.*]]
; CHECK:       inner.cont.5:
; CHECK-NEXT:    [[VGEP_5:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 20
; CHECK-NEXT:    [[V_5:%.*]] = load i32, ptr [[VGEP_5]], align 4
; CHECK-NEXT:    [[SUM_NEXT_5:%.*]] = add i32 [[V_5]], [[SUM_NEXT_4]]
; CHECK-NEXT:    [[CGEP_6:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 24
; CHECK-NEXT:    [[C_6:%.*]] = load i32, ptr [[CGEP_6]], align 4
; CHECK-NEXT:    [[BRK_6:%.*]] = icmp eq i32 [[C_6]], 0
; CHECK-NEXT:    br i1 [[BRK_6]], label [[OUTER_LATCH]], label [[INNER_CONT_6:%.*]]
; CHECK:       inner.cont.6:
; CHECK-NEXT:    [[VGEP_6:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 24
; CHECK-NEXT:    [[V_6:%.*]] = load i32, ptr [[VGEP_6]], align 4
; CHECK-NEXT:    [[SUM_NEXT_6:%.*]] = add i32 [[V_6]], [[SUM_NEXT_5]]
; CHECK-NEXT:    [[CGEP_7:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 28
; CHECK-NEXT:    [[C_7:%.*]] = load i32, ptr [[CGEP_7]], align 4
; CHECK-NEXT:    [[BRK_7:%.*]] = icmp eq i32 [[C_7]], 0
; CHECK-NEXT:    br i1 [[BRK_7]], label [[OUTER_LATCH]], label [[INNER_CONT_7:%.*]]
; CHECK:       inner.cont.7:
; CHECK-NEXT:    [[VGEP_7:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 28
; CHECK-NEXT:    [[V_7:%.*]] = load i32, ptr [[VGEP_7]], align 4
; CHECK-NEXT:    [[SUM_NEXT_7:%.*]] = add i32 [[V_7]], [[SUM_NEXT_6]]
; CHECK-NEXT:    [[CGEP_8:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 32
; CHECK-NEXT:    [[C_8:%.*]] = load i32, ptr [[CGEP_8]], align 4
; CHECK-NEXT:    [[BRK_8:%.*]] = icmp eq i32 [[C_8]], 0
; CHECK-NEXT:    br i1 [[BRK_8]], label [[OUTER_LATCH]], label [[INNER_CONT_8:%.*]]
; CHECK:       inner.cont.8:
; CHECK-NEXT:    [[VGEP_8:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 32
; CHECK-NEXT:    [[V_8:%.*]] = load i32, ptr [[VGEP_8]], align 4
; CHECK-NEXT:    [[SUM_NEXT_8:%.*]] = add i32 [[V_8]], [[SUM_NEXT_7]]
; CHECK-NEXT:    [[CGEP_9:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 36
; CHECK-NEXT:    [[C_9:%.*]] = load i32, ptr [[CGEP_9]], align 4
; CHECK-NEXT:    [[BRK_9:%.*]] = icmp eq i32 [[C_9]], 0
; CHECK-NEXT:    br i1 [[BRK_9]], label [[OUTER_LATCH]], label [[INNER_CONT_9:%.*]]
; CHECK:       inner.cont.9:
; CHECK-NEXT:    [[VGEP_9:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 36
; CHECK-NEXT:    [[V_9:%.*]] = load i32, ptr [[VGEP_9]], align 4
; CHECK-NEXT:    [[SUM_NEXT_9:%.*]] = add i32 [[V_9]], [[SUM_NEXT_8]]
; CHECK-NEXT:    br label [[OUTER_LATCH]]
; CHECK:       outer.latch:
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[SUM_NEXT_9]], [[INNER_CONT_9]] ], [ [[V]], [[INNER_CONT]] ], [ [[SUM_NEXT_8]], [[INNER_CONT_8]] ], [ [[SUM_NEXT_1]], [[INNER_CONT_1]] ], [ [[SUM_NEXT_6]], [[INNER_CONT_6]] ], [ [[SUM_NEXT_2]], [[INNER_CONT_2]] ], [ [[SUM_NEXT_7]], [[INNER_CONT_7]] ], [ [[SUM_NEXT_3]], [[INNER_CONT_3]] ], [ [[SUM_NEXT_5]], [[INNER_CONT_5]] ], [ [[SUM_NEXT_4]], [[INNER_CONT_4]] ]
; CHECK-NEXT:    [[CGEP_11:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 40
; CHECK-NEXT:    [[C_12:%.*]] = load i32, ptr [[CGEP_11]], align 4
; CHECK-NEXT:    [[BRK_13:%.*]] = icmp eq i32 [[C_12]], 0
; CHECK-NEXT:    br i1 [[BRK_13]], label [[OUTER_LATCH_1:%.*]], label [[INNER_CONT_17:%.*]]
; CHECK:       inner.cont.17:
; CHECK-NEXT:    [[VGEP_14:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 40
; CHECK-NEXT:    [[V_15:%.*]] = load i32, ptr [[VGEP_14]], align 4
; CHECK-NEXT:    [[SUM_NEXT_16:%.*]] = add i32 [[V_15]], [[ACC_NEXT]]
; CHECK-NEXT:    [[CGEP_1_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 44
; CHECK-NEXT:    [[C_1_1:%.*]] = load i32, ptr [[CGEP_1_1]], align 4
; CHECK-NEXT:    [[BRK_1_1:%.*]] = icmp eq i32 [[C_1_1]], 0
; CHECK-NEXT:    br i1 [[BRK_1_1]], label [[OUTER_LATCH_1]], label [[INNER_CONT_1_1:%.*]]
; CHECK:       inner.cont.1.1:
; CHECK-NEXT:    [[VGEP_1_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 44
; CHECK-NEXT:    [[V_1_1:%.*]] = load i32, ptr [[VGEP_1_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_1_1:%.*]] = add i32 [[V_1_1]], [[SUM_NEXT_16]]
; CHECK-NEXT:    [[CGEP_2_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 48
; CHECK-NEXT:    [[C_2_1:%.*]] = load i32, ptr [[CGEP_2_1]], align 4
; CHECK-NEXT:    [[BRK_2_1:%.*]] = icmp eq i32 [[C_2_1]], 0
; CHECK-NEXT:    br i1 [[BRK_2_1]], label [[OUTER_LATCH_1]], label [[INNER_CONT_2_1:%.*]]
; CHECK:       inner.cont.2.1:
; CHECK-NEXT:    [[VGEP_2_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 48
; CHECK-NEXT:    [[V_2_1:%.*]] = load i32, ptr [[VGEP_2_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_2_1:%.*]] = add i32 [[V_2_1]], [[SUM_NEXT_1_1]]
; CHECK-NEXT:    [[CGEP_3_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 52
; CHECK-NEXT:    [[C_3_1:%.*]] = load i32, ptr [[CGEP_3_1]], align 4
; CHECK-NEXT:    [[BRK_3_1:%.*]] = icmp eq i32 [[C_3_1]], 0
; CHECK-NEXT:    br i1 [[BRK_3_1]], label [[OUTER_LATCH_1]], label [[INNER_CONT_3_1:%.*]]
; CHECK:       inner.cont.3.1:
; CHECK-NEXT:    [[VGEP_3_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 52
; CHECK-NEXT:    [[V_3_1:%.*]] = load i32, ptr [[VGEP_3_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_3_1:%.*]] = add i32 [[V_3_1]], [[SUM_NEXT_2_1]]
; CHECK-NEXT:    [[CGEP_4_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 56
; CHECK-NEXT:    [[C_4_1:%.*]] = load i32, ptr [[CGEP_4_1]], align 4
; CHECK-NEXT:    [[BRK_4_1:%.*]] = icmp eq i32 [[C_4_1]], 0
; CHECK-NEXT:    br i1 [[BRK_4_1]], label [[OUTER_LATCH_1]], label [[INNER_CONT_4_1:%.*]]
; CHECK:       inner.cont.4.1:
; CHECK-NEXT:    [[VGEP_4_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 56
; CHECK-NEXT:    [[V_4_1:%.*]] = load i32, ptr [[VGEP_4_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_4_1:%.*]] = add i32 [[V_4_1]], [[SUM_NEXT_3_1]]
; CHECK-NEXT:    [[CGEP_5_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 60
; CHECK-NEXT:    [[C_5_1:%.*]] = load i32, ptr [[CGEP_5_1]], align 4
; CHECK-NEXT:    [[BRK_5_1:%.*]] = icmp eq i32 [[C_5_1]], 0
; CHECK-NEXT:    br i1 [[BRK_5_1]], label [[OUTER_LATCH_1]], label [[INNER_CONT_5_1:%.*]]
; CHECK:       inner.cont.5.1:
; CHECK-NEXT:    [[VGEP_5_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 60
; CHECK-NEXT:    [[V_5_1:%.*]] = load i32, ptr [[VGEP_5_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_5_1:%.*]] = add i32 [[V_5_1]], [[SUM_NEXT_4_1]]
; CHECK-NEXT:    [[CGEP_6_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 64
; CHECK-NEXT:    [[C_6_1:%.*]] = load i32, ptr [[CGEP_6_1]], align 4
; CHECK-NEXT:    [[BRK_6_1:%.*]] = icmp eq i32 [[C_6_1]], 0
; CHECK-NEXT:    br i1 [[BRK_6_1]], label [[OUTER_LATCH_1]], label [[INNER_CONT_6_1:%.*]]
; CHECK:       inner.cont.6.1:
; CHECK-NEXT:    [[VGEP_6_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 64
; CHECK-NEXT:    [[V_6_1:%.*]] = load i32, ptr [[VGEP_6_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_6_1:%.*]] = add i32 [[V_6_1]], [[SUM_NEXT_5_1]]
; CHECK-NEXT:    [[CGEP_7_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 68
; CHECK-NEXT:    [[C_7_1:%.*]] = load i32, ptr [[CGEP_7_1]], align 4
; CHECK-NEXT:    [[BRK_7_1:%.*]] = icmp eq i32 [[C_7_1]], 0
; CHECK-NEXT:    br i1 [[BRK_7_1]], label [[OUTER_LATCH_1]], label [[INNER_CONT_7_1:%.*]]
; CHECK:       inner.cont.7.1:
; CHECK-NEXT:    [[VGEP_7_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 68
; CHECK-NEXT:    [[V_7_1:%.*]] = load i32, ptr [[VGEP_7_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_7_1:%.*]] = add i32 [[V_7_1]], [[SUM_NEXT_6_1]]
; CHECK-NEXT:    [[CGEP_8_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 72
; CHECK-NEXT:    [[C_8_1:%.*]] = load i32, ptr [[CGEP_8_1]], align 4
; CHECK-NEXT:    [[BRK_8_1:%.*]] = icmp eq i32 [[C_8_1]], 0
; CHECK-NEXT:    br i1 [[BRK_8_1]], label [[OUTER_LATCH_1]], label [[INNER_CONT_8_1:%.*]]
; CHECK:       inner.cont.8.1:
; CHECK-NEXT:    [[VGEP_8_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 72
; CHECK-NEXT:    [[V_8_1:%.*]] = load i32, ptr [[VGEP_8_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_8_1:%.*]] = add i32 [[V_8_1]], [[SUM_NEXT_7_1]]
; CHECK-NEXT:    [[CGEP_9_1:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 76
; CHECK-NEXT:    [[C_9_1:%.*]] = load i32, ptr [[CGEP_9_1]], align 4
; CHECK-NEXT:    [[BRK_9_1:%.*]] = icmp eq i32 [[C_9_1]], 0
; CHECK-NEXT:    br i1 [[BRK_9_1]], label [[OUTER_LATCH_1]], label [[INNER_CONT_9_1:%.*]]
; CHECK:       inner.cont.9.1:
; CHECK-NEXT:    [[VGEP_9_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 76
; CHECK-NEXT:    [[V_9_1:%.*]] = load i32, ptr [[VGEP_9_1]], align 4
; CHECK-NEXT:    [[SUM_NEXT_9_1:%.*]] = add i32 [[V_9_1]], [[SUM_NEXT_8_1]]
; CHECK-NEXT:    br label [[OUTER_LATCH_1]]
; CHECK:       outer.latch.1:
; CHECK-NEXT:    [[ACC_NEXT_1:%.*]] = phi i32 [ [[ACC_NEXT]], [[OUTER_LATCH]] ], [ [[SUM_NEXT_9_1]], [[INNER_CONT_9_1]] ], [ [[SUM_NEXT_16]], [[INNER_CONT_17]] ], [ [[SUM_NEXT_8_1]], [[INNER_CONT_8_1]] ], [ [[SUM_NEXT_1_1]], [[INNER_CONT_1_1]] ], [ [[SUM_NEXT_6_1]], [[INNER_CONT_6_1]] ], [ [[SUM_NEXT_2_1]], [[INNER_CONT_2_1]] ], [ [[SUM_NEXT_7_1]], [[INNER_CONT_7_1]] ], [ [[SUM_NEXT_3_1]], [[INNER_CONT_3_1]] ], [ [[SUM_NEXT_5_1]], [[INNER_CONT_5_1]] ], [ [[SUM_NEXT_4_1]], [[INNER_CONT_4_1]] ]
; CHECK-NEXT:    [[CGEP_28:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 80
; CHECK-NEXT:    [[C_29:%.*]] = load i32, ptr [[CGEP_28]], align 4
; CHECK-NEXT:    [[BRK_210:%.*]] = icmp eq i32 [[C_29]], 0
; CHECK-NEXT:    br i1 [[BRK_210]], label [[OUTER_LATCH_2:%.*]], label [[INNER_CONT_214:%.*]]
; CHECK:       inner.cont.214:
; CHECK-NEXT:    [[VGEP_211:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 80
; CHECK-NEXT:    [[V_212:%.*]] = load i32, ptr [[VGEP_211]], align 4
; CHECK-NEXT:    [[SUM_NEXT_213:%.*]] = add i32 [[V_212]], [[ACC_NEXT_1]]
; CHECK-NEXT:    [[CGEP_1_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 84
; CHECK-NEXT:    [[C_1_2:%.*]] = load i32, ptr [[CGEP_1_2]], align 4
; CHECK-NEXT:    [[BRK_1_2:%.*]] = icmp eq i32 [[C_1_2]], 0
; CHECK-NEXT:    br i1 [[BRK_1_2]], label [[OUTER_LATCH_2]], label [[INNER_CONT_1_2:%.*]]
; CHECK:       inner.cont.1.2:
; CHECK-NEXT:    [[VGEP_1_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 84
; CHECK-NEXT:    [[V_1_2:%.*]] = load i32, ptr [[VGEP_1_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_1_2:%.*]] = add i32 [[V_1_2]], [[SUM_NEXT_213]]
; CHECK-NEXT:    [[CGEP_2_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 88
; CHECK-NEXT:    [[C_2_2:%.*]] = load i32, ptr [[CGEP_2_2]], align 4
; CHECK-NEXT:    [[BRK_2_2:%.*]] = icmp eq i32 [[C_2_2]], 0
; CHECK-NEXT:    br i1 [[BRK_2_2]], label [[OUTER_LATCH_2]], label [[INNER_CONT_2_2:%.*]]
; CHECK:       inner.cont.2.2:
; CHECK-NEXT:    [[VGEP_2_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 88
; CHECK-NEXT:    [[V_2_2:%.*]] = load i32, ptr [[VGEP_2_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_2_2:%.*]] = add i32 [[V_2_2]], [[SUM_NEXT_1_2]]
; CHECK-NEXT:    [[CGEP_3_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 92
; CHECK-NEXT:    [[C_3_2:%.*]] = load i32, ptr [[CGEP_3_2]], align 4
; CHECK-NEXT:    [[BRK_3_2:%.*]] = icmp eq i32 [[C_3_2]], 0
; CHECK-NEXT:    br i1 [[BRK_3_2]], label [[OUTER_LATCH_2]], label [[INNER_CONT_3_2:%.*]]
; CHECK:       inner.cont.3.2:
; CHECK-NEXT:    [[VGEP_3_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 92
; CHECK-NEXT:    [[V_3_2:%.*]] = load i32, ptr [[VGEP_3_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_3_2:%.*]] = add i32 [[V_3_2]], [[SUM_NEXT_2_2]]
; CHECK-NEXT:    [[CGEP_4_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 96
; CHECK-NEXT:    [[C_4_2:%.*]] = load i32, ptr [[CGEP_4_2]], align 4
; CHECK-NEXT:    [[BRK_4_2:%.*]] = icmp eq i32 [[C_4_2]], 0
; CHECK-NEXT:    br i1 [[BRK_4_2]], label [[OUTER_LATCH_2]], label [[INNER_CONT_4_2:%.*]]
; CHECK:       inner.cont.4.2:
; CHECK-NEXT:    [[VGEP_4_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 96
; CHECK-NEXT:    [[V_4_2:%.*]] = load i32, ptr [[VGEP_4_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_4_2:%.*]] = add i32 [[V_4_2]], [[SUM_NEXT_3_2]]
; CHECK-NEXT:    [[CGEP_5_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 100
; CHECK-NEXT:    [[C_5_2:%.*]] = load i32, ptr [[CGEP_5_2]], align 4
; CHECK-NEXT:    [[BRK_5_2:%.*]] = icmp eq i32 [[C_5_2]], 0
; CHECK-NEXT:    br i1 [[BRK_5_2]], label [[OUTER_LATCH_2]], label [[INNER_CONT_5_2:%.*]]
; CHECK:       inner.cont.5.2:
; CHECK-NEXT:    [[VGEP_5_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 100
; CHECK-NEXT:    [[V_5_2:%.*]] = load i32, ptr [[VGEP_5_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_5_2:%.*]] = add i32 [[V_5_2]], [[SUM_NEXT_4_2]]
; CHECK-NEXT:    [[CGEP_6_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 104
; CHECK-NEXT:    [[C_6_2:%.*]] = load i32, ptr [[CGEP_6_2]], align 4
; CHECK-NEXT:    [[BRK_6_2:%.*]] = icmp eq i32 [[C_6_2]], 0
; CHECK-NEXT:    br i1 [[BRK_6_2]], label [[OUTER_LATCH_2]], label [[INNER_CONT_6_2:%.*]]
; CHECK:       inner.cont.6.2:
; CHECK-NEXT:    [[VGEP_6_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 104
; CHECK-NEXT:    [[V_6_2:%.*]] = load i32, ptr [[VGEP_6_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_6_2:%.*]] = add i32 [[V_6_2]], [[SUM_NEXT_5_2]]
; CHECK-NEXT:    [[CGEP_7_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 108
; CHECK-NEXT:    [[C_7_2:%.*]] = load i32, ptr [[CGEP_7_2]], align 4
; CHECK-NEXT:    [[BRK_7_2:%.*]] = icmp eq i32 [[C_7_2]], 0
; CHECK-NEXT:    br i1 [[BRK_7_2]], label [[OUTER_LATCH_2]], label [[INNER_CONT_7_2:%.*]]
; CHECK:       inner.cont.7.2:
; CHECK-NEXT:    [[VGEP_7_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 108
; CHECK-NEXT:    [[V_7_2:%.*]] = load i32, ptr [[VGEP_7_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_7_2:%.*]] = add i32 [[V_7_2]], [[SUM_NEXT_6_2]]
; CHECK-NEXT:    [[CGEP_8_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 112
; CHECK-NEXT:    [[C_8_2:%.*]] = load i32, ptr [[CGEP_8_2]], align 4
; CHECK-NEXT:    [[BRK_8_2:%.*]] = icmp eq i32 [[C_8_2]], 0
; CHECK-NEXT:    br i1 [[BRK_8_2]], label [[OUTER_LATCH_2]], label [[INNER_CONT_8_2:%.*]]
; CHECK:       inner.cont.8.2:
; CHECK-NEXT:    [[VGEP_8_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 112
; CHECK-NEXT:    [[V_8_2:%.*]] = load i32, ptr [[VGEP_8_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_8_2:%.*]] = add i32 [[V_8_2]], [[SUM_NEXT_7_2]]
; CHECK-NEXT:    [[CGEP_9_2:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 116
; CHECK-NEXT:    [[C_9_2:%.*]] = load i32, ptr [[CGEP_9_2]], align 4
; CHECK-NEXT:    [[BRK_9_2:%.*]] = icmp eq i32 [[C_9_2]], 0
; CHECK-NEXT:    br i1 [[BRK_9_2]], label [[OUTER_LATCH_2]], label [[INNER_CONT_9_2:%.*]]
; CHECK:       inner.cont.9.2:
; CHECK-NEXT:    [[VGEP_9_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 116
; CHECK-NEXT:    [[V_9_2:%.*]] = load i32, ptr [[VGEP_9_2]], align 4
; CHECK-NEXT:    [[SUM_NEXT_9_2:%.*]] = add i32 [[V_9_2]], [[SUM_NEXT_8_2]]
; CHECK-NEXT:    br label [[OUTER_LATCH_2]]
; CHECK:       outer.latch.2:
; CHECK-NEXT:    [[ACC_NEXT_2:%.*]] = phi i32 [ [[ACC_NEXT_1]], [[OUTER_LATCH_1]] ], [ [[SUM_NEXT_9_2]], [[INNER_CONT_9_2]] ], [ [[SUM_NEXT_213]], [[INNER_CONT_214]] ], [ [[SUM_NEXT_8_2]], [[INNER_CONT_8_2]] ], [ [[SUM_NEXT_1_2]], [[INNER_CONT_1_2]] ], [ [[SUM_NEXT_6_2]], [[INNER_CONT_6_2]] ], [ [[SUM_NEXT_2_2]], [[INNER_CONT_2_2]] ], [ [[SUM_NEXT_7_2]], [[INNER_CONT_7_2]] ], [ [[SUM_NEXT_3_2]], [[INNER_CONT_3_2]] ], [ [[SUM_NEXT_5_2]], [[INNER_CONT_5_2]] ], [ [[SUM_NEXT_4_2]], [[INNER_CONT_4_2]] ]
; CHECK-NEXT:    [[CGEP_315:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 120
; CHECK-NEXT:    [[C_316:%.*]] = load i32, ptr [[CGEP_315]], align 4
; CHECK-NEXT:    [[BRK_317:%.*]] = icmp eq i32 [[C_316]], 0
; CHECK-NEXT:    br i1 [[BRK_317]], label [[OUTER_LATCH_3:%.*]], label [[INNER_CONT_321:%.*]]
; CHECK:       inner.cont.321:
; CHECK-NEXT:    [[VGEP_318:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 120
; CHECK-NEXT:    [[V_319:%.*]] = load i32, ptr [[VGEP_318]], align 4
; CHECK-NEXT:    [[SUM_NEXT_320:%.*]] = add i32 [[V_319]], [[ACC_NEXT_2]]
; CHECK-NEXT:    [[CGEP_1_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 124
; CHECK-NEXT:    [[C_1_3:%.*]] = load i32, ptr [[CGEP_1_3]], align 4
; CHECK-NEXT:    [[BRK_1_3:%.*]] = icmp eq i32 [[C_1_3]], 0
; CHECK-NEXT:    br i1 [[BRK_1_3]], label [[OUTER_LATCH_3]], label [[INNER_CONT_1_3:%.*]]
; CHECK:       inner.cont.1.3:
; CHECK-NEXT:    [[VGEP_1_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 124
; CHECK-NEXT:    [[V_1_3:%.*]] = load i32, ptr [[VGEP_1_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_1_3:%.*]] = add i32 [[V_1_3]], [[SUM_NEXT_320]]
; CHECK-NEXT:    [[CGEP_2_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 128
; CHECK-NEXT:    [[C_2_3:%.*]] = load i32, ptr [[CGEP_2_3]], align 4
; CHECK-NEXT:    [[BRK_2_3:%.*]] = icmp eq i32 [[C_2_3]], 0
; CHECK-NEXT:    br i1 [[BRK_2_3]], label [[OUTER_LATCH_3]], label [[INNER_CONT_2_3:%.*]]
; CHECK:       inner.cont.2.3:
; CHECK-NEXT:    [[VGEP_2_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 128
; CHECK-NEXT:    [[V_2_3:%.*]] = load i32, ptr [[VGEP_2_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_2_3:%.*]] = add i32 [[V_2_3]], [[SUM_NEXT_1_3]]
; CHECK-NEXT:    [[CGEP_3_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 132
; CHECK-NEXT:    [[C_3_3:%.*]] = load i32, ptr [[CGEP_3_3]], align 4
; CHECK-NEXT:    [[BRK_3_3:%.*]] = icmp eq i32 [[C_3_3]], 0
; CHECK-NEXT:    br i1 [[BRK_3_3]], label [[OUTER_LATCH_3]], label [[INNER_CONT_3_3:%.*]]
; CHECK:       inner.cont.3.3:
; CHECK-NEXT:    [[VGEP_3_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 132
; CHECK-NEXT:    [[V_3_3:%.*]] = load i32, ptr [[VGEP_3_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_3_3:%.*]] = add i32 [[V_3_3]], [[SUM_NEXT_2_3]]
; CHECK-NEXT:    [[CGEP_4_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 136
; CHECK-NEXT:    [[C_4_3:%.*]] = load i32, ptr [[CGEP_4_3]], align 4
; CHECK-NEXT:    [[BRK_4_3:%.*]] = icmp eq i32 [[C_4_3]], 0
; CHECK-NEXT:    br i1 [[BRK_4_3]], label [[OUTER_LATCH_3]], label [[INNER_CONT_4_3:%.*]]
; CHECK:       inner.cont.4.3:
; CHECK-NEXT:    [[VGEP_4_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 136
; CHECK-NEXT:    [[V_4_3:%.*]] = load i32, ptr [[VGEP_4_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_4_3:%.*]] = add i32 [[V_4_3]], [[SUM_NEXT_3_3]]
; CHECK-NEXT:    [[CGEP_5_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 140
; CHECK-NEXT:    [[C_5_3:%.*]] = load i32, ptr [[CGEP_5_3]], align 4
; CHECK-NEXT:    [[BRK_5_3:%.*]] = icmp eq i32 [[C_5_3]], 0
; CHECK-NEXT:    br i1 [[BRK_5_3]], label [[OUTER_LATCH_3]], label [[INNER_CONT_5_3:%.*]]
; CHECK:       inner.cont.5.3:
; CHECK-NEXT:    [[VGEP_5_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 140
; CHECK-NEXT:    [[V_5_3:%.*]] = load i32, ptr [[VGEP_5_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_5_3:%.*]] = add i32 [[V_5_3]], [[SUM_NEXT_4_3]]
; CHECK-NEXT:    [[CGEP_6_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 144
; CHECK-NEXT:    [[C_6_3:%.*]] = load i32, ptr [[CGEP_6_3]], align 4
; CHECK-NEXT:    [[BRK_6_3:%.*]] = icmp eq i32 [[C_6_3]], 0
; CHECK-NEXT:    br i1 [[BRK_6_3]], label [[OUTER_LATCH_3]], label [[INNER_CONT_6_3:%.*]]
; CHECK:       inner.cont.6.3:
; CHECK-NEXT:    [[VGEP_6_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 144
; CHECK-NEXT:    [[V_6_3:%.*]] = load i32, ptr [[VGEP_6_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_6_3:%.*]] = add i32 [[V_6_3]], [[SUM_NEXT_5_3]]
; CHECK-NEXT:    [[CGEP_7_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 148
; CHECK-NEXT:    [[C_7_3:%.*]] = load i32, ptr [[CGEP_7_3]], align 4
; CHECK-NEXT:    [[BRK_7_3:%.*]] = icmp eq i32 [[C_7_3]], 0
; CHECK-NEXT:    br i1 [[BRK_7_3]], label [[OUTER_LATCH_3]], label [[INNER_CONT_7_3:%.*]]
; CHECK:       inner.cont.7.3:
; CHECK-NEXT:    [[VGEP_7_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 148
; CHECK-NEXT:    [[V_7_3:%.*]] = load i32, ptr [[VGEP_7_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_7_3:%.*]] = add i32 [[V_7_3]], [[SUM_NEXT_6_3]]
; CHECK-NEXT:    [[CGEP_8_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 152
; CHECK-NEXT:    [[C_8_3:%.*]] = load i32, ptr [[CGEP_8_3]], align 4
; CHECK-NEXT:    [[BRK_8_3:%.*]] = icmp eq i32 [[C_8_3]], 0
; CHECK-NEXT:    br i1 [[BRK_8_3]], label [[OUTER_LATCH_3]], label [[INNER_CONT_8_3:%.*]]
; CHECK:       inner.cont.8.3:
; CHECK-NEXT:    [[VGEP_8_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 152
; CHECK-NEXT:    [[V_8_3:%.*]] = load i32, ptr [[VGEP_8_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_8_3:%.*]] = add i32 [[V_8_3]], [[SUM_NEXT_7_3]]
; CHECK-NEXT:    [[CGEP_9_3:%.*]] = getelementptr inbounds nuw i8, ptr [[COND]], i64 156
; CHECK-NEXT:    [[C_9_3:%.*]] = load i32, ptr [[CGEP_9_3]], align 4
; CHECK-NEXT:    [[BRK_9_3:%.*]] = icmp eq i32 [[C_9_3]], 0
; CHECK-NEXT:    br i1 [[BRK_9_3]], label [[OUTER_LATCH_3]], label [[INNER_CONT_9_3:%.*]]
; CHECK:       inner.cont.9.3:
; CHECK-NEXT:    [[VGEP_9_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 156
; CHECK-NEXT:    [[V_9_3:%.*]] = load i32, ptr [[VGEP_9_3]], align 4
; CHECK-NEXT:    [[SUM_NEXT_9_3:%.*]] = add i32 [[V_9_3]], [[SUM_NEXT_8_3]]
; CHECK-NEXT:    br label [[OUTER_LATCH_3]]
; CHECK:       outer.latch.3:
; CHECK-NEXT:    [[ACC_NEXT_3:%.*]] = phi i32 [ [[ACC_NEXT_2]], [[OUTER_LATCH_2]] ], [ [[SUM_NEXT_9_3]], [[INNER_CONT_9_3]] ], [ [[SUM_NEXT_320]], [[INNER_CONT_321]] ], [ [[SUM_NEXT_8_3]], [[INNER_CONT_8_3]] ], [ [[SUM_NEXT_1_3]], [[INNER_CONT_1_3]] ], [ [[SUM_NEXT_6_3]], [[INNER_CONT_6_3]] ], [ [[SUM_NEXT_2_3]], [[INNER_CONT_2_3]] ], [ [[SUM_NEXT_7_3]], [[INNER_CONT_7_3]] ], [ [[SUM_NEXT_3_3]], [[INNER_CONT_3_3]] ], [ [[SUM_NEXT_5_3]], [[INNER_CONT_5_3]] ], [ [[SUM_NEXT_4_3]], [[INNER_CONT_4_3]] ]
; CHECK-NEXT:    ret i32 [[ACC_NEXT_3]]
;
; The outer 4-iter loop must still fully unroll. The early-exit inner
; ends up as separate (peeled / partially unrolled) iterations -- never
; as a deferred body that gates the outer.
entry:
  br label %outer

outer:
  %i = phi i64 [ 0, %entry ], [ %i.next, %outer.latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %outer.latch ]
  br label %inner

inner:
  %j = phi i64 [ 0, %outer ], [ %j.next, %inner.cont ]
  %sum = phi i32 [ %acc, %outer ], [ %sum.next, %inner.cont ]
  %off = mul i64 %i, 10
  %idx = add i64 %off, %j
  %cgep = getelementptr inbounds i32, ptr %cond, i64 %idx
  %c = load i32, ptr %cgep, align 4
  %brk = icmp eq i32 %c, 0
  br i1 %brk, label %outer.latch, label %inner.cont

inner.cont:
  %vgep = getelementptr inbounds i32, ptr %a, i64 %idx
  %v = load i32, ptr %vgep, align 4
  %sum.next = add i32 %sum, %v
  %j.next = add nuw nsw i64 %j, 1
  %j.cmp = icmp ult i64 %j.next, 10
  br i1 %j.cmp, label %inner, label %outer.latch

outer.latch:
  %acc.next = phi i32 [ %sum, %inner ], [ %sum.next, %inner.cont ]
  %i.next = add nuw nsw i64 %i, 1
  %i.cmp = icmp ult i64 %i.next, 4
  br i1 %i.cmp, label %outer, label %exit

exit:
  ret i32 %acc.next
}

; A small-TC inner whose memory accesses would require runtime alias
; checks for LoopVectorize (the pointers are not noalias). The predicate
; should not defer here: the small TC pushes the LV runtime-check + vector
; epilogue cost above the gain, and -- because the surrounding outer has
; TC=4 -- deferring would also leave the outer's body too large for the
; late LoopUnrollPass to fully unroll. SLP cannot rescue this either: the
; alias-required loads/stores block its merging. The right answer is to
; let the early full unroller do the work.
define void @inner_needs_runtime_alias_checks(ptr %dst, ptr %a) {
; CHECK-LABEL: @inner_needs_runtime_alias_checks(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[A:%.*]], align 4
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[V]], 1
; CHECK-NEXT:    store i32 [[ADD]], ptr [[DST:%.*]], align 4
; CHECK-NEXT:    [[SRC_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 4
; CHECK-NEXT:    [[V_1:%.*]] = load i32, ptr [[SRC_1]], align 4
; CHECK-NEXT:    [[ADD_1:%.*]] = add nsw i32 [[V_1]], 1
; CHECK-NEXT:    [[DGEP_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 4
; CHECK-NEXT:    store i32 [[ADD_1]], ptr [[DGEP_1]], align 4
; CHECK-NEXT:    [[SRC_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 8
; CHECK-NEXT:    [[V_2:%.*]] = load i32, ptr [[SRC_2]], align 4
; CHECK-NEXT:    [[ADD_2:%.*]] = add nsw i32 [[V_2]], 1
; CHECK-NEXT:    [[DGEP_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 8
; CHECK-NEXT:    store i32 [[ADD_2]], ptr [[DGEP_2]], align 4
; CHECK-NEXT:    [[SRC_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 12
; CHECK-NEXT:    [[V_3:%.*]] = load i32, ptr [[SRC_3]], align 4
; CHECK-NEXT:    [[ADD_3:%.*]] = add nsw i32 [[V_3]], 1
; CHECK-NEXT:    [[DGEP_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 12
; CHECK-NEXT:    store i32 [[ADD_3]], ptr [[DGEP_3]], align 4
; CHECK-NEXT:    [[SRC_4:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    [[V_4:%.*]] = load i32, ptr [[SRC_4]], align 4
; CHECK-NEXT:    [[ADD_4:%.*]] = add nsw i32 [[V_4]], 1
; CHECK-NEXT:    [[DGEP_4:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 16
; CHECK-NEXT:    store i32 [[ADD_4]], ptr [[DGEP_4]], align 4
; CHECK-NEXT:    [[SRC_5:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 20
; CHECK-NEXT:    [[V_5:%.*]] = load i32, ptr [[SRC_5]], align 4
; CHECK-NEXT:    [[ADD_5:%.*]] = add nsw i32 [[V_5]], 1
; CHECK-NEXT:    [[DGEP_5:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 20
; CHECK-NEXT:    store i32 [[ADD_5]], ptr [[DGEP_5]], align 4
; CHECK-NEXT:    [[SRC_11:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 24
; CHECK-NEXT:    [[V_12:%.*]] = load i32, ptr [[SRC_11]], align 4
; CHECK-NEXT:    [[ADD_13:%.*]] = add nsw i32 [[V_12]], 1
; CHECK-NEXT:    [[DGEP_14:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 24
; CHECK-NEXT:    store i32 [[ADD_13]], ptr [[DGEP_14]], align 4
; CHECK-NEXT:    [[SRC_1_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 28
; CHECK-NEXT:    [[V_1_1:%.*]] = load i32, ptr [[SRC_1_1]], align 4
; CHECK-NEXT:    [[ADD_1_1:%.*]] = add nsw i32 [[V_1_1]], 1
; CHECK-NEXT:    [[DGEP_1_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 28
; CHECK-NEXT:    store i32 [[ADD_1_1]], ptr [[DGEP_1_1]], align 4
; CHECK-NEXT:    [[SRC_2_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 32
; CHECK-NEXT:    [[V_2_1:%.*]] = load i32, ptr [[SRC_2_1]], align 4
; CHECK-NEXT:    [[ADD_2_1:%.*]] = add nsw i32 [[V_2_1]], 1
; CHECK-NEXT:    [[DGEP_2_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 32
; CHECK-NEXT:    store i32 [[ADD_2_1]], ptr [[DGEP_2_1]], align 4
; CHECK-NEXT:    [[SRC_3_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 36
; CHECK-NEXT:    [[V_3_1:%.*]] = load i32, ptr [[SRC_3_1]], align 4
; CHECK-NEXT:    [[ADD_3_1:%.*]] = add nsw i32 [[V_3_1]], 1
; CHECK-NEXT:    [[DGEP_3_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 36
; CHECK-NEXT:    store i32 [[ADD_3_1]], ptr [[DGEP_3_1]], align 4
; CHECK-NEXT:    [[SRC_4_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 40
; CHECK-NEXT:    [[V_4_1:%.*]] = load i32, ptr [[SRC_4_1]], align 4
; CHECK-NEXT:    [[ADD_4_1:%.*]] = add nsw i32 [[V_4_1]], 1
; CHECK-NEXT:    [[DGEP_4_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 40
; CHECK-NEXT:    store i32 [[ADD_4_1]], ptr [[DGEP_4_1]], align 4
; CHECK-NEXT:    [[SRC_5_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 44
; CHECK-NEXT:    [[V_5_1:%.*]] = load i32, ptr [[SRC_5_1]], align 4
; CHECK-NEXT:    [[ADD_5_1:%.*]] = add nsw i32 [[V_5_1]], 1
; CHECK-NEXT:    [[DGEP_5_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 44
; CHECK-NEXT:    store i32 [[ADD_5_1]], ptr [[DGEP_5_1]], align 4
; CHECK-NEXT:    [[SRC_25:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 48
; CHECK-NEXT:    [[V_26:%.*]] = load i32, ptr [[SRC_25]], align 4
; CHECK-NEXT:    [[ADD_27:%.*]] = add nsw i32 [[V_26]], 1
; CHECK-NEXT:    [[DGEP_28:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 48
; CHECK-NEXT:    store i32 [[ADD_27]], ptr [[DGEP_28]], align 4
; CHECK-NEXT:    [[SRC_1_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 52
; CHECK-NEXT:    [[V_1_2:%.*]] = load i32, ptr [[SRC_1_2]], align 4
; CHECK-NEXT:    [[ADD_1_2:%.*]] = add nsw i32 [[V_1_2]], 1
; CHECK-NEXT:    [[DGEP_1_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 52
; CHECK-NEXT:    store i32 [[ADD_1_2]], ptr [[DGEP_1_2]], align 4
; CHECK-NEXT:    [[SRC_2_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 56
; CHECK-NEXT:    [[V_2_2:%.*]] = load i32, ptr [[SRC_2_2]], align 4
; CHECK-NEXT:    [[ADD_2_2:%.*]] = add nsw i32 [[V_2_2]], 1
; CHECK-NEXT:    [[DGEP_2_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 56
; CHECK-NEXT:    store i32 [[ADD_2_2]], ptr [[DGEP_2_2]], align 4
; CHECK-NEXT:    [[SRC_3_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 60
; CHECK-NEXT:    [[V_3_2:%.*]] = load i32, ptr [[SRC_3_2]], align 4
; CHECK-NEXT:    [[ADD_3_2:%.*]] = add nsw i32 [[V_3_2]], 1
; CHECK-NEXT:    [[DGEP_3_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 60
; CHECK-NEXT:    store i32 [[ADD_3_2]], ptr [[DGEP_3_2]], align 4
; CHECK-NEXT:    [[SRC_4_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 64
; CHECK-NEXT:    [[V_4_2:%.*]] = load i32, ptr [[SRC_4_2]], align 4
; CHECK-NEXT:    [[ADD_4_2:%.*]] = add nsw i32 [[V_4_2]], 1
; CHECK-NEXT:    [[DGEP_4_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 64
; CHECK-NEXT:    store i32 [[ADD_4_2]], ptr [[DGEP_4_2]], align 4
; CHECK-NEXT:    [[SRC_5_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 68
; CHECK-NEXT:    [[V_5_2:%.*]] = load i32, ptr [[SRC_5_2]], align 4
; CHECK-NEXT:    [[ADD_5_2:%.*]] = add nsw i32 [[V_5_2]], 1
; CHECK-NEXT:    [[DGEP_5_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 68
; CHECK-NEXT:    store i32 [[ADD_5_2]], ptr [[DGEP_5_2]], align 4
; CHECK-NEXT:    [[SRC_39:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 72
; CHECK-NEXT:    [[V_310:%.*]] = load i32, ptr [[SRC_39]], align 4
; CHECK-NEXT:    [[ADD_311:%.*]] = add nsw i32 [[V_310]], 1
; CHECK-NEXT:    [[DGEP_312:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 72
; CHECK-NEXT:    store i32 [[ADD_311]], ptr [[DGEP_312]], align 4
; CHECK-NEXT:    [[SRC_1_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 76
; CHECK-NEXT:    [[V_1_3:%.*]] = load i32, ptr [[SRC_1_3]], align 4
; CHECK-NEXT:    [[ADD_1_3:%.*]] = add nsw i32 [[V_1_3]], 1
; CHECK-NEXT:    [[DGEP_1_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 76
; CHECK-NEXT:    store i32 [[ADD_1_3]], ptr [[DGEP_1_3]], align 4
; CHECK-NEXT:    [[SRC_2_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 80
; CHECK-NEXT:    [[V_2_3:%.*]] = load i32, ptr [[SRC_2_3]], align 4
; CHECK-NEXT:    [[ADD_2_3:%.*]] = add nsw i32 [[V_2_3]], 1
; CHECK-NEXT:    [[DGEP_2_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 80
; CHECK-NEXT:    store i32 [[ADD_2_3]], ptr [[DGEP_2_3]], align 4
; CHECK-NEXT:    [[SRC_3_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 84
; CHECK-NEXT:    [[V_3_3:%.*]] = load i32, ptr [[SRC_3_3]], align 4
; CHECK-NEXT:    [[ADD_3_3:%.*]] = add nsw i32 [[V_3_3]], 1
; CHECK-NEXT:    [[DGEP_3_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 84
; CHECK-NEXT:    store i32 [[ADD_3_3]], ptr [[DGEP_3_3]], align 4
; CHECK-NEXT:    [[SRC_4_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 88
; CHECK-NEXT:    [[V_4_3:%.*]] = load i32, ptr [[SRC_4_3]], align 4
; CHECK-NEXT:    [[ADD_4_3:%.*]] = add nsw i32 [[V_4_3]], 1
; CHECK-NEXT:    [[DGEP_4_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 88
; CHECK-NEXT:    store i32 [[ADD_4_3]], ptr [[DGEP_4_3]], align 4
; CHECK-NEXT:    [[SRC_5_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 92
; CHECK-NEXT:    [[V_5_3:%.*]] = load i32, ptr [[SRC_5_3]], align 4
; CHECK-NEXT:    [[ADD_5_3:%.*]] = add nsw i32 [[V_5_3]], 1
; CHECK-NEXT:    [[DGEP_5_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 92
; CHECK-NEXT:    store i32 [[ADD_5_3]], ptr [[DGEP_5_3]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %outer

outer:
  %i = phi i64 [ 0, %entry ], [ %i.next, %outer.latch ]
  br label %inner

inner:
  %j = phi i64 [ 0, %outer ], [ %j.next, %inner ]
  %off = mul i64 %i, 6
  %idx = add i64 %off, %j
  %src = getelementptr inbounds i32, ptr %a, i64 %idx
  %v = load i32, ptr %src, align 4
  %add = add nsw i32 %v, 1
  %dgep = getelementptr inbounds i32, ptr %dst, i64 %idx
  store i32 %add, ptr %dgep, align 4
  %j.next = add nuw nsw i64 %j, 1
  %j.cmp = icmp ult i64 %j.next, 6
  br i1 %j.cmp, label %inner, label %outer.latch

outer.latch:
  %i.next = add nuw nsw i64 %i, 1
  %i.cmp = icmp ult i64 %i.next, 4
  br i1 %i.cmp, label %outer, label %exit

exit:
  ret void
}

; Stale-marker case (aom_sad-style): a function whose innermost loop is
; deferred when the function is processed in isolation, then inlined into
; a context where an enclosing loop has a small constant trip count.
; Without re-evaluating the marker, the outer would be skipped from
; full-unroll forever; with re-evaluation, the marker is treated as stale
; and the outer fully unrolls.
define internal i32 @inner_callee(ptr %a, ptr %b, i32 %width) {
entry:
  br label %loop

loop:
  %j = phi i32 [ 0, %entry ], [ %j.next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %j64 = sext i32 %j to i64
  %ap = getelementptr inbounds i8, ptr %a, i64 %j64
  %va = load i8, ptr %ap, align 1
  %va.z = zext i8 %va to i32
  %bp = getelementptr inbounds i8, ptr %b, i64 %j64
  %vb = load i8, ptr %bp, align 1
  %vb.z = zext i8 %vb to i32
  %diff = sub nsw i32 %va.z, %vb.z
  %abs = tail call i32 @llvm.abs.i32(i32 %diff, i1 true)
  %acc.next = add i32 %acc, %abs
  %j.next = add nuw nsw i32 %j, 1
  %cmp = icmp slt i32 %j.next, %width
  br i1 %cmp, label %loop, label %exit

exit:
  ret i32 %acc.next
}

define void @stale_marker_caller(ptr noalias %dst, ptr noalias %a, ptr noalias %b) {
; CHECK-LABEL: @stale_marker_caller(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <16 x i8>, ptr [[A:%.*]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = zext <16 x i8> [[TMP0]] to <16 x i16>
; CHECK-NEXT:    [[TMP2:%.*]] = load <16 x i8>, ptr [[B:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = zext <16 x i8> [[TMP2]] to <16 x i16>
; CHECK-NEXT:    [[TMP4:%.*]] = sub nsw <16 x i16> [[TMP1]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP4]], i1 false)
; CHECK-NEXT:    [[TMP6:%.*]] = zext <16 x i16> [[TMP5]] to <16 x i32>
; CHECK-NEXT:    [[TMP7:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP6]])
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[DST:%.*]], align 4
; CHECK-NEXT:    [[AI_1:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    [[BI_1:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i64 16
; CHECK-NEXT:    [[TMP8:%.*]] = load <16 x i8>, ptr [[AI_1]], align 1
; CHECK-NEXT:    [[TMP9:%.*]] = zext <16 x i8> [[TMP8]] to <16 x i16>
; CHECK-NEXT:    [[TMP10:%.*]] = load <16 x i8>, ptr [[BI_1]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = zext <16 x i8> [[TMP10]] to <16 x i16>
; CHECK-NEXT:    [[TMP12:%.*]] = sub nsw <16 x i16> [[TMP9]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP12]], i1 false)
; CHECK-NEXT:    [[TMP14:%.*]] = zext <16 x i16> [[TMP13]] to <16 x i32>
; CHECK-NEXT:    [[TMP15:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP14]])
; CHECK-NEXT:    [[DGEP_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 4
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[DGEP_1]], align 4
; CHECK-NEXT:    [[AI_2:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 32
; CHECK-NEXT:    [[BI_2:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i64 32
; CHECK-NEXT:    [[TMP16:%.*]] = load <16 x i8>, ptr [[AI_2]], align 1
; CHECK-NEXT:    [[TMP17:%.*]] = zext <16 x i8> [[TMP16]] to <16 x i16>
; CHECK-NEXT:    [[TMP18:%.*]] = load <16 x i8>, ptr [[BI_2]], align 1
; CHECK-NEXT:    [[TMP19:%.*]] = zext <16 x i8> [[TMP18]] to <16 x i16>
; CHECK-NEXT:    [[TMP20:%.*]] = sub nsw <16 x i16> [[TMP17]], [[TMP19]]
; CHECK-NEXT:    [[TMP21:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP20]], i1 false)
; CHECK-NEXT:    [[TMP22:%.*]] = zext <16 x i16> [[TMP21]] to <16 x i32>
; CHECK-NEXT:    [[TMP23:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP22]])
; CHECK-NEXT:    [[DGEP_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 8
; CHECK-NEXT:    store i32 [[TMP23]], ptr [[DGEP_2]], align 4
; CHECK-NEXT:    [[AI_3:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 48
; CHECK-NEXT:    [[BI_3:%.*]] = getelementptr inbounds nuw i8, ptr [[B]], i64 48
; CHECK-NEXT:    [[TMP24:%.*]] = load <16 x i8>, ptr [[AI_3]], align 1
; CHECK-NEXT:    [[TMP25:%.*]] = zext <16 x i8> [[TMP24]] to <16 x i16>
; CHECK-NEXT:    [[TMP26:%.*]] = load <16 x i8>, ptr [[BI_3]], align 1
; CHECK-NEXT:    [[TMP27:%.*]] = zext <16 x i8> [[TMP26]] to <16 x i16>
; CHECK-NEXT:    [[TMP28:%.*]] = sub nsw <16 x i16> [[TMP25]], [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = tail call <16 x i16> @llvm.abs.v16i16(<16 x i16> [[TMP28]], i1 false)
; CHECK-NEXT:    [[TMP30:%.*]] = zext <16 x i16> [[TMP29]] to <16 x i32>
; CHECK-NEXT:    [[TMP31:%.*]] = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> [[TMP30]])
; CHECK-NEXT:    [[DGEP_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 12
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[DGEP_3]], align 4
; CHECK-NEXT:    ret void
;
; The 4-iter outer must fully unroll, even though @inner_callee was
; deferred when processed standalone (its parent at that point was
; runtime, but here it ends up nested inside a TC=4 outer).
entry:
  br label %outer

outer:
  %i = phi i64 [ 0, %entry ], [ %i.next, %outer.latch ]
  %ai = getelementptr inbounds [16 x i8], ptr %a, i64 %i, i64 0
  %bi = getelementptr inbounds [16 x i8], ptr %b, i64 %i, i64 0
  %sad = call i32 @inner_callee(ptr %ai, ptr %bi, i32 16)
  %dgep = getelementptr inbounds i32, ptr %dst, i64 %i
  store i32 %sad, ptr %dgep, align 4
  br label %outer.latch

outer.latch:
  %i.next = add nuw nsw i64 %i, 1
  %i.cmp = icmp ult i64 %i.next, 4
  br i1 %i.cmp, label %outer, label %exit

exit:
  ret void
}

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.vectorize.enable", i1 false}
