; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -passes="default<O3>" -S %s | FileCheck %s

; PhaseOrdering regression guard for extra-unroll-after-vectorize-passes:
; a 13x13 matmul kernel (trip count 13 is odd, prime, and small enough
; that the baseline's early LoopFullUnroll unrolls only the innermost
; k-reduction). The outer i-loop is deliberately kept as a real loop
; by the baseline because the combined i*j*k body would exceed the
; early full-unroll threshold.
;
; Baseline pipeline (opt.a):
;   early LoopFullUnrollPass fully unrolls only the innermost k-loop
;   (1 NumCompletelyUnrolled event); the i- and j-loops are left as
;   loops; SLP coalesces the inner body. Final IR has 2 loop
;   back-edges, 1 store, 93 instructions.
;
; With extra-unroll-after-vectorize-passes (opt.b):
;   the inner loops are deferred in the early pipeline; LV processes
;   the inner and the post-LV LoopFullUnrollPass then becomes able to
;   fully unroll the enclosing j- and i-loops too because the
;   LV-compacted body is smaller. Result: 14 NumCompletelyUnrolled
;   events (8-13x more than baseline), every output element materialised
;   as straight-line code, no i/j back-edges. Final IR has 1 back-edge
;   and 758 instructions (+716% over baseline). The regression is
;   visible all the way down to assembly: ~560 aarch64 instructions
;   with 182 fmul/fadd vs baseline's 62 / 26.
;
; This matches the dealii matrix_free and nektarpp MatrixFreeOps
; corpus regressions where files doubled or tripled in total
; instruction count exactly because of this chain of:
;   defer early unroll -> LV vectorize -> post-LV unroll everything.

target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-macosx14"


define void @matmul13(ptr noalias %A, ptr noalias %B, ptr noalias %C) {
; CHECK-LABEL: define void @matmul13(
; CHECK-SAME: ptr noalias readonly captures(none) [[A:%.*]], ptr noalias readonly captures(none) [[B:%.*]], ptr noalias writeonly captures(none) [[C:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[I_LOOP:.*]]
; CHECK:       [[I_LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[I_LATCH:.*]] ]
; CHECK-NEXT:    [[AOFF:%.*]] = mul nuw nsw i64 [[I]], 13
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr [8 x i8], ptr [[C]], i64 [[AOFF]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [8 x i8], ptr [[A]], i64 [[AOFF]]
; CHECK-NEXT:    [[AV_PRE:%.*]] = load double, ptr [[TMP1]], align 8
; CHECK-NEXT:    [[APTR_1_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 8
; CHECK-NEXT:    [[AV_1_PRE:%.*]] = load double, ptr [[APTR_1_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_2_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 16
; CHECK-NEXT:    [[AV_2_PRE:%.*]] = load double, ptr [[APTR_2_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_3_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 24
; CHECK-NEXT:    [[AV_3_PRE:%.*]] = load double, ptr [[APTR_3_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_4_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 32
; CHECK-NEXT:    [[AV_4_PRE:%.*]] = load double, ptr [[APTR_4_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_5_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 40
; CHECK-NEXT:    [[AV_5_PRE:%.*]] = load double, ptr [[APTR_5_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_6_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 48
; CHECK-NEXT:    [[AV_6_PRE:%.*]] = load double, ptr [[APTR_6_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_7_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 56
; CHECK-NEXT:    [[AV_7_PRE:%.*]] = load double, ptr [[APTR_7_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_8_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 64
; CHECK-NEXT:    [[AV_8_PRE:%.*]] = load double, ptr [[APTR_8_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_9_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 72
; CHECK-NEXT:    [[AV_9_PRE:%.*]] = load double, ptr [[APTR_9_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_10_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 80
; CHECK-NEXT:    [[AV_10_PRE:%.*]] = load double, ptr [[APTR_10_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_11_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 88
; CHECK-NEXT:    [[AV_11_PRE:%.*]] = load double, ptr [[APTR_11_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    [[APTR_12_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr [[TMP1]], i64 96
; CHECK-NEXT:    [[AV_12_PRE:%.*]] = load double, ptr [[APTR_12_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    br label %[[J_LOOP:.*]]
; CHECK:       [[J_LOOP]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[I_LOOP]] ], [ [[J_NEXT:%.*]], %[[J_LOOP]] ]
; CHECK-NEXT:    [[INVARIANT_GEP:%.*]] = getelementptr [8 x i8], ptr [[B]], i64 [[J]]
; CHECK-NEXT:    [[BV:%.*]] = load double, ptr [[INVARIANT_GEP]], align 8
; CHECK-NEXT:    [[M:%.*]] = fmul double [[AV_PRE]], [[BV]]
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = fadd double [[M]], 0.000000e+00
; CHECK-NEXT:    [[GEP_1:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 104
; CHECK-NEXT:    [[BV_1:%.*]] = load double, ptr [[GEP_1]], align 8
; CHECK-NEXT:    [[M_1:%.*]] = fmul double [[AV_1_PRE]], [[BV_1]]
; CHECK-NEXT:    [[ACC_NEXT_1:%.*]] = fadd double [[ACC_NEXT]], [[M_1]]
; CHECK-NEXT:    [[GEP_2:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 208
; CHECK-NEXT:    [[BV_2:%.*]] = load double, ptr [[GEP_2]], align 8
; CHECK-NEXT:    [[M_2:%.*]] = fmul double [[AV_2_PRE]], [[BV_2]]
; CHECK-NEXT:    [[ACC_NEXT_2:%.*]] = fadd double [[ACC_NEXT_1]], [[M_2]]
; CHECK-NEXT:    [[GEP_3:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 312
; CHECK-NEXT:    [[BV_3:%.*]] = load double, ptr [[GEP_3]], align 8
; CHECK-NEXT:    [[M_3:%.*]] = fmul double [[AV_3_PRE]], [[BV_3]]
; CHECK-NEXT:    [[ACC_NEXT_3:%.*]] = fadd double [[ACC_NEXT_2]], [[M_3]]
; CHECK-NEXT:    [[GEP_4:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 416
; CHECK-NEXT:    [[BV_4:%.*]] = load double, ptr [[GEP_4]], align 8
; CHECK-NEXT:    [[M_4:%.*]] = fmul double [[AV_4_PRE]], [[BV_4]]
; CHECK-NEXT:    [[ACC_NEXT_4:%.*]] = fadd double [[ACC_NEXT_3]], [[M_4]]
; CHECK-NEXT:    [[GEP_5:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 520
; CHECK-NEXT:    [[BV_5:%.*]] = load double, ptr [[GEP_5]], align 8
; CHECK-NEXT:    [[M_5:%.*]] = fmul double [[AV_5_PRE]], [[BV_5]]
; CHECK-NEXT:    [[ACC_NEXT_5:%.*]] = fadd double [[ACC_NEXT_4]], [[M_5]]
; CHECK-NEXT:    [[GEP_6:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 624
; CHECK-NEXT:    [[BV_6:%.*]] = load double, ptr [[GEP_6]], align 8
; CHECK-NEXT:    [[M_6:%.*]] = fmul double [[AV_6_PRE]], [[BV_6]]
; CHECK-NEXT:    [[ACC_NEXT_6:%.*]] = fadd double [[ACC_NEXT_5]], [[M_6]]
; CHECK-NEXT:    [[GEP_7:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 728
; CHECK-NEXT:    [[BV_7:%.*]] = load double, ptr [[GEP_7]], align 8
; CHECK-NEXT:    [[M_7:%.*]] = fmul double [[AV_7_PRE]], [[BV_7]]
; CHECK-NEXT:    [[ACC_NEXT_7:%.*]] = fadd double [[ACC_NEXT_6]], [[M_7]]
; CHECK-NEXT:    [[GEP_8:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 832
; CHECK-NEXT:    [[BV_8:%.*]] = load double, ptr [[GEP_8]], align 8
; CHECK-NEXT:    [[M_8:%.*]] = fmul double [[AV_8_PRE]], [[BV_8]]
; CHECK-NEXT:    [[ACC_NEXT_8:%.*]] = fadd double [[ACC_NEXT_7]], [[M_8]]
; CHECK-NEXT:    [[GEP_9:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 936
; CHECK-NEXT:    [[BV_9:%.*]] = load double, ptr [[GEP_9]], align 8
; CHECK-NEXT:    [[M_9:%.*]] = fmul double [[AV_9_PRE]], [[BV_9]]
; CHECK-NEXT:    [[ACC_NEXT_9:%.*]] = fadd double [[ACC_NEXT_8]], [[M_9]]
; CHECK-NEXT:    [[GEP_10:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 1040
; CHECK-NEXT:    [[BV_10:%.*]] = load double, ptr [[GEP_10]], align 8
; CHECK-NEXT:    [[M_10:%.*]] = fmul double [[AV_10_PRE]], [[BV_10]]
; CHECK-NEXT:    [[ACC_NEXT_10:%.*]] = fadd double [[ACC_NEXT_9]], [[M_10]]
; CHECK-NEXT:    [[GEP_11:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 1144
; CHECK-NEXT:    [[BV_11:%.*]] = load double, ptr [[GEP_11]], align 8
; CHECK-NEXT:    [[M_11:%.*]] = fmul double [[AV_11_PRE]], [[BV_11]]
; CHECK-NEXT:    [[ACC_NEXT_11:%.*]] = fadd double [[ACC_NEXT_10]], [[M_11]]
; CHECK-NEXT:    [[GEP_12:%.*]] = getelementptr i8, ptr [[INVARIANT_GEP]], i64 1248
; CHECK-NEXT:    [[BV_12:%.*]] = load double, ptr [[GEP_12]], align 8
; CHECK-NEXT:    [[M_12:%.*]] = fmul double [[AV_12_PRE]], [[BV_12]]
; CHECK-NEXT:    [[ACC_NEXT_12:%.*]] = fadd double [[ACC_NEXT_11]], [[M_12]]
; CHECK-NEXT:    [[CPTR:%.*]] = getelementptr [8 x i8], ptr [[TMP0]], i64 [[J]]
; CHECK-NEXT:    store double [[ACC_NEXT_12]], ptr [[CPTR]], align 8
; CHECK-NEXT:    [[J_NEXT]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[J_DONE:%.*]] = icmp eq i64 [[J_NEXT]], 13
; CHECK-NEXT:    br i1 [[J_DONE]], label %[[I_LATCH]], label %[[J_LOOP]]
; CHECK:       [[I_LATCH]]:
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[I_DONE:%.*]] = icmp eq i64 [[I_NEXT]], 13
; CHECK-NEXT:    br i1 [[I_DONE]], label %[[EXIT:.*]], label %[[I_LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %i.loop

i.loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %i.latch ]
  br label %j.loop

j.loop:
  %j = phi i64 [ 0, %i.loop ], [ %j.next, %j.latch ]
  br label %k.loop

k.loop:
  %k = phi i64 [ 0, %j.loop ], [ %k.next, %k.loop ]
  %acc = phi double [ 0.0, %j.loop ], [ %acc.next, %k.loop ]
  %aoff = mul i64 %i, 13
  %aidx = add i64 %aoff, %k
  %aptr = getelementptr inbounds double, ptr %A, i64 %aidx
  %av = load double, ptr %aptr
  %boff = mul i64 %k, 13
  %bidx = add i64 %boff, %j
  %bptr = getelementptr inbounds double, ptr %B, i64 %bidx
  %bv = load double, ptr %bptr
  %m = fmul double %av, %bv
  %acc.next = fadd double %acc, %m
  %k.next = add nuw nsw i64 %k, 1
  %k.done = icmp eq i64 %k.next, 13
  br i1 %k.done, label %j.latch, label %k.loop

j.latch:
  %coff = mul i64 %i, 13
  %cidx = add i64 %coff, %j
  %cptr = getelementptr inbounds double, ptr %C, i64 %cidx
  store double %acc.next, ptr %cptr
  %j.next = add nuw nsw i64 %j, 1
  %j.done = icmp eq i64 %j.next, 13
  br i1 %j.done, label %i.latch, label %j.loop

i.latch:
  %i.next = add nuw nsw i64 %i, 1
  %i.done = icmp eq i64 %i.next, 13
  br i1 %i.done, label %exit, label %i.loop

exit:
  ret void
}
