; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes='default<O3>' -S < %s | FileCheck %s

; End-to-end test for the non-SCEV LoopUtils helper that lets
; PostOrderFunctionAttrsPass infer `initializes`/`writeonly` on a sret
; arg whose only writes happen inside a counted loop with TC=64. The
; inner loop is too large to fully unroll under the default cost
; threshold, so the function-attr pass has to recover the byte range
; from the IV-strided GEP. The callee is marked noinline to make sure
; the caller observes the inferred attribute on the call site.

target triple = "arm64-apple-macosx"

; The callee writes the entire 256-byte sret buffer in a TC=64 loop and
; reads nothing from it -- so its sret arg should end up with
; `writeonly` and `initializes((0, 256))`.
define void @fill_dst(ptr noalias sret([256 x i8]) align 16 %dst, float %v) noinline {
; CHECK-LABEL: @fill_dst(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x float> poison, float [[V:%.*]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x float> [[BROADCAST_SPLATINSERT]], <4 x float> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i8, ptr [[DST:%.*]], i64 16
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[DST]], align 16
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 32
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 48
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP1]], align 16
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 64
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 80
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP3]], align 16
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP4]], align 16
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 96
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 112
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP5]], align 16
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP6]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 128
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 144
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP7]], align 16
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP8]], align 16
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 160
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 176
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP9]], align 16
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP10]], align 16
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 192
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 208
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP11]], align 16
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP12]], align 16
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 224
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 240
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP13]], align 16
; CHECK-NEXT:    store <4 x float> [[BROADCAST_SPLAT]], ptr [[TMP14]], align 16
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep = getelementptr inbounds [4 x i8], ptr %dst, i64 %iv
  store float %v, ptr %gep, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 64
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; The redundant zero-store at %dst is killed by the call -- but only if
; the call site sees `initializes((0, 256))` on the sret arg. Verify the
; memset is gone in the optimized output.
define float @caller_dse(ptr noalias dereferenceable(256) %dst) {
; CHECK-LABEL: @caller_dse(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @fill_dst(ptr nonnull sret([256 x i8]) align 16 [[DST:%.*]], float 1.000000e+00)
; CHECK-NEXT:    [[OFF:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 68
; CHECK-NEXT:    [[V:%.*]] = load float, ptr [[OFF]], align 4
; CHECK-NEXT:    ret float [[V]]
;
entry:
  ; A redundant memset that DSE should kill once @fill_dst's call site
  ; carries `initializes((0, 256))` on the sret arg.
  call void @llvm.memset.p0.i64(ptr %dst, i8 0, i64 256, i1 false)
  call void @fill_dst(ptr sret([256 x i8]) align 16 %dst, float 1.0)
  %off = getelementptr inbounds [4 x i8], ptr %dst, i64 17
  %v = load float, ptr %off, align 4
  ret float %v
}

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)
