; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -passes="default<O3>" -S %s | FileCheck %s

; PhaseOrdering regression guard for the bjarne screen_init pattern:
; a doubly-nested init loop should collapse to a single @llvm.memset.
;
; This broke in an earlier defer-unroll + extra-unroll-after-vectorize
; experiment: the post-LV full unroll eagerly unrolled the stride-24
; inner loop before LoopIdiomRecognizePass on the outer could fold the
; nested pattern into a memset, leaving ~840 explicit stores in the
; final IR.
;
; Source equivalent (MultiSource/Benchmarks/Prolangs-C++/shapes/bjarne.cpp):
;   char screen[40][24];
;   void init() {
;     for (int y = 0; y < 24; y++)       // outer = y
;       for (int x = 0; x < 40; x++)     // inner = x  (stride-24 stores)
;         screen[x][y] = ' ';
;   }

target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-macosx14"

@screen = dso_local local_unnamed_addr global [40 x [24 x i8]] zeroinitializer, align 16


define void @init() local_unnamed_addr {
; CHECK-LABEL: define void @init(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i8 32, ptr @screen, align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 24), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 48), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 72), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 96), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 120), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 144), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 168), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 192), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 216), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 240), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 264), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 288), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 312), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 336), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 360), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 384), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 408), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 432), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 456), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 480), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 504), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 528), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 552), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 576), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 600), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 624), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 648), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 672), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 696), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 720), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 744), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 768), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 792), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 816), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 840), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 864), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 888), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 912), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 936), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 1), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 25), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 49), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 73), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 97), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 121), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 145), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 169), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 193), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 217), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 241), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 265), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 289), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 313), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 337), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 361), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 385), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 409), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 433), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 457), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 481), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 505), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 529), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 553), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 577), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 601), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 625), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 649), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 673), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 697), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 721), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 745), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 769), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 793), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 817), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 841), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 865), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 889), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 913), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 937), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 2), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 26), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 50), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 74), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 98), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 122), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 146), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 170), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 194), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 218), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 242), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 266), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 290), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 314), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 338), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 362), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 386), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 410), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 434), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 458), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 482), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 506), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 530), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 554), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 578), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 602), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 626), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 650), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 674), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 698), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 722), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 746), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 770), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 794), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 818), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 842), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 866), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 890), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 914), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 938), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 3), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 27), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 51), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 75), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 99), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 123), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 147), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 171), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 195), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 219), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 243), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 267), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 291), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 315), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 339), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 363), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 387), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 411), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 435), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 459), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 483), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 507), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 531), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 555), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 579), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 603), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 627), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 651), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 675), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 699), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 723), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 747), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 771), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 795), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 819), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 843), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 867), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 891), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 915), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 939), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 4), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 28), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 52), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 76), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 100), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 124), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 148), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 172), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 196), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 220), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 244), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 268), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 292), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 316), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 340), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 364), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 388), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 412), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 436), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 460), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 484), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 508), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 532), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 556), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 580), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 604), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 628), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 652), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 676), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 700), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 724), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 748), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 772), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 796), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 820), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 844), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 868), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 892), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 916), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 940), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 5), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 29), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 53), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 77), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 101), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 125), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 149), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 173), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 197), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 221), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 245), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 269), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 293), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 317), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 341), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 365), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 389), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 413), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 437), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 461), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 485), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 509), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 533), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 557), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 581), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 605), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 629), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 653), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 677), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 701), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 725), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 749), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 773), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 797), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 821), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 845), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 869), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 893), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 917), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 941), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 6), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 30), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 54), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 78), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 102), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 126), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 150), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 174), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 198), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 222), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 246), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 270), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 294), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 318), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 342), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 366), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 390), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 414), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 438), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 462), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 486), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 510), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 534), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 558), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 582), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 606), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 630), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 654), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 678), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 702), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 726), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 750), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 774), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 798), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 822), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 846), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 870), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 894), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 918), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 942), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 7), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 31), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 55), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 79), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 103), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 127), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 151), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 175), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 199), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 223), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 247), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 271), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 295), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 319), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 343), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 367), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 391), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 415), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 439), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 463), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 487), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 511), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 535), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 559), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 583), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 607), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 631), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 655), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 679), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 703), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 727), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 751), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 775), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 799), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 823), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 847), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 871), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 895), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 919), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 943), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 8), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 32), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 56), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 80), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 104), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 128), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 152), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 176), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 200), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 224), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 248), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 272), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 296), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 320), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 344), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 368), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 392), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 416), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 440), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 464), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 488), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 512), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 536), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 560), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 584), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 608), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 632), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 656), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 680), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 704), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 728), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 752), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 776), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 800), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 824), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 848), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 872), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 896), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 920), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 944), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 9), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 33), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 57), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 81), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 105), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 129), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 153), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 177), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 201), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 225), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 249), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 273), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 297), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 321), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 345), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 369), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 393), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 417), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 441), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 465), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 489), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 513), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 537), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 561), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 585), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 609), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 633), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 657), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 681), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 705), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 729), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 753), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 777), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 801), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 825), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 849), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 873), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 897), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 921), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 945), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 10), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 34), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 58), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 82), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 106), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 130), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 154), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 178), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 202), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 226), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 250), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 274), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 298), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 322), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 346), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 370), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 394), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 418), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 442), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 466), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 490), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 514), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 538), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 562), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 586), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 610), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 634), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 658), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 682), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 706), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 730), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 754), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 778), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 802), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 826), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 850), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 874), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 898), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 922), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 946), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 11), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 35), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 59), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 83), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 107), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 131), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 155), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 179), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 203), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 227), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 251), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 275), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 299), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 323), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 347), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 371), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 395), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 419), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 443), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 467), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 491), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 515), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 539), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 563), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 587), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 611), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 635), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 659), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 683), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 707), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 731), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 755), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 779), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 803), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 827), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 851), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 875), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 899), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 923), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 947), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 12), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 36), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 60), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 84), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 108), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 132), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 156), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 180), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 204), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 228), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 252), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 276), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 300), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 324), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 348), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 372), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 396), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 420), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 444), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 468), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 492), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 516), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 540), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 564), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 588), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 612), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 636), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 660), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 684), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 708), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 732), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 756), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 780), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 804), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 828), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 852), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 876), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 900), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 924), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 948), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 13), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 37), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 61), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 85), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 109), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 133), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 157), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 181), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 205), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 229), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 253), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 277), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 301), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 325), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 349), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 373), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 397), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 421), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 445), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 469), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 493), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 517), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 541), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 565), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 589), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 613), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 637), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 661), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 685), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 709), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 733), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 757), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 781), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 805), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 829), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 853), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 877), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 901), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 925), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 949), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 14), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 38), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 62), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 86), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 110), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 134), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 158), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 182), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 206), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 230), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 254), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 278), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 302), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 326), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 350), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 374), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 398), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 422), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 446), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 470), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 494), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 518), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 542), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 566), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 590), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 614), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 638), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 662), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 686), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 710), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 734), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 758), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 782), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 806), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 830), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 854), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 878), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 902), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 926), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 950), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 15), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 39), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 63), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 87), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 111), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 135), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 159), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 183), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 207), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 231), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 255), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 279), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 303), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 327), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 351), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 375), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 399), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 423), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 447), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 471), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 495), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 519), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 543), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 567), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 591), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 615), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 639), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 663), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 687), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 711), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 735), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 759), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 783), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 807), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 831), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 855), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 879), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 903), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 927), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 951), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 16), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 40), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 64), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 88), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 112), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 136), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 160), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 184), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 208), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 232), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 256), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 280), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 304), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 328), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 352), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 376), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 400), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 424), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 448), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 472), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 496), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 520), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 544), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 568), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 592), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 616), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 640), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 664), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 688), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 712), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 736), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 760), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 784), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 808), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 832), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 856), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 880), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 904), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 928), align 16
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 952), align 8
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 17), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 41), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 65), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 89), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 113), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 137), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 161), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 185), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 209), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 233), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 257), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 281), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 305), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 329), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 353), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 377), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 401), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 425), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 449), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 473), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 497), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 521), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 545), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 569), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 593), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 617), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 641), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 665), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 689), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 713), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 737), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 761), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 785), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 809), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 833), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 857), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 881), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 905), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 929), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 953), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 18), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 42), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 66), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 90), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 114), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 138), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 162), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 186), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 210), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 234), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 258), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 282), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 306), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 330), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 354), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 378), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 402), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 426), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 450), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 474), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 498), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 522), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 546), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 570), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 594), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 618), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 642), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 666), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 690), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 714), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 738), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 762), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 786), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 810), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 834), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 858), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 882), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 906), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 930), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 954), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 19), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 43), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 67), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 91), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 115), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 139), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 163), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 187), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 211), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 235), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 259), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 283), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 307), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 331), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 355), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 379), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 403), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 427), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 451), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 475), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 499), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 523), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 547), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 571), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 595), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 619), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 643), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 667), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 691), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 715), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 739), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 763), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 787), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 811), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 835), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 859), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 883), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 907), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 931), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 955), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 20), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 44), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 68), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 92), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 116), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 140), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 164), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 188), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 212), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 236), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 260), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 284), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 308), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 332), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 356), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 380), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 404), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 428), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 452), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 476), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 500), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 524), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 548), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 572), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 596), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 620), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 644), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 668), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 692), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 716), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 740), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 764), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 788), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 812), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 836), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 860), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 884), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 908), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 932), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 956), align 4
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 21), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 45), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 69), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 93), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 117), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 141), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 165), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 189), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 213), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 237), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 261), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 285), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 309), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 333), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 357), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 381), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 405), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 429), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 453), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 477), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 501), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 525), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 549), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 573), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 597), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 621), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 645), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 669), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 693), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 717), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 741), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 765), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 789), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 813), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 837), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 861), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 885), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 909), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 933), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 957), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 22), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 46), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 70), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 94), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 118), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 142), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 166), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 190), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 214), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 238), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 262), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 286), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 310), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 334), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 358), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 382), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 406), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 430), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 454), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 478), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 502), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 526), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 550), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 574), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 598), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 622), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 646), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 670), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 694), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 718), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 742), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 766), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 790), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 814), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 838), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 862), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 886), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 910), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 934), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 958), align 2
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 23), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 47), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 71), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 95), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 119), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 143), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 167), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 191), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 215), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 239), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 263), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 287), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 311), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 335), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 359), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 383), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 407), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 431), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 455), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 479), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 503), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 527), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 551), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 575), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 599), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 623), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 647), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 671), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 695), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 719), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 743), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 767), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 791), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 815), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 839), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 863), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 887), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 911), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 935), align 1
; CHECK-NEXT:    store i8 32, ptr getelementptr inbounds nuw (i8, ptr @screen, i64 959), align 1
; CHECK-NEXT:    ret void
;
entry:
  br label %y.header

y.header:
  %y = phi i64 [ 0, %entry ], [ %y.next, %y.latch ]
  br label %x.body

x.body:
  %x = phi i64 [ 0, %y.header ], [ %x.next, %x.body ]
  %gep = getelementptr inbounds [40 x [24 x i8]], ptr @screen, i64 0, i64 %x, i64 %y
  store i8 32, ptr %gep, align 1
  %x.next = add nuw nsw i64 %x, 1
  %x.done = icmp eq i64 %x.next, 40
  br i1 %x.done, label %y.latch, label %x.body

y.latch:
  %y.next = add nuw nsw i64 %y, 1
  %y.done = icmp eq i64 %y.next, 24
  br i1 %y.done, label %exit, label %y.header

exit:
  ret void
}
