; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -O3 < %s | FileCheck %s --check-prefixes=CHECK-O3
; RUN: opt -S -passes="default<O3>,default<O3>" < %s | FileCheck %s --check-prefixes=CHECK-LTO

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64"

define dso_local i32 @test(ptr noundef %p1, i32 noundef %s_p1, ptr noundef %p2, i32 noundef %s_p2) #0 {
; CHECK-O3-LABEL: define dso_local i32 @test(
; CHECK-O3-SAME: ptr noundef readonly captures(none) [[P1:%.*]], i32 noundef [[S_P1:%.*]], ptr noundef readonly captures(none) [[P2:%.*]], i32 noundef [[S_P2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-O3-NEXT:  [[ENTRY:.*:]]
; CHECK-O3-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[S_P1]] to i64
; CHECK-O3-NEXT:    [[IDX_EXT8:%.*]] = sext i32 [[S_P2]] to i64
; CHECK-O3-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr [[P1]], align 1, !tbaa [[CHAR_TBAA0:![0-9]+]]
; CHECK-O3-NEXT:    [[WIDE_LOAD16:%.*]] = load <16 x i8>, ptr [[P2]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD19:%.*]] = load <16 x i8>, ptr [[ADD_PTR]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD20:%.*]] = load <16 x i8>, ptr [[ADD_PTR9]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD25:%.*]] = load <16 x i8>, ptr [[ADD_PTR_1]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD26:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_1]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_1]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_1]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD31:%.*]] = load <16 x i8>, ptr [[ADD_PTR_2]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD32:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_2]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_3:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_2]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_3:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_2]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD37:%.*]] = load <16 x i8>, ptr [[ADD_PTR_3]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD38:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_3]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_4:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_3]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_4:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_3]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD43:%.*]] = load <16 x i8>, ptr [[ADD_PTR_4]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD44:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_4]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_5:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_4]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_5:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_4]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD49:%.*]] = load <16 x i8>, ptr [[ADD_PTR_5]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD50:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_5]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_6:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_5]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_6:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_5]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD55:%.*]] = load <16 x i8>, ptr [[ADD_PTR_6]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD56:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_6]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_7:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_6]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_7:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_6]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD61:%.*]] = load <16 x i8>, ptr [[ADD_PTR_7]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD62:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_7]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_8:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_7]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_8:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_7]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD67:%.*]] = load <16 x i8>, ptr [[ADD_PTR_8]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD68:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_8]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_9:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_8]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_9:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_8]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD73:%.*]] = load <16 x i8>, ptr [[ADD_PTR_9]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD74:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_9]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_10:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_9]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_10:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_9]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD79:%.*]] = load <16 x i8>, ptr [[ADD_PTR_10]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD80:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_10]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_11:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_10]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_11:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_10]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD85:%.*]] = load <16 x i8>, ptr [[ADD_PTR_11]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD86:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_11]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_12:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_11]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_12:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_11]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD91:%.*]] = load <16 x i8>, ptr [[ADD_PTR_12]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD92:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_12]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[ADD_PTR_13:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_12]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[ADD_PTR9_13:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_12]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD97:%.*]] = load <16 x i8>, ptr [[ADD_PTR_13]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[WIDE_LOAD98:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_13]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[TMP0:%.*]] = freeze <16 x i8> [[WIDE_LOAD]]
; CHECK-O3-NEXT:    [[TMP1:%.*]] = freeze <16 x i8> [[WIDE_LOAD16]]
; CHECK-O3-NEXT:    [[TMP2:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP0]], <16 x i8> [[TMP1]])
; CHECK-O3-NEXT:    [[TMP3:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP0]], <16 x i8> [[TMP1]])
; CHECK-O3-NEXT:    [[TMP4:%.*]] = sub <16 x i8> [[TMP2]], [[TMP3]]
; CHECK-O3-NEXT:    [[TMP5:%.*]] = zext <16 x i8> [[TMP4]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> zeroinitializer, <16 x i32> [[TMP5]])
; CHECK-O3-NEXT:    [[TMP6:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE]])
; CHECK-O3-NEXT:    [[TMP7:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP6]], i64 0
; CHECK-O3-NEXT:    [[TMP8:%.*]] = freeze <16 x i8> [[WIDE_LOAD19]]
; CHECK-O3-NEXT:    [[TMP9:%.*]] = freeze <16 x i8> [[WIDE_LOAD20]]
; CHECK-O3-NEXT:    [[TMP10:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP8]], <16 x i8> [[TMP9]])
; CHECK-O3-NEXT:    [[TMP11:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP8]], <16 x i8> [[TMP9]])
; CHECK-O3-NEXT:    [[TMP12:%.*]] = sub <16 x i8> [[TMP10]], [[TMP11]]
; CHECK-O3-NEXT:    [[TMP13:%.*]] = zext <16 x i8> [[TMP12]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE21:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP7]], <16 x i32> [[TMP13]])
; CHECK-O3-NEXT:    [[TMP14:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE21]])
; CHECK-O3-NEXT:    [[TMP15:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP14]], i64 0
; CHECK-O3-NEXT:    [[TMP16:%.*]] = freeze <16 x i8> [[WIDE_LOAD25]]
; CHECK-O3-NEXT:    [[TMP17:%.*]] = freeze <16 x i8> [[WIDE_LOAD26]]
; CHECK-O3-NEXT:    [[TMP18:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP16]], <16 x i8> [[TMP17]])
; CHECK-O3-NEXT:    [[TMP19:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP16]], <16 x i8> [[TMP17]])
; CHECK-O3-NEXT:    [[TMP20:%.*]] = sub <16 x i8> [[TMP18]], [[TMP19]]
; CHECK-O3-NEXT:    [[TMP21:%.*]] = zext <16 x i8> [[TMP20]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE27:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP15]], <16 x i32> [[TMP21]])
; CHECK-O3-NEXT:    [[TMP22:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE27]])
; CHECK-O3-NEXT:    [[TMP23:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP22]], i64 0
; CHECK-O3-NEXT:    [[TMP24:%.*]] = freeze <16 x i8> [[WIDE_LOAD31]]
; CHECK-O3-NEXT:    [[TMP25:%.*]] = freeze <16 x i8> [[WIDE_LOAD32]]
; CHECK-O3-NEXT:    [[TMP26:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP24]], <16 x i8> [[TMP25]])
; CHECK-O3-NEXT:    [[TMP27:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP24]], <16 x i8> [[TMP25]])
; CHECK-O3-NEXT:    [[TMP28:%.*]] = sub <16 x i8> [[TMP26]], [[TMP27]]
; CHECK-O3-NEXT:    [[TMP29:%.*]] = zext <16 x i8> [[TMP28]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE33:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP23]], <16 x i32> [[TMP29]])
; CHECK-O3-NEXT:    [[TMP30:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE33]])
; CHECK-O3-NEXT:    [[TMP31:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP30]], i64 0
; CHECK-O3-NEXT:    [[TMP32:%.*]] = freeze <16 x i8> [[WIDE_LOAD37]]
; CHECK-O3-NEXT:    [[TMP33:%.*]] = freeze <16 x i8> [[WIDE_LOAD38]]
; CHECK-O3-NEXT:    [[TMP34:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP32]], <16 x i8> [[TMP33]])
; CHECK-O3-NEXT:    [[TMP35:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP32]], <16 x i8> [[TMP33]])
; CHECK-O3-NEXT:    [[TMP36:%.*]] = sub <16 x i8> [[TMP34]], [[TMP35]]
; CHECK-O3-NEXT:    [[TMP37:%.*]] = zext <16 x i8> [[TMP36]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE39:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP31]], <16 x i32> [[TMP37]])
; CHECK-O3-NEXT:    [[TMP38:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE39]])
; CHECK-O3-NEXT:    [[TMP39:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP38]], i64 0
; CHECK-O3-NEXT:    [[TMP40:%.*]] = freeze <16 x i8> [[WIDE_LOAD43]]
; CHECK-O3-NEXT:    [[TMP41:%.*]] = freeze <16 x i8> [[WIDE_LOAD44]]
; CHECK-O3-NEXT:    [[TMP42:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP40]], <16 x i8> [[TMP41]])
; CHECK-O3-NEXT:    [[TMP43:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP40]], <16 x i8> [[TMP41]])
; CHECK-O3-NEXT:    [[TMP44:%.*]] = sub <16 x i8> [[TMP42]], [[TMP43]]
; CHECK-O3-NEXT:    [[TMP45:%.*]] = zext <16 x i8> [[TMP44]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE45:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP39]], <16 x i32> [[TMP45]])
; CHECK-O3-NEXT:    [[TMP46:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE45]])
; CHECK-O3-NEXT:    [[TMP47:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP46]], i64 0
; CHECK-O3-NEXT:    [[TMP48:%.*]] = freeze <16 x i8> [[WIDE_LOAD49]]
; CHECK-O3-NEXT:    [[TMP49:%.*]] = freeze <16 x i8> [[WIDE_LOAD50]]
; CHECK-O3-NEXT:    [[TMP50:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP48]], <16 x i8> [[TMP49]])
; CHECK-O3-NEXT:    [[TMP51:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP48]], <16 x i8> [[TMP49]])
; CHECK-O3-NEXT:    [[TMP52:%.*]] = sub <16 x i8> [[TMP50]], [[TMP51]]
; CHECK-O3-NEXT:    [[TMP53:%.*]] = zext <16 x i8> [[TMP52]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE51:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP47]], <16 x i32> [[TMP53]])
; CHECK-O3-NEXT:    [[TMP54:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE51]])
; CHECK-O3-NEXT:    [[TMP55:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP54]], i64 0
; CHECK-O3-NEXT:    [[TMP56:%.*]] = freeze <16 x i8> [[WIDE_LOAD55]]
; CHECK-O3-NEXT:    [[TMP57:%.*]] = freeze <16 x i8> [[WIDE_LOAD56]]
; CHECK-O3-NEXT:    [[TMP58:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP56]], <16 x i8> [[TMP57]])
; CHECK-O3-NEXT:    [[TMP59:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP56]], <16 x i8> [[TMP57]])
; CHECK-O3-NEXT:    [[TMP60:%.*]] = sub <16 x i8> [[TMP58]], [[TMP59]]
; CHECK-O3-NEXT:    [[TMP61:%.*]] = zext <16 x i8> [[TMP60]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE57:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP55]], <16 x i32> [[TMP61]])
; CHECK-O3-NEXT:    [[TMP62:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE57]])
; CHECK-O3-NEXT:    [[TMP63:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP62]], i64 0
; CHECK-O3-NEXT:    [[TMP64:%.*]] = freeze <16 x i8> [[WIDE_LOAD61]]
; CHECK-O3-NEXT:    [[TMP65:%.*]] = freeze <16 x i8> [[WIDE_LOAD62]]
; CHECK-O3-NEXT:    [[TMP66:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP64]], <16 x i8> [[TMP65]])
; CHECK-O3-NEXT:    [[TMP67:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP64]], <16 x i8> [[TMP65]])
; CHECK-O3-NEXT:    [[TMP68:%.*]] = sub <16 x i8> [[TMP66]], [[TMP67]]
; CHECK-O3-NEXT:    [[TMP69:%.*]] = zext <16 x i8> [[TMP68]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE63:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP63]], <16 x i32> [[TMP69]])
; CHECK-O3-NEXT:    [[TMP70:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE63]])
; CHECK-O3-NEXT:    [[TMP71:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP70]], i64 0
; CHECK-O3-NEXT:    [[TMP72:%.*]] = freeze <16 x i8> [[WIDE_LOAD67]]
; CHECK-O3-NEXT:    [[TMP73:%.*]] = freeze <16 x i8> [[WIDE_LOAD68]]
; CHECK-O3-NEXT:    [[TMP74:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP72]], <16 x i8> [[TMP73]])
; CHECK-O3-NEXT:    [[TMP75:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP72]], <16 x i8> [[TMP73]])
; CHECK-O3-NEXT:    [[TMP76:%.*]] = sub <16 x i8> [[TMP74]], [[TMP75]]
; CHECK-O3-NEXT:    [[TMP77:%.*]] = zext <16 x i8> [[TMP76]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE69:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP71]], <16 x i32> [[TMP77]])
; CHECK-O3-NEXT:    [[TMP78:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE69]])
; CHECK-O3-NEXT:    [[TMP79:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP78]], i64 0
; CHECK-O3-NEXT:    [[TMP80:%.*]] = freeze <16 x i8> [[WIDE_LOAD73]]
; CHECK-O3-NEXT:    [[TMP81:%.*]] = freeze <16 x i8> [[WIDE_LOAD74]]
; CHECK-O3-NEXT:    [[TMP82:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP80]], <16 x i8> [[TMP81]])
; CHECK-O3-NEXT:    [[TMP83:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP80]], <16 x i8> [[TMP81]])
; CHECK-O3-NEXT:    [[TMP84:%.*]] = sub <16 x i8> [[TMP82]], [[TMP83]]
; CHECK-O3-NEXT:    [[TMP85:%.*]] = zext <16 x i8> [[TMP84]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE75:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP79]], <16 x i32> [[TMP85]])
; CHECK-O3-NEXT:    [[TMP86:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE75]])
; CHECK-O3-NEXT:    [[TMP87:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP86]], i64 0
; CHECK-O3-NEXT:    [[TMP88:%.*]] = freeze <16 x i8> [[WIDE_LOAD79]]
; CHECK-O3-NEXT:    [[TMP89:%.*]] = freeze <16 x i8> [[WIDE_LOAD80]]
; CHECK-O3-NEXT:    [[TMP90:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP88]], <16 x i8> [[TMP89]])
; CHECK-O3-NEXT:    [[TMP91:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP88]], <16 x i8> [[TMP89]])
; CHECK-O3-NEXT:    [[TMP92:%.*]] = sub <16 x i8> [[TMP90]], [[TMP91]]
; CHECK-O3-NEXT:    [[TMP93:%.*]] = zext <16 x i8> [[TMP92]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE81:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP87]], <16 x i32> [[TMP93]])
; CHECK-O3-NEXT:    [[TMP94:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE81]])
; CHECK-O3-NEXT:    [[TMP95:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP94]], i64 0
; CHECK-O3-NEXT:    [[TMP96:%.*]] = freeze <16 x i8> [[WIDE_LOAD85]]
; CHECK-O3-NEXT:    [[TMP97:%.*]] = freeze <16 x i8> [[WIDE_LOAD86]]
; CHECK-O3-NEXT:    [[TMP98:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP96]], <16 x i8> [[TMP97]])
; CHECK-O3-NEXT:    [[TMP99:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP96]], <16 x i8> [[TMP97]])
; CHECK-O3-NEXT:    [[TMP100:%.*]] = sub <16 x i8> [[TMP98]], [[TMP99]]
; CHECK-O3-NEXT:    [[TMP101:%.*]] = zext <16 x i8> [[TMP100]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE87:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP95]], <16 x i32> [[TMP101]])
; CHECK-O3-NEXT:    [[TMP102:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE87]])
; CHECK-O3-NEXT:    [[TMP103:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP102]], i64 0
; CHECK-O3-NEXT:    [[TMP104:%.*]] = freeze <16 x i8> [[WIDE_LOAD91]]
; CHECK-O3-NEXT:    [[TMP105:%.*]] = freeze <16 x i8> [[WIDE_LOAD92]]
; CHECK-O3-NEXT:    [[TMP106:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP104]], <16 x i8> [[TMP105]])
; CHECK-O3-NEXT:    [[TMP107:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP104]], <16 x i8> [[TMP105]])
; CHECK-O3-NEXT:    [[TMP108:%.*]] = sub <16 x i8> [[TMP106]], [[TMP107]]
; CHECK-O3-NEXT:    [[TMP109:%.*]] = zext <16 x i8> [[TMP108]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE93:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP103]], <16 x i32> [[TMP109]])
; CHECK-O3-NEXT:    [[TMP110:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE93]])
; CHECK-O3-NEXT:    [[TMP111:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP110]], i64 0
; CHECK-O3-NEXT:    [[TMP112:%.*]] = freeze <16 x i8> [[WIDE_LOAD97]]
; CHECK-O3-NEXT:    [[TMP113:%.*]] = freeze <16 x i8> [[WIDE_LOAD98]]
; CHECK-O3-NEXT:    [[TMP114:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP112]], <16 x i8> [[TMP113]])
; CHECK-O3-NEXT:    [[TMP115:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP112]], <16 x i8> [[TMP113]])
; CHECK-O3-NEXT:    [[TMP116:%.*]] = sub <16 x i8> [[TMP114]], [[TMP115]]
; CHECK-O3-NEXT:    [[TMP117:%.*]] = zext <16 x i8> [[TMP116]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE99:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP111]], <16 x i32> [[TMP117]])
; CHECK-O3-NEXT:    [[TMP118:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE99]])
; CHECK-O3-NEXT:    [[TMP119:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP118]], i64 0
; CHECK-O3-NEXT:    [[ADD_PTR_14:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_13]], i64 [[IDX_EXT]]
; CHECK-O3-NEXT:    [[WIDE_LOAD103:%.*]] = load <16 x i8>, ptr [[ADD_PTR_14]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[TMP120:%.*]] = freeze <16 x i8> [[WIDE_LOAD103]]
; CHECK-O3-NEXT:    [[ADD_PTR9_14:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_13]], i64 [[IDX_EXT8]]
; CHECK-O3-NEXT:    [[WIDE_LOAD104:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_14]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-O3-NEXT:    [[TMP121:%.*]] = freeze <16 x i8> [[WIDE_LOAD104]]
; CHECK-O3-NEXT:    [[TMP122:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP120]], <16 x i8> [[TMP121]])
; CHECK-O3-NEXT:    [[TMP123:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP120]], <16 x i8> [[TMP121]])
; CHECK-O3-NEXT:    [[TMP124:%.*]] = sub <16 x i8> [[TMP122]], [[TMP123]]
; CHECK-O3-NEXT:    [[TMP125:%.*]] = zext <16 x i8> [[TMP124]] to <16 x i32>
; CHECK-O3-NEXT:    [[PARTIAL_REDUCE105:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP119]], <16 x i32> [[TMP125]])
; CHECK-O3-NEXT:    [[OP_RDX_15:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE105]])
; CHECK-O3-NEXT:    ret i32 [[OP_RDX_15]]
;
; CHECK-LTO-LABEL: define dso_local i32 @test(
; CHECK-LTO-SAME: ptr noundef readonly captures(none) [[P1:%.*]], i32 noundef [[S_P1:%.*]], ptr noundef readonly captures(none) [[P2:%.*]], i32 noundef [[S_P2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-LTO-NEXT:  [[ENTRY:.*:]]
; CHECK-LTO-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[S_P1]] to i64
; CHECK-LTO-NEXT:    [[IDX_EXT8:%.*]] = sext i32 [[S_P2]] to i64
; CHECK-LTO-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr [[P1]], align 1, !tbaa [[CHAR_TBAA0:![0-9]+]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD16:%.*]] = load <16 x i8>, ptr [[P2]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD19:%.*]] = load <16 x i8>, ptr [[ADD_PTR]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD20:%.*]] = load <16 x i8>, ptr [[ADD_PTR9]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD25:%.*]] = load <16 x i8>, ptr [[ADD_PTR_1]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD26:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_1]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_1]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_1]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD31:%.*]] = load <16 x i8>, ptr [[ADD_PTR_2]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD32:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_2]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_3:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_2]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_3:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_2]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD37:%.*]] = load <16 x i8>, ptr [[ADD_PTR_3]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD38:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_3]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_4:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_3]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_4:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_3]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD43:%.*]] = load <16 x i8>, ptr [[ADD_PTR_4]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD44:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_4]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_5:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_4]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_5:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_4]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD49:%.*]] = load <16 x i8>, ptr [[ADD_PTR_5]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD50:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_5]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_6:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_5]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_6:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_5]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD55:%.*]] = load <16 x i8>, ptr [[ADD_PTR_6]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD56:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_6]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_7:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_6]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_7:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_6]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD61:%.*]] = load <16 x i8>, ptr [[ADD_PTR_7]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD62:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_7]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_8:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_7]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_8:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_7]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD67:%.*]] = load <16 x i8>, ptr [[ADD_PTR_8]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD68:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_8]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_9:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_8]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_9:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_8]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD73:%.*]] = load <16 x i8>, ptr [[ADD_PTR_9]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD74:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_9]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_10:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_9]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_10:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_9]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD79:%.*]] = load <16 x i8>, ptr [[ADD_PTR_10]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD80:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_10]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_11:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_10]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_11:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_10]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD85:%.*]] = load <16 x i8>, ptr [[ADD_PTR_11]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD86:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_11]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_12:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_11]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_12:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_11]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD91:%.*]] = load <16 x i8>, ptr [[ADD_PTR_12]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD92:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_12]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[ADD_PTR_13:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_12]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_13:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_12]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD97:%.*]] = load <16 x i8>, ptr [[ADD_PTR_13]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD98:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_13]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[TMP0:%.*]] = freeze <16 x i8> [[WIDE_LOAD]]
; CHECK-LTO-NEXT:    [[TMP1:%.*]] = freeze <16 x i8> [[WIDE_LOAD16]]
; CHECK-LTO-NEXT:    [[TMP2:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP0]], <16 x i8> [[TMP1]])
; CHECK-LTO-NEXT:    [[TMP3:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP0]], <16 x i8> [[TMP1]])
; CHECK-LTO-NEXT:    [[TMP4:%.*]] = sub <16 x i8> [[TMP2]], [[TMP3]]
; CHECK-LTO-NEXT:    [[TMP5:%.*]] = zext <16 x i8> [[TMP4]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> zeroinitializer, <16 x i32> [[TMP5]])
; CHECK-LTO-NEXT:    [[TMP6:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE]])
; CHECK-LTO-NEXT:    [[TMP7:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP6]], i64 0
; CHECK-LTO-NEXT:    [[TMP8:%.*]] = freeze <16 x i8> [[WIDE_LOAD19]]
; CHECK-LTO-NEXT:    [[TMP9:%.*]] = freeze <16 x i8> [[WIDE_LOAD20]]
; CHECK-LTO-NEXT:    [[TMP10:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP8]], <16 x i8> [[TMP9]])
; CHECK-LTO-NEXT:    [[TMP11:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP8]], <16 x i8> [[TMP9]])
; CHECK-LTO-NEXT:    [[TMP12:%.*]] = sub <16 x i8> [[TMP10]], [[TMP11]]
; CHECK-LTO-NEXT:    [[TMP13:%.*]] = zext <16 x i8> [[TMP12]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE21:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP7]], <16 x i32> [[TMP13]])
; CHECK-LTO-NEXT:    [[TMP14:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE21]])
; CHECK-LTO-NEXT:    [[TMP15:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP14]], i64 0
; CHECK-LTO-NEXT:    [[TMP16:%.*]] = freeze <16 x i8> [[WIDE_LOAD25]]
; CHECK-LTO-NEXT:    [[TMP17:%.*]] = freeze <16 x i8> [[WIDE_LOAD26]]
; CHECK-LTO-NEXT:    [[TMP18:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP16]], <16 x i8> [[TMP17]])
; CHECK-LTO-NEXT:    [[TMP19:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP16]], <16 x i8> [[TMP17]])
; CHECK-LTO-NEXT:    [[TMP20:%.*]] = sub <16 x i8> [[TMP18]], [[TMP19]]
; CHECK-LTO-NEXT:    [[TMP21:%.*]] = zext <16 x i8> [[TMP20]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE27:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP15]], <16 x i32> [[TMP21]])
; CHECK-LTO-NEXT:    [[TMP22:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE27]])
; CHECK-LTO-NEXT:    [[TMP23:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP22]], i64 0
; CHECK-LTO-NEXT:    [[TMP24:%.*]] = freeze <16 x i8> [[WIDE_LOAD31]]
; CHECK-LTO-NEXT:    [[TMP25:%.*]] = freeze <16 x i8> [[WIDE_LOAD32]]
; CHECK-LTO-NEXT:    [[TMP26:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP24]], <16 x i8> [[TMP25]])
; CHECK-LTO-NEXT:    [[TMP27:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP24]], <16 x i8> [[TMP25]])
; CHECK-LTO-NEXT:    [[TMP28:%.*]] = sub <16 x i8> [[TMP26]], [[TMP27]]
; CHECK-LTO-NEXT:    [[TMP29:%.*]] = zext <16 x i8> [[TMP28]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE33:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP23]], <16 x i32> [[TMP29]])
; CHECK-LTO-NEXT:    [[TMP30:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE33]])
; CHECK-LTO-NEXT:    [[TMP31:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP30]], i64 0
; CHECK-LTO-NEXT:    [[TMP32:%.*]] = freeze <16 x i8> [[WIDE_LOAD37]]
; CHECK-LTO-NEXT:    [[TMP33:%.*]] = freeze <16 x i8> [[WIDE_LOAD38]]
; CHECK-LTO-NEXT:    [[TMP34:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP32]], <16 x i8> [[TMP33]])
; CHECK-LTO-NEXT:    [[TMP35:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP32]], <16 x i8> [[TMP33]])
; CHECK-LTO-NEXT:    [[TMP36:%.*]] = sub <16 x i8> [[TMP34]], [[TMP35]]
; CHECK-LTO-NEXT:    [[TMP37:%.*]] = zext <16 x i8> [[TMP36]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE39:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP31]], <16 x i32> [[TMP37]])
; CHECK-LTO-NEXT:    [[TMP38:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE39]])
; CHECK-LTO-NEXT:    [[TMP39:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP38]], i64 0
; CHECK-LTO-NEXT:    [[TMP40:%.*]] = freeze <16 x i8> [[WIDE_LOAD43]]
; CHECK-LTO-NEXT:    [[TMP41:%.*]] = freeze <16 x i8> [[WIDE_LOAD44]]
; CHECK-LTO-NEXT:    [[TMP42:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP40]], <16 x i8> [[TMP41]])
; CHECK-LTO-NEXT:    [[TMP43:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP40]], <16 x i8> [[TMP41]])
; CHECK-LTO-NEXT:    [[TMP44:%.*]] = sub <16 x i8> [[TMP42]], [[TMP43]]
; CHECK-LTO-NEXT:    [[TMP45:%.*]] = zext <16 x i8> [[TMP44]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE45:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP39]], <16 x i32> [[TMP45]])
; CHECK-LTO-NEXT:    [[TMP46:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE45]])
; CHECK-LTO-NEXT:    [[TMP47:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP46]], i64 0
; CHECK-LTO-NEXT:    [[TMP48:%.*]] = freeze <16 x i8> [[WIDE_LOAD49]]
; CHECK-LTO-NEXT:    [[TMP49:%.*]] = freeze <16 x i8> [[WIDE_LOAD50]]
; CHECK-LTO-NEXT:    [[TMP50:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP48]], <16 x i8> [[TMP49]])
; CHECK-LTO-NEXT:    [[TMP51:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP48]], <16 x i8> [[TMP49]])
; CHECK-LTO-NEXT:    [[TMP52:%.*]] = sub <16 x i8> [[TMP50]], [[TMP51]]
; CHECK-LTO-NEXT:    [[TMP53:%.*]] = zext <16 x i8> [[TMP52]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE51:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP47]], <16 x i32> [[TMP53]])
; CHECK-LTO-NEXT:    [[TMP54:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE51]])
; CHECK-LTO-NEXT:    [[TMP55:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP54]], i64 0
; CHECK-LTO-NEXT:    [[TMP56:%.*]] = freeze <16 x i8> [[WIDE_LOAD55]]
; CHECK-LTO-NEXT:    [[TMP57:%.*]] = freeze <16 x i8> [[WIDE_LOAD56]]
; CHECK-LTO-NEXT:    [[TMP58:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP56]], <16 x i8> [[TMP57]])
; CHECK-LTO-NEXT:    [[TMP59:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP56]], <16 x i8> [[TMP57]])
; CHECK-LTO-NEXT:    [[TMP60:%.*]] = sub <16 x i8> [[TMP58]], [[TMP59]]
; CHECK-LTO-NEXT:    [[TMP61:%.*]] = zext <16 x i8> [[TMP60]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE57:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP55]], <16 x i32> [[TMP61]])
; CHECK-LTO-NEXT:    [[TMP62:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE57]])
; CHECK-LTO-NEXT:    [[TMP63:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP62]], i64 0
; CHECK-LTO-NEXT:    [[TMP64:%.*]] = freeze <16 x i8> [[WIDE_LOAD61]]
; CHECK-LTO-NEXT:    [[TMP65:%.*]] = freeze <16 x i8> [[WIDE_LOAD62]]
; CHECK-LTO-NEXT:    [[TMP66:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP64]], <16 x i8> [[TMP65]])
; CHECK-LTO-NEXT:    [[TMP67:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP64]], <16 x i8> [[TMP65]])
; CHECK-LTO-NEXT:    [[TMP68:%.*]] = sub <16 x i8> [[TMP66]], [[TMP67]]
; CHECK-LTO-NEXT:    [[TMP69:%.*]] = zext <16 x i8> [[TMP68]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE63:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP63]], <16 x i32> [[TMP69]])
; CHECK-LTO-NEXT:    [[TMP70:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE63]])
; CHECK-LTO-NEXT:    [[TMP71:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP70]], i64 0
; CHECK-LTO-NEXT:    [[TMP72:%.*]] = freeze <16 x i8> [[WIDE_LOAD67]]
; CHECK-LTO-NEXT:    [[TMP73:%.*]] = freeze <16 x i8> [[WIDE_LOAD68]]
; CHECK-LTO-NEXT:    [[TMP74:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP72]], <16 x i8> [[TMP73]])
; CHECK-LTO-NEXT:    [[TMP75:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP72]], <16 x i8> [[TMP73]])
; CHECK-LTO-NEXT:    [[TMP76:%.*]] = sub <16 x i8> [[TMP74]], [[TMP75]]
; CHECK-LTO-NEXT:    [[TMP77:%.*]] = zext <16 x i8> [[TMP76]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE69:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP71]], <16 x i32> [[TMP77]])
; CHECK-LTO-NEXT:    [[TMP78:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE69]])
; CHECK-LTO-NEXT:    [[TMP79:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP78]], i64 0
; CHECK-LTO-NEXT:    [[TMP80:%.*]] = freeze <16 x i8> [[WIDE_LOAD73]]
; CHECK-LTO-NEXT:    [[TMP81:%.*]] = freeze <16 x i8> [[WIDE_LOAD74]]
; CHECK-LTO-NEXT:    [[TMP82:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP80]], <16 x i8> [[TMP81]])
; CHECK-LTO-NEXT:    [[TMP83:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP80]], <16 x i8> [[TMP81]])
; CHECK-LTO-NEXT:    [[TMP84:%.*]] = sub <16 x i8> [[TMP82]], [[TMP83]]
; CHECK-LTO-NEXT:    [[TMP85:%.*]] = zext <16 x i8> [[TMP84]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE75:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP79]], <16 x i32> [[TMP85]])
; CHECK-LTO-NEXT:    [[TMP86:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE75]])
; CHECK-LTO-NEXT:    [[TMP87:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP86]], i64 0
; CHECK-LTO-NEXT:    [[TMP88:%.*]] = freeze <16 x i8> [[WIDE_LOAD79]]
; CHECK-LTO-NEXT:    [[TMP89:%.*]] = freeze <16 x i8> [[WIDE_LOAD80]]
; CHECK-LTO-NEXT:    [[TMP90:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP88]], <16 x i8> [[TMP89]])
; CHECK-LTO-NEXT:    [[TMP91:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP88]], <16 x i8> [[TMP89]])
; CHECK-LTO-NEXT:    [[TMP92:%.*]] = sub <16 x i8> [[TMP90]], [[TMP91]]
; CHECK-LTO-NEXT:    [[TMP93:%.*]] = zext <16 x i8> [[TMP92]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE81:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP87]], <16 x i32> [[TMP93]])
; CHECK-LTO-NEXT:    [[TMP94:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE81]])
; CHECK-LTO-NEXT:    [[TMP95:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP94]], i64 0
; CHECK-LTO-NEXT:    [[TMP96:%.*]] = freeze <16 x i8> [[WIDE_LOAD85]]
; CHECK-LTO-NEXT:    [[TMP97:%.*]] = freeze <16 x i8> [[WIDE_LOAD86]]
; CHECK-LTO-NEXT:    [[TMP98:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP96]], <16 x i8> [[TMP97]])
; CHECK-LTO-NEXT:    [[TMP99:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP96]], <16 x i8> [[TMP97]])
; CHECK-LTO-NEXT:    [[TMP100:%.*]] = sub <16 x i8> [[TMP98]], [[TMP99]]
; CHECK-LTO-NEXT:    [[TMP101:%.*]] = zext <16 x i8> [[TMP100]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE87:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP95]], <16 x i32> [[TMP101]])
; CHECK-LTO-NEXT:    [[TMP102:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE87]])
; CHECK-LTO-NEXT:    [[TMP103:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP102]], i64 0
; CHECK-LTO-NEXT:    [[TMP104:%.*]] = freeze <16 x i8> [[WIDE_LOAD91]]
; CHECK-LTO-NEXT:    [[TMP105:%.*]] = freeze <16 x i8> [[WIDE_LOAD92]]
; CHECK-LTO-NEXT:    [[TMP106:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP104]], <16 x i8> [[TMP105]])
; CHECK-LTO-NEXT:    [[TMP107:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP104]], <16 x i8> [[TMP105]])
; CHECK-LTO-NEXT:    [[TMP108:%.*]] = sub <16 x i8> [[TMP106]], [[TMP107]]
; CHECK-LTO-NEXT:    [[TMP109:%.*]] = zext <16 x i8> [[TMP108]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE93:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP103]], <16 x i32> [[TMP109]])
; CHECK-LTO-NEXT:    [[TMP110:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE93]])
; CHECK-LTO-NEXT:    [[TMP111:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP110]], i64 0
; CHECK-LTO-NEXT:    [[TMP112:%.*]] = freeze <16 x i8> [[WIDE_LOAD97]]
; CHECK-LTO-NEXT:    [[TMP113:%.*]] = freeze <16 x i8> [[WIDE_LOAD98]]
; CHECK-LTO-NEXT:    [[TMP114:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP112]], <16 x i8> [[TMP113]])
; CHECK-LTO-NEXT:    [[TMP115:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP112]], <16 x i8> [[TMP113]])
; CHECK-LTO-NEXT:    [[TMP116:%.*]] = sub <16 x i8> [[TMP114]], [[TMP115]]
; CHECK-LTO-NEXT:    [[TMP117:%.*]] = zext <16 x i8> [[TMP116]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE99:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP111]], <16 x i32> [[TMP117]])
; CHECK-LTO-NEXT:    [[TMP118:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE99]])
; CHECK-LTO-NEXT:    [[TMP119:%.*]] = insertelement <4 x i32> <i32 poison, i32 0, i32 0, i32 0>, i32 [[TMP118]], i64 0
; CHECK-LTO-NEXT:    [[ADD_PTR_14:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_13]], i64 [[IDX_EXT]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD103:%.*]] = load <16 x i8>, ptr [[ADD_PTR_14]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[TMP120:%.*]] = freeze <16 x i8> [[WIDE_LOAD103]]
; CHECK-LTO-NEXT:    [[ADD_PTR9_14:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR9_13]], i64 [[IDX_EXT8]]
; CHECK-LTO-NEXT:    [[WIDE_LOAD104:%.*]] = load <16 x i8>, ptr [[ADD_PTR9_14]], align 1, !tbaa [[CHAR_TBAA0]]
; CHECK-LTO-NEXT:    [[TMP121:%.*]] = freeze <16 x i8> [[WIDE_LOAD104]]
; CHECK-LTO-NEXT:    [[TMP122:%.*]] = tail call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[TMP120]], <16 x i8> [[TMP121]])
; CHECK-LTO-NEXT:    [[TMP123:%.*]] = tail call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[TMP120]], <16 x i8> [[TMP121]])
; CHECK-LTO-NEXT:    [[TMP124:%.*]] = sub <16 x i8> [[TMP122]], [[TMP123]]
; CHECK-LTO-NEXT:    [[TMP125:%.*]] = zext <16 x i8> [[TMP124]] to <16 x i32>
; CHECK-LTO-NEXT:    [[PARTIAL_REDUCE105:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v16i32(<4 x i32> [[TMP119]], <16 x i32> [[TMP125]])
; CHECK-LTO-NEXT:    [[OP_RDX_15:%.*]] = tail call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE105]])
; CHECK-LTO-NEXT:    ret i32 [[OP_RDX_15]]
;
entry:
  %p1.addr = alloca ptr, align 8
  %s_p1.addr = alloca i32, align 4
  %p2.addr = alloca ptr, align 8
  %s_p2.addr = alloca i32, align 4
  %i_sum = alloca i32, align 4
  %y = alloca i32, align 4
  %cleanup.dest.slot = alloca i32, align 4
  %x = alloca i32, align 4
  store ptr %p1, ptr %p1.addr, align 8, !tbaa !4
  store i32 %s_p1, ptr %s_p1.addr, align 4, !tbaa !9
  store ptr %p2, ptr %p2.addr, align 8, !tbaa !4
  store i32 %s_p2, ptr %s_p2.addr, align 4, !tbaa !9
  call void @llvm.lifetime.start.p0(ptr %i_sum) #3
  store i32 0, ptr %i_sum, align 4, !tbaa !9
  call void @llvm.lifetime.start.p0(ptr %y) #3
  store i32 0, ptr %y, align 4, !tbaa !9
  br label %for.cond

for.cond:                                         ; preds = %for.inc10, %entry
  %0 = load i32, ptr %y, align 4, !tbaa !9
  %cmp = icmp slt i32 %0, 16
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  store i32 2, ptr %cleanup.dest.slot, align 4
  call void @llvm.lifetime.end.p0(ptr %y) #3
  br label %for.end12

for.body:                                         ; preds = %for.cond
  call void @llvm.lifetime.start.p0(ptr %x) #3
  store i32 0, ptr %x, align 4, !tbaa !9
  br label %for.cond1

for.cond1:                                        ; preds = %for.inc, %for.body
  %1 = load i32, ptr %x, align 4, !tbaa !9
  %cmp2 = icmp slt i32 %1, 16
  br i1 %cmp2, label %for.body4, label %for.cond.cleanup3

for.cond.cleanup3:                                ; preds = %for.cond1
  store i32 5, ptr %cleanup.dest.slot, align 4
  call void @llvm.lifetime.end.p0(ptr %x) #3
  br label %for.end

for.body4:                                        ; preds = %for.cond1
  %2 = load ptr, ptr %p1.addr, align 8, !tbaa !4
  %3 = load i32, ptr %x, align 4, !tbaa !9
  %idxprom = sext i32 %3 to i64
  %arrayidx = getelementptr inbounds i8, ptr %2, i64 %idxprom
  %4 = load i8, ptr %arrayidx, align 1, !tbaa !11
  %conv = zext i8 %4 to i32
  %5 = load ptr, ptr %p2.addr, align 8, !tbaa !4
  %6 = load i32, ptr %x, align 4, !tbaa !9
  %idxprom5 = sext i32 %6 to i64
  %arrayidx6 = getelementptr inbounds i8, ptr %5, i64 %idxprom5
  %7 = load i8, ptr %arrayidx6, align 1, !tbaa !11
  %conv7 = zext i8 %7 to i32
  %sub = sub nsw i32 %conv, %conv7
  %8 = call i32 @llvm.abs.i32(i32 %sub, i1 true)
  %9 = load i32, ptr %i_sum, align 4, !tbaa !9
  %add = add nsw i32 %9, %8
  store i32 %add, ptr %i_sum, align 4, !tbaa !9
  br label %for.inc

for.inc:                                          ; preds = %for.body4
  %10 = load i32, ptr %x, align 4, !tbaa !9
  %inc = add nsw i32 %10, 1
  store i32 %inc, ptr %x, align 4, !tbaa !9
  br label %for.cond1, !llvm.loop !12

for.end:                                          ; preds = %for.cond.cleanup3
  %11 = load i32, ptr %s_p1.addr, align 4, !tbaa !9
  %12 = load ptr, ptr %p1.addr, align 8, !tbaa !4
  %idx.ext = sext i32 %11 to i64
  %add.ptr = getelementptr inbounds i8, ptr %12, i64 %idx.ext
  store ptr %add.ptr, ptr %p1.addr, align 8, !tbaa !4
  %13 = load i32, ptr %s_p2.addr, align 4, !tbaa !9
  %14 = load ptr, ptr %p2.addr, align 8, !tbaa !4
  %idx.ext8 = sext i32 %13 to i64
  %add.ptr9 = getelementptr inbounds i8, ptr %14, i64 %idx.ext8
  store ptr %add.ptr9, ptr %p2.addr, align 8, !tbaa !4
  br label %for.inc10

for.inc10:                                        ; preds = %for.end
  %15 = load i32, ptr %y, align 4, !tbaa !9
  %inc11 = add nsw i32 %15, 1
  store i32 %inc11, ptr %y, align 4, !tbaa !9
  br label %for.cond, !llvm.loop !14

for.end12:                                        ; preds = %for.cond.cleanup
  %16 = load i32, ptr %i_sum, align 4, !tbaa !9
  store i32 1, ptr %cleanup.dest.slot, align 4
  call void @llvm.lifetime.end.p0(ptr %i_sum) #3
  ret i32 %16
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(ptr) #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.abs.i32(i32, i1 immarg) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(ptr) #1

attributes #0 = { nounwind uwtable vscale_range(1,16) "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+bf16,+bti,+ccidx,+complxnum,+crc,+dit,+dotprod,+ete,+flagm,+fp-armv8,+fp16fml,+fullfp16,+i8mm,+jsconv,+lse,+mte,+neon,+pauth,+perfmon,+predres,+rand,+ras,+rcpc,+rdm,+sb,+spe,+ssbs,+sve,+sve-bitperm,+sve2,+trbe,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+v8.5a,+v8a,+v9a,-fmv" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #3 = { nounwind }


!4 = !{!5, !5, i64 0}
!5 = !{!"p1 omnipotent char", !6, i64 0}
!6 = !{!"any pointer", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!10, !10, i64 0}
!10 = !{!"int", !7, i64 0}
!11 = !{!7, !7, i64 0}
!12 = distinct !{!12, !13}
!13 = !{!"llvm.loop.mustprogress"}
!14 = distinct !{!14, !13}
;.
; CHECK-O3: [[CHAR_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK-O3: [[META1]] = !{!"omnipotent char", [[META2:![0-9]+]], i64 0}
; CHECK-O3: [[META2]] = !{!"Simple C/C++ TBAA"}
;.
; CHECK-LTO: [[CHAR_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK-LTO: [[META1]] = !{!"omnipotent char", [[META2:![0-9]+]], i64 0}
; CHECK-LTO: [[META2]] = !{!"Simple C/C++ TBAA"}
;.
