; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='default<O3>' -S %s | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Reduced from SPEC's XalanUTF16Transcoder::transcodeFrom.
;
;   unsigned transcode(const unsigned short *src, unsigned n,
;                      char *dst, unsigned dstsize) {
;     unsigned i = 0, pos = 0;
;     while (i != n && pos + 1 < dstsize) {
;       __builtin_memcpy(dst + pos, &src[i], sizeof(unsigned short));
;       pos += 2;
;       ++i;
;     }
;     return pos;
;   }
;
; InstCombine turns the 'pos + 1' of the exit condition into 'or disjoint',
; because pos is even. Recovering a bound on pos from that condition needs the
; disjoint flag: without it the shifted-back range wraps around and pos is not
; known to be below dstsize, which keeps the induction variable narrow and the
; loop from being vectorized.

define i32 @transcode(ptr noundef %src, i32 noundef %n, ptr noundef %dst, i32 noundef %dstsize) {
; CHECK-LABEL: define range(i32 2, 1) i32 @transcode(
; CHECK-SAME: ptr nofree noundef readonly captures(none) [[SRC:%.*]], i32 noundef [[N:%.*]], ptr nofree noundef writeonly captures(none) [[DST:%.*]], i32 noundef [[DSTSIZE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP6:%.*]] = icmp ne i32 [[N]], 0
; CHECK-NEXT:    [[CMP17:%.*]] = icmp ugt i32 [[DSTSIZE]], 1
; CHECK-NEXT:    [[TMP0:%.*]] = and i1 [[CMP6]], [[CMP17]]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[ITER_CHECK:.*]], label %[[WHILE_END:.*]]
; CHECK:       [[ITER_CHECK]]:
; CHECK-NEXT:    [[DST16:%.*]] = ptrtoaddr ptr [[DST]] to i64
; CHECK-NEXT:    [[SRC17:%.*]] = ptrtoaddr ptr [[SRC]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[DSTSIZE]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = zext i32 [[N]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw i64 [[TMP1]], -2
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = add nsw i64 [[TMP2]], -1
; CHECK-NEXT:    [[UMIN:%.*]] = tail call i64 @llvm.umin.i64(i64 [[TMP4]], i64 [[TMP5]])
; CHECK-NEXT:    [[TMP6:%.*]] = add nuw i64 [[UMIN]], 1
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp samesign ult i64 [[UMIN]], 3
; CHECK-NEXT:    [[TMP7:%.*]] = sub i64 [[SRC17]], [[DST16]]
; CHECK-NEXT:    [[DIFF_CHECK:%.*]] = icmp ugt i64 [[TMP7]], -32
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[MIN_ITERS_CHECK]], [[DIFF_CHECK]]
; CHECK-NEXT:    br i1 [[OR_COND]], label %[[WHILE_BODY_PREHEADER:.*]], label %[[VECTOR_MAIN_LOOP_ITER_CHECK:.*]]
; CHECK:       [[VECTOR_MAIN_LOOP_ITER_CHECK]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK18:%.*]] = icmp samesign ult i64 [[UMIN]], 15
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK18]], label %[[VEC_EPILOG_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP8:%.*]] = and i64 [[TMP6]], 12
; CHECK-NEXT:    [[N_VEC:%.*]] = and i64 [[TMP6]], -16
; CHECK-NEXT:    [[TMP9:%.*]] = shl i64 [[N_VEC]], 1
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP10:%.*]] = shl nuw i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw [2 x i8], ptr [[SRC]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP12]], i64 16
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i16>, ptr [[TMP12]], align 2
; CHECK-NEXT:    [[WIDE_LOAD19:%.*]] = load <8 x i16>, ptr [[TMP13]], align 2
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP11]], i64 16
; CHECK-NEXT:    store <8 x i16> [[WIDE_LOAD]], ptr [[TMP11]], align 1
; CHECK-NEXT:    store <8 x i16> [[WIDE_LOAD19]], ptr [[TMP14]], align 1
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 16
; CHECK-NEXT:    [[TMP15:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP15]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP6]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[WHILE_END_LOOPEXIT:.*]], label %[[VEC_EPILOG_ITER_CHECK:.*]]
; CHECK:       [[VEC_EPILOG_ITER_CHECK]]:
; CHECK-NEXT:    [[MIN_EPILOG_ITERS_CHECK:%.*]] = icmp eq i64 [[TMP8]], 0
; CHECK-NEXT:    br i1 [[MIN_EPILOG_ITERS_CHECK]], label %[[WHILE_BODY_PREHEADER]], label %[[VEC_EPILOG_PH]], !prof [[PROF3:![0-9]+]]
; CHECK:       [[VEC_EPILOG_PH]]:
; CHECK-NEXT:    [[VEC_EPILOG_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[VEC_EPILOG_ITER_CHECK]] ], [ 0, %[[VECTOR_MAIN_LOOP_ITER_CHECK]] ]
; CHECK-NEXT:    [[N_VEC20:%.*]] = and i64 [[TMP6]], -4
; CHECK-NEXT:    [[TMP16:%.*]] = shl i64 [[N_VEC20]], 1
; CHECK-NEXT:    br label %[[VEC_EPILOG_VECTOR_BODY:.*]]
; CHECK:       [[VEC_EPILOG_VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX21:%.*]] = phi i64 [ [[VEC_EPILOG_RESUME_VAL]], %[[VEC_EPILOG_PH]] ], [ [[INDEX_NEXT23:%.*]], %[[VEC_EPILOG_VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP17:%.*]] = shl nuw i64 [[INDEX21]], 1
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 [[TMP17]]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw [2 x i8], ptr [[SRC]], i64 [[INDEX21]]
; CHECK-NEXT:    [[WIDE_LOAD22:%.*]] = load <4 x i16>, ptr [[TMP19]], align 2
; CHECK-NEXT:    store <4 x i16> [[WIDE_LOAD22]], ptr [[TMP18]], align 1
; CHECK-NEXT:    [[INDEX_NEXT23]] = add nuw i64 [[INDEX21]], 4
; CHECK-NEXT:    [[TMP20:%.*]] = icmp eq i64 [[INDEX_NEXT23]], [[N_VEC20]]
; CHECK-NEXT:    br i1 [[TMP20]], label %[[VEC_EPILOG_MIDDLE_BLOCK:.*]], label %[[VEC_EPILOG_VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[VEC_EPILOG_MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N24:%.*]] = icmp eq i64 [[TMP6]], [[N_VEC20]]
; CHECK-NEXT:    br i1 [[CMP_N24]], label %[[WHILE_END_LOOPEXIT]], label %[[WHILE_BODY_PREHEADER]]
; CHECK:       [[WHILE_BODY_PREHEADER]]:
; CHECK-NEXT:    [[INDVARS_IV11_PH:%.*]] = phi i64 [ 0, %[[ITER_CHECK]] ], [ [[N_VEC]], %[[VEC_EPILOG_ITER_CHECK]] ], [ [[N_VEC20]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ]
; CHECK-NEXT:    [[INDVARS_IV_PH:%.*]] = phi i64 [ 0, %[[ITER_CHECK]] ], [ [[TMP9]], %[[VEC_EPILOG_ITER_CHECK]] ], [ [[TMP16]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ]
; CHECK-NEXT:    br label %[[WHILE_BODY:.*]]
; CHECK:       [[WHILE_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV11:%.*]] = phi i64 [ [[INDVARS_IV_NEXT12:%.*]], %[[WHILE_BODY]] ], [ [[INDVARS_IV11_PH]], %[[WHILE_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[WHILE_BODY]] ], [ [[INDVARS_IV_PH]], %[[WHILE_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [2 x i8], ptr [[SRC]], i64 [[INDVARS_IV11]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[ARRAYIDX]], align 2
; CHECK-NEXT:    store i16 [[TMP21]], ptr [[ADD_PTR]], align 1
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 2
; CHECK-NEXT:    [[INDVARS_IV_NEXT12]] = add nuw nsw i64 [[INDVARS_IV11]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT12]], [[TMP2]]
; CHECK-NEXT:    [[TMP22:%.*]] = or disjoint i64 [[INDVARS_IV_NEXT]], 1
; CHECK-NEXT:    [[CMP1:%.*]] = icmp samesign ult i64 [[TMP22]], [[TMP1]]
; CHECK-NEXT:    [[TMP23:%.*]] = select i1 [[CMP]], i1 [[CMP1]], i1 false
; CHECK-NEXT:    br i1 [[TMP23]], label %[[WHILE_BODY]], label %[[WHILE_END_LOOPEXIT]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[WHILE_END_LOOPEXIT]]:
; CHECK-NEXT:    [[INDVARS_IV_NEXT_LCSSA:%.*]] = phi i64 [ [[TMP16]], %[[VEC_EPILOG_MIDDLE_BLOCK]] ], [ [[TMP9]], %[[MIDDLE_BLOCK]] ], [ [[INDVARS_IV_NEXT]], %[[WHILE_BODY]] ]
; CHECK-NEXT:    [[TMP24:%.*]] = trunc nuw i64 [[INDVARS_IV_NEXT_LCSSA]] to i32
; CHECK-NEXT:    br label %[[WHILE_END]]
; CHECK:       [[WHILE_END]]:
; CHECK-NEXT:    [[POS_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[TMP24]], %[[WHILE_END_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[POS_0_LCSSA]]
;
entry:
  %src.addr = alloca ptr, align 8
  %n.addr = alloca i32, align 4
  %dst.addr = alloca ptr, align 8
  %dstsize.addr = alloca i32, align 4
  %i = alloca i32, align 4
  %pos = alloca i32, align 4
  store ptr %src, ptr %src.addr, align 8
  store i32 %n, ptr %n.addr, align 4
  store ptr %dst, ptr %dst.addr, align 8
  store i32 %dstsize, ptr %dstsize.addr, align 4
  call void @llvm.lifetime.start.p0(ptr %i)
  store i32 0, ptr %i, align 4
  call void @llvm.lifetime.start.p0(ptr %pos)
  store i32 0, ptr %pos, align 4
  br label %while.cond

while.cond:                                       ; preds = %while.body, %entry
  %0 = load i32, ptr %i, align 4
  %1 = load i32, ptr %n.addr, align 4
  %cmp = icmp ne i32 %0, %1
  br i1 %cmp, label %land.rhs, label %land.end

land.rhs:                                         ; preds = %while.cond
  %2 = load i32, ptr %pos, align 4
  %add = add i32 %2, 1
  %3 = load i32, ptr %dstsize.addr, align 4
  %cmp1 = icmp ult i32 %add, %3
  br label %land.end

land.end:                                         ; preds = %land.rhs, %while.cond
  %4 = phi i1 [ false, %while.cond ], [ %cmp1, %land.rhs ]
  br i1 %4, label %while.body, label %while.end

while.body:                                       ; preds = %land.end
  %5 = load ptr, ptr %dst.addr, align 8
  %6 = load i32, ptr %pos, align 4
  %idx.ext = zext i32 %6 to i64
  %add.ptr = getelementptr inbounds nuw i8, ptr %5, i64 %idx.ext
  %7 = load ptr, ptr %src.addr, align 8
  %8 = load i32, ptr %i, align 4
  %idxprom = zext i32 %8 to i64
  %arrayidx = getelementptr inbounds nuw i16, ptr %7, i64 %idxprom
  call void @llvm.memcpy.p0.p0.i64(ptr align 1 %add.ptr, ptr align 2 %arrayidx, i64 2, i1 false)
  %9 = load i32, ptr %pos, align 4
  %add2 = add i32 %9, 2
  store i32 %add2, ptr %pos, align 4
  %10 = load i32, ptr %i, align 4
  %inc = add i32 %10, 1
  store i32 %inc, ptr %i, align 4
  br label %while.cond

while.end:                                        ; preds = %land.end
  %11 = load i32, ptr %pos, align 4
  call void @llvm.lifetime.end.p0(ptr %pos)
  call void @llvm.lifetime.end.p0(ptr %i)
  ret i32 %11
}

declare void @llvm.lifetime.start.p0(ptr)
declare void @llvm.lifetime.end.p0(ptr)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[PROF3]] = !{!"branch_weights", i32 4, i32 12}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]]}
;.
