; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -p loop-unroll -S %s | FileCheck %s

; Test last-iteration peeling with ULT predicate - loop counts up with unsigned comparison
define void @test_ult_last_iter(i32 %n) {
; CHECK-LABEL: define void @test_ult_last_iter(
; CHECK-SAME: i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN:.*]], label %[[IF_END:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_1:.*]], label %[[IF_END_1:.*]]
; CHECK:       [[IF_THEN_1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_1]]
; CHECK:       [[IF_END_1]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_2:.*]], label %[[IF_END_2:.*]]
; CHECK:       [[IF_THEN_2]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_2]]
; CHECK:       [[IF_END_2]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_3:.*]], label %[[IF_END_3:.*]]
; CHECK:       [[IF_THEN_3]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_3]]
; CHECK:       [[IF_END_3]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_4:.*]], label %[[IF_END_4:.*]]
; CHECK:       [[IF_THEN_4]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_4]]
; CHECK:       [[IF_END_4]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_5:.*]], label %[[IF_END_5:.*]]
; CHECK:       [[IF_THEN_5]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_5]]
; CHECK:       [[IF_END_5]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_6:.*]], label %[[IF_END_6:.*]]
; CHECK:       [[IF_THEN_6]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_6]]
; CHECK:       [[IF_END_6]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_7:.*]], label %[[IF_END_7:.*]]
; CHECK:       [[IF_THEN_7]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_7]]
; CHECK:       [[IF_END_7]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_8:.*]], label %[[IF_END_8:.*]]
; CHECK:       [[IF_THEN_8]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_8]]
; CHECK:       [[IF_END_8]]:
; CHECK-NEXT:    br i1 true, label %[[IF_THEN_9:.*]], label %[[IF_END_9:.*]]
; CHECK:       [[IF_THEN_9]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_9]]
; CHECK:       [[IF_END_9]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %if.end ]
  %cmp.last = icmp eq i32 %iv, 9
  br i1 %cmp.last, label %if.then, label %if.end

if.then:
  call void @foo()
  br label %if.end

if.end:
  %iv.next = add i32 %iv, 1
  %cmp = icmp ult i32 %iv.next, 10
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Test last-iteration peeling with ULE predicate - loop counts up with unsigned comparison
define void @test_ule_last_iter(i32 %n) {
; CHECK-LABEL: define void @test_ule_last_iter(
; CHECK-SAME: i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN:.*]], label %[[IF_END:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_1:.*]], label %[[IF_END_1:.*]]
; CHECK:       [[IF_THEN_1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_1]]
; CHECK:       [[IF_END_1]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_2:.*]], label %[[IF_END_2:.*]]
; CHECK:       [[IF_THEN_2]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_2]]
; CHECK:       [[IF_END_2]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_3:.*]], label %[[IF_END_3:.*]]
; CHECK:       [[IF_THEN_3]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_3]]
; CHECK:       [[IF_END_3]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_4:.*]], label %[[IF_END_4:.*]]
; CHECK:       [[IF_THEN_4]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_4]]
; CHECK:       [[IF_END_4]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_5:.*]], label %[[IF_END_5:.*]]
; CHECK:       [[IF_THEN_5]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_5]]
; CHECK:       [[IF_END_5]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_6:.*]], label %[[IF_END_6:.*]]
; CHECK:       [[IF_THEN_6]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_6]]
; CHECK:       [[IF_END_6]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_7:.*]], label %[[IF_END_7:.*]]
; CHECK:       [[IF_THEN_7]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_7]]
; CHECK:       [[IF_END_7]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_8:.*]], label %[[IF_END_8:.*]]
; CHECK:       [[IF_THEN_8]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_8]]
; CHECK:       [[IF_END_8]]:
; CHECK-NEXT:    br i1 false, label %[[IF_THEN_9:.*]], label %[[IF_END_9:.*]]
; CHECK:       [[IF_THEN_9]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_9]]
; CHECK:       [[IF_END_9]]:
; CHECK-NEXT:    br i1 true, label %[[IF_THEN_10:.*]], label %[[IF_END_10:.*]]
; CHECK:       [[IF_THEN_10]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[IF_END_10]]
; CHECK:       [[IF_END_10]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %if.end ]
  %cmp.last = icmp eq i32 %iv, 10
  br i1 %cmp.last, label %if.then, label %if.end

if.then:
  call void @foo()
  br label %if.end

if.end:
  %iv.next = add i32 %iv, 1
  %cmp = icmp ule i32 %iv.next, 10
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Test with variable bound to ensure correctness with ULT
define void @test_ult_variable_bound(i32 %n) {
; CHECK-LABEL: define void @test_ult_variable_bound(
; CHECK-SAME: i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  call void @foo()
  %iv.next = add i32 %iv, 1
  %cmp = icmp ult i32 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Test with variable bound to ensure correctness with ULE
define void @test_ule_variable_bound(i32 %n) {
; CHECK-LABEL: define void @test_ule_variable_bound(
; CHECK-SAME: i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ule i32 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  call void @foo()
  %iv.next = add i32 %iv, 1
  %cmp = icmp ule i32 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

declare void @foo()