; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: %if aarch64-registered-target %{ opt -passes=slp-vectorizer -S -mtriple=aarch64-apple-macosx15.0.0 < %s | FileCheck %s %}
; RUN: %if aarch64-registered-target %{ opt -passes=slp-vectorizer -slp-use-vplan-codegen -S -mtriple=aarch64-apple-macosx15.0.0 < %s | FileCheck %s --check-prefix=VPLAN %}

; Test that PHI nodes with gather operands (extractelements from the same
; vector) are correctly handled in VPlan codegen. The gather BuildVector must
; be placed in the incoming block so it dominates the PHI.
define float @phi_with_gather_operand(i1 %c) {
; CHECK-LABEL: define float @phi_with_gather_operand(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[C]], label [[IF_END:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[TMP0:%.*]] = phi <2 x float> [ zeroinitializer, [[IF_THEN]] ], [ zeroinitializer, [[ENTRY:%.*]] ]
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[TMP0]], i32 0
; CHECK-NEXT:    ret float [[TMP1]]
;
; VPLAN-LABEL: define float @phi_with_gather_operand(
; VPLAN-SAME: i1 [[C:%.*]]) {
; VPLAN-NEXT:  entry:
; VPLAN-NEXT:    br i1 [[C]], label [[IF_END:%.*]], label [[IF_THEN:%.*]]
; VPLAN:       if.then:
; VPLAN-NEXT:    br label [[IF_END]]
; VPLAN:       if.end:
; VPLAN-NEXT:    [[TMP0:%.*]] = phi <2 x float> [ zeroinitializer, [[IF_THEN]] ], [ zeroinitializer, [[ENTRY:%.*]] ]
; VPLAN-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[TMP0]], i32 0
; VPLAN-NEXT:    br label [[EXIT:%.*]]
; VPLAN:       exit:
; VPLAN-NEXT:    ret float [[TMP1]]
;
entry:
  br i1 %c, label %if.end, label %if.then

if.then:
  %e0 = extractelement <2 x float> zeroinitializer, i64 0
  %e1 = extractelement <2 x float> zeroinitializer, i64 1
  br label %if.end

if.end:
  %p0 = phi float [ %e0, %if.then ], [ 0.000000e+00, %entry ]
  %p1 = phi float [ %e1, %if.then ], [ 0.000000e+00, %entry ]
  br label %exit

exit:
  ret float %p0
}
