; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: %if aarch64-registered-target %{ opt -passes=slp-vectorizer -S -mtriple=aarch64-apple-macosx15.0.0 < %s | FileCheck %s %}
; RUN: %if aarch64-registered-target %{ opt -passes=slp-vectorizer -slp-use-vplan-codegen -S -mtriple=aarch64-apple-macosx15.0.0 < %s | FileCheck %s --check-prefix=VPLAN %}

; Test that PHI gather operands extracted from vectors of different widths
; do not crash in the extract-from-vector shuffle optimization.
define void @phi_gather_mixed_width_vectors() {
; CHECK-LABEL: define void @phi_gather_mixed_width_vectors() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 false, label [[EXIT:%.*]], label [[BB1:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[TMP0:%.*]] = phi <2 x double> [ zeroinitializer, [[ENTRY:%.*]] ], [ zeroinitializer, [[BB1]] ]
; CHECK-NEXT:    ret void
;
; VPLAN-LABEL: define void @phi_gather_mixed_width_vectors() {
; VPLAN-NEXT:  entry:
; VPLAN-NEXT:    br i1 false, label [[EXIT:%.*]], label [[BB1:%.*]]
; VPLAN:       bb1:
; VPLAN-NEXT:    [[E0:%.*]] = extractelement <2 x double> zeroinitializer, i64 0
; VPLAN-NEXT:    [[E1:%.*]] = extractelement <8 x double> zeroinitializer, i64 1
; VPLAN-NEXT:    [[TMP0:%.*]] = insertelement <2 x double> poison, double [[E0]], i32 0
; VPLAN-NEXT:    [[TMP1:%.*]] = insertelement <2 x double> [[TMP0]], double [[E1]], i32 1
; VPLAN-NEXT:    br label [[EXIT]]
; VPLAN:       exit:
; VPLAN-NEXT:    [[TMP2:%.*]] = phi <2 x double> [ zeroinitializer, [[ENTRY:%.*]] ], [ [[TMP1]], [[BB1]] ]
; VPLAN-NEXT:    ret void
;
entry:
  br i1 false, label %exit, label %bb1

bb1:
  %e0 = extractelement <2 x double> zeroinitializer, i64 0
  %e1 = extractelement <8 x double> zeroinitializer, i64 1
  br label %exit

exit:
  %p0 = phi double [ 0.000000e+00, %entry ], [ %e0, %bb1 ]
  %p1 = phi double [ 0.000000e+00, %entry ], [ %e1, %bb1 ]
  ret void
}
