; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=sroa -S | FileCheck %s

; ModuleID = 'zzz_test.ll'
source_filename = "zzz_test.i"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #0

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #0

define i32 @main() local_unnamed_addr {
; CHECK-LABEL: @main(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret i32 undef
; CHECK:       i.exit:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr undef, ptr_provenance ptr null, align 4, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    ret i32 0
;
entry:
  %h.i = alloca [21 x i32], align 16
  %0 = bitcast [21 x i32]* %h.i to ptr
  call void @llvm.lifetime.start.p0(i64 84, ptr %0)
  ret i32 undef

i.exit:                                           ; No predecessors!
  %arraydecay.i = getelementptr inbounds [21 x i32], [21 x i32]* %h.i, i64 0, i64 0
  %1 = load i32, ptr undef, ptr_provenance ptr %arraydecay.i, align 4, !tbaa !0
  ret i32 0
}

attributes #0 = { argmemonly nofree nosync nounwind willreturn }

!0 = !{!1, !1, i64 0}
!1 = !{!"int", !2, i64 0}
!2 = !{!"omnipotent char", !3, i64 0}
!3 = !{!"Simple C/C++ TBAA"}
