; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -slp-use-vplan-codegen -O3 -S %s | FileCheck %s

; Verify that SLP VPlan codegen handles compares bundled with swapped
; predicates. After inlining and SimplifyCFG, icmp sgt and icmp slt end up in
; the same basic block. SLP bundles them by normalizing to a single predicate
; via operand swapping, but VPlan codegen must use the main compare's predicate
; rather than trying to intersect different predicates.

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx13.0.0"

%struct.Rect = type { float, float, float, float }

define ptr @caller(ptr %p) {
; CHECK-LABEL: define noalias noundef ptr @caller(
; CHECK-SAME: ptr readonly captures(none) [[P:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[RECT:%.*]] = alloca [[STRUCT_RECT:%.*]], align 16
; CHECK-NEXT:    [[BASE:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    [[GEP_LEFT:%.*]] = getelementptr i8, ptr [[BASE]], i64 52
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i32>, ptr [[GEP_LEFT]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = sitofp <4 x i32> [[TMP0]] to <4 x float>
; CHECK-NEXT:    [[TMP2:%.*]] = fdiv <4 x float> [[TMP1]], <float 1.000000e+00, float 1.000000e+03, float 1.000000e+00, float 1.000000e+03>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x float> [[TMP2]], <4 x float> poison, <4 x i32> <i32 0, i32 2, i32 3, i32 1>
; CHECK-NEXT:    store <4 x float> [[TMP3]], ptr [[RECT]], align 16
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <2 x i32> <i32 3, i32 0>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> poison, <2 x i32> <i32 1, i32 2>
; CHECK-NEXT:    [[TMP10:%.*]] = icmp slt <2 x i32> [[TMP6]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x i1> [[TMP10]], i64 0
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x i1> [[TMP10]], i64 1
; CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP12]], i1 [[TMP11]], i1 false
; CHECK-NEXT:    br i1 [[OR_COND]], label %[[IF_END:.*]], label %[[COMMON_RET:.*]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    ret ptr null
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    call void @use_rect(ptr nonnull [[RECT]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  %rect = alloca %struct.Rect, align 4
  %base = load ptr, ptr %p, align 8
  %gep.bottom = getelementptr i8, ptr %base, i64 64
  %bottom = load i32, ptr %gep.bottom, align 4
  %gep.right = getelementptr i8, ptr %base, i64 60
  %gep.top = getelementptr i8, ptr %base, i64 56
  %top = load i32, ptr %gep.top, align 4
  %gep.left = getelementptr i8, ptr %base, i64 52
  %left = load i32, ptr %gep.left, align 4
  %left.f = sitofp i32 %left to float
  %bottom.f = sitofp i32 %bottom to float
  %bottom.scaled = fdiv float %bottom.f, 1.000000e+03
  %right.i = load i32, ptr %gep.right, align 4
  %right.f = sitofp i32 %right.i to float
  %top.f = sitofp i32 %top to float
  %top.scaled = fdiv float %top.f, 1.000000e+03
  %call = call ptr @init_rect(ptr %rect, float %left.f, float %bottom.scaled, float %right.f, float %top.scaled)
  %right.reload = load i32, ptr %gep.right, align 4
  %left.reload = load i32, ptr %gep.left, align 4
  %cmp.sgt = icmp sgt i32 %right.reload, %left.reload
  br i1 %cmp.sgt, label %check2, label %exit

check2:
  %bottom.reload = load i32, ptr %gep.bottom, align 4
  %top.reload = load i32, ptr %gep.top, align 4
  %cmp.slt = icmp slt i32 %bottom.reload, %top.reload
  br i1 %cmp.slt, label %if.end, label %exit

exit:
  ret ptr null

if.end:
  call void @use_rect(ptr %rect)
  ret ptr null
}

define ptr @init_rect(ptr %this, float %a, float %b, float %c, float %d) {
; CHECK-LABEL: define noalias noundef ptr @init_rect(
; CHECK-SAME: ptr writeonly captures(none) initializes((0, 16)) [[THIS:%.*]], float [[A:%.*]], float [[B:%.*]], float [[C:%.*]], float [[D:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store float [[A]], ptr [[THIS]], align 4
; CHECK-NEXT:    [[GEP_B:%.*]] = getelementptr i8, ptr [[THIS]], i64 8
; CHECK-NEXT:    store float [[B]], ptr [[GEP_B]], align 4
; CHECK-NEXT:    [[GEP_C:%.*]] = getelementptr i8, ptr [[THIS]], i64 4
; CHECK-NEXT:    store float [[C]], ptr [[GEP_C]], align 4
; CHECK-NEXT:    [[GEP_D:%.*]] = getelementptr i8, ptr [[THIS]], i64 12
; CHECK-NEXT:    store float [[D]], ptr [[GEP_D]], align 4
; CHECK-NEXT:    ret ptr null
;
entry:
  store float %a, ptr %this, align 4
  %gep.b = getelementptr i8, ptr %this, i64 8
  store float %b, ptr %gep.b, align 4
  %gep.c = getelementptr i8, ptr %this, i64 4
  store float %c, ptr %gep.c, align 4
  %gep.d = getelementptr i8, ptr %this, i64 12
  store float %d, ptr %gep.d, align 4
  ret ptr null
}

declare void @use_rect(ptr)
