; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -slp-use-vplan-codegen -passes=slp-vectorizer -S %s | FileCheck %s

; Verify that SLP VPlan codegen places vector instructions at per-entry insert
; points. The fmul and fadd chains produce intermediate results used both by
; stores (root of the SLP tree) and by external uses (insertvalue/ret). With a
; single insert point at the store position, vector instructions for the fadd
; entries would be placed after their external users, breaking dominance.

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx15.0.0"

%retty = type { [2 x %inner] }
%inner = type { float }

@gval = external global float

define %retty @test_vplan_per_entry_insert_point(ptr %p) {
; CHECK-LABEL: define %retty @test_vplan_per_entry_insert_point(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load float, ptr [[P]], align 4
; CHECK-NEXT:    [[GEP16:%.*]] = getelementptr i8, ptr [[P]], i64 16
; CHECK-NEXT:    [[GEP20:%.*]] = getelementptr i8, ptr [[P]], i64 20
; CHECK-NEXT:    store float 0.000000e+00, ptr [[GEP20]], align 4
; CHECK-NEXT:    [[FMA:%.*]] = call float @llvm.fmuladd.f32(float [[V0]], float 0.000000e+00, float 0.000000e+00)
; CHECK-NEXT:    [[GEP4:%.*]] = getelementptr i8, ptr [[P]], i64 4
; CHECK-NEXT:    [[GEP8:%.*]] = getelementptr i8, ptr [[P]], i64 8
; CHECK-NEXT:    [[V8:%.*]] = load float, ptr [[GEP8]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x float> poison, float [[FMA]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = insertelement <2 x float> [[TMP0]], float [[V0]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = fmul <2 x float> [[TMP1]], zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x float> [[TMP2]], i32 1
; CHECK-NEXT:    store float [[TMP4]], ptr [[GEP16]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[TMP2]], i32 0
; CHECK-NEXT:    store float [[TMP3]], ptr [[GEP4]], align 4
; CHECK-NEXT:    [[G:%.*]] = load float, ptr @gval, align 4
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x float> poison, float [[G]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x float> [[TMP5]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = fmul <2 x float> [[TMP2]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = fadd <2 x float> [[TMP7]], zeroinitializer
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x float> poison, float [[G]], i32 0
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <2 x float> [[TMP9]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x float> <float poison, float 0.000000e+00>, float [[V8]], i32 0
; CHECK-NEXT:    [[TMP11:%.*]] = fmul <2 x float> [[TMP15]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = fadd <2 x float> [[TMP8]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <2 x float> [[TMP12]], i32 0
; CHECK-NEXT:    [[R0:%.*]] = insertvalue [[RETTY:%.*]] zeroinitializer, float [[TMP13]], 0, 0, 0
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <2 x float> [[TMP12]], i32 1
; CHECK-NEXT:    [[R1:%.*]] = insertvalue [[RETTY]] [[R0]], float [[TMP14]], 0, 1, 0
; CHECK-NEXT:    ret [[RETTY]] [[R1]]
;
entry:
  %v0 = load float, ptr %p, align 4
  %mul0 = fmul float %v0, 0.000000e+00
  %gep16 = getelementptr i8, ptr %p, i64 16
  store float %mul0, ptr %gep16, align 4
  %gep20 = getelementptr i8, ptr %p, i64 20
  store float 0.000000e+00, ptr %gep20, align 4
  %fma = call float @llvm.fmuladd.f32(float %v0, float 0.000000e+00, float 0.000000e+00)
  %scaled = fmul ninf float %fma, 0.000000e+00
  %gep4 = getelementptr i8, ptr %p, i64 4
  store float %scaled, ptr %gep4, align 4
  %g = load float, ptr @gval, align 4
  %m0 = fmul float %scaled, %g
  %a0 = fadd float %m0, 0.000000e+00
  %gep8 = getelementptr i8, ptr %p, i64 8
  %v8 = load float, ptr %gep8, align 4
  %m1 = fmul float %g, %v8
  %a1 = fadd float %a0, %m1
  %m2 = fmul float %mul0, %g
  %a2 = fadd float %m2, 0.000000e+00
  %m3 = fmul float %g, 0.000000e+00
  %a3 = fadd float %m3, %a2
  %r0 = insertvalue %retty zeroinitializer, float %a1, 0, 0, 0
  %r1 = insertvalue %retty %r0, float %a3, 0, 1, 0
  ret %retty %r1
}

declare float @llvm.fmuladd.f32(float, float, float)
