; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=slp-vectorizer,verify -slp-threshold=-99999 -mtriple=aarch64-unknown-linux -S -pass-remarks-output=%t | FileCheck %s
; RUN: FileCheck --input-file=%t --check-prefix=YAML %s
; RUN: opt < %s -passes=slp-vectorizer,verify -slp-use-vplan-codegen -slp-threshold=-99999 -mtriple=aarch64-unknown-linux -S -pass-remarks-output=%t | FileCheck %s --check-prefix=VPLAN

; YAML-LABEL: --- !Passed
; YAML-NEXT: Pass:            slp-vectorizer
; YAML-NEXT: Name:            VectorizedList
; YAML-NEXT: Function:        foo
; YAML-NEXT: Args:
; YAML-NEXT:   - String:          'SLP vectorized with cost '
; YAML-NEXT:   - Cost:            '4'
; YAML-NEXT:   - String:          ' and with tree size '
; YAML-NEXT:   - TreeSize:        '2'

; YAML-LABEL: --- !Passed
; YAML-NEXT: Pass:            slp-vectorizer
; YAML-NEXT: Name:            VectorizedList
; YAML-NEXT: Function:        foo
; YAML-NEXT: Args:
; YAML-NEXT:   - String:          'SLP vectorized with cost '
; YAML-NEXT:   - Cost:            '0'
; YAML-NEXT:   - String:          ' and with tree size '
; YAML-NEXT:   - TreeSize:        '3'

; YAML-LABEL: --- !Passed
; YAML-NEXT: Pass:            slp-vectorizer
; YAML-NEXT: Name:            VectorizedList
; YAML-NEXT: Function:        foo
; YAML-NEXT: Args:
; YAML-NEXT:   - String:          'SLP vectorized with cost '
; YAML-NEXT:   - Cost:            '8'
; YAML-NEXT:   - String:          ' and with tree size '
; YAML-NEXT:   - TreeSize:        '5'

define void @foo() personality ptr @bar {
; CHECK-LABEL: @foo(
; CHECK-NEXT:  bb1:
; CHECK-NEXT:    br label [[BB3:%.*]]
; CHECK:       bb2.loopexit:
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[TMP0:%.*]] = phi <2 x i64> [ poison, [[BB9:%.*]] ], [ poison, [[BB2_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = phi <2 x i64> [ [[TMP8:%.*]], [[BB9]] ], [ poison, [[BB2_LOOPEXIT]] ]
; CHECK-NEXT:    ret void
; CHECK:       bb3:
; CHECK-NEXT:    [[TMP2:%.*]] = phi <2 x i64> [ [[TMP6:%.*]], [[BB6:%.*]] ], [ poison, [[BB1:%.*]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i64> [[TMP2]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x i64> [[TMP2]], i32 1
; CHECK-NEXT:    [[TMP5:%.*]] = invoke i64 poison(ptr addrspace(1) nonnull poison, i64 0, i64 0, i64 poison) [ "deopt"() ]
; CHECK-NEXT:            to label [[BB4:%.*]] unwind label [[BB10:%.*]]
; CHECK:       bb4:
; CHECK-NEXT:    br i1 poison, label [[BB11:%.*]], label [[BB5:%.*]]
; CHECK:       bb5:
; CHECK-NEXT:    br label [[BB7:%.*]]
; CHECK:       bb6:
; CHECK-NEXT:    [[TMP6]] = phi <2 x i64> [ <i64 0, i64 poison>, [[BB8:%.*]] ]
; CHECK-NEXT:    br label [[BB3]]
; CHECK:       bb7:
; CHECK-NEXT:    [[LOCAL_5_84111:%.*]] = phi i64 [ poison, [[BB8]] ], [ poison, [[BB5]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = invoke i64 poison(ptr addrspace(1) nonnull poison, i64 poison, i64 poison, i64 poison) [ "deopt"() ]
; CHECK-NEXT:            to label [[BB8]] unwind label [[BB12:%.*]]
; CHECK:       bb8:
; CHECK-NEXT:    br i1 poison, label [[BB7]], label [[BB6]]
; CHECK:       bb9:
; CHECK-NEXT:    [[INDVARS_IV528799:%.*]] = phi i64 [ poison, [[BB10]] ], [ poison, [[BB12]] ]
; CHECK-NEXT:    [[TMP8]] = phi <2 x i64> [ [[TMP10:%.*]], [[BB10]] ], [ [[TMP12:%.*]], [[BB12]] ]
; CHECK-NEXT:    br label [[BB2]]
; CHECK:       bb10:
; CHECK-NEXT:    [[LOCAL_10_38123_LCSSA:%.*]] = phi i64 [ [[TMP4]], [[BB3]] ]
; CHECK-NEXT:    [[LOCAL_5_33118_LCSSA:%.*]] = phi i64 [ [[TMP3]], [[BB3]] ]
; CHECK-NEXT:    [[LANDING_PAD68:%.*]] = landingpad { ptr, i64 }
; CHECK-NEXT:            cleanup
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x i64> poison, i64 [[LOCAL_10_38123_LCSSA]], i32 0
; CHECK-NEXT:    [[TMP10]] = insertelement <2 x i64> [[TMP9]], i64 [[LOCAL_5_33118_LCSSA]], i32 1
; CHECK-NEXT:    br label [[BB9]]
; CHECK:       bb11:
; CHECK-NEXT:    ret void
; CHECK:       bb12:
; CHECK-NEXT:    [[LOCAL_10_89113_LCSSA:%.*]] = phi i64 [ poison, [[BB7]] ]
; CHECK-NEXT:    [[LOCAL_5_84111_LCSSA:%.*]] = phi i64 [ [[LOCAL_5_84111]], [[BB7]] ]
; CHECK-NEXT:    [[LANDING_PAD149:%.*]] = landingpad { ptr, i64 }
; CHECK-NEXT:            cleanup
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <2 x i64> poison, i64 [[LOCAL_10_89113_LCSSA]], i32 0
; CHECK-NEXT:    [[TMP12]] = insertelement <2 x i64> [[TMP11]], i64 [[LOCAL_5_84111_LCSSA]], i32 1
; CHECK-NEXT:    br label [[BB9]]
;
; VPLAN-LABEL: @foo(
; VPLAN-NEXT:  bb1:
; VPLAN-NEXT:    br label [[BB3:%.*]]
; VPLAN:       bb2.loopexit:
; VPLAN-NEXT:    br label [[BB2:%.*]]
; VPLAN:       bb2:
; VPLAN-NEXT:    [[TMP0:%.*]] = phi <2 x i64> [ poison, [[BB9:%.*]] ], [ poison, [[BB2_LOOPEXIT:%.*]] ]
; VPLAN-NEXT:    [[TMP1:%.*]] = phi <2 x i64> [ [[TMP12:%.*]], [[BB9]] ], [ poison, [[BB2_LOOPEXIT]] ]
; VPLAN-NEXT:    ret void
; VPLAN:       bb3:
; VPLAN-NEXT:    [[TMP2:%.*]] = phi <2 x i64> [ [[TMP10:%.*]], [[BB6:%.*]] ], [ poison, [[BB1:%.*]] ]
; VPLAN-NEXT:    [[TMP3:%.*]] = extractelement <2 x i64> [[TMP2]], i32 0
; VPLAN-NEXT:    [[TMP4:%.*]] = extractelement <2 x i64> [[TMP2]], i32 1
; VPLAN-NEXT:    [[TMP5:%.*]] = invoke i64 poison(ptr addrspace(1) nonnull poison, i64 0, i64 0, i64 poison) [ "deopt"() ]
; VPLAN-NEXT:            to label [[BB4:%.*]] unwind label [[BB10:%.*]]
; VPLAN:       bb4:
; VPLAN-NEXT:    br i1 poison, label [[BB11:%.*]], label [[BB5:%.*]]
; VPLAN:       bb5:
; VPLAN-NEXT:    br label [[BB7:%.*]]
; VPLAN:       bb6:
; VPLAN-NEXT:    [[TMP6:%.*]] = phi <2 x i64> [ <i64 0, i64 poison>, [[BB8:%.*]] ]
; VPLAN-NEXT:    [[TMP7:%.*]] = extractelement <2 x i64> [[TMP6]], i32 1
; VPLAN-NEXT:    [[TMP8:%.*]] = insertelement <2 x i64> poison, i64 [[TMP7]], i32 0
; VPLAN-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i64> [[TMP8]], <2 x i64> poison, <2 x i32> <i32 poison, i32 0>
; VPLAN-NEXT:    [[TMP10]] = freeze <2 x i64> [[TMP9]]
; VPLAN-NEXT:    br label [[BB3]]
; VPLAN:       bb7:
; VPLAN-NEXT:    [[LOCAL_5_84111:%.*]] = phi i64 [ poison, [[BB8]] ], [ poison, [[BB5]] ]
; VPLAN-NEXT:    [[TMP11:%.*]] = invoke i64 poison(ptr addrspace(1) nonnull poison, i64 poison, i64 poison, i64 poison) [ "deopt"() ]
; VPLAN-NEXT:            to label [[BB8]] unwind label [[BB12:%.*]]
; VPLAN:       bb8:
; VPLAN-NEXT:    br i1 poison, label [[BB7]], label [[BB6]]
; VPLAN:       bb9:
; VPLAN-NEXT:    [[INDVARS_IV528799:%.*]] = phi i64 [ poison, [[BB10]] ], [ poison, [[BB12]] ]
; VPLAN-NEXT:    [[TMP12]] = phi <2 x i64> [ [[TMP14:%.*]], [[BB10]] ], [ [[TMP16:%.*]], [[BB12]] ]
; VPLAN-NEXT:    br label [[BB2]]
; VPLAN:       bb10:
; VPLAN-NEXT:    [[LOCAL_10_38123_LCSSA:%.*]] = phi i64 [ [[TMP4]], [[BB3]] ]
; VPLAN-NEXT:    [[LOCAL_5_33118_LCSSA:%.*]] = phi i64 [ [[TMP3]], [[BB3]] ]
; VPLAN-NEXT:    [[LANDING_PAD68:%.*]] = landingpad { ptr, i64 }
; VPLAN-NEXT:            cleanup
; VPLAN-NEXT:    [[TMP13:%.*]] = insertelement <2 x i64> poison, i64 [[LOCAL_10_38123_LCSSA]], i32 0
; VPLAN-NEXT:    [[TMP14]] = insertelement <2 x i64> [[TMP13]], i64 [[LOCAL_5_33118_LCSSA]], i32 1
; VPLAN-NEXT:    br label [[BB9]]
; VPLAN:       bb11:
; VPLAN-NEXT:    ret void
; VPLAN:       bb12:
; VPLAN-NEXT:    [[LOCAL_10_89113_LCSSA:%.*]] = phi i64 [ poison, [[BB7]] ]
; VPLAN-NEXT:    [[LOCAL_5_84111_LCSSA:%.*]] = phi i64 [ [[LOCAL_5_84111]], [[BB7]] ]
; VPLAN-NEXT:    [[LANDING_PAD149:%.*]] = landingpad { ptr, i64 }
; VPLAN-NEXT:            cleanup
; VPLAN-NEXT:    [[TMP15:%.*]] = insertelement <2 x i64> poison, i64 [[LOCAL_10_89113_LCSSA]], i32 0
; VPLAN-NEXT:    [[TMP16]] = insertelement <2 x i64> [[TMP15]], i64 [[LOCAL_5_84111_LCSSA]], i32 1
; VPLAN-NEXT:    br label [[BB9]]
;
bb1:
  br label %bb3

bb2.loopexit:
  br label %bb2

bb2:
  %local_8_3681 = phi i64 [ poison, %bb9 ], [ 1, %bb2.loopexit ]
  %local_2_44 = phi i64 [ poison, %bb9 ], [ poison, %bb2.loopexit ]
  %local_5_47 = phi i64 [ %local_5_19, %bb9 ], [ poison, %bb2.loopexit ]
  %local_10_52 = phi i64 [ %local_10_24, %bb9 ], [ poison, %bb2.loopexit ]
  ret void

bb3:
  %local_10_38123 = phi i64 [ %.lcssa773, %bb6 ], [ poison, %bb1 ]
  %local_5_33118 = phi i64 [ poison, %bb6 ], [ poison, %bb1 ]
  %0 = invoke i64 poison(ptr addrspace(1) nonnull poison, i64 0, i64 0, i64 poison) [ "deopt"() ]
  to label %bb4 unwind label %bb10

bb4:
  br i1 poison, label %bb11, label %bb5

bb5:
  br label %bb7

bb6:
  %.lcssa773 = phi i64 [ poison, %bb8 ]
  %.lcssa770 = phi i64 [ 0, %bb8 ]
  br label %bb3

bb7:
  %local_5_84111 = phi i64 [ poison, %bb8 ], [ poison, %bb5 ]
  %1 = invoke i64 poison(ptr addrspace(1) nonnull poison, i64 poison, i64 poison, i64 poison) [ "deopt"() ]
  to label %bb8 unwind label %bb12

bb8:
  br i1 poison, label %bb7, label %bb6

bb9:
  %indvars.iv528799 = phi i64 [ poison, %bb10 ], [ poison, %bb12 ]
  %local_5_19 = phi i64 [ %local_5_33118.lcssa, %bb10 ], [ %local_5_84111.lcssa, %bb12 ]
  %local_10_24 = phi i64 [ %local_10_38123.lcssa, %bb10 ], [ %local_10_89113.lcssa, %bb12 ]
  br label %bb2

bb10:
  %local_10_38123.lcssa = phi i64 [ %local_10_38123, %bb3 ]
  %local_5_33118.lcssa = phi i64 [ %local_5_33118, %bb3 ]
  %landing_pad68 = landingpad { ptr, i64 }
  cleanup
  br label %bb9

bb11:
  ret void

bb12:
  %local_10_89113.lcssa = phi i64 [ poison, %bb7 ]
  %local_5_84111.lcssa = phi i64 [ %local_5_84111, %bb7 ]
  %landing_pad149 = landingpad { ptr, i64 }
  cleanup
  br label %bb9
}

declare ptr @bar()


