; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=slp-vectorizer -S -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck --check-prefixes=CHECK,LEGACY %s
; RUN: opt -passes=slp-vectorizer -slp-use-vplan-codegen -S -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck --check-prefixes=CHECK,VPLAN %s

; The existing codegen path strips nuw from a trunc it only uses as a gather
; element (in BoUpSLP::gather()), mutating an instruction that is not part of
; the tree and stays in the function. VPlan-based codegen leaves it alone.
define void @nuw_on_gathered_trunc(ptr %dst, ptr %src, i64 %a0, i64 %a2, i32 %b1, i32 %b3) {
; LEGACY-LABEL: define void @nuw_on_gathered_trunc(
; LEGACY-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i64 [[A0:%.*]], i64 [[A2:%.*]], i32 [[B1:%.*]], i32 [[B3:%.*]]) {
; LEGACY-NEXT:    [[T0:%.*]] = trunc i64 [[A0]] to i32
; LEGACY-NEXT:    [[T2:%.*]] = trunc i64 [[A2]] to i32
; LEGACY-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[SRC]], align 4
; LEGACY-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> poison, i32 [[B1]], i64 1
; LEGACY-NEXT:    [[TMP3:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[B3]], i64 3
; LEGACY-NEXT:    [[TMP4:%.*]] = insertelement <4 x i32> [[TMP3]], i32 [[T0]], i64 0
; LEGACY-NEXT:    [[TMP5:%.*]] = insertelement <4 x i32> [[TMP4]], i32 [[T2]], i64 2
; LEGACY-NEXT:    [[TMP6:%.*]] = mul <4 x i32> [[TMP1]], [[TMP5]]
; LEGACY-NEXT:    store <4 x i32> [[TMP6]], ptr [[DST]], align 4
; LEGACY-NEXT:    ret void
;
; VPLAN-LABEL: define void @nuw_on_gathered_trunc(
; VPLAN-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i64 [[A0:%.*]], i64 [[A2:%.*]], i32 [[B1:%.*]], i32 [[B3:%.*]]) {
; VPLAN-NEXT:    [[T0:%.*]] = trunc nuw i64 [[A0]] to i32
; VPLAN-NEXT:    [[T2:%.*]] = trunc nuw i64 [[A2]] to i32
; VPLAN-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[SRC]], align 4
; VPLAN-NEXT:    [[TMP1:%.*]] = insertelement <4 x i32> poison, i32 [[T0]], i64 0
; VPLAN-NEXT:    [[TMP2:%.*]] = insertelement <4 x i32> [[TMP1]], i32 [[B1]], i64 1
; VPLAN-NEXT:    [[TMP3:%.*]] = insertelement <4 x i32> [[TMP2]], i32 [[T2]], i64 2
; VPLAN-NEXT:    [[TMP4:%.*]] = insertelement <4 x i32> [[TMP3]], i32 [[B3]], i64 3
; VPLAN-NEXT:    [[TMP5:%.*]] = mul <4 x i32> [[WIDE_LOAD]], [[TMP4]]
; VPLAN-NEXT:    store <4 x i32> [[TMP5]], ptr [[DST]], align 4
; VPLAN-NEXT:    ret void
;
  %t0 = trunc nuw i64 %a0 to i32
  %t2 = trunc nuw i64 %a2 to i32
  %sg1 = getelementptr i32, ptr %src, i64 1
  %sg2 = getelementptr i32, ptr %src, i64 2
  %sg3 = getelementptr i32, ptr %src, i64 3
  %l0 = load i32, ptr %src, align 4
  %l1 = load i32, ptr %sg1, align 4
  %l2 = load i32, ptr %sg2, align 4
  %l3 = load i32, ptr %sg3, align 4
  %m0 = mul i32 %l0, %t0
  %m1 = mul i32 %l1, %b1
  %m2 = mul i32 %l2, %t2
  %m3 = mul i32 %l3, %b3
  %dg1 = getelementptr i32, ptr %dst, i64 1
  %dg2 = getelementptr i32, ptr %dst, i64 2
  %dg3 = getelementptr i32, ptr %dst, i64 3
  store i32 %m0, ptr %dst, align 4
  store i32 %m1, ptr %dg1, align 4
  store i32 %m2, ptr %dg2, align 4
  store i32 %m3, ptr %dg3, align 4
  ret void
}

; The existing codegen path builds a widened cast with IRBuilder and never
; propagates the scalar cast flags, so nsw is dropped. VPlan-based codegen
; carries the flags all lanes agree on.
define void @nsw_on_widened_trunc(ptr %dst, ptr %src) {
; LEGACY-LABEL: define void @nsw_on_widened_trunc(
; LEGACY-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; LEGACY-NEXT:    [[SG0:%.*]] = getelementptr i32, ptr [[SRC]], i64 0
; LEGACY-NEXT:    [[DG0:%.*]] = getelementptr i16, ptr [[DST]], i64 0
; LEGACY-NEXT:    [[TMP1:%.*]] = load <8 x i32>, ptr [[SG0]], align 4
; LEGACY-NEXT:    [[TMP2:%.*]] = trunc <8 x i32> [[TMP1]] to <8 x i16>
; LEGACY-NEXT:    store <8 x i16> [[TMP2]], ptr [[DG0]], align 2
; LEGACY-NEXT:    ret void
;
; VPLAN-LABEL: define void @nsw_on_widened_trunc(
; VPLAN-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; VPLAN-NEXT:    [[SG0:%.*]] = getelementptr i32, ptr [[SRC]], i64 0
; VPLAN-NEXT:    [[DG0:%.*]] = getelementptr i16, ptr [[DST]], i64 0
; VPLAN-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i32>, ptr [[SG0]], align 4
; VPLAN-NEXT:    [[TMP1:%.*]] = trunc nsw <8 x i32> [[WIDE_LOAD]] to <8 x i16>
; VPLAN-NEXT:    store <8 x i16> [[TMP1]], ptr [[DG0]], align 2
; VPLAN-NEXT:    ret void
;
  %sg0 = getelementptr i32, ptr %src, i64 0
  %l0 = load i32, ptr %sg0, align 4
  %sg1 = getelementptr i32, ptr %src, i64 1
  %l1 = load i32, ptr %sg1, align 4
  %sg2 = getelementptr i32, ptr %src, i64 2
  %l2 = load i32, ptr %sg2, align 4
  %sg3 = getelementptr i32, ptr %src, i64 3
  %l3 = load i32, ptr %sg3, align 4
  %sg4 = getelementptr i32, ptr %src, i64 4
  %l4 = load i32, ptr %sg4, align 4
  %sg5 = getelementptr i32, ptr %src, i64 5
  %l5 = load i32, ptr %sg5, align 4
  %sg6 = getelementptr i32, ptr %src, i64 6
  %l6 = load i32, ptr %sg6, align 4
  %sg7 = getelementptr i32, ptr %src, i64 7
  %l7 = load i32, ptr %sg7, align 4
  %t0 = trunc nsw i32 %l0 to i16
  %t1 = trunc nsw i32 %l1 to i16
  %t2 = trunc nsw i32 %l2 to i16
  %t3 = trunc nsw i32 %l3 to i16
  %t4 = trunc nsw i32 %l4 to i16
  %t5 = trunc nsw i32 %l5 to i16
  %t6 = trunc nsw i32 %l6 to i16
  %t7 = trunc nsw i32 %l7 to i16
  %dg0 = getelementptr i16, ptr %dst, i64 0
  store i16 %t0, ptr %dg0, align 2
  %dg1 = getelementptr i16, ptr %dst, i64 1
  store i16 %t1, ptr %dg1, align 2
  %dg2 = getelementptr i16, ptr %dst, i64 2
  store i16 %t2, ptr %dg2, align 2
  %dg3 = getelementptr i16, ptr %dst, i64 3
  store i16 %t3, ptr %dg3, align 2
  %dg4 = getelementptr i16, ptr %dst, i64 4
  store i16 %t4, ptr %dg4, align 2
  %dg5 = getelementptr i16, ptr %dst, i64 5
  store i16 %t5, ptr %dg5, align 2
  %dg6 = getelementptr i16, ptr %dst, i64 6
  store i16 %t6, ptr %dg6, align 2
  %dg7 = getelementptr i16, ptr %dst, i64 7
  store i16 %t7, ptr %dg7, align 2
  ret void
}

; Only one lane has nsw, so the widened trunc must not have it either.
define void @nsw_on_widened_trunc_one_lane_only(ptr %dst, ptr %src) {
; LEGACY-LABEL: define void @nsw_on_widened_trunc_one_lane_only(
; LEGACY-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; LEGACY-NEXT:    [[SG0:%.*]] = getelementptr i32, ptr [[SRC]], i64 0
; LEGACY-NEXT:    [[DG0:%.*]] = getelementptr i16, ptr [[DST]], i64 0
; LEGACY-NEXT:    [[TMP1:%.*]] = load <8 x i32>, ptr [[SG0]], align 4
; LEGACY-NEXT:    [[TMP2:%.*]] = trunc <8 x i32> [[TMP1]] to <8 x i16>
; LEGACY-NEXT:    store <8 x i16> [[TMP2]], ptr [[DG0]], align 2
; LEGACY-NEXT:    ret void
;
; VPLAN-LABEL: define void @nsw_on_widened_trunc_one_lane_only(
; VPLAN-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; VPLAN-NEXT:    [[SG0:%.*]] = getelementptr i32, ptr [[SRC]], i64 0
; VPLAN-NEXT:    [[DG0:%.*]] = getelementptr i16, ptr [[DST]], i64 0
; VPLAN-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i32>, ptr [[SG0]], align 4
; VPLAN-NEXT:    [[TMP1:%.*]] = trunc <8 x i32> [[WIDE_LOAD]] to <8 x i16>
; VPLAN-NEXT:    store <8 x i16> [[TMP1]], ptr [[DG0]], align 2
; VPLAN-NEXT:    ret void
;
  %sg0 = getelementptr i32, ptr %src, i64 0
  %l0 = load i32, ptr %sg0, align 4
  %sg1 = getelementptr i32, ptr %src, i64 1
  %l1 = load i32, ptr %sg1, align 4
  %sg2 = getelementptr i32, ptr %src, i64 2
  %l2 = load i32, ptr %sg2, align 4
  %sg3 = getelementptr i32, ptr %src, i64 3
  %l3 = load i32, ptr %sg3, align 4
  %sg4 = getelementptr i32, ptr %src, i64 4
  %l4 = load i32, ptr %sg4, align 4
  %sg5 = getelementptr i32, ptr %src, i64 5
  %l5 = load i32, ptr %sg5, align 4
  %sg6 = getelementptr i32, ptr %src, i64 6
  %l6 = load i32, ptr %sg6, align 4
  %sg7 = getelementptr i32, ptr %src, i64 7
  %l7 = load i32, ptr %sg7, align 4
  %t0 = trunc nsw i32 %l0 to i16
  %t1 = trunc i32 %l1 to i16
  %t2 = trunc i32 %l2 to i16
  %t3 = trunc i32 %l3 to i16
  %t4 = trunc i32 %l4 to i16
  %t5 = trunc i32 %l5 to i16
  %t6 = trunc i32 %l6 to i16
  %t7 = trunc i32 %l7 to i16
  %dg0 = getelementptr i16, ptr %dst, i64 0
  store i16 %t0, ptr %dg0, align 2
  %dg1 = getelementptr i16, ptr %dst, i64 1
  store i16 %t1, ptr %dg1, align 2
  %dg2 = getelementptr i16, ptr %dst, i64 2
  store i16 %t2, ptr %dg2, align 2
  %dg3 = getelementptr i16, ptr %dst, i64 3
  store i16 %t3, ptr %dg3, align 2
  %dg4 = getelementptr i16, ptr %dst, i64 4
  store i16 %t4, ptr %dg4, align 2
  %dg5 = getelementptr i16, ptr %dst, i64 5
  store i16 %t5, ptr %dg5, align 2
  %dg6 = getelementptr i16, ptr %dst, i64 6
  store i16 %t6, ptr %dg6, align 2
  %dg7 = getelementptr i16, ptr %dst, i64 7
  store i16 %t7, ptr %dg7, align 2
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
