; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=slp-vectorizer -slp-use-vplan-codegen -S %s | FileCheck %s

; Verify that extracts for PHI users from multiple incoming blocks are placed
; correctly. Each incoming block gets its own extract.

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx15.0.0"

define ptr @phi_extract_multi_incoming(ptr %call47) {
; CHECK-LABEL: @phi_extract_multi_incoming(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 false, label [[IF_ELSE115:%.*]], label [[IF_THEN105:%.*]]
; CHECK:       if.then105:
; CHECK-NEXT:    [[PARENTCLS_I:%.*]] = getelementptr i8, ptr [[CALL47:%.*]], i64 32
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x ptr>, ptr [[PARENTCLS_I]], align 8
; CHECK-NEXT:    br label [[IF_ELSE115]]
; CHECK:       if.else115:
; CHECK-NEXT:    [[TMP0:%.*]] = phi <2 x ptr> [ [[WIDE_LOAD]], [[IF_THEN105]] ], [ zeroinitializer, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x ptr> [[TMP0]], i32 0
; CHECK-NEXT:    br i1 false, label [[IF_END4_I_I:%.*]], label [[EXIT:%.*]]
; CHECK:       if.end4.i.i:
; CHECK-NEXT:    br i1 false, label [[EXIT]], label [[FOR_END_I_I:%.*]]
; CHECK:       for.end.i.i:
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x ptr> [[TMP0]], i32 0
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[COMMON_RET_OP_I_I:%.*]] = phi ptr [ null, [[IF_END4_I_I]] ], [ [[TMP1]], [[IF_ELSE115]] ], [ [[TMP2]], [[FOR_END_I_I]] ]
; CHECK-NEXT:    ret ptr [[COMMON_RET_OP_I_I]]
;
entry:
  br i1 false, label %if.else115, label %if.then105

if.then105:
  %parentCls.i = getelementptr i8, ptr %call47, i64 32
  %0 = load ptr, ptr %parentCls.i, align 8
  %parentLits.i = getelementptr i8, ptr %call47, i64 40
  %1 = load ptr, ptr %parentLits.i, align 8
  br label %if.else115

if.else115:
  %PClauses.0 = phi ptr [ %0, %if.then105 ], [ null, %entry ]
  %PLits.0 = phi ptr [ %1, %if.then105 ], [ null, %entry ]
  br i1 false, label %if.end4.i.i, label %exit

if.end4.i.i:
  br i1 false, label %exit, label %for.end.i.i

for.end.i.i:
  br label %exit

exit:
  %common.ret.op.i.i = phi ptr [ null, %if.end4.i.i ], [ %PClauses.0, %if.else115 ], [ %PClauses.0, %for.end.i.i ]
  ret ptr %common.ret.op.i.i
}
