; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=slp-vectorizer -slp-use-vplan-codegen -S %s | FileCheck %s

; Verify that extracts for external uses in sibling (non-dominating) blocks
; are placed correctly. The extract for %0 must be in each block that uses it,
; not just in one of them.

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx15.0.0"

define fastcc i64 @extract_in_sibling_blocks(ptr %v) {
; CHECK-LABEL: @extract_in_sibling_blocks(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[BLOCK_INDEX_I_I:%.*]] = getelementptr i8, ptr [[V:%.*]], i64 4784
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x i32>, ptr [[BLOCK_INDEX_I_I]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i32> [[WIDE_LOAD]], i32 0
; CHECK-NEXT:    store <2 x i32> [[WIDE_LOAD]], ptr [[BLOCK_INDEX_I_I]], align 8
; CHECK-NEXT:    br i1 false, label [[IF_THEN54:%.*]], label [[IF_ELSE59:%.*]]
; CHECK:       if.then54:
; CHECK-NEXT:    [[IDXPROM85_I:%.*]] = sext i32 [[TMP0]] to i64
; CHECK-NEXT:    ret i64 [[IDXPROM85_I]]
; CHECK:       if.else59:
; CHECK-NEXT:    [[IDXPROM96_I:%.*]] = sext i32 [[TMP0]] to i64
; CHECK-NEXT:    ret i64 [[IDXPROM96_I]]
;
entry:
  %block_index.i.i = getelementptr i8, ptr %v, i64 4784
  %0 = load i32, ptr %block_index.i.i, align 8
  store i32 %0, ptr %block_index.i.i, align 8
  %arrayidx3.i.i = getelementptr i8, ptr %v, i64 4788
  %1 = load i32, ptr %arrayidx3.i.i, align 4
  store i32 %1, ptr %arrayidx3.i.i, align 4
  br i1 false, label %if.then54, label %if.else59

if.then54:
  %idxprom85.i = sext i32 %0 to i64
  ret i64 %idxprom85.i

if.else59:
  %idxprom96.i = sext i32 %0 to i64
  ret i64 %idxprom96.i
}
