; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck --check-prefix=NON-VPLAN %s
; RUN: opt -passes=slp-vectorizer -slp-use-vplan-codegen -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck --check-prefix=VPLAN %s

; GEP with constant index offset applied to loaded base pointers.
define void @gep_constant_idx(ptr %src, ptr %dst) {
; NON-VPLAN-LABEL: define void @gep_constant_idx(
; NON-VPLAN-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; NON-VPLAN-NEXT:  [[ENTRY:.*:]]
; NON-VPLAN-NEXT:    [[TMP0:%.*]] = load <2 x ptr>, ptr [[SRC]], align 8
; NON-VPLAN-NEXT:    [[TMP1:%.*]] = getelementptr i32, <2 x ptr> [[TMP0]], <2 x i64> splat (i64 16)
; NON-VPLAN-NEXT:    store <2 x ptr> [[TMP1]], ptr [[DST]], align 8
; NON-VPLAN-NEXT:    ret void
;
; VPLAN-LABEL: define void @gep_constant_idx(
; VPLAN-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; VPLAN-NEXT:  [[ENTRY:.*:]]
; VPLAN-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x ptr>, ptr [[SRC]], align 8
; VPLAN-NEXT:    [[TMP0:%.*]] = getelementptr i32, <2 x ptr> [[WIDE_LOAD]], <2 x i64> splat (i64 16)
; VPLAN-NEXT:    store <2 x ptr> [[TMP0]], ptr [[DST]], align 8
; VPLAN-NEXT:    ret void
;
entry:
  %s0 = load ptr, ptr %src, align 8
  %src1 = getelementptr ptr, ptr %src, i64 1
  %s1 = load ptr, ptr %src1, align 8
  %gep0 = getelementptr i32, ptr %s0, i64 16
  %gep1 = getelementptr i32, ptr %s1, i64 16
  store ptr %gep0, ptr %dst, align 8
  %dst1 = getelementptr ptr, ptr %dst, i64 1
  store ptr %gep1, ptr %dst1, align 8
  ret void
}

; GEP with inbounds and constant index.
define void @gep_inbounds_constant_idx(ptr %src, ptr %dst) {
; NON-VPLAN-LABEL: define void @gep_inbounds_constant_idx(
; NON-VPLAN-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; NON-VPLAN-NEXT:  [[ENTRY:.*:]]
; NON-VPLAN-NEXT:    [[TMP0:%.*]] = load <2 x ptr>, ptr [[SRC]], align 8
; NON-VPLAN-NEXT:    [[TMP1:%.*]] = getelementptr i32, <2 x ptr> [[TMP0]], <2 x i64> splat (i64 4)
; NON-VPLAN-NEXT:    store <2 x ptr> [[TMP1]], ptr [[DST]], align 8
; NON-VPLAN-NEXT:    ret void
;
; VPLAN-LABEL: define void @gep_inbounds_constant_idx(
; VPLAN-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; VPLAN-NEXT:  [[ENTRY:.*:]]
; VPLAN-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x ptr>, ptr [[SRC]], align 8
; VPLAN-NEXT:    [[TMP0:%.*]] = getelementptr i32, <2 x ptr> [[WIDE_LOAD]], <2 x i64> splat (i64 4)
; VPLAN-NEXT:    store <2 x ptr> [[TMP0]], ptr [[DST]], align 8
; VPLAN-NEXT:    ret void
;
entry:
  %s0 = load ptr, ptr %src, align 8
  %src1 = getelementptr ptr, ptr %src, i64 1
  %s1 = load ptr, ptr %src1, align 8
  %gep0 = getelementptr inbounds i32, ptr %s0, i64 4
  %gep1 = getelementptr inbounds i32, ptr %s1, i64 4
  store ptr %gep0, ptr %dst, align 8
  %dst1 = getelementptr ptr, ptr %dst, i64 1
  store ptr %gep1, ptr %dst1, align 8
  ret void
}
