; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=slp-vectorizer -slp-use-vplan-codegen -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

; External uses of vectorized values: the fadd results are stored but also
; returned, requiring extractelement from the vectorized fadd.
define {double, double} @fadd_ext_use(ptr %src, ptr %dst) {
; CHECK-LABEL: define { double, double } @fadd_ext_use(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x double>, ptr [[SRC]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = fadd <2 x double> [[TMP0]], [[TMP0]]
; CHECK-NEXT:    store <2 x double> [[TMP1]], ptr [[DST]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x double> [[TMP1]], i32 0
; CHECK-NEXT:    [[R_0:%.*]] = insertvalue { double, double } undef, double [[TMP2]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x double> [[TMP1]], i32 1
; CHECK-NEXT:    [[R_1:%.*]] = insertvalue { double, double } [[R_0]], double [[TMP3]], 1
; CHECK-NEXT:    ret { double, double } [[R_1]]
;
entry:
  %src.0 = load double, ptr %src, align 8
  %src.gep.1 = getelementptr double, ptr %src, i64 1
  %src.1 = load double, ptr %src.gep.1, align 8
  %fadd.0 = fadd double %src.0, %src.0
  %fadd.1 = fadd double %src.1, %src.1
  store double %fadd.0, ptr %dst, align 8
  %dst.gep.1 = getelementptr double, ptr %dst, i64 1
  store double %fadd.1, ptr %dst.gep.1, align 8
  %r.0 = insertvalue {double, double} undef, double %fadd.0, 0
  %r.1 = insertvalue {double, double} %r.0, double %fadd.1, 1
  ret {double, double} %r.1
}

; External use of a single lane.
define double @add_ext_use_one_lane(ptr %src, ptr %dst) {
; CHECK-LABEL: define double @add_ext_use_one_lane(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x double>, ptr [[SRC]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = fadd <2 x double> [[TMP0]], [[TMP0]]
; CHECK-NEXT:    store <2 x double> [[TMP1]], ptr [[DST]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x double> [[TMP1]], i32 0
; CHECK-NEXT:    ret double [[TMP2]]
;
entry:
  %src.0 = load double, ptr %src, align 8
  %src.gep.1 = getelementptr double, ptr %src, i64 1
  %src.1 = load double, ptr %src.gep.1, align 8
  %fadd.0 = fadd double %src.0, %src.0
  %fadd.1 = fadd double %src.1, %src.1
  store double %fadd.0, ptr %dst, align 8
  %dst.gep.1 = getelementptr double, ptr %dst, i64 1
  store double %fadd.1, ptr %dst.gep.1, align 8
  ret double %fadd.0
}
