; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck --check-prefixes=CHECK,LEGACY %s
; RUN: opt -passes=slp-vectorizer -slp-use-vplan-codegen -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck --check-prefixes=CHECK,VPLAN %s

; Gather entries whose scalars are extractelements of one or two vectors are
; materialized with a single shufflevector of those vectors, rather than one
; insertelement per lane. Both codegen paths must agree.

define <2 x double> @gather_from_one_wide_vector(<8 x double> %v) {
; CHECK-LABEL: define <2 x double> @gather_from_one_wide_vector(
; CHECK-SAME: <8 x double> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x double> [[V]], <8 x double> poison, <2 x i32> <i32 1, i32 2>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x double> [[V]], <8 x double> poison, <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP3:%.*]] = fadd <2 x double> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    ret <2 x double> [[TMP3]]
;
  %e1 = extractelement <8 x double> %v, i64 1
  %e2 = extractelement <8 x double> %v, i64 2
  %e0 = extractelement <8 x double> %v, i64 0
  %e3 = extractelement <8 x double> %v, i64 3
  %a0 = fadd double %e1, %e0
  %a1 = fadd double %e2, %e3
  %r0 = insertelement <2 x double> poison, double %a0, i64 0
  %r1 = insertelement <2 x double> %r0, double %a1, i64 1
  ret <2 x double> %r1
}

; Every lane is the same extractelement, so the gather is a splat of a lane of
; the source vector.
define <2 x double> @splat_of_extract(<8 x double> %v) {
; CHECK-LABEL: define <2 x double> @splat_of_extract(
; CHECK-SAME: <8 x double> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x double> [[V]], <8 x double> poison, <2 x i32> <i32 3, i32 3>
; CHECK-NEXT:    [[TMP2:%.*]] = fadd <2 x double> [[TMP1]], <double 1.000000e+00, double 2.000000e+00>
; CHECK-NEXT:    ret <2 x double> [[TMP2]]
;
  %e = extractelement <8 x double> %v, i64 3
  %a0 = fadd double %e, 1.000000e+00
  %a1 = fadd double %e, 2.000000e+00
  %r0 = insertelement <2 x double> poison, double %a0, i64 0
  %r1 = insertelement <2 x double> %r0, double %a1, i64 1
  ret <2 x double> %r1
}

; Both gathers draw their lanes from two source vectors.
define <2 x double> @gather_from_two_vectors(<4 x double> %a, <4 x double> %b) {
; CHECK-LABEL: define <2 x double> @gather_from_two_vectors(
; CHECK-SAME: <4 x double> [[A:%.*]], <4 x double> [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x double> [[A]], <4 x double> [[B]], <2 x i32> <i32 1, i32 6>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x double> [[A]], <4 x double> [[B]], <2 x i32> <i32 3, i32 4>
; CHECK-NEXT:    [[TMP3:%.*]] = fmul <2 x double> [[TMP1]], [[TMP2]]
; CHECK-NEXT:    ret <2 x double> [[TMP3]]
;
  %e0 = extractelement <4 x double> %a, i64 1
  %e1 = extractelement <4 x double> %b, i64 2
  %f0 = extractelement <4 x double> %a, i64 3
  %f1 = extractelement <4 x double> %b, i64 0
  %m0 = fmul double %e0, %f0
  %m1 = fmul double %e1, %f1
  %r0 = insertelement <2 x double> poison, double %m0, i64 0
  %r1 = insertelement <2 x double> %r0, double %m1, i64 1
  ret <2 x double> %r1
}

; All lanes extracted from a single vector of the same width, in order: the
; source vector already provides all lanes and no shuffle is needed.
define <2 x double> @gather_is_identity(<2 x double> %v) {
; CHECK-LABEL: define <2 x double> @gather_is_identity(
; CHECK-SAME: <2 x double> [[V:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = fadd <2 x double> [[V]], <double 1.000000e+00, double 2.000000e+00>
; CHECK-NEXT:    ret <2 x double> [[TMP1]]
;
  %e0 = extractelement <2 x double> %v, i64 0
  %e1 = extractelement <2 x double> %v, i64 1
  %a0 = fadd double %e0, 1.000000e+00
  %a1 = fadd double %e1, 2.000000e+00
  %r0 = insertelement <2 x double> poison, double %a0, i64 0
  %r1 = insertelement <2 x double> %r0, double %a1, i64 1
  ret <2 x double> %r1
}

; More than two source vectors: shuffle the two providing the most lanes and
; insert the rest.
define void @gather_from_four_vectors(ptr %dst, <8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d, <4 x i16> %m) {
; CHECK-LABEL: define void @gather_from_four_vectors(
; CHECK-SAME: ptr [[DST:%.*]], <8 x i16> [[A:%.*]], <8 x i16> [[B:%.*]], <8 x i16> [[C:%.*]], <8 x i16> [[D:%.*]], <4 x i16> [[M:%.*]]) {
; CHECK-NEXT:    [[E2:%.*]] = extractelement <8 x i16> [[C]], i64 0
; CHECK-NEXT:    [[E3:%.*]] = extractelement <8 x i16> [[D]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> [[B]], <4 x i32> <i32 0, i32 8, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i16> [[TMP1]], i16 [[E2]], i64 2
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x i16> [[TMP2]], i16 [[E3]], i64 3
; CHECK-NEXT:    [[TMP4:%.*]] = add <4 x i16> [[TMP3]], [[M]]
; CHECK-NEXT:    store <4 x i16> [[TMP4]], ptr [[DST]], align 2
; CHECK-NEXT:    ret void
;
  %e0 = extractelement <8 x i16> %a, i64 0
  %e1 = extractelement <8 x i16> %b, i64 0
  %e2 = extractelement <8 x i16> %c, i64 0
  %e3 = extractelement <8 x i16> %d, i64 0
  %m0 = extractelement <4 x i16> %m, i64 0
  %m1 = extractelement <4 x i16> %m, i64 1
  %m2 = extractelement <4 x i16> %m, i64 2
  %m3 = extractelement <4 x i16> %m, i64 3
  %r0 = add i16 %e0, %m0
  %r1 = add i16 %e1, %m1
  %r2 = add i16 %e2, %m2
  %r3 = add i16 %e3, %m3
  %g1 = getelementptr i16, ptr %dst, i64 1
  %g2 = getelementptr i16, ptr %dst, i64 2
  %g3 = getelementptr i16, ptr %dst, i64 3
  store i16 %r0, ptr %dst, align 2
  store i16 %r1, ptr %g1, align 2
  store i16 %r2, ptr %g2, align 2
  store i16 %r3, ptr %g3, align 2
  ret void
}

; Only some lanes are extracts; the others are inserted into the shuffle.
define void @gather_mixed_extract_and_scalar(ptr %dst, <8 x i16> %a, i16 %x, i16 %y, <4 x i16> %m) {
; CHECK-LABEL: define void @gather_mixed_extract_and_scalar(
; CHECK-SAME: ptr [[DST:%.*]], <8 x i16> [[A:%.*]], i16 [[X:%.*]], i16 [[Y:%.*]], <4 x i16> [[M:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 3, i32 poison, i32 5, i32 poison>
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i16> [[TMP1]], i16 [[X]], i64 1
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x i16> [[TMP2]], i16 [[Y]], i64 3
; CHECK-NEXT:    [[TMP4:%.*]] = add <4 x i16> [[TMP3]], [[M]]
; CHECK-NEXT:    store <4 x i16> [[TMP4]], ptr [[DST]], align 2
; CHECK-NEXT:    ret void
;
  %e0 = extractelement <8 x i16> %a, i64 3
  %e1 = extractelement <8 x i16> %a, i64 5
  %m0 = extractelement <4 x i16> %m, i64 0
  %m1 = extractelement <4 x i16> %m, i64 1
  %m2 = extractelement <4 x i16> %m, i64 2
  %m3 = extractelement <4 x i16> %m, i64 3
  %r0 = add i16 %e0, %m0
  %r1 = add i16 %x, %m1
  %r2 = add i16 %e1, %m2
  %r3 = add i16 %y, %m3
  %g1 = getelementptr i16, ptr %dst, i64 1
  %g2 = getelementptr i16, ptr %dst, i64 2
  %g3 = getelementptr i16, ptr %dst, i64 3
  store i16 %r0, ptr %dst, align 2
  store i16 %r1, ptr %g1, align 2
  store i16 %r2, ptr %g2, align 2
  store i16 %r3, ptr %g3, align 2
  ret void
}

; %a provides two lanes and %b and %c one each, so %a and %b are shuffled and
; the %c lane is inserted. The shuffle operands are ordered by the first lane
; they provide, so %b comes first.
define void @gather_picks_most_covering_sources(ptr %dst, <8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <4 x i16> %m) {
; CHECK-LABEL: define void @gather_picks_most_covering_sources(
; CHECK-SAME: ptr [[DST:%.*]], <8 x i16> [[A:%.*]], <8 x i16> [[B:%.*]], <8 x i16> [[C:%.*]], <4 x i16> [[M:%.*]]) {
; CHECK-NEXT:    [[E2:%.*]] = extractelement <8 x i16> [[C]], i64 3
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[B]], <8 x i16> [[A]], <4 x i32> <i32 1, i32 10, i32 poison, i32 12>
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i16> [[TMP1]], i16 [[E2]], i64 2
; CHECK-NEXT:    [[TMP3:%.*]] = add <4 x i16> [[TMP2]], [[M]]
; CHECK-NEXT:    store <4 x i16> [[TMP3]], ptr [[DST]], align 2
; CHECK-NEXT:    ret void
;
  %e0 = extractelement <8 x i16> %b, i64 1
  %e1 = extractelement <8 x i16> %a, i64 2
  %e2 = extractelement <8 x i16> %c, i64 3
  %e3 = extractelement <8 x i16> %a, i64 4
  %m0 = extractelement <4 x i16> %m, i64 0
  %m1 = extractelement <4 x i16> %m, i64 1
  %m2 = extractelement <4 x i16> %m, i64 2
  %m3 = extractelement <4 x i16> %m, i64 3
  %r0 = add i16 %e0, %m0
  %r1 = add i16 %e1, %m1
  %r2 = add i16 %e2, %m2
  %r3 = add i16 %e3, %m3
  %g1 = getelementptr i16, ptr %dst, i64 1
  %g2 = getelementptr i16, ptr %dst, i64 2
  %g3 = getelementptr i16, ptr %dst, i64 3
  store i16 %r0, ptr %dst, align 2
  store i16 %r1, ptr %g1, align 2
  store i16 %r2, ptr %g2, align 2
  store i16 %r3, ptr %g3, align 2
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; LEGACY: {{.*}}
; VPLAN: {{.*}}
