; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=slp-vectorizer -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s
; RUN: opt -passes=slp-vectorizer -slp-use-vplan-codegen -S -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @fadd_store(ptr %src, ptr %dst) {
; CHECK-LABEL: define void @fadd_store(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SRC_GEP_2:%.*]] = getelementptr double, ptr [[SRC]], i64 2
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x double>, ptr [[SRC]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = fadd <2 x double> [[TMP0]], [[TMP0]]
; CHECK-NEXT:    [[DST_GEP_2:%.*]] = getelementptr double, ptr [[DST]], i64 2
; CHECK-NEXT:    [[TMP2:%.*]] = load <2 x double>, ptr [[SRC_GEP_2]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = fadd <2 x double> [[TMP2]], [[TMP2]]
; CHECK-NEXT:    store <2 x double> [[TMP1]], ptr [[DST]], align 8
; CHECK-NEXT:    store <2 x double> [[TMP3]], ptr [[DST_GEP_2]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %src.0 = load double, ptr %src, align 8
  %src.gep.1 = getelementptr double, ptr %src, i64 1
  %src.1 = load double, ptr %src.gep.1, align 8
  %src.gep.2 = getelementptr double, ptr %src, i64 2
  %src.2 = load double, ptr %src.gep.2, align 8
  %src.gep.3 = getelementptr double, ptr %src, i64 3
  %src.3 = load double, ptr %src.gep.3, align 8
  %fadd.0 = fadd double %src.0, %src.0
  %fadd.1 = fadd double %src.1, %src.1
  %fadd.2 = fadd double %src.2, %src.2
  %fadd.3 = fadd double %src.3, %src.3
  store double %fadd.0, ptr %dst, align 8
  %dst.gep.1 = getelementptr double, ptr %dst, i64 1
  store double %fadd.1, ptr %dst.gep.1, align 8
  %dst.gep.2 = getelementptr double, ptr %dst, i64 2
  store double %fadd.2, ptr %dst.gep.2, align 8
  %dst.gep.3 = getelementptr double, ptr %dst, i64 3
  store double %fadd.3, ptr %dst.gep.3, align 8
  ret void
}

define void @add_store(ptr %src, ptr %dst) {
; CHECK-LABEL: define void @add_store(
; CHECK-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i32>, ptr [[SRC]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = add <4 x i32> [[TMP0]], [[TMP0]]
; CHECK-NEXT:    store <4 x i32> [[TMP1]], ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %src.0 = load i32, ptr %src, align 4
  %src.gep.1 = getelementptr i32, ptr %src, i64 1
  %src.1 = load i32, ptr %src.gep.1, align 4
  %src.gep.2 = getelementptr i32, ptr %src, i64 2
  %src.2 = load i32, ptr %src.gep.2, align 4
  %src.gep.3 = getelementptr i32, ptr %src, i64 3
  %src.3 = load i32, ptr %src.gep.3, align 4
  %add.0 = add i32 %src.0, %src.0
  %add.1 = add i32 %src.1, %src.1
  %add.2 = add i32 %src.2, %src.2
  %add.3 = add i32 %src.3, %src.3
  store i32 %add.0, ptr %dst, align 4
  %dst.gep.1 = getelementptr i32, ptr %dst, i64 1
  store i32 %add.1, ptr %dst.gep.1, align 4
  %dst.gep.2 = getelementptr i32, ptr %dst, i64 2
  store i32 %add.2, ptr %dst.gep.2, align 4
  %dst.gep.3 = getelementptr i32, ptr %dst, i64 3
  store i32 %add.3, ptr %dst.gep.3, align 4
  ret void
}

define void @fmul_store(ptr %src1, ptr %src2, ptr %dst) {
; CHECK-LABEL: define void @fmul_store(
; CHECK-SAME: ptr [[SRC1:%.*]], ptr [[SRC2:%.*]], ptr [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[WIDE_LOAD1:%.*]] = load <4 x float>, ptr [[SRC1]], align 4
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x float>, ptr [[SRC2]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = fmul <4 x float> [[WIDE_LOAD1]], [[WIDE_LOAD]]
; CHECK-NEXT:    store <4 x float> [[TMP0]], ptr [[DST]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %s1.0 = load float, ptr %src1, align 4
  %s1.gep.1 = getelementptr float, ptr %src1, i64 1
  %s1.1 = load float, ptr %s1.gep.1, align 4
  %s1.gep.2 = getelementptr float, ptr %src1, i64 2
  %s1.2 = load float, ptr %s1.gep.2, align 4
  %s1.gep.3 = getelementptr float, ptr %src1, i64 3
  %s1.3 = load float, ptr %s1.gep.3, align 4
  %s2.0 = load float, ptr %src2, align 4
  %s2.gep.1 = getelementptr float, ptr %src2, i64 1
  %s2.1 = load float, ptr %s2.gep.1, align 4
  %s2.gep.2 = getelementptr float, ptr %src2, i64 2
  %s2.2 = load float, ptr %s2.gep.2, align 4
  %s2.gep.3 = getelementptr float, ptr %src2, i64 3
  %s2.3 = load float, ptr %s2.gep.3, align 4
  %fmul.0 = fmul float %s1.0, %s2.0
  %fmul.1 = fmul float %s1.1, %s2.1
  %fmul.2 = fmul float %s1.2, %s2.2
  %fmul.3 = fmul float %s1.3, %s2.3
  store float %fmul.0, ptr %dst, align 4
  %dst.gep.1 = getelementptr float, ptr %dst, i64 1
  store float %fmul.1, ptr %dst.gep.1, align 4
  %dst.gep.2 = getelementptr float, ptr %dst, i64 2
  store float %fmul.2, ptr %dst.gep.2, align 4
  %dst.gep.3 = getelementptr float, ptr %dst, i64 3
  store float %fmul.3, ptr %dst.gep.3, align 4
  ret void
}
