; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=inline -S < %s | FileCheck %s

; When a callee promises a pointer parameter is `dereferenceable(N)`, inlining
; preserves that guarantee at the (now inlined) call site as an `llvm.assume`
; operand bundle, carrying the parameter's alignment along in the same bundle.
; This keeps accessor-style loads speculatable after the accessor is inlined
; away. See AddDereferenceableAssumptions in InlineFunction.cpp.

; Address space 200 has 128-bit pointers, wider than the i64 the assume
; bundle's size operand must be.
target datalayout = "e-p200:128:128:128"

; Positive: plain `dereferenceable` + `align` is preserved.
define float @callee_deref(ptr dereferenceable(12) align 4 %p) {
; CHECK-LABEL: define float @callee_deref(
; CHECK-SAME: ptr align 4 dereferenceable(12) [[P:%.*]]) {
; CHECK-NEXT:    [[G:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 8
; CHECK-NEXT:    [[V:%.*]] = load float, ptr [[G]], align 4
; CHECK-NEXT:    ret float [[V]]
;
  %g = getelementptr inbounds i8, ptr %p, i64 8
  %v = load float, ptr %g, align 4
  ret float %v
}

define float @caller_deref(ptr %p) {
; CHECK-LABEL: define float @caller_deref(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[P]], i64 12), "align"(ptr [[P]], i64 4) ]
; CHECK-NEXT:    [[G_I:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 8
; CHECK-NEXT:    [[V_I:%.*]] = load float, ptr [[G_I]], align 4
; CHECK-NEXT:    ret float [[V_I]]
;
  %r = call float @callee_deref(ptr dereferenceable(12) align 4 %p)
  ret float %r
}

; Negative: `dereferenceable_or_null` is NOT preserved (the pointer may be null,
; so it is not safe to speculate a load from it).
define float @callee_deref_or_null(ptr dereferenceable_or_null(12) align 4 %p) {
; CHECK-LABEL: define float @callee_deref_or_null(
; CHECK-SAME: ptr align 4 dereferenceable_or_null(12) [[P:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = load float, ptr [[P]], align 4
; CHECK-NEXT:    ret float [[V]]
;
  %v = load float, ptr %p, align 4
  ret float %v
}

define float @caller_deref_or_null(ptr %p) {
; CHECK-LABEL: define float @caller_deref_or_null(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[V_I:%.*]] = load float, ptr [[P]], align 4
; CHECK-NEXT:    ret float [[V_I]]
;
  %r = call float @callee_deref_or_null(ptr dereferenceable_or_null(12) align 4 %p)
  ret float %r
}

; Negative: a byval argument's dereferenceability describes the callee's private
; copy, so it must NOT be turned into an assume on the caller's pointer.
define float @callee_byval(ptr byval(i32) dereferenceable(4) %p) {
; CHECK-LABEL: define float @callee_byval(
; CHECK-SAME: ptr byval(i32) dereferenceable(4) [[P:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = load float, ptr [[P]], align 4
; CHECK-NEXT:    ret float [[V]]
;
  %v = load float, ptr %p, align 4
  ret float %v
}

define float @caller_byval(ptr %p) {
; CHECK-LABEL: define float @caller_byval(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[P1:%.*]] = alloca i32, align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[P1]])
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[P1]], ptr [[P]], i64 4, i1 false)
; CHECK-NEXT:    [[V_I:%.*]] = load float, ptr [[P1]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[P1]])
; CHECK-NEXT:    ret float [[V_I]]
;
  %r = call float @callee_byval(ptr byval(i32) %p)
  ret float %r
}

; Negative: if the caller can already prove the dereferenceable fact (the caller
; arg already carries a large enough `dereferenceable` attribute), no redundant
; assume is added.
define float @caller_already_known(ptr dereferenceable(16) align 4 %p) {
; CHECK-LABEL: define float @caller_already_known(
; CHECK-SAME: ptr align 4 dereferenceable(16) [[P:%.*]]) {
; CHECK-NEXT:    [[G_I:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 8
; CHECK-NEXT:    [[V_I:%.*]] = load float, ptr [[G_I]], align 4
; CHECK-NEXT:    ret float [[V_I]]
;
  %r = call float @callee_deref(ptr dereferenceable(12) align 4 %p)
  ret float %r
}

; Positive: on targets with pointers wider than 64 bits, the dereferenceable
; assume bundle's size operand must still be an i64 (the verifier rejects
; integer operands wider than 64 bits). Make sure inlining a callee with a
; `dereferenceable` parameter in such an address space produces valid IR.
define i8 @callee_wide_ptr(ptr addrspace(200) dereferenceable(16) %p) {
; CHECK-LABEL: define i8 @callee_wide_ptr(
; CHECK-SAME: ptr addrspace(200) dereferenceable(16) [[P:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = load i8, ptr addrspace(200) [[P]], align 1
; CHECK-NEXT:    ret i8 [[V]]
;
  %v = load i8, ptr addrspace(200) %p
  ret i8 %v
}

define i8 @caller_wide_ptr(ptr addrspace(200) %p) {
; CHECK-LABEL: define i8 @caller_wide_ptr(
; CHECK-SAME: ptr addrspace(200) [[P:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr addrspace(200) [[P]], i64 16) ]
; CHECK-NEXT:    [[V_I:%.*]] = load i8, ptr addrspace(200) [[P]], align 1
; CHECK-NEXT:    ret i8 [[V_I]]
;
  %r = call i8 @callee_wide_ptr(ptr addrspace(200) dereferenceable(16) %p)
  ret i8 %r
}
