; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -loop-reduce < %s | FileCheck %s

target datalayout = "e-p:64:64:64-n32:64"

; Pointer IV with a complex start value (GEP chain).
; The SCEVUse mechanism should help preserve nuw on the start GEP.
define void @ptr_iv_complex_start(ptr %base, i64 %off, i64 %len) {
; CHECK-LABEL: @ptr_iv_complex_start(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[OFF:%.*]], 20
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr nuw i8, ptr [[BASE:%.*]], i64 [[TMP0]]
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[LSR_IV2:%.*]] = phi i64 [ [[LSR_IV_NEXT:%.*]], [[LOOP]] ], [ [[LEN:%.*]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi ptr [ [[SCEVGEP1:%.*]], [[LOOP]] ], [ [[SCEVGEP]], [[ENTRY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = load volatile i32, ptr [[LSR_IV]], align 4
; CHECK-NEXT:    [[SCEVGEP1]] = getelementptr nuw i8, ptr [[LSR_IV]], i64 4
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i64 [[LSR_IV2]], -1
; CHECK-NEXT:    [[C:%.*]] = icmp ne i64 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %gep1 = getelementptr i8, ptr %base, i64 %off
  %gep2 = getelementptr i8, ptr %gep1, i64 16
  br label %loop

loop:
  %p = phi ptr [ %gep2, %entry ], [ %p.next, %loop ]
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %p.next = getelementptr nuw i8, ptr %p, i64 4
  %i.next = add nuw i64 %i, 1
  load volatile i32, ptr %p.next
  %c = icmp ne i64 %i.next, %len
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Pointer IV with a simple start value (argument) - should not be affected.
define void @ptr_iv_simple_start(ptr %p.start, i64 %len) {
; CHECK-LABEL: @ptr_iv_simple_start(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr nuw i8, ptr [[P_START:%.*]], i64 4
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[LSR_IV2:%.*]] = phi i64 [ [[LSR_IV_NEXT:%.*]], [[LOOP]] ], [ [[LEN:%.*]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi ptr [ [[SCEVGEP1:%.*]], [[LOOP]] ], [ [[SCEVGEP]], [[ENTRY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load volatile i32, ptr [[LSR_IV]], align 4
; CHECK-NEXT:    [[SCEVGEP1]] = getelementptr nuw i8, ptr [[LSR_IV]], i64 4
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i64 [[LSR_IV2]], -1
; CHECK-NEXT:    [[C:%.*]] = icmp ne i64 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %p = phi ptr [ %p.start, %entry ], [ %p.next, %loop ]
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %p.next = getelementptr nuw i8, ptr %p, i64 4
  %i.next = add nuw i64 %i, 1
  load volatile i32, ptr %p.next
  %c = icmp ne i64 %i.next, %len
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; Integer IV - should not be affected by the pointer localization.
define void @int_iv_not_affected(ptr %base, i64 %len) {
; CHECK-LABEL: @int_iv_not_affected(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[LSR_IV1:%.*]] = phi ptr [ [[SCEVGEP:%.*]], [[LOOP]] ], [ [[BASE:%.*]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i64 [ [[LSR_IV_NEXT:%.*]], [[LOOP]] ], [ [[LEN:%.*]], [[ENTRY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load volatile i32, ptr [[LSR_IV1]], align 4
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i64 [[LSR_IV]], -1
; CHECK-NEXT:    [[SCEVGEP]] = getelementptr i8, ptr [[LSR_IV1]], i64 4
; CHECK-NEXT:    [[C:%.*]] = icmp ne i64 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[C]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %p = getelementptr i32, ptr %base, i64 %i
  %i.next = add nuw i64 %i, 1
  load volatile i32, ptr %p
  %c = icmp ne i64 %i.next, %len
  br i1 %c, label %loop, label %exit

exit:
  ret void
}
