; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='print<scalar-evolution>' -disable-output %s 2>&1 | FileCheck %s

; When a loop exits via `icmp slt (k * iv), n` for a constant `k > 0`, the
; exit condition is equivalent to `iv slt (n + k - 1) /s k` (ceildiv).
; ScalarEvolution's trip-count machinery recognizes this for `shl nsw` (see
; @exit_on_shifted_iv below, which produces a clean `((3 + smax) /u 4)` BTC),
; but not for a plain `mul iv, 3` where the <nsw> flag is missing -- even
; though the IV is {0,+,1}<nuw><nsw> so the mul result can be proved not to
; wrap for any reachable iteration, and trip count is representable.
;
; @exit_on_scaled_iv shows the gap: `Unpredictable backedge-taken count`.

define void @exit_on_scaled_iv(i32 %n) {
; CHECK-LABEL: 'exit_on_scaled_iv'
; CHECK-NEXT:  Classifying expressions for: @exit_on_scaled_iv
; CHECK-NEXT:    %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,-2147483648) S: [0,-2147483648) Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %iv3 = mul i32 %iv, 3
; CHECK-NEXT:    --> {0,+,3}<%loop> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %iv.next = add nuw nsw i32 %iv, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><%loop> U: [1,0) S: [1,0) Exits: <<Unknown>> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @exit_on_scaled_iv
; CHECK-NEXT:  Loop %loop: Unpredictable backedge-taken count.
; CHECK-NEXT:  Loop %loop: Unpredictable constant max backedge-taken count.
; CHECK-NEXT:  Loop %loop: Unpredictable symbolic max backedge-taken count.
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %iv3 = mul i32 %iv, 3
  %c = icmp slt i32 %iv3, %n
  %iv.next = add nuw nsw i32 %iv, 1
  br i1 %c, label %loop, label %exit

exit:
  ret void
}

; shl form of the same pattern (iv << 2 < n). This case *is* handled --
; `shl nsw` is treated like a `mul nsw` by a constant power of two in the
; AddRec path, so the BTC is computable. Included as a reference point for
; contrast with @exit_on_scaled_iv.
define void @exit_on_shifted_iv(i32 %n) {
; CHECK-LABEL: 'exit_on_shifted_iv'
; CHECK-NEXT:  Classifying expressions for: @exit_on_shifted_iv
; CHECK-NEXT:    %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,536870912) S: [0,536870912) Exits: ((3 + (0 smax %n))<nuw> /u 4) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %iv4 = shl nsw i32 %iv, 2
; CHECK-NEXT:    --> {0,+,4}<nuw><nsw><%loop> U: [0,2147483645) S: [0,2147483645) Exits: (4 * ((3 + (0 smax %n))<nuw> /u 4))<nuw> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %iv.next = add nuw nsw i32 %iv, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,536870913) S: [1,536870913) Exits: (1 + ((3 + (0 smax %n))<nuw> /u 4))<nuw><nsw> LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @exit_on_shifted_iv
; CHECK-NEXT:  Loop %loop: backedge-taken count is ((3 + (0 smax %n))<nuw> /u 4)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 536870911
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is ((3 + (0 smax %n))<nuw> /u 4)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %iv4 = shl nsw i32 %iv, 2
  %c = icmp slt i32 %iv4, %n
  %iv.next = add nuw nsw i32 %iv, 1
  br i1 %c, label %loop, label %exit

exit:
  ret void
}
