; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=indvars -S < %s | FileCheck %s

target datalayout = "e-m:e-i64:64-n32:64-S128"

declare void @llvm.assume(i1)
declare void @use(i1)

; %d is the 3-operand SCEVAddExpr
;   ((64 * %c)<nuw><nsw> + (1024 * %b)<nuw><nsw> + (65536 * %a)<nsw>)<nsw>
; whose value range is [-114688,-32831), i.e. it is always negative, so
; %i <s %d must not be folded to true for %i in [0,3]. The assume only serves
; to give isImpliedCond a dominating condition to work from; it says nothing
; about %a, %b, %c or %d.
define void @nary_add_negative_operand(ptr %base, i64 range(i64 -2, 0) %a, i64 range(i64 16, 32) %b, i64 range(i64 0, 16) %c, i64 %p, i64 %q) {
; CHECK-LABEL: define void @nary_add_negative_operand(
; CHECK-SAME: ptr [[BASE:%.*]], i64 range(i64 -2, 0) [[A:%.*]], i64 range(i64 16, 32) [[B:%.*]], i64 range(i64 0, 16) [[C:%.*]], i64 [[P:%.*]], i64 [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[G:%.*]] = icmp slt i64 [[P]], [[Q]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[G]])
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [64 x [16 x [16 x i32]]], ptr [[BASE]], i64 [[A]], i64 [[B]], i64 [[C]]
; CHECK-NEXT:    store i32 0, ptr [[GEP]], align 4
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[I_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %g = icmp slt i64 %p, %q
  call void @llvm.assume(i1 %g)
  %gep = getelementptr inbounds [64 x [16 x [16 x i32]]], ptr %base, i64 %a, i64 %b, i64 %c
  store i32 0, ptr %gep, align 4
  %pi = ptrtoint ptr %gep to i64
  %bi = ptrtoint ptr %base to i64
  %d = sub i64 %pi, %bi
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %cmp = icmp slt i64 %i, %d
  call void @use(i1 %cmp)
  %i.next = add nuw nsw i64 %i, 1
  %ec = icmp slt i64 %i.next, 4
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; Same as above without the assume, which must not change the result.
define void @nary_add_negative_operand_no_assume(ptr %base, i64 range(i64 -2, 0) %a, i64 range(i64 16, 32) %b, i64 range(i64 0, 16) %c) {
; CHECK-LABEL: define void @nary_add_negative_operand_no_assume(
; CHECK-SAME: ptr [[BASE:%.*]], i64 range(i64 -2, 0) [[A:%.*]], i64 range(i64 16, 32) [[B:%.*]], i64 range(i64 0, 16) [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [64 x [16 x [16 x i32]]], ptr [[BASE]], i64 [[A]], i64 [[B]], i64 [[C]]
; CHECK-NEXT:    store i32 0, ptr [[GEP]], align 4
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[I_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %gep = getelementptr inbounds [64 x [16 x [16 x i32]]], ptr %base, i64 %a, i64 %b, i64 %c
  store i32 0, ptr %gep, align 4
  %pi = ptrtoint ptr %gep to i64
  %bi = ptrtoint ptr %base to i64
  %d = sub i64 %pi, %bi
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %cmp = icmp slt i64 %i, %d
  call void @use(i1 %cmp)
  %i.next = add nuw nsw i64 %i, 1
  %ec = icmp slt i64 %i.next, 4
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}
