; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; RUN: opt < %s -S -disable-output "-passes=print<scalar-evolution>" 2>&1 | FileCheck %s

; An outer-loop IV that is advanced by an entire inner loop (with a computable
; backedge-taken count) should be recognized as an add-recurrence of the outer
; loop, using the inner loop's exit value as its step.

; %outer.ptr advances by 8 bytes per inner iteration for %n iterations, so its
; outer step is 8 * %n and it should become {%p,+,(8 * %n)}<%outer>.
define void @outer_ptr_advanced_by_inner(ptr %p, i32 %n, i32 %m) {
; CHECK-LABEL: 'outer_ptr_advanced_by_inner'
; CHECK-NEXT:  Classifying expressions for: @outer_ptr_advanced_by_inner
; CHECK-NEXT:    %guard = and i1 %n.pos, %m.pos
; CHECK-NEXT:    --> (%n.pos umin %m.pos) U: full-set S: full-set
; CHECK-NEXT:    %outer.iv = phi i32 [ 0, %entry ], [ %outer.iv.next, %outer.latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%outer> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %m) LoopDispositions: { %outer: Computable, %inner: Invariant }
; CHECK-NEXT:    %outer.ptr = phi ptr [ %p, %entry ], [ %inner.ptr.next.lcssa, %outer.latch ]
; CHECK-NEXT:    --> {%p,+,(8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw>)<nuw><nsw>}<%outer> U: full-set S: full-set Exits: (((zext i32 (-1 + %m) to i64) * (8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw>)<nuw><nsw>) + %p) LoopDispositions: { %outer: Computable, %inner: Invariant }
; CHECK-NEXT:    %inner.iv = phi i32 [ 0, %outer ], [ %inner.iv.next, %inner ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%inner> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %n) LoopDispositions: { %inner: Computable, %outer: Uniform }
; CHECK-NEXT:    %inner.ptr = phi ptr [ %outer.ptr, %outer ], [ %inner.ptr.next, %inner ]
; CHECK-NEXT:    --> {{\{\{}}%p,+,(8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw>)<nuw><nsw>}<%outer>,+,8}<nuw><%inner> U: full-set S: full-set Exits: {((8 * (zext i32 (-1 + %n) to i64))<nuw><nsw> + %p),+,(8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw>)<nuw><nsw>}<%outer> LoopDispositions: { %inner: Computable, %outer: Variant }
; CHECK-NEXT:    %inner.ptr.next = getelementptr inbounds i8, ptr %inner.ptr, i64 8
; CHECK-NEXT:    --> {{\{\{}}(8 + %p),+,(8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw>)<nuw><nsw>}<%outer>,+,8}<nw><%inner> U: full-set S: full-set Exits: {(8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw> + %p),+,(8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw>)<nuw><nsw>}<%outer> LoopDispositions: { %inner: Computable, %outer: Variant }
; CHECK-NEXT:    %inner.iv.next = add nuw nsw i32 %inner.iv, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%inner> U: [1,-2147483648) S: [1,-2147483648) Exits: %n LoopDispositions: { %inner: Computable, %outer: Uniform }
; CHECK-NEXT:    %inner.ptr.next.lcssa = phi ptr [ %inner.ptr.next, %inner ]
; CHECK-NEXT:    --> {{\{\{}}(8 + %p),+,(8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw>)<nuw><nsw>}<%outer>,+,8}<nw><%inner> U: full-set S: full-set --> {(8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw> + %p),+,(8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw>)<nuw><nsw>}<%outer> U: full-set S: full-set Exits: (8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw> + ((zext i32 (-1 + %m) to i64) * (8 + (8 * (zext i32 (-1 + %n) to i64))<nuw><nsw>)<nuw><nsw>) + %p) LoopDispositions: { %outer: Variant, %inner: Computable }
; CHECK-NEXT:    %outer.iv.next = add nuw nsw i32 %outer.iv, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%outer> U: [1,-2147483648) S: [1,-2147483648) Exits: %m LoopDispositions: { %outer: Computable, %inner: Invariant }
; CHECK-NEXT:  Determining loop execution counts for: @outer_ptr_advanced_by_inner
; CHECK-NEXT:  Loop %inner: backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %inner: constant max backedge-taken count is i32 -2
; CHECK-NEXT:  Loop %inner: symbolic max backedge-taken count is (-1 + %n)
; CHECK-NEXT:  Loop %inner: Trip multiple is 1
; CHECK-NEXT:  Loop %outer: backedge-taken count is (-1 + %m)
; CHECK-NEXT:  Loop %outer: constant max backedge-taken count is i32 -2
; CHECK-NEXT:  Loop %outer: symbolic max backedge-taken count is (-1 + %m)
; CHECK-NEXT:  Loop %outer: Trip multiple is 1
;
entry:
  %n.pos = icmp ne i32 %n, 0
  %m.pos = icmp ne i32 %m, 0
  %guard = and i1 %n.pos, %m.pos
  br i1 %guard, label %outer, label %exit

outer:
  %outer.iv = phi i32 [ 0, %entry ], [ %outer.iv.next, %outer.latch ]
  %outer.ptr = phi ptr [ %p, %entry ], [ %inner.ptr.next.lcssa, %outer.latch ]
  br label %inner

inner:
  %inner.iv = phi i32 [ 0, %outer ], [ %inner.iv.next, %inner ]
  %inner.ptr = phi ptr [ %outer.ptr, %outer ], [ %inner.ptr.next, %inner ]
  store i64 0, ptr %inner.ptr, align 8
  %inner.ptr.next = getelementptr inbounds i8, ptr %inner.ptr, i64 8
  %inner.iv.next = add nuw nsw i32 %inner.iv, 1
  %inner.ec = icmp eq i32 %inner.iv.next, %n
  br i1 %inner.ec, label %outer.latch, label %inner

outer.latch:
  %inner.ptr.next.lcssa = phi ptr [ %inner.ptr.next, %inner ]
  %outer.iv.next = add nuw nsw i32 %outer.iv, 1
  %outer.ec = icmp eq i32 %outer.iv.next, %m
  br i1 %outer.ec, label %exit, label %outer

exit:
  ret void
}

; Negative test: the inner trip count depends on the outer IV (triangular
; loop), so the outer IV's step is not loop-invariant and the outer PHI must
; not be turned into an affine add-recurrence.
define void @triangular_not_affine(ptr %p, i32 %m) {
; CHECK-LABEL: 'triangular_not_affine'
; CHECK-NEXT:  Classifying expressions for: @triangular_not_affine
; CHECK-NEXT:    %outer.iv = phi i32 [ 0, %entry ], [ %outer.iv.next, %outer.latch ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%outer> U: [0,-2147483648) S: [0,-2147483648) Exits: (-1 + %m) LoopDispositions: { %outer: Computable, %inner: Invariant }
; CHECK-NEXT:    %outer.ptr = phi ptr [ %p, %entry ], [ %inner.ptr.next.lcssa, %outer.latch ]
; CHECK-NEXT:    --> %outer.ptr U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %outer: Variant, %inner: Invariant }
; CHECK-NEXT:    %inner.iv = phi i32 [ 0, %outer ], [ %inner.iv.next, %inner ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%inner> U: [0,2147483647) S: [0,2147483647) Exits: {-1,+,1}<nw><%outer> LoopDispositions: { %inner: Computable, %outer: Uniform }
; CHECK-NEXT:    %inner.ptr = phi ptr [ %outer.ptr, %outer ], [ %inner.ptr.next, %inner ]
; CHECK-NEXT:    --> {%outer.ptr,+,8}<nuw><%inner> U: full-set S: full-set Exits: ((8 * (zext i32 {-1,+,1}<nw><%outer> to i64))<nuw><nsw> + %outer.ptr) LoopDispositions: { %inner: Computable, %outer: Variant }
; CHECK-NEXT:    %inner.ptr.next = getelementptr inbounds i8, ptr %inner.ptr, i64 8
; CHECK-NEXT:    --> {(8 + %outer.ptr),+,8}<nw><%inner> U: full-set S: full-set Exits: (8 + (8 * (zext i32 {-1,+,1}<nw><%outer> to i64))<nuw><nsw> + %outer.ptr) LoopDispositions: { %inner: Computable, %outer: Variant }
; CHECK-NEXT:    %inner.iv.next = add nuw nsw i32 %inner.iv, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%inner> U: [1,-2147483648) S: [1,-2147483648) Exits: {0,+,1}<nuw><nsw><%outer> LoopDispositions: { %inner: Computable, %outer: Uniform }
; CHECK-NEXT:    %inner.ptr.next.lcssa = phi ptr [ %inner.ptr.next, %inner ], [ %outer.ptr, %outer ]
; CHECK-NEXT:    --> %inner.ptr.next.lcssa U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %outer: Variant, %inner: Invariant }
; CHECK-NEXT:    %outer.iv.next = add nuw nsw i32 %outer.iv, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%outer> U: [1,-2147483648) S: [1,-2147483648) Exits: %m LoopDispositions: { %outer: Computable, %inner: Invariant }
; CHECK-NEXT:  Determining loop execution counts for: @triangular_not_affine
; CHECK-NEXT:  Loop %inner: backedge-taken count is {-1,+,1}<nw><%outer>
; CHECK-NEXT:  Loop %inner: constant max backedge-taken count is i32 2147483646
; CHECK-NEXT:  Loop %inner: symbolic max backedge-taken count is {-1,+,1}<nw><%outer>
; CHECK-NEXT:  Loop %inner: Trip multiple is 1
; CHECK-NEXT:  Loop %outer: backedge-taken count is (-1 + %m)
; CHECK-NEXT:  Loop %outer: constant max backedge-taken count is i32 -2
; CHECK-NEXT:  Loop %outer: symbolic max backedge-taken count is (-1 + %m)
; CHECK-NEXT:  Loop %outer: Trip multiple is 1
;
entry:
  %m.pos = icmp ne i32 %m, 0
  br i1 %m.pos, label %outer, label %exit

outer:
  %outer.iv = phi i32 [ 0, %entry ], [ %outer.iv.next, %outer.latch ]
  %outer.ptr = phi ptr [ %p, %entry ], [ %inner.ptr.next.lcssa, %outer.latch ]
  %inner.guard = icmp ne i32 %outer.iv, 0
  br i1 %inner.guard, label %inner, label %outer.latch

inner:
  %inner.iv = phi i32 [ 0, %outer ], [ %inner.iv.next, %inner ]
  %inner.ptr = phi ptr [ %outer.ptr, %outer ], [ %inner.ptr.next, %inner ]
  store i64 0, ptr %inner.ptr, align 8
  %inner.ptr.next = getelementptr inbounds i8, ptr %inner.ptr, i64 8
  %inner.iv.next = add nuw nsw i32 %inner.iv, 1
  %inner.ec = icmp eq i32 %inner.iv.next, %outer.iv
  br i1 %inner.ec, label %outer.latch, label %inner

outer.latch:
  %inner.ptr.next.lcssa = phi ptr [ %inner.ptr.next, %inner ], [ %outer.ptr, %outer ]
  %outer.iv.next = add nuw nsw i32 %outer.iv, 1
  %outer.ec = icmp eq i32 %outer.iv.next, %m
  br i1 %outer.ec, label %exit, label %outer

exit:
  ret void
}
