; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='print<scalar-evolution>' -disable-output %s 2>&1 | FileCheck %s

target datalayout = "e-p:64:64-i64:64-n8:16:32:64"

; An integer recurrence plus an invariant pointer is a pointer start.
; Preserve the integer-only restriction when the pointer is outside the AddRec.
define void @pointer_start(ptr %dst, i64 %a, i64 %n, i1 %enter) {
; CHECK-LABEL: 'pointer_start'
; CHECK-NEXT:  Classifying expressions for: @pointer_start
; CHECK-NEXT:    %iv = phi i64 [ %a, %entry ], [ %next, %loop ]
; CHECK-NEXT:    --> {%a,+,1}<nuw><%loop> U: full-set S: full-set Exits: (-1 + %n) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %p = getelementptr nuw i8, ptr %dst, i64 %iv
; CHECK-NEXT:    --> {(%a + %dst),+,1}<nuw><%loop> U: full-set S: full-set Exits: (-1 + %n + %dst) LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %next = add nuw i64 %iv, 1
; CHECK-NEXT:    --> {(1 + %a),+,1}<nuw><%loop> U: full-set S: full-set Exits: %n LoopDispositions: { %loop: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @pointer_start
; CHECK-NEXT:  Loop %loop: backedge-taken count is (-1 + (-1 * %a) + %n)
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i64 -1
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is (-1 + (-1 * %a) + %n)
; CHECK-NEXT:  Loop %loop: Trip multiple is 1
;
entry:
  br i1 %enter, label %loop, label %exit
loop:
  %iv = phi i64 [ %a, %entry ], [ %next, %loop ]
  %p = getelementptr nuw i8, ptr %dst, i64 %iv
  store i8 0, ptr %p
  %next = add nuw i64 %iv, 1
  %done = icmp eq i64 %next, %n
  br i1 %done, label %exit, label %loop
exit:
  ret void
}
