; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='print<scalar-evolution>' -disable-output %s 2>&1 | FileCheck %s

; `X udiv C` folds to 0 when SCEV can prove the unsigned range of X is
; smaller than C. The `X urem C` case falls out of the fallback
; `X - (X udiv C) * C`, which simplifies to X.

define i32 @urem_bounded_iv_nonpow2() {
; CHECK-LABEL: 'urem_bounded_iv_nonpow2'
; CHECK-NEXT:  Classifying expressions for: @urem_bounded_iv_nonpow2
; CHECK-NEXT:    %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,100) S: [0,100) Exits: 99 LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %rem = urem i32 %iv, 200
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,100) S: [0,100) Exits: 99 LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %iv.next = add nuw nsw i32 %iv, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,101) S: [1,101) Exits: 100 LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %r = phi i32 [ %rem, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,100) S: [0,100) --> 99 U: [99,100) S: [99,100)
; CHECK-NEXT:  Determining loop execution counts for: @urem_bounded_iv_nonpow2
; CHECK-NEXT:  Loop %loop: backedge-taken count is i32 99
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 99
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is i32 99
; CHECK-NEXT:  Loop %loop: Trip multiple is 100
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %rem = urem i32 %iv, 200
  %iv.next = add nuw nsw i32 %iv, 1
  %cmp = icmp slt i32 %iv.next, 100
  br i1 %cmp, label %loop, label %exit

exit:
  %r = phi i32 [ %rem, %loop ]
  ret i32 %r
}

; Same situation for udiv: x range in [0, 100), divisor 200 -- result is 0.

define i32 @udiv_bounded_iv_nonpow2() {
; CHECK-LABEL: 'udiv_bounded_iv_nonpow2'
; CHECK-NEXT:  Classifying expressions for: @udiv_bounded_iv_nonpow2
; CHECK-NEXT:    %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
; CHECK-NEXT:    --> {0,+,1}<nuw><nsw><%loop> U: [0,100) S: [0,100) Exits: 99 LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %div = udiv i32 %iv, 200
; CHECK-NEXT:    --> 0 U: [0,1) S: [0,1) Exits: 0 LoopDispositions: { %loop: Invariant }
; CHECK-NEXT:    %iv.next = add nuw nsw i32 %iv, 1
; CHECK-NEXT:    --> {1,+,1}<nuw><nsw><%loop> U: [1,101) S: [1,101) Exits: 100 LoopDispositions: { %loop: Computable }
; CHECK-NEXT:    %r = phi i32 [ %div, %loop ]
; CHECK-NEXT:    --> 0 U: [0,1) S: [0,1)
; CHECK-NEXT:  Determining loop execution counts for: @udiv_bounded_iv_nonpow2
; CHECK-NEXT:  Loop %loop: backedge-taken count is i32 99
; CHECK-NEXT:  Loop %loop: constant max backedge-taken count is i32 99
; CHECK-NEXT:  Loop %loop: symbolic max backedge-taken count is i32 99
; CHECK-NEXT:  Loop %loop: Trip multiple is 100
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %div = udiv i32 %iv, 200
  %iv.next = add nuw nsw i32 %iv, 1
  %cmp = icmp slt i32 %iv.next, 100
  br i1 %cmp, label %loop, label %exit

exit:
  %r = phi i32 [ %div, %loop ]
  ret i32 %r
}
