# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64 -o - %s \
# RUN:   -run-pass dead-machine-loop-elim | FileCheck %s

# Test that a dead read-only inner loop is removed. The inner loop
# (bb.1/bb.2) loads and compares values but no register defined in
# the loop is used outside it.

--- |
  define void @dead_inner_loop(ptr %p, ptr %q) {
    ret void
  }

  define i32 @live_inner_loop(ptr %p) {
    ret i32 0
  }

  define void @dead_inner_loop_with_store(ptr %p, ptr %q) {
    ret void
  }

  define void @dead_three_block_loop(ptr %p, ptr %q) {
    ret void
  }

  define i32 @live_three_block_loop(ptr %p, ptr %q) {
    ret i32 0
  }

  define void @dead_three_block_loop_with_store(ptr %p, ptr %q) {
    ret void
  }

  define i32 @nested_dead_inner_loop(ptr %p, ptr %q) {
    ret i32 0
  }

  define i32 @nested_live_inner_loop(ptr %p, ptr %q) {
    ret i32 0
  }

  define void @volatile_load_loop(ptr %p) {
    ret void
  }

  define i32 @dead_loop_exit_phi(ptr %p) {
    ret i32 0
  }

  define i32 @dead_loop_exit_phi_multiple_preds(ptr %p) {
    ret i32 0
  }

  define i32 @dead_loop_conflicting_exit_phi(ptr %p) {
    ret i32 0
  }
...
---
name:            dead_inner_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_inner_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %6:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %6, %bb.0, %7, %bb.2
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    %4:gpr32 = LDRBBroX %1, %2, 0, 0
    %5:gpr32 = SUBSWrr %3, %4, implicit-def $nzcv
    Bcc 1, %bb.3, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %7:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %2, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    RET_ReallyLR

...
---
# Negative test: the inner loop has a live-out vreg (%2 is used in bb.3).


name:            live_inner_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr32 }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: live_inner_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = PHI [[COPY1]], %bb.0, %3, %bb.2
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[COPY1]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY1]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   $w0 = COPY [[COPY1]].sub_32
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0

    %0:gpr64common = COPY $x0
    %2:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %2, %bb.0, %3, %bb.2
    %1:gpr32 = LDRBBroX %0, %2, 0, 0
    CBNZW %1, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %3:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %2, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    $w0 = COPY %2.sub_32
    RET_ReallyLR

...
---
# Negative test: the inner loop has a store.


name:            dead_inner_loop_with_store
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_inner_loop_with_store
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %4, %bb.2
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[COPY2]], 0, 0
  ; CHECK-NEXT:   STRBBroX [[LDRBBroX]], [[COPY1]], [[COPY2]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY2]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY2]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %2:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %2, %bb.0, %4, %bb.2
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    STRBBroX %3, %1, %2, 0, 0
    CBNZW %3, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %4:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %2, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    RET_ReallyLR

...
---
# Dead three-block inner loop: bb.1 -> bb.2 -> bb.3 form a loop with
# header bb.1. Two exiting blocks (bb.1 and bb.3) both exit to bb.4.
# No values escape.


name:            dead_three_block_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_three_block_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   RET_ReallyLR
  ; bb.1 -> bb.2 -> bb.3 -> bb.1 with exits from bb.1 and bb.3 to bb.4.
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %6:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.4(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %6, %bb.0, %7, %bb.3
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    %4:gpr32 = LDRBBroX %1, %2, 0, 0
    %5:gpr32 = SUBSWrr %3, %4, implicit-def $nzcv
    Bcc 1, %bb.4, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    ; Intermediate block with no exit.
    %7:gpr64sp = ADDXri %2, 1, 0

  bb.3:
    successors: %bb.4(0x10000000), %bb.1(0x70000000)

    dead $xzr = SUBSXri %7, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.4

  bb.4:
    RET_ReallyLR

...
---
# Negative test: three-block inner loop with a live-out vreg.
# %2 is used in bb.4, so the loop must not be deleted.


name:            live_three_block_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: live_three_block_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.3
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[LDRBBroX1:%[0-9]+]]:gpr32 = LDRBBroX [[COPY1]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[SUBSWrr:%[0-9]+]]:gpr32 = SUBSWrr [[LDRBBroX]], [[LDRBBroX1]], implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.4, implicit $nzcv
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI]], 1, 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   $w0 = COPY [[PHI]].sub_32
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %6:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.4(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %6, %bb.0, %7, %bb.3
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    %4:gpr32 = LDRBBroX %1, %2, 0, 0
    %5:gpr32 = SUBSWrr %3, %4, implicit-def $nzcv
    Bcc 1, %bb.4, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    %7:gpr64sp = ADDXri %2, 1, 0

  bb.3:
    successors: %bb.4(0x10000000), %bb.1(0x70000000)

    dead $xzr = SUBSXri %7, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.4

  bb.4:
    ; %2 is live-out.
    $w0 = COPY %2.sub_32
    RET_ReallyLR

...
---
# Negative test: three-block inner loop where one block has a store.


name:            dead_three_block_loop_with_store
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_three_block_loop_with_store
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.3
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[LDRBBroX1:%[0-9]+]]:gpr32 = LDRBBroX [[COPY1]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[SUBSWrr:%[0-9]+]]:gpr32 = SUBSWrr [[LDRBBroX]], [[LDRBBroX1]], implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.4, implicit $nzcv
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI]], 1, 0
  ; CHECK-NEXT:   STRBBui [[LDRBBroX]], [[COPY1]], 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %6:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.4(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %6, %bb.0, %7, %bb.3
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    %4:gpr32 = LDRBBroX %1, %2, 0, 0
    %5:gpr32 = SUBSWrr %3, %4, implicit-def $nzcv
    Bcc 1, %bb.4, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    %7:gpr64sp = ADDXri %2, 1, 0
    STRBBui %3, %1, 0

  bb.3:
    successors: %bb.4(0x10000000), %bb.1(0x70000000)

    dead $xzr = SUBSXri %7, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.4

  bb.4:
    RET_ReallyLR

...
---
# Nested loop: dead inner loop inside a live outer loop.
# The inner loop (bb.3 self-loop) is read-only with no live-outs,
# so it should be removed. bb.2 is the inner loop's preheader.
# The outer loop (bb.1-bb.4) has a live-out (%2 used in bb.5),
# so it must remain.


name:            nested_dead_inner_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64common }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64sp }
  - { id: 7, class: gpr64sp }
  - { id: 8, class: gpr64common }
body:             |
  ; CHECK-LABEL: name: nested_dead_inner_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.4
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.5
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   $w0 = COPY [[PHI]].sub_32
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %8:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.5(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %8, %bb.0, %7, %bb.4
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    CBNZW %3, %bb.5
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    B %bb.3

  bb.3:
    successors: %bb.4(0x10000000), %bb.3(0x70000000)

    %4:gpr64common = PHI %2, %bb.2, %6, %bb.3
    %5:gpr32 = LDRBBroX %1, %4, 0, 0
    %6:gpr64sp = ADDXri %4, 1, 0
    dead $xzr = SUBSXri %6, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.3, implicit $nzcv
    B %bb.4

  bb.4:
    successors: %bb.5(0x10000000), %bb.1(0x70000000)

    %7:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %7, 10, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.5

  bb.5:
    $w0 = COPY %2.sub_32
    RET_ReallyLR

...
---
# Negative test: nested loop where inner loop has a live-out vreg.
# %4 from the inner loop (bb.3) is used in bb.4, so the inner loop
# must not be deleted.


name:            nested_live_inner_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64common }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64sp }
  - { id: 7, class: gpr64sp }
  - { id: 8, class: gpr64common }
body:             |
  ; CHECK-LABEL: name: nested_live_inner_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.4
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.5
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.3(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr64common = PHI [[PHI]], %bb.2, %6, %bb.3
  ; CHECK-NEXT:   [[LDRBBroX1:%[0-9]+]]:gpr32 = LDRBBroX [[COPY1]], [[PHI1]], 0, 0
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.3, implicit $nzcv
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri1:%[0-9]+]]:gpr64sp = ADDXri [[PHI1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri1]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   $w0 = COPY [[PHI]].sub_32
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %8:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.5(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %8, %bb.0, %7, %bb.4
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    CBNZW %3, %bb.5
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    B %bb.3

  bb.3:
    successors: %bb.4(0x10000000), %bb.3(0x70000000)

    %4:gpr64common = PHI %2, %bb.2, %6, %bb.3
    %5:gpr32 = LDRBBroX %1, %4, 0, 0
    %6:gpr64sp = ADDXri %4, 1, 0
    dead $xzr = SUBSXri %6, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.3, implicit $nzcv
    B %bb.4

  bb.4:
    successors: %bb.5(0x10000000), %bb.1(0x70000000)

    ; %4 is live-out from the inner loop.
    %7:gpr64sp = ADDXri %4, 1, 0
    dead $xzr = SUBSXri %7, 10, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.5

  bb.5:
    $w0 = COPY %2.sub_32
    RET_ReallyLR

...
---
# Negative test: loop with a volatile load must not be removed.
# The volatile load is an observable side effect.

name:            volatile_load_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr32 }
body:             |
  ; CHECK-LABEL: name: volatile_load_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LDRWui:%[0-9]+]]:gpr32 = LDRWui [[COPY]], 0 :: (volatile load (s32))
  ; CHECK-NEXT:   CBNZW [[LDRWui]], %bb.1
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0

    %0:gpr64common = COPY $x0

  bb.1:
    successors: %bb.2(0x10000000), %bb.1(0x70000000)

    %1:gpr32 = LDRWui %0, 0 :: (volatile load (s32))
    CBNZW %1, %bb.1
    B %bb.2

  bb.2:
    RET_ReallyLR

...
---
# Test that a dead loop with PHI nodes in the exit block is removed
# correctly, with exit block PHIs updated to reference the preheader.

name:            dead_loop_exit_phi
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr32 }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64sp }
  - { id: 5, class: gpr32 }
body:             |
  ; CHECK-LABEL: name: dead_loop_exit_phi
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $wzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr32 = PHI [[COPY2]], %bb.0
  ; CHECK-NEXT:   $w0 = COPY [[PHI]]
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $xzr
    %5:gpr32 = COPY $wzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %1:gpr64common = PHI %1, %bb.0, %4, %bb.2
    %2:gpr32 = LDRBBroX %0, %1, 0, 0
    CBNZW %2, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %4:gpr64sp = ADDXri %1, 1, 0
    dead $xzr = SUBSXri %1, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    %3:gpr32 = PHI %5, %bb.1, %5, %bb.2
    $w0 = COPY %3
    RET_ReallyLR

...
---
# Test that a dead loop with PHI nodes in the exit block is removed
# correctly when the exit block also has predecessors from outside the loop.

name:            dead_loop_exit_phi_multiple_preds
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr32 }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64sp }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr32 }
body:             |
  ; CHECK-LABEL: name: dead_loop_exit_phi_multiple_preds
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT:   liveins: $x0, $w1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $wzr
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr32 = COPY $w1
  ; CHECK-NEXT:   CBNZW [[COPY3]], %bb.4
  ; CHECK-NEXT:   B %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = PHI [[COPY1]], %bb.0, %4, %bb.2
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[COPY1]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY1]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr32 = PHI [[COPY2]], %bb.1, [[COPY2]], %bb.2
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   $w0 = COPY [[COPY2]]
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x40000000), %bb.4(0x40000000)
    liveins: $x0, $w1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $xzr
    %5:gpr32 = COPY $wzr
    %6:gpr32 = COPY $w1
    CBNZW %6, %bb.4
    B %bb.1

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %1:gpr64common = PHI %1, %bb.0, %4, %bb.2
    %2:gpr32 = LDRBBroX %0, %1, 0, 0
    CBNZW %2, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %4:gpr64sp = ADDXri %1, 1, 0
    dead $xzr = SUBSXri %1, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    successors: %bb.4(0x80000000)

    %3:gpr32 = PHI %5, %bb.1, %5, %bb.2
    B %bb.4

  bb.4:
    $w0 = COPY %5
    RET_ReallyLR

...
---
# Negative test: dead loop where the exit block PHI has conflicting values
# from different loop exits. The pass cannot determine which value to use
# for the preheader, so the loop must not be deleted.
# bb.1 exits to bb.3 with %10 (value A) and bb.2 exits to bb.3 with %11 (value B).

name:            dead_loop_conflicting_exit_phi
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64 }
  - { id: 3, class: gpr64sp }
  - { id: 10, class: gpr64common }
  - { id: 11, class: gpr64common }
body:             |
  ; CHECK-LABEL: name: dead_loop_conflicting_exit_phi
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %3, %bb.2
  ; CHECK-NEXT:   [[LDRXui:%[0-9]+]]:gpr64 = LDRXui [[COPY2]], 0 :: (load (s64))
  ; CHECK-NEXT:   CBZX [[LDRXui]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY2]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY]], %bb.1, [[COPY1]], %bb.2
  ; CHECK-NEXT:   $x0 = COPY [[PHI]]
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %10:gpr64common = COPY $x0
    %11:gpr64common = COPY $x1
    %0:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x04000000), %bb.2(0x7c000000)

    %0:gpr64common = PHI %0, %bb.0, %3, %bb.2
    %2:gpr64 = LDRXui %0, 0 :: (load (s64))
    CBZX %2, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x04000000), %bb.1(0x7c000000)

    %3:gpr64sp = ADDXri %0, 1, 0
    dead $xzr = SUBSXri %3, 10, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    ; PHI with DIFFERENT values from bb.1 (%10) vs bb.2 (%11).
    %1:gpr64common = PHI %10, %bb.1, %11, %bb.2
    $x0 = COPY %1
    RET_ReallyLR

...
