# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64 -o - %s \
# RUN:   -run-pass machine-loop-delete -verify-machine-dom-info | FileCheck %s

# Negative tests: loops that must not be removed due to side effects
# or missing mustprogress.

--- |
  define void @volatile_load_loop(ptr %p) mustprogress {
    ret void
  }

  define void @dead_loop_with_inlineasm(ptr %p) mustprogress {
    ret void
  }

  define void @dead_loop_reserved_physreg(ptr %p) mustprogress {
    ret void
  }

  define void @no_mustprogress_dead_loop(ptr %p, ptr %q) {
    ret void
  }
...
---
# Negative test: loop with a volatile load must not be removed.
# The volatile load is an observable side effect.

name:            volatile_load_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr32 }
body:             |
  ; CHECK-LABEL: name: volatile_load_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LDRWui:%[0-9]+]]:gpr32 = LDRWui [[COPY]], 0 :: (volatile load (s32))
  ; CHECK-NEXT:   CBNZW [[LDRWui]], %bb.1
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0

    %0:gpr64common = COPY $x0

  bb.1:
    successors: %bb.2(0x10000000), %bb.1(0x70000000)

    %1:gpr32 = LDRWui %0, 0 :: (volatile load (s32))
    CBNZW %1, %bb.1
    B %bb.2

  bb.2:
    RET_ReallyLR

...
---
# Negative test: loop contains inline asm (without sideeffect flag).
# Even without the sideeffect flag, inline asm represents explicit user
# intent and should not be removed.

name:            dead_loop_with_inlineasm
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr32 }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_loop_with_inlineasm
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = PHI [[COPY1]], %bb.0, %3, %bb.2
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[COPY1]], 0, 0
  ; CHECK-NEXT:   INLINEASM &nop, 0 /* attdialect */
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY1]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0

    %0:gpr64common = COPY $x0
    %2:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %2, %bb.0, %3, %bb.2
    %1:gpr32 = LDRBBroX %0, %2, 0, 0
    INLINEASM &"nop", 0 /* attdialect */
    CBNZW %1, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %3:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %2, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    RET_ReallyLR

...
---
# Negative test: loop defines a reserved physical register ($sp).
# Reserved registers have implicit global liveness and must not be
# considered dead, even if they don't appear in exit block live-ins.

name:            dead_loop_reserved_physreg
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr32 }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_loop_reserved_physreg
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = PHI [[COPY1]], %bb.0, %3, %bb.2
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[COPY1]], 0, 0
  ; CHECK-NEXT:   $sp = ADDXri $sp, 16, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY1]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0

    %0:gpr64common = COPY $x0
    %2:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %2, %bb.0, %3, %bb.2
    %1:gpr32 = LDRBBroX %0, %2, 0, 0
    $sp = ADDXri $sp, 16, 0
    CBNZW %1, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %3:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %2, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    RET_ReallyLR

...
---
# Negative test: function does not have mustprogress, so the dead loop
# must be preserved (non-termination is observable).

name:            no_mustprogress_dead_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: no_mustprogress_dead_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.2
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[LDRBBroX1:%[0-9]+]]:gpr32 = LDRBBroX [[COPY1]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[SUBSWrr:%[0-9]+]]:gpr32 = SUBSWrr [[LDRBBroX]], [[LDRBBroX1]], implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.3, implicit $nzcv
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[PHI]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %6:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %6, %bb.0, %7, %bb.2
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    %4:gpr32 = LDRBBroX %1, %2, 0, 0
    %5:gpr32 = SUBSWrr %3, %4, implicit-def $nzcv
    Bcc 1, %bb.3, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %7:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %2, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    RET_ReallyLR

...
