# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64 -o - %s \
# RUN:   -run-pass machine-loop-delete -verify-machine-dom-info | FileCheck %s

# Tests for dead machine loop elimination with nested loops.

--- |
  define i32 @nested_dead_inner_loop(ptr %p, ptr %q) mustprogress {
    ret i32 0
  }

  define i32 @nested_live_inner_loop(ptr %p, ptr %q) mustprogress {
    ret i32 0
  }

  define void @nested_both_dead(ptr %p, ptr %q) mustprogress {
    ret void
  }

  define void @nested_two_dead_inner_loops(ptr %p, ptr %q) mustprogress {
    ret void
  }
...
---
# Nested loop: dead inner loop inside a live outer loop.
# The inner loop (bb.3 self-loop) is read-only with no live-outs,
# so it should be removed. bb.2 is the inner loop's preheader.
# The outer loop (bb.1-bb.4) has a live-out (%2 used in bb.5),
# so it must remain.


name:            nested_dead_inner_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64common }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64sp }
  - { id: 7, class: gpr64sp }
  - { id: 8, class: gpr64common }
body:             |
  ; CHECK-LABEL: name: nested_dead_inner_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.4
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.5
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   $w0 = COPY [[PHI]].sub_32
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %8:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.5(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %8, %bb.0, %7, %bb.4
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    CBNZW %3, %bb.5
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    B %bb.3

  bb.3:
    successors: %bb.4(0x10000000), %bb.3(0x70000000)

    %4:gpr64common = PHI %2, %bb.2, %6, %bb.3
    %5:gpr32 = LDRBBroX %1, %4, 0, 0
    %6:gpr64sp = ADDXri %4, 1, 0
    dead $xzr = SUBSXri %6, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.3, implicit $nzcv
    B %bb.4

  bb.4:
    successors: %bb.5(0x10000000), %bb.1(0x70000000)

    %7:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %7, 10, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.5

  bb.5:
    $w0 = COPY %2.sub_32
    RET_ReallyLR

...
---
# Negative test: nested loop where inner loop has a live-out vreg.
# %4 from the inner loop (bb.3) is used in bb.4, so the inner loop
# must not be deleted.


name:            nested_live_inner_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64common }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64sp }
  - { id: 7, class: gpr64sp }
  - { id: 8, class: gpr64common }
body:             |
  ; CHECK-LABEL: name: nested_live_inner_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.4
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.5
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.3(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr64common = PHI [[PHI]], %bb.2, %6, %bb.3
  ; CHECK-NEXT:   [[LDRBBroX1:%[0-9]+]]:gpr32 = LDRBBroX [[COPY1]], [[PHI1]], 0, 0
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.3, implicit $nzcv
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri1:%[0-9]+]]:gpr64sp = ADDXri [[PHI1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri1]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   $w0 = COPY [[PHI]].sub_32
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %8:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.5(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %8, %bb.0, %7, %bb.4
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    CBNZW %3, %bb.5
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    B %bb.3

  bb.3:
    successors: %bb.4(0x10000000), %bb.3(0x70000000)

    %4:gpr64common = PHI %2, %bb.2, %6, %bb.3
    %5:gpr32 = LDRBBroX %1, %4, 0, 0
    %6:gpr64sp = ADDXri %4, 1, 0
    dead $xzr = SUBSXri %6, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.3, implicit $nzcv
    B %bb.4

  bb.4:
    successors: %bb.5(0x10000000), %bb.1(0x70000000)

    ; %4 is live-out from the inner loop.
    %7:gpr64sp = ADDXri %4, 1, 0
    dead $xzr = SUBSXri %7, 10, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.5

  bb.5:
    $w0 = COPY %2.sub_32
    RET_ReallyLR

...
---
# Nested loop where both inner and outer loops are dead (read-only,
# no live-outs). The pass only removes the inner loop because the
# outer loop was not innermost when the worklist was built.
# Structure: bb.0 -> bb.1 (outer header) -> bb.2 (inner preheader)
#            -> bb.3 (inner self-loop) -> bb.4 (outer latch) -> bb.1
# Exit: bb.5.


name:            nested_both_dead
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64common }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64sp }
  - { id: 7, class: gpr64sp }
  - { id: 8, class: gpr64common }
body:             |
  ; CHECK-LABEL: name: nested_both_dead
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.4
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.5
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %8:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.5(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %8, %bb.0, %7, %bb.4
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    CBNZW %3, %bb.5
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    B %bb.3

  bb.3:
    successors: %bb.4(0x10000000), %bb.3(0x70000000)

    %4:gpr64common = PHI %2, %bb.2, %6, %bb.3
    %5:gpr32 = LDRBBroX %1, %4, 0, 0
    %6:gpr64sp = ADDXri %4, 1, 0
    dead $xzr = SUBSXri %6, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.3, implicit $nzcv
    B %bb.4

  bb.4:
    successors: %bb.5(0x10000000), %bb.1(0x70000000)

    %7:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %7, 10, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.5

  bb.5:
    RET_ReallyLR

...
---
# Two dead inner loops inside the same outer loop.
# The outer loop (bb.1-bb.7) is live (%2 used in bb.8).
# Inner loop A (bb.3 self-loop, preheader bb.2) and inner loop B
# (bb.5 self-loop, preheader bb.4) are both read-only with no
# live-outs, so both should be removed.


name:            nested_two_dead_inner_loops
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr64common }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr64sp }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr32 }
  - { id: 8, class: gpr64sp }
  - { id: 9, class: gpr64sp }
  - { id: 10, class: gpr64common }
  - { id: 11, class: gpr32 }
body:             |
  ; CHECK-LABEL: name: nested_two_dead_inner_loops
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.8(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %9, %bb.7
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.8
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   B %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.7(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   B %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.8(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8:
  ; CHECK-NEXT:   $w0 = COPY [[PHI]].sub_32
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %10:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.8(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %10, %bb.0, %9, %bb.7
    %11:gpr32 = LDRBBroX %0, %2, 0, 0
    CBNZW %11, %bb.8
    B %bb.2

  ; Preheader for inner loop A.
  bb.2:
    successors: %bb.3(0x80000000)

    B %bb.3

  ; Inner loop A: self-loop at bb.3, dead read-only.
  bb.3:
    successors: %bb.4(0x10000000), %bb.3(0x70000000)

    %3:gpr64common = PHI %2, %bb.2, %5, %bb.3
    %4:gpr32 = LDRBBroX %1, %3, 0, 0
    %5:gpr64sp = ADDXri %3, 1, 0
    dead $xzr = SUBSXri %5, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.3, implicit $nzcv
    B %bb.4

  ; Preheader for inner loop B.
  bb.4:
    successors: %bb.5(0x80000000)

    B %bb.5

  ; Inner loop B: self-loop at bb.5, dead read-only.
  bb.5:
    successors: %bb.6(0x10000000), %bb.5(0x70000000)

    %6:gpr64common = PHI %2, %bb.4, %8, %bb.5
    %7:gpr32 = LDRBBroX %1, %6, 0, 0
    %8:gpr64sp = ADDXri %6, 1, 0
    dead $xzr = SUBSXri %8, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.5, implicit $nzcv
    B %bb.6

  ; Continuation inside outer loop.
  bb.6:
    successors: %bb.7(0x80000000)

    B %bb.7

  ; Outer latch.
  bb.7:
    successors: %bb.8(0x10000000), %bb.1(0x70000000)

    %9:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %9, 10, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.8

  bb.8:
    $w0 = COPY %2.sub_32
    RET_ReallyLR

...
