# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64 -o - %s \
# RUN:   -run-pass machine-loop-delete -verify-machine-dom-info | FileCheck %s

# Tests for dead machine loop elimination with exit block PHIs and
# debug values.

--- |
  define i32 @dead_loop_exit_phi(ptr %p) mustprogress {
    ret i32 0
  }

  define i32 @dead_loop_exit_phi_multiple_preds(ptr %p) mustprogress {
    ret i32 0
  }

  define i32 @dead_loop_conflicting_exit_phi(ptr %p) mustprogress {
    ret i32 0
  }

  define void @dead_loop_dbg_value_outside(ptr %p) mustprogress !dbg !5 {
    ret void
  }

  !llvm.dbg.cu = !{!0}
  !llvm.module.flags = !{!3, !4}

  !0 = distinct !DICompileUnit(language: DW_LANG_C11, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
  !1 = !DIFile(filename: "test.c", directory: "/tmp")
  !3 = !{i32 7, !"Dwarf Version", i32 5}
  !4 = !{i32 2, !"Debug Info Version", i32 3}
  !5 = distinct !DISubprogram(name: "f", scope: !1, file: !1, line: 1, type: !6, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !8)
  !6 = !DISubroutineType(types: !7)
  !7 = !{null}
  !8 = !{!9}
  !9 = !DILocalVariable(name: "x", scope: !5, file: !1, line: 2, type: !10)
  !10 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
  !11 = !DILocation(line: 2, column: 1, scope: !5)
...
---
# Test that a dead loop with PHI nodes in the exit block is removed
# correctly, with exit block PHIs updated to reference the preheader.

name:            dead_loop_exit_phi
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr32 }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64sp }
  - { id: 5, class: gpr32 }
body:             |
  ; CHECK-LABEL: name: dead_loop_exit_phi
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $wzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr32 = PHI [[COPY2]], %bb.0
  ; CHECK-NEXT:   $w0 = COPY [[PHI]]
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $xzr
    %5:gpr32 = COPY $wzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %1:gpr64common = PHI %1, %bb.0, %4, %bb.2
    %2:gpr32 = LDRBBroX %0, %1, 0, 0
    CBNZW %2, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %4:gpr64sp = ADDXri %1, 1, 0
    dead $xzr = SUBSXri %1, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    %3:gpr32 = PHI %5, %bb.1, %5, %bb.2
    $w0 = COPY %3
    RET_ReallyLR

...
---
# Negative test: the preheader (bb.0) has multiple successors, so
# findLoopPreheader returns nullptr and the loop is not removed.

name:            dead_loop_exit_phi_multiple_preds
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr32 }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64sp }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr32 }
body:             |
  ; CHECK-LABEL: name: dead_loop_exit_phi_multiple_preds
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT:   liveins: $x0, $w1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr32 = COPY $wzr
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr32 = COPY $w1
  ; CHECK-NEXT:   CBNZW [[COPY3]], %bb.4
  ; CHECK-NEXT:   B %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = PHI [[COPY1]], %bb.0, %4, %bb.2
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[COPY1]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY1]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr32 = PHI [[COPY2]], %bb.1, [[COPY2]], %bb.2
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   $w0 = COPY [[COPY2]]
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x40000000), %bb.4(0x40000000)
    liveins: $x0, $w1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $xzr
    %5:gpr32 = COPY $wzr
    %6:gpr32 = COPY $w1
    CBNZW %6, %bb.4
    B %bb.1

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %1:gpr64common = PHI %1, %bb.0, %4, %bb.2
    %2:gpr32 = LDRBBroX %0, %1, 0, 0
    CBNZW %2, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %4:gpr64sp = ADDXri %1, 1, 0
    dead $xzr = SUBSXri %1, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    successors: %bb.4(0x80000000)

    %3:gpr32 = PHI %5, %bb.1, %5, %bb.2
    B %bb.4

  bb.4:
    $w0 = COPY %5
    RET_ReallyLR

...
---
# Negative test: dead loop where the exit block PHI has conflicting values
# from different loop exits. The pass cannot determine which value to use
# for the preheader, so the loop must not be deleted.
# bb.1 exits to bb.3 with %10 (value A) and bb.2 exits to bb.3 with %11 (value B).

name:            dead_loop_conflicting_exit_phi
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64 }
  - { id: 3, class: gpr64sp }
  - { id: 10, class: gpr64common }
  - { id: 11, class: gpr64common }
body:             |
  ; CHECK-LABEL: name: dead_loop_conflicting_exit_phi
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x04000000), %bb.2(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %3, %bb.2
  ; CHECK-NEXT:   [[LDRXui:%[0-9]+]]:gpr64 = LDRXui [[COPY2]], 0 :: (load (s64))
  ; CHECK-NEXT:   CBZX [[LDRXui]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY2]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 10, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY]], %bb.1, [[COPY1]], %bb.2
  ; CHECK-NEXT:   $x0 = COPY [[PHI]]
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %10:gpr64common = COPY $x0
    %11:gpr64common = COPY $x1
    %0:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x04000000), %bb.2(0x7c000000)

    %0:gpr64common = PHI %0, %bb.0, %3, %bb.2
    %2:gpr64 = LDRXui %0, 0 :: (load (s64))
    CBZX %2, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x04000000), %bb.1(0x7c000000)

    %3:gpr64sp = ADDXri %0, 1, 0
    dead $xzr = SUBSXri %3, 10, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    ; PHI with DIFFERENT values from bb.1 (%10) vs bb.2 (%11).
    %1:gpr64common = PHI %10, %bb.1, %11, %bb.2
    $x0 = COPY %1
    RET_ReallyLR

...
---
# Test that debug value references to virtual registers defined inside
# a dead loop are properly undef'd when the loop is removed.

name:            dead_loop_dbg_value_outside
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr32 }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_loop_dbg_value_outside
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   DBG_VALUE $noreg, $noreg, !8, !DIExpression(), debug-location !DILocation(line: 2, column: 1, scope: !4)
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %1:gpr64common = PHI %1, %bb.0, %4, %bb.2
    %2:gpr32 = LDRBBroX %0, %1, 0, 0
    CBNZW %2, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %4:gpr64sp = ADDXri %1, 1, 0
    dead $xzr = SUBSXri %1, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    ; DBG_VALUE references %2 which is defined inside the dead loop.
    DBG_VALUE %2, $noreg, !9, !DIExpression(), debug-location !11
    RET_ReallyLR

...
