# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64 -o - %s \
# RUN:   -run-pass machine-loop-delete -verify-machine-dom-info | FileCheck %s

# Test that a dead read-only inner loop is removed. The inner loop
# (bb.1/bb.2) loads and compares values but no register defined in
# the loop is used outside it.

--- |
  define void @dead_inner_loop(ptr %p, ptr %q) mustprogress {
    ret void
  }

  define i32 @live_inner_loop(ptr %p) mustprogress {
    ret i32 0
  }

  define void @dead_inner_loop_with_store(ptr %p, ptr %q) mustprogress {
    ret void
  }

  define void @dead_three_block_loop(ptr %p, ptr %q) mustprogress {
    ret void
  }

  define i32 @live_three_block_loop(ptr %p, ptr %q) mustprogress {
    ret i32 0
  }

  define void @dead_three_block_loop_with_store(ptr %p, ptr %q) mustprogress {
    ret void
  }
...
---
name:            dead_inner_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_inner_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %6:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %6, %bb.0, %7, %bb.2
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    %4:gpr32 = LDRBBroX %1, %2, 0, 0
    %5:gpr32 = SUBSWrr %3, %4, implicit-def $nzcv
    Bcc 1, %bb.3, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %7:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %2, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    RET_ReallyLR

...
---
# Negative test: the inner loop has a live-out vreg (%2 is used in bb.3).


name:            live_inner_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr32 }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: live_inner_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = PHI [[COPY1]], %bb.0, %3, %bb.2
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[COPY1]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY1]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY1]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   $w0 = COPY [[COPY1]].sub_32
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0

    %0:gpr64common = COPY $x0
    %2:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %2, %bb.0, %3, %bb.2
    %1:gpr32 = LDRBBroX %0, %2, 0, 0
    CBNZW %1, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %3:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %2, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    $w0 = COPY %2.sub_32
    RET_ReallyLR

...
---
# Negative test: the inner loop has a store.


name:            dead_inner_loop_with_store
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_inner_loop_with_store
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %4, %bb.2
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[COPY2]], 0, 0
  ; CHECK-NEXT:   STRBBroX [[LDRBBroX]], [[COPY1]], [[COPY2]], 0, 0
  ; CHECK-NEXT:   CBNZW [[LDRBBroX]], %bb.3
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[COPY2]], 1, 0
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY2]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %2:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.3(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %2, %bb.0, %4, %bb.2
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    STRBBroX %3, %1, %2, 0, 0
    CBNZW %3, %bb.3
    B %bb.2

  bb.2:
    successors: %bb.3(0x10000000), %bb.1(0x70000000)

    %4:gpr64sp = ADDXri %2, 1, 0
    dead $xzr = SUBSXri %2, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.3

  bb.3:
    RET_ReallyLR

...
---
# Dead three-block inner loop: bb.1 -> bb.2 -> bb.3 form a loop with
# header bb.1. Two exiting blocks (bb.1 and bb.3) both exit to bb.4.
# No values escape.


name:            dead_three_block_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_three_block_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   RET_ReallyLR
  ; bb.1 -> bb.2 -> bb.3 -> bb.1 with exits from bb.1 and bb.3 to bb.4.
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %6:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.4(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %6, %bb.0, %7, %bb.3
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    %4:gpr32 = LDRBBroX %1, %2, 0, 0
    %5:gpr32 = SUBSWrr %3, %4, implicit-def $nzcv
    Bcc 1, %bb.4, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    ; Intermediate block with no exit.
    %7:gpr64sp = ADDXri %2, 1, 0

  bb.3:
    successors: %bb.4(0x10000000), %bb.1(0x70000000)

    dead $xzr = SUBSXri %7, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.4

  bb.4:
    RET_ReallyLR

...
---
# Negative test: three-block inner loop with a live-out vreg.
# %2 is used in bb.4, so the loop must not be deleted.


name:            live_three_block_loop
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: live_three_block_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.3
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[LDRBBroX1:%[0-9]+]]:gpr32 = LDRBBroX [[COPY1]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[SUBSWrr:%[0-9]+]]:gpr32 = SUBSWrr [[LDRBBroX]], [[LDRBBroX1]], implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.4, implicit $nzcv
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI]], 1, 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   $w0 = COPY [[PHI]].sub_32
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %6:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.4(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %6, %bb.0, %7, %bb.3
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    %4:gpr32 = LDRBBroX %1, %2, 0, 0
    %5:gpr32 = SUBSWrr %3, %4, implicit-def $nzcv
    Bcc 1, %bb.4, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    %7:gpr64sp = ADDXri %2, 1, 0

  bb.3:
    successors: %bb.4(0x10000000), %bb.1(0x70000000)

    dead $xzr = SUBSXri %7, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.4

  bb.4:
    ; %2 is live-out.
    $w0 = COPY %2.sub_32
    RET_ReallyLR

...
---
# Negative test: three-block inner loop where one block has a store.


name:            dead_three_block_loop_with_store
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr64common }
  - { id: 1, class: gpr64common }
  - { id: 2, class: gpr64common }
  - { id: 3, class: gpr32 }
  - { id: 4, class: gpr32 }
  - { id: 5, class: gpr32 }
  - { id: 6, class: gpr64common }
  - { id: 7, class: gpr64sp }
body:             |
  ; CHECK-LABEL: name: dead_three_block_loop_with_store
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $x0, $x1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64common = COPY $x0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64common = COPY $x1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64common = COPY $xzr
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.2(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64common = PHI [[COPY2]], %bb.0, %7, %bb.3
  ; CHECK-NEXT:   [[LDRBBroX:%[0-9]+]]:gpr32 = LDRBBroX [[COPY]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[LDRBBroX1:%[0-9]+]]:gpr32 = LDRBBroX [[COPY1]], [[PHI]], 0, 0
  ; CHECK-NEXT:   [[SUBSWrr:%[0-9]+]]:gpr32 = SUBSWrr [[LDRBBroX]], [[LDRBBroX1]], implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.4, implicit $nzcv
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[ADDXri:%[0-9]+]]:gpr64sp = ADDXri [[PHI]], 1, 0
  ; CHECK-NEXT:   STRBBui [[LDRBBroX]], [[COPY1]], 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x10000000), %bb.1(0x70000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[ADDXri]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 1, %bb.1, implicit $nzcv
  ; CHECK-NEXT:   B %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   RET_ReallyLR
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $x0, $x1

    %0:gpr64common = COPY $x0
    %1:gpr64common = COPY $x1
    %6:gpr64common = COPY $xzr

  bb.1:
    successors: %bb.4(0x10000000), %bb.2(0x70000000)

    %2:gpr64common = PHI %6, %bb.0, %7, %bb.3
    %3:gpr32 = LDRBBroX %0, %2, 0, 0
    %4:gpr32 = LDRBBroX %1, %2, 0, 0
    %5:gpr32 = SUBSWrr %3, %4, implicit-def $nzcv
    Bcc 1, %bb.4, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.3(0x80000000)

    %7:gpr64sp = ADDXri %2, 1, 0
    STRBBui %3, %1, 0

  bb.3:
    successors: %bb.4(0x10000000), %bb.1(0x70000000)

    dead $xzr = SUBSXri %7, 3, 0, implicit-def $nzcv
    Bcc 1, %bb.1, implicit $nzcv
    B %bb.4

  bb.4:
    RET_ReallyLR

...
