; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='default<O2>' < %s | FileCheck %s
;
; The smin reduction loop is runtime-unrolled. The induction variable needs
; nowrap flags for the unroller to reason about the trip count; those flags are
; now inferred independently of SCEV query order (see the nowrap-flag
; re-inference in ScalarEvolution::getBackedgeTakenInfo), so the loop is
; reliably unrolled by 4 with a reduction tree (llvm.smin.i32 on rdx.minmax).

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx15.0.0"

define i32 @reduce_smin(i32 %dir) #0 {
; CHECK-LABEL: define range(i32 -2147483648, 1) i32 @reduce_smin(
; CHECK-SAME: i32 [[DIR:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[DIR]], 3
; CHECK-NEXT:    br i1 [[TMP0]], label %[[SWITCH_LOOKUP:.*]], label %[[COMMON_RET:.*]]
; CHECK:       [[COMMON_RET_LOOPEXIT_UNR_LCSSA:.*]]:
; CHECK-NEXT:    [[RDX_MINMAX:%.*]] = tail call i32 @llvm.smin.i32(i32 [[COND13:%.*]], i32 [[COND13_1:%.*]])
; CHECK-NEXT:    [[RDX_MINMAX6:%.*]] = tail call i32 @llvm.smin.i32(i32 [[RDX_MINMAX]], i32 [[COND13_2:%.*]])
; CHECK-NEXT:    [[RDX_MINMAX7:%.*]] = tail call i32 @llvm.smin.i32(i32 [[RDX_MINMAX6]], i32 [[COND13_3:%.*]])
; CHECK-NEXT:    [[LCMP_MOD_NOT:%.*]] = icmp eq i64 [[XTRAITER:%.*]], 0
; CHECK-NEXT:    br i1 [[LCMP_MOD_NOT]], label %[[COMMON_RET]], label %[[FOR_BODY_EPIL_PREHEADER:.*]]
; CHECK:       [[FOR_BODY_EPIL_PREHEADER]]:
; CHECK-NEXT:    [[INDVARS_IV_EPIL_INIT:%.*]] = phi i64 [ 0, %[[SWITCH_LOOKUP]] ], [ [[INDVARS_IV_NEXT_3:%.*]], %[[COMMON_RET_LOOPEXIT_UNR_LCSSA]] ]
; CHECK-NEXT:    [[MY_MIN_02_EPIL_INIT:%.*]] = phi i32 [ 0, %[[SWITCH_LOOKUP]] ], [ [[RDX_MINMAX7]], %[[COMMON_RET_LOOPEXIT_UNR_LCSSA]] ]
; CHECK-NEXT:    [[LCMP_MOD5:%.*]] = icmp ne i64 [[XTRAITER]], 0
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[LCMP_MOD5]])
; CHECK-NEXT:    br label %[[FOR_BODY_EPIL:.*]]
; CHECK:       [[FOR_BODY_EPIL]]:
; CHECK-NEXT:    [[INDVARS_IV_EPIL:%.*]] = phi i64 [ [[INDVARS_IV_EPIL_INIT]], %[[FOR_BODY_EPIL_PREHEADER]] ], [ [[INDVARS_IV_NEXT_EPIL:%.*]], %[[FOR_BODY_EPIL]] ]
; CHECK-NEXT:    [[MY_MIN_02_EPIL:%.*]] = phi i32 [ [[MY_MIN_02_EPIL_INIT]], %[[FOR_BODY_EPIL_PREHEADER]] ], [ [[COND13_EPIL:%.*]], %[[FOR_BODY_EPIL]] ]
; CHECK-NEXT:    [[EPIL_ITER:%.*]] = phi i64 [ 0, %[[FOR_BODY_EPIL_PREHEADER]] ], [ [[EPIL_ITER_NEXT:%.*]], %[[FOR_BODY_EPIL]] ]
; CHECK-NEXT:    [[ARRAYIDX6_EPIL:%.*]] = getelementptr [8 x i8], ptr null, i64 [[INDVARS_IV_EPIL]]
; CHECK-NEXT:    [[ARRAYIDX7_EPIL:%.*]] = getelementptr i8, ptr [[ARRAYIDX6_EPIL]], i64 4
; CHECK-NEXT:    [[V_EPIL:%.*]] = load i32, ptr [[ARRAYIDX7_EPIL]], align 4
; CHECK-NEXT:    [[COND13_EPIL]] = tail call i32 @llvm.smin.i32(i32 [[MY_MIN_02_EPIL]], i32 [[V_EPIL]])
; CHECK-NEXT:    [[INDVARS_IV_NEXT_EPIL]] = add nuw nsw i64 [[INDVARS_IV_EPIL]], 1
; CHECK-NEXT:    [[EPIL_ITER_NEXT]] = add i64 [[EPIL_ITER]], 1
; CHECK-NEXT:    [[EPIL_ITER_CMP_NOT:%.*]] = icmp eq i64 [[EPIL_ITER_NEXT]], [[XTRAITER]]
; CHECK-NEXT:    br i1 [[EPIL_ITER_CMP_NOT]], label %[[COMMON_RET]], label %[[FOR_BODY_EPIL]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[RDX_MINMAX7]], %[[COMMON_RET_LOOPEXIT_UNR_LCSSA]] ], [ [[COND13_EPIL]], %[[FOR_BODY_EPIL]] ]
; CHECK-NEXT:    ret i32 [[COMMON_RET_OP]]
; CHECK:       [[SWITCH_LOOKUP]]:
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i32 [[DIR]] to i64
; CHECK-NEXT:    [[SWITCH_GEP:%.*]] = getelementptr inbounds nuw i8, ptr @switch.table.reduce_smin, i64 [[TMP1]]
; CHECK-NEXT:    [[SWITCH_LOAD:%.*]] = load i8, ptr [[SWITCH_GEP]], align 1
; CHECK-NEXT:    [[SWITCH_EXT:%.*]] = zext i8 [[SWITCH_LOAD]] to i64
; CHECK-NEXT:    [[XTRAITER]] = and i64 [[SWITCH_EXT]], 3
; CHECK-NEXT:    [[TMP2:%.*]] = add i8 [[SWITCH_LOAD]], -1
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ult i8 [[TMP2]], 3
; CHECK-NEXT:    br i1 [[TMP3]], label %[[FOR_BODY_EPIL_PREHEADER]], label %[[SWITCH_LOOKUP_NEW:.*]]
; CHECK:       [[SWITCH_LOOKUP_NEW]]:
; CHECK-NEXT:    [[UNROLL_ITER:%.*]] = and i64 [[SWITCH_EXT]], 252
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[SWITCH_LOOKUP_NEW]] ], [ [[INDVARS_IV_NEXT_3]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[MY_MIN_02_1:%.*]] = phi i32 [ 2147483647, %[[SWITCH_LOOKUP_NEW]] ], [ [[COND13_1]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[MY_MIN_02_2:%.*]] = phi i32 [ 2147483647, %[[SWITCH_LOOKUP_NEW]] ], [ [[COND13_2]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[MY_MIN_02_3:%.*]] = phi i32 [ 2147483647, %[[SWITCH_LOOKUP_NEW]] ], [ [[COND13_3]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[MY_MIN_02:%.*]] = phi i32 [ 0, %[[SWITCH_LOOKUP_NEW]] ], [ [[COND13]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[NITER:%.*]] = phi i64 [ 0, %[[SWITCH_LOOKUP_NEW]] ], [ [[NITER_NEXT_3:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr [8 x i8], ptr null, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr i8, ptr [[ARRAYIDX6]], i64 4
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[ARRAYIDX7]], align 4
; CHECK-NEXT:    [[COND13]] = tail call i32 @llvm.smin.i32(i32 [[MY_MIN_02]], i32 [[V]])
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [8 x i8], ptr null, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[ARRAYIDX7_1:%.*]] = getelementptr i8, ptr [[TMP4]], i64 12
; CHECK-NEXT:    [[V_1:%.*]] = load i32, ptr [[ARRAYIDX7_1]], align 4
; CHECK-NEXT:    [[COND13_1]] = tail call i32 @llvm.smin.i32(i32 [[MY_MIN_02_1]], i32 [[V_1]])
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [8 x i8], ptr null, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[ARRAYIDX7_2:%.*]] = getelementptr i8, ptr [[TMP5]], i64 20
; CHECK-NEXT:    [[V_2:%.*]] = load i32, ptr [[ARRAYIDX7_2]], align 4
; CHECK-NEXT:    [[COND13_2]] = tail call i32 @llvm.smin.i32(i32 [[MY_MIN_02_2]], i32 [[V_2]])
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [8 x i8], ptr null, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[ARRAYIDX7_3:%.*]] = getelementptr i8, ptr [[TMP6]], i64 28
; CHECK-NEXT:    [[V_3:%.*]] = load i32, ptr [[ARRAYIDX7_3]], align 4
; CHECK-NEXT:    [[COND13_3]] = tail call i32 @llvm.smin.i32(i32 [[MY_MIN_02_3]], i32 [[V_3]])
; CHECK-NEXT:    [[INDVARS_IV_NEXT_3]] = add nuw nsw i64 [[INDVARS_IV]], 4
; CHECK-NEXT:    [[NITER_NEXT_3]] = add i64 [[NITER]], 4
; CHECK-NEXT:    [[NITER_NCMP_3:%.*]] = icmp eq i64 [[NITER_NEXT_3]], [[UNROLL_ITER]]
; CHECK-NEXT:    br i1 [[NITER_NCMP_3]], label %[[COMMON_RET_LOOPEXIT_UNR_LCSSA]], label %[[FOR_BODY]]
;
entry:
  switch i32 %dir, label %common.ret [
  i32 0, label %sw.epilog
  i32 2, label %sw.bb2
  i32 1, label %sw.epilog
  ]

sw.bb2:
  br label %sw.epilog

common.ret:
  %common.ret.op = phi i32 [ 0, %entry ], [ %my_min.0, %for.cond ]
  ret i32 %common.ret.op

sw.epilog:
  %mvs.0 = phi i32 [ 1, %entry ], [ 2, %sw.bb2 ], [ 1, %entry ]
  br label %for.cond

for.cond:
  %i.0 = phi i32 [ 0, %sw.epilog ], [ %inc, %for.body ]
  %my_min.0 = phi i32 [ 0, %sw.epilog ], [ %cond13, %for.body ]
  %cmp4 = icmp slt i32 %i.0, %mvs.0
  br i1 %cmp4, label %for.body, label %common.ret

for.body:
  %idxprom5 = zext i32 %i.0 to i64
  %arrayidx6 = getelementptr [8 x i8], ptr null, i64 %idxprom5
  %arrayidx7 = getelementptr i8, ptr %arrayidx6, i64 4
  %v = load i32, ptr %arrayidx7, align 4
  %cond13 = call i32 @llvm.smin.i32(i32 %my_min.0, i32 %v)
  %inc = add i32 %i.0, 1
  br label %for.cond
}

declare i32 @llvm.smin.i32(i32, i32)

attributes #0 = { "target-cpu"="apple-m1" }
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.unroll.disable"}
;.
