; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; x & mask: result <= mask, so result < bound when mask < bound.
define i1 @and_ult_mask_bound(i32 noundef %x, i32 noundef %mask, i32 noundef %bound) {
; CHECK-LABEL: @and_ult_mask_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[MASK:%.*]], [[BOUND:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = and i32 [[X:%.*]], [[MASK]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp ult i32 %mask, %bound
  br i1 %cmp, label %mid, label %else

mid:
  %r = and i32 %x, %mask
  br label %check

check:
  %v = icmp ult i32 %r, %bound
  ret i1 %v

else:
  ret i1 false
}

; x & mask: result <= mask, so result ule bound when mask ule bound.
define i1 @and_ule_mask_bound(i32 noundef %x, i32 noundef %mask, i32 noundef %bound) {
; CHECK-LABEL: @and_ule_mask_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ule i32 [[MASK:%.*]], [[BOUND:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = and i32 [[X:%.*]], [[MASK]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp ule i32 %mask, %bound
  br i1 %cmp, label %mid, label %else

mid:
  %r = and i32 %x, %mask
  br label %check

check:
  %v = icmp ule i32 %r, %bound
  ret i1 %v

else:
  ret i1 false
}

; x & y: result <= y, so we can prove result ule y directly.
define i1 @and_ule_rhs(i32 noundef %x, i32 noundef %y) {
; CHECK-LABEL: @and_ule_rhs(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = and i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = and i32 %x, %y
  %v = icmp ule i32 %r, %y
  ret i1 %v
}

; x & y: result <= x, so we can prove result ule x directly.
define i1 @and_ule_lhs(i32 noundef %x, i32 noundef %y) {
; CHECK-LABEL: @and_ule_lhs(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = and i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = and i32 %x, %y
  %v = icmp ule i32 %r, %x
  ret i1 %v
}

; x & y <= x <= bound => x & y <= bound (transitive).
define i1 @and_ule_lhs_bound(i32 noundef %x, i32 noundef %y, i32 noundef %bound) {
; CHECK-LABEL: @and_ule_lhs_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ule i32 [[X:%.*]], [[BOUND:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = and i32 [[X]], [[Y:%.*]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp ule i32 %x, %bound
  br i1 %cmp, label %mid, label %else

mid:
  %r = and i32 %x, %y
  br label %check

check:
  %v = icmp ule i32 %r, %bound
  ret i1 %v

else:
  ret i1 false
}

; Constant mask: x & 0xFF <= 255, so result < 256.
define i1 @and_constant_mask_ult(i32 noundef %x) {
; CHECK-LABEL: @and_constant_mask_ult(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = and i32 [[X:%.*]], 255
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = and i32 %x, 255
  %v = icmp ult i32 %r, 256
  ret i1 %v
}

; Constant mask: x & 0xFF <= 255.
define i1 @and_constant_mask_ule(i32 noundef %x) {
; CHECK-LABEL: @and_constant_mask_ule(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = and i32 [[X:%.*]], 255
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = and i32 %x, 255
  %v = icmp ule i32 %r, 255
  ret i1 %v
}

; NEGATIVE: x & y is NOT guaranteed >= y.
define i1 @and_not_uge_rhs(i32 noundef %x, i32 noundef %y) {
; CHECK-LABEL: @and_not_uge_rhs(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = and i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[V:%.*]] = icmp uge i32 [[R]], [[Y]]
; CHECK-NEXT:    ret i1 [[V]]
;
entry:
  %r = and i32 %x, %y
  %v = icmp uge i32 %r, %y
  ret i1 %v
}

; NEGATIVE: Cannot prove x & mask >= bound.
define i1 @and_cannot_prove_uge(i32 noundef %x, i32 noundef %mask, i32 noundef %bound) {
; CHECK-LABEL: @and_cannot_prove_uge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[MASK:%.*]], [[BOUND:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = and i32 [[X:%.*]], [[MASK]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 false
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp ult i32 %mask, %bound
  br i1 %cmp, label %mid, label %else

mid:
  %r = and i32 %x, %mask
  br label %check

check:
  %v = icmp uge i32 %r, %bound
  ret i1 %v

else:
  ret i1 false
}

; Chained AND facts: (x & y) & z <= x & y <= x.
define i1 @and_chained_ule(i32 noundef %x, i32 noundef %y, i32 noundef %z, i32 noundef %bound) {
; CHECK-LABEL: @and_chained_ule(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ule i32 [[X:%.*]], [[BOUND:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R1:%.*]] = and i32 [[X]], [[Y:%.*]]
; CHECK-NEXT:    [[R2:%.*]] = and i32 [[R1]], [[Z:%.*]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp ule i32 %x, %bound
  br i1 %cmp, label %mid, label %else

mid:
  %r1 = and i32 %x, %y
  %r2 = and i32 %r1, %z
  br label %check

check:
  %v = icmp ule i32 %r2, %bound
  ret i1 %v

else:
  ret i1 false
}
