; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; Tests for decomposing expressions for unsigned predicates where the
; no-unsigned-wrap property is proven using the constraint systems instead of
; being available as a flag in the IR. The uses of the decomposed values are
; not dominated by the facts, so the flags cannot be materialized on the
; definitions either.

declare void @use(i8)

define i1 @mul_via_range(i8 %a) {
; CHECK-LABEL: define i1 @mul_via_range(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M:%.*]] = mul i8 [[A]], 10
; CHECK-NEXT:    call void @use(i8 [[M]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp ule i8 [[A]], 25
; CHECK-NEXT:    br i1 [[C_1]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    ret i1 true
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %m = mul i8 %a, 10
  call void @use(i8 %m)
  %c.1 = icmp ule i8 %a, 25
  br i1 %c.1, label %then, label %exit
then:
  %c = icmp ule i8 %m, 250
  ret i1 %c
exit:
  ret i1 false
}

; 26 * 10 does not fit in i8, so the multiply may wrap.
define i1 @mul_range_too_wide(i8 %a) {
; CHECK-LABEL: define i1 @mul_range_too_wide(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M:%.*]] = mul i8 [[A]], 10
; CHECK-NEXT:    call void @use(i8 [[M]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp ule i8 [[A]], 26
; CHECK-NEXT:    br i1 [[C_1]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[C:%.*]] = icmp ule i8 [[M]], -6
; CHECK-NEXT:    ret i1 [[C]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %m = mul i8 %a, 10
  call void @use(i8 %m)
  %c.1 = icmp ule i8 %a, 26
  br i1 %c.1, label %then, label %exit
then:
  %c = icmp ule i8 %m, 250
  ret i1 %c
exit:
  ret i1 false
}

define i1 @shl_via_range(i8 %a) {
; CHECK-LABEL: define i1 @shl_via_range(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M:%.*]] = shl i8 [[A]], 2
; CHECK-NEXT:    call void @use(i8 [[M]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp ule i8 [[A]], 60
; CHECK-NEXT:    br i1 [[C_1]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    ret i1 true
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %m = shl i8 %a, 2
  call void @use(i8 %m)
  %c.1 = icmp ule i8 %a, 60
  br i1 %c.1, label %then, label %exit
then:
  %c = icmp ule i8 %m, 240
  ret i1 %c
exit:
  ret i1 false
}

; 64 << 2 does not fit in i8, so the shift may wrap.
define i1 @shl_range_too_wide(i8 %a) {
; CHECK-LABEL: define i1 @shl_range_too_wide(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M:%.*]] = shl i8 [[A]], 2
; CHECK-NEXT:    call void @use(i8 [[M]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp ule i8 [[A]], 64
; CHECK-NEXT:    br i1 [[C_1]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[C:%.*]] = icmp ule i8 [[M]], -16
; CHECK-NEXT:    ret i1 [[C]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %m = shl i8 %a, 2
  call void @use(i8 %m)
  %c.1 = icmp ule i8 %a, 64
  br i1 %c.1, label %then, label %exit
then:
  %c = icmp ule i8 %m, 240
  ret i1 %c
exit:
  ret i1 false
}
