; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; Tests for decomposing expressions for signed predicates where the no-signed-
; wrap property is proven using the constraint systems instead of being
; available as a flag in the IR. The uses of the decomposed values are not
; dominated by the facts, so the flags cannot be materialized on the
; definitions either.

declare void @use(i8)

define i1 @mul_via_range(i8 %a) {
; CHECK-LABEL: define i1 @mul_via_range(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M:%.*]] = mul i8 [[A]], 10
; CHECK-NEXT:    call void @use(i8 [[M]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp sle i8 [[A]], 5
; CHECK-NEXT:    [[C_2:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[C_1]], [[C_2]]
; CHECK-NEXT:    br i1 [[AND]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    ret i1 true
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %m = mul i8 %a, 10
  call void @use(i8 %m)
  %c.1 = icmp sle i8 %a, 5
  %c.2 = icmp sge i8 %a, 0
  %and = and i1 %c.1, %c.2
  br i1 %and, label %then, label %exit

then:
  %c = icmp sle i8 %m, 50
  ret i1 %c

exit:
  ret i1 false
}

; 20 * 10 does not fit in i8, so the multiply may wrap.
define i1 @mul_range_too_wide(i8 %a) {
; CHECK-LABEL: define i1 @mul_range_too_wide(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M:%.*]] = mul i8 [[A]], 10
; CHECK-NEXT:    call void @use(i8 [[M]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp sle i8 [[A]], 20
; CHECK-NEXT:    [[C_2:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[C_1]], [[C_2]]
; CHECK-NEXT:    br i1 [[AND]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[C:%.*]] = icmp sle i8 [[M]], 50
; CHECK-NEXT:    ret i1 [[C]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %m = mul i8 %a, 10
  call void @use(i8 %m)
  %c.1 = icmp sle i8 %a, 20
  %c.2 = icmp sge i8 %a, 0
  %and = and i1 %c.1, %c.2
  br i1 %and, label %then, label %exit

then:
  %c = icmp sle i8 %m, 50
  ret i1 %c

exit:
  ret i1 false
}

define i1 @shl_via_range(i8 %a) {
; CHECK-LABEL: define i1 @shl_via_range(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M:%.*]] = shl i8 [[A]], 2
; CHECK-NEXT:    call void @use(i8 [[M]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp sle i8 [[A]], 5
; CHECK-NEXT:    [[C_2:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[C_1]], [[C_2]]
; CHECK-NEXT:    br i1 [[AND]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    ret i1 true
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %m = shl i8 %a, 2
  call void @use(i8 %m)
  %c.1 = icmp sle i8 %a, 5
  %c.2 = icmp sge i8 %a, 0
  %and = and i1 %c.1, %c.2
  br i1 %and, label %then, label %exit

then:
  %c = icmp sle i8 %m, 20
  ret i1 %c

exit:
  ret i1 false
}

; 40 << 2 does not fit in i8, so the shift may wrap.
define i1 @shl_range_too_wide(i8 %a) {
; CHECK-LABEL: define i1 @shl_range_too_wide(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[M:%.*]] = shl i8 [[A]], 2
; CHECK-NEXT:    call void @use(i8 [[M]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp sle i8 [[A]], 40
; CHECK-NEXT:    [[C_2:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[C_1]], [[C_2]]
; CHECK-NEXT:    br i1 [[AND]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[C:%.*]] = icmp sle i8 [[M]], 20
; CHECK-NEXT:    ret i1 [[C]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %m = shl i8 %a, 2
  call void @use(i8 %m)
  %c.1 = icmp sle i8 %a, 40
  %c.2 = icmp sge i8 %a, 0
  %and = and i1 %c.1, %c.2
  br i1 %and, label %then, label %exit

then:
  %c = icmp sle i8 %m, 20
  ret i1 %c

exit:
  ret i1 false
}

define i1 @sub_via_operand_signs(i8 %a, i8 %b) {
; CHECK-LABEL: define i1 @sub_via_operand_signs(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[S:%.*]] = sub i8 [[A]], [[B]]
; CHECK-NEXT:    call void @use(i8 [[S]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp sge i8 [[B]], 0
; CHECK-NEXT:    [[C_2:%.*]] = icmp sge i8 [[A]], [[B]]
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[C_1]], [[C_2]]
; CHECK-NEXT:    br i1 [[AND]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[C:%.*]] = icmp sle i8 [[S]], [[A]]
; CHECK-NEXT:    ret i1 [[C]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %s = sub i8 %a, %b
  call void @use(i8 %s)
  %c.1 = icmp sge i8 %b, 0
  %c.2 = icmp sge i8 %a, %b
  %and = and i1 %c.1, %c.2
  br i1 %and, label %then, label %exit

then:
  %c = icmp sle i8 %s, %a
  ret i1 %c

exit:
  ret i1 false
}

; Without a bound relating %a and %b, the subtract may wrap.
define i1 @sub_no_order_between_operands(i8 %a, i8 %b) {
; CHECK-LABEL: define i1 @sub_no_order_between_operands(
; CHECK-SAME: i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[S:%.*]] = sub i8 [[A]], [[B]]
; CHECK-NEXT:    call void @use(i8 [[S]])
; CHECK-NEXT:    [[C_1:%.*]] = icmp sge i8 [[B]], 0
; CHECK-NEXT:    br i1 [[C_1]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[C:%.*]] = icmp sle i8 [[S]], [[A]]
; CHECK-NEXT:    ret i1 [[C]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %s = sub i8 %a, %b
  call void @use(i8 %s)
  %c.1 = icmp sge i8 %b, 0
  br i1 %c.1, label %then, label %exit

then:
  %c = icmp sle i8 %s, %a
  ret i1 %c

exit:
  ret i1 false
}
