; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)

define void @checked_add_start_bound(i64 %n) {
; CHECK-LABEL: define void @checked_add_start_bound(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 3, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp sge i64 [[IV]], 3
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    [[S:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[IV]], i64 1)
; CHECK-NEXT:    [[IV_NEXT]] = extractvalue { i64, i1 } [[S]], 0
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[S]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[EXIT:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %iv = phi i64 [ 3, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp sge i64 %iv, 3
  call void @use(i1 %c)
  %s = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %iv, i64 1)
  %iv.next = extractvalue { i64, i1 } %s, 0
  %ov = extractvalue { i64, i1 } %s, 1
  br i1 %ov, label %exit, label %loop.latch

loop.latch:
  %ec = icmp ne i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}

define void @checked_add_ne_latch(i64 %n) {
; CHECK-LABEL: define void @checked_add_ne_latch(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp eq i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[PRE]])
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i64 [[IV]], [[N]]
; CHECK-NEXT:    call void @use(i1 [[C]])
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[S:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[IV]], i64 1)
; CHECK-NEXT:    [[IV_NEXT]] = extractvalue { i64, i1 } [[S]], 0
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP_HEADER]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp eq i64 %n, 0
  call void @llvm.assume(i1 %pre)
  br label %loop.header

loop.header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  %c = icmp ult i64 %iv, %n
  call void @use(i1 %c)
  br label %loop.latch

loop.latch:
  %s = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %iv, i64 1)
  %iv.next = extractvalue { i64, i1 } %s, 0
  %ec = icmp ne i64 %iv.next, %n
  br i1 %ec, label %loop.header, label %exit

exit:
  ret void
}
