; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; lshr x, C: result <= UINT_MAX >> C, so result < (UINT_MAX >> C) + 1.
define i1 @lshr_const_shift_ule_max(i32 noundef %x) {
; CHECK-LABEL: @lshr_const_shift_ule_max(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = lshr i32 [[X:%.*]], 8
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = lshr i32 %x, 8
  ; Result <= 0x00FFFFFF (16777215)
  %v = icmp ule i32 %r, 16777215
  ret i1 %v
}

; lshr x, C: result < bound when (UINT_MAX >> C) < bound.
define i1 @lshr_const_shift_ult_bound(i32 noundef %x) {
; CHECK-LABEL: @lshr_const_shift_ult_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = lshr i32 [[X:%.*]], 16
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = lshr i32 %x, 16
  ; Result <= 0x0000FFFF (65535), so result < 65536.
  %v = icmp ult i32 %r, 65536
  ret i1 %v
}

; lshr x, C with bound: result <= x <= bound => result <= bound.
define i1 @lshr_ule_bound(i32 noundef %x, i32 noundef %bound) {
; CHECK-LABEL: @lshr_ule_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ule i32 [[X:%.*]], [[BOUND:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = lshr i32 [[X]], 4
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp ule i32 %x, %bound
  br i1 %cmp, label %mid, label %else

mid:
  %r = lshr i32 %x, 4
  br label %check

check:
  %v = icmp ule i32 %r, %bound
  ret i1 %v

else:
  ret i1 false
}

; lshr by 1: result <= x/2 = UINT_MAX/2.
define i1 @lshr_by_1_ule_half_max(i32 noundef %x) {
; CHECK-LABEL: @lshr_by_1_ule_half_max(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = lshr i32 [[X:%.*]], 1
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = lshr i32 %x, 1
  %v = icmp ule i32 %r, 2147483647
  ret i1 %v
}

; ashr x, C when x >= 0: result >= 0 and result <= x.
define i1 @ashr_nonneg_ule_lhs(i32 noundef %x) {
; CHECK-LABEL: @ashr_nonneg_ule_lhs(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = ashr i32 [[X]], 2
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sge i32 %x, 0
  br i1 %cmp, label %mid, label %else

mid:
  %r = ashr i32 %x, 2
  %v = icmp ule i32 %r, %x
  ret i1 %v

else:
  ret i1 false
}

; ashr x, C when x >= 0: result is non-negative.
define i1 @ashr_nonneg_sge_zero(i32 noundef %x) {
; CHECK-LABEL: @ashr_nonneg_sge_zero(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = ashr i32 [[X]], 3
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sge i32 %x, 0
  br i1 %cmp, label %mid, label %else

mid:
  %r = ashr i32 %x, 3
  %v = icmp sge i32 %r, 0
  ret i1 %v

else:
  ret i1 false
}

; ashr x, C with bound: when x >= 0 and x <= bound, result <= bound.
define i1 @ashr_nonneg_ule_bound(i32 noundef %x, i32 noundef %bound) {
; CHECK-LABEL: @ashr_nonneg_ule_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    [[CMP2:%.*]] = icmp ule i32 [[X]], [[BOUND:%.*]]
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[CMP1]], [[CMP2]]
; CHECK-NEXT:    br i1 [[AND]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = ashr i32 [[X]], 1
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp1 = icmp sge i32 %x, 0
  %cmp2 = icmp ule i32 %x, %bound
  %and = and i1 %cmp1, %cmp2
  br i1 %and, label %mid, label %else

mid:
  %r = ashr i32 %x, 1
  br label %check

check:
  %v = icmp ule i32 %r, %bound
  ret i1 %v

else:
  ret i1 false
}

; NEGATIVE: lshr x, y: cannot prove result >= x.
define i1 @lshr_not_uge_lhs(i32 noundef %x, i32 noundef %y) {
; CHECK-LABEL: @lshr_not_uge_lhs(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = lshr i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[V:%.*]] = icmp uge i32 [[R]], [[X]]
; CHECK-NEXT:    ret i1 [[V]]
;
entry:
  %r = lshr i32 %x, %y
  %v = icmp uge i32 %r, %x
  ret i1 %v
}

; NEGATIVE: ashr x, y when x sign unknown: cannot prove result >= 0.
define i1 @ashr_unknown_sign_cannot_prove(i32 noundef %x, i32 noundef %y) {
; CHECK-LABEL: @ashr_unknown_sign_cannot_prove(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = ashr i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[V:%.*]] = icmp sge i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[V]]
;
entry:
  %r = ashr i32 %x, %y
  %v = icmp sge i32 %r, 0
  ret i1 %v
}

; NEGATIVE: lshr by 0 doesn't add tighter bound than UINT_MAX.
define i1 @lshr_by_0_no_extra_bound(i32 noundef %x) {
; CHECK-LABEL: @lshr_by_0_no_extra_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = lshr i32 [[X:%.*]], 0
; CHECK-NEXT:    [[V:%.*]] = icmp ult i32 [[R]], 100
; CHECK-NEXT:    ret i1 [[V]]
;
entry:
  %r = lshr i32 %x, 0
  %v = icmp ult i32 %r, 100
  ret i1 %v
}

; Chained: lshr + and.
define i1 @lshr_then_and_ule_bound(i32 noundef %x) {
; CHECK-LABEL: @lshr_then_and_ule_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[X:%.*]], 16
; CHECK-NEXT:    [[MASKED:%.*]] = and i32 [[SHR]], 255
; CHECK-NEXT:    ret i1 true
;
entry:
  %shr = lshr i32 %x, 16
  %masked = and i32 %shr, 255
  ; masked <= 255 (from AND) and masked <= 65535 (from lshr), so masked < 256.
  %v = icmp ult i32 %masked, 256
  ret i1 %v
}
