; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare { i8, i1 } @llvm.umul.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.smul.with.overflow.i8(i8, i8)

define i8 @umul_no_overflow_due_to_upper_bound(i8 %a) {
; CHECK-LABEL: define i8 @umul_no_overflow_due_to_upper_bound(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C_1:%.*]] = icmp ule i8 [[A]], 10
; CHECK-NEXT:    br i1 [[C_1]], label %[[MATH:.*]], label %[[EXIT_FAIL:.*]]
; CHECK:       [[MATH]]:
; CHECK-NEXT:    [[TMP0:%.*]] = mul nuw i8 [[A]], 10
; CHECK-NEXT:    br i1 false, label %[[EXIT_FAIL]], label %[[EXIT_OK:.*]]
; CHECK:       [[EXIT_OK]]:
; CHECK-NEXT:    ret i8 [[TMP0]]
; CHECK:       [[EXIT_FAIL]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %c.1 = icmp ule i8 %a, 10
  br i1 %c.1, label %math, label %exit.fail

math:
  %op = tail call { i8, i1 } @llvm.umul.with.overflow.i8(i8 %a, i8 10)
  %status = extractvalue { i8, i1 } %op, 1
  br i1 %status, label %exit.fail, label %exit.ok

exit.ok:
  %res = extractvalue { i8, i1 } %op, 0
  ret i8 %res

exit.fail:
  ret i8 0
}

; 26 * 10 does not fit in i8.
define i8 @umul_may_overflow_upper_bound_too_large(i8 %a) {
; CHECK-LABEL: define i8 @umul_may_overflow_upper_bound_too_large(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C_1:%.*]] = icmp ule i8 [[A]], 26
; CHECK-NEXT:    br i1 [[C_1]], label %[[MATH:.*]], label %[[EXIT_FAIL:.*]]
; CHECK:       [[MATH]]:
; CHECK-NEXT:    [[OP:%.*]] = tail call { i8, i1 } @llvm.umul.with.overflow.i8(i8 [[A]], i8 10)
; CHECK-NEXT:    [[STATUS:%.*]] = extractvalue { i8, i1 } [[OP]], 1
; CHECK-NEXT:    br i1 [[STATUS]], label %[[EXIT_FAIL]], label %[[EXIT_OK:.*]]
; CHECK:       [[EXIT_OK]]:
; CHECK-NEXT:    [[RES:%.*]] = extractvalue { i8, i1 } [[OP]], 0
; CHECK-NEXT:    ret i8 [[RES]]
; CHECK:       [[EXIT_FAIL]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %c.1 = icmp ule i8 %a, 26
  br i1 %c.1, label %math, label %exit.fail

math:
  %op = tail call { i8, i1 } @llvm.umul.with.overflow.i8(i8 %a, i8 10)
  %status = extractvalue { i8, i1 } %op, 1
  br i1 %status, label %exit.fail, label %exit.ok

exit.ok:
  %res = extractvalue { i8, i1 } %op, 0
  ret i8 %res

exit.fail:
  ret i8 0
}

; Both bounds are needed to rule out a signed overflow.
define i8 @smul_no_overflow_due_to_bounds(i8 %a) {
; CHECK-LABEL: define i8 @smul_no_overflow_due_to_bounds(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C_1:%.*]] = icmp sle i8 [[A]], 5
; CHECK-NEXT:    [[C_2:%.*]] = icmp sge i8 [[A]], -5
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[C_1]], [[C_2]]
; CHECK-NEXT:    br i1 [[AND]], label %[[MATH:.*]], label %[[EXIT_FAIL:.*]]
; CHECK:       [[MATH]]:
; CHECK-NEXT:    [[TMP0:%.*]] = mul nsw i8 [[A]], 10
; CHECK-NEXT:    br i1 false, label %[[EXIT_FAIL]], label %[[EXIT_OK:.*]]
; CHECK:       [[EXIT_OK]]:
; CHECK-NEXT:    ret i8 [[TMP0]]
; CHECK:       [[EXIT_FAIL]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %c.1 = icmp sle i8 %a, 5
  %c.2 = icmp sge i8 %a, -5
  %and = and i1 %c.1, %c.2
  br i1 %and, label %math, label %exit.fail

math:
  %op = tail call { i8, i1 } @llvm.smul.with.overflow.i8(i8 %a, i8 10)
  %status = extractvalue { i8, i1 } %op, 1
  br i1 %status, label %exit.fail, label %exit.ok

exit.ok:
  %res = extractvalue { i8, i1 } %op, 0
  ret i8 %res

exit.fail:
  ret i8 0
}

define i8 @smul_may_overflow_missing_lower_bound(i8 %a) {
; CHECK-LABEL: define i8 @smul_may_overflow_missing_lower_bound(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C_1:%.*]] = icmp sle i8 [[A]], 5
; CHECK-NEXT:    br i1 [[C_1]], label %[[MATH:.*]], label %[[EXIT_FAIL:.*]]
; CHECK:       [[MATH]]:
; CHECK-NEXT:    [[OP:%.*]] = tail call { i8, i1 } @llvm.smul.with.overflow.i8(i8 [[A]], i8 10)
; CHECK-NEXT:    [[STATUS:%.*]] = extractvalue { i8, i1 } [[OP]], 1
; CHECK-NEXT:    br i1 [[STATUS]], label %[[EXIT_FAIL]], label %[[EXIT_OK:.*]]
; CHECK:       [[EXIT_OK]]:
; CHECK-NEXT:    [[RES:%.*]] = extractvalue { i8, i1 } [[OP]], 0
; CHECK-NEXT:    ret i8 [[RES]]
; CHECK:       [[EXIT_FAIL]]:
; CHECK-NEXT:    ret i8 0
;
entry:
  %c.1 = icmp sle i8 %a, 5
  br i1 %c.1, label %math, label %exit.fail

math:
  %op = tail call { i8, i1 } @llvm.smul.with.overflow.i8(i8 %a, i8 10)
  %status = extractvalue { i8, i1 } %op, 1
  br i1 %status, label %exit.fail, label %exit.ok

exit.ok:
  %res = extractvalue { i8, i1 } %op, 0
  ret i8 %res

exit.fail:
  ret i8 0
}
