; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; The value component of a signed checked add/sub that is only evaluated on the
; no-overflow edge of the branch on its overflow flag is exactly the
; mathematical sum/difference there, so it can be decomposed. The branch on the
; overflow flag is what establishes this, so it is part of every test.

declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.uadd.with.overflow.i64(i64, i64)
declare void @llvm.assume(i1)
declare void @use(i1)

; %sum is only evaluated when the add did not overflow, so it is exactly
; %a + %b there. With %a s<= 10 and %b s<= 20 that gives %sum s<= 30 s< 100.
define void @sadd_guarded_signed(i64 %a, i64 %b) {
; CHECK-LABEL: define void @sadd_guarded_signed(
; CHECK-SAME: i64 [[A:%.*]], i64 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp sle i64 [[A]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C0]])
; CHECK-NEXT:    [[C1:%.*]] = icmp sle i64 [[B]], 20
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    [[O:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[A]], i64 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[O]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[TRAP:.*]], label %[[CONT:.*]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[SUM:%.*]] = extractvalue { i64, i1 } [[O]], 0
; CHECK-NEXT:    [[T:%.*]] = icmp slt i64 [[SUM]], 100
; CHECK-NEXT:    call void @use(i1 [[T]])
; CHECK-NEXT:    ret void
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp sle i64 %a, 10
  call void @llvm.assume(i1 %c0)
  %c1 = icmp sle i64 %b, 20
  call void @llvm.assume(i1 %c1)
  %o = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 %b)
  %ov = extractvalue { i64, i1 } %o, 1
  br i1 %ov, label %trap, label %cont

cont:
  %sum = extractvalue { i64, i1 } %o, 0
  %t = icmp slt i64 %sum, 100
  call void @use(i1 %t)
  ret void

trap:
  ret void
}

; Same in the unsigned system. Both operands are non-negative, so the exact
; signed sum cannot wrap when interpreted as unsigned either.
define void @sadd_guarded_unsigned(i64 %a, i64 %b) {
; CHECK-LABEL: define void @sadd_guarded_unsigned(
; CHECK-SAME: i64 [[A:%.*]], i64 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[N0:%.*]] = icmp sge i64 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[N0]])
; CHECK-NEXT:    [[N1:%.*]] = icmp sge i64 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[N1]])
; CHECK-NEXT:    [[C0:%.*]] = icmp ule i64 [[A]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C0]])
; CHECK-NEXT:    [[C1:%.*]] = icmp ule i64 [[B]], 20
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    [[O:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[A]], i64 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[O]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[TRAP:.*]], label %[[CONT:.*]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[SUM:%.*]] = extractvalue { i64, i1 } [[O]], 0
; CHECK-NEXT:    [[T:%.*]] = icmp ult i64 [[SUM]], 100
; CHECK-NEXT:    call void @use(i1 [[T]])
; CHECK-NEXT:    ret void
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    ret void
;
entry:
  %n0 = icmp sge i64 %a, 0
  call void @llvm.assume(i1 %n0)
  %n1 = icmp sge i64 %b, 0
  call void @llvm.assume(i1 %n1)
  %c0 = icmp ule i64 %a, 10
  call void @llvm.assume(i1 %c0)
  %c1 = icmp ule i64 %b, 20
  call void @llvm.assume(i1 %c1)
  %o = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 %b)
  %ov = extractvalue { i64, i1 } %o, 1
  br i1 %ov, label %trap, label %cont

cont:
  %sum = extractvalue { i64, i1 } %o, 0
  %t = icmp ult i64 %sum, 100
  call void @use(i1 %t)
  ret void

trap:
  ret void
}

; ssub.with.overflow gets the same treatment: on the no-overflow edge %diff is
; exactly %a - %b, and with %a s<= 10 and %b s>= 0 that is s<= 10.
define void @ssub_guarded_signed(i64 %a, i64 %b) {
; CHECK-LABEL: define void @ssub_guarded_signed(
; CHECK-SAME: i64 [[A:%.*]], i64 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp sle i64 [[A]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C0]])
; CHECK-NEXT:    [[C1:%.*]] = icmp sge i64 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    [[O:%.*]] = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 [[A]], i64 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[O]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[TRAP:.*]], label %[[CONT:.*]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[DIFF:%.*]] = extractvalue { i64, i1 } [[O]], 0
; CHECK-NEXT:    [[T:%.*]] = icmp slt i64 [[DIFF]], 100
; CHECK-NEXT:    call void @use(i1 [[T]])
; CHECK-NEXT:    ret void
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp sle i64 %a, 10
  call void @llvm.assume(i1 %c0)
  %c1 = icmp sge i64 %b, 0
  call void @llvm.assume(i1 %c1)
  %o = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 %a, i64 %b)
  %ov = extractvalue { i64, i1 } %o, 1
  br i1 %ov, label %trap, label %cont

cont:
  %diff = extractvalue { i64, i1 } %o, 0
  %t = icmp slt i64 %diff, 100
  call void @use(i1 %t)
  ret void

trap:
  ret void
}

; The unsigned decomposition needs both operands non-negative: without that the
; exact signed sum can be negative and the unsigned interpretation wraps. %b may
; be negative here.
define void @neg_sadd_guarded_unsigned_maybe_negative(i64 %a, i64 %b) {
; CHECK-LABEL: define void @neg_sadd_guarded_unsigned_maybe_negative(
; CHECK-SAME: i64 [[A:%.*]], i64 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp ule i64 [[A]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C0]])
; CHECK-NEXT:    [[C1:%.*]] = icmp sle i64 [[B]], 20
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    [[O:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[A]], i64 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[O]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[TRAP:.*]], label %[[CONT:.*]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[SUM:%.*]] = extractvalue { i64, i1 } [[O]], 0
; CHECK-NEXT:    [[T:%.*]] = icmp ult i64 [[SUM]], 100
; CHECK-NEXT:    call void @use(i1 [[T]])
; CHECK-NEXT:    ret void
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp ule i64 %a, 10
  call void @llvm.assume(i1 %c0)
  %c1 = icmp sle i64 %b, 20
  call void @llvm.assume(i1 %c1)
  %o = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 %b)
  %ov = extractvalue { i64, i1 } %o, 1
  br i1 %ov, label %trap, label %cont

cont:
  %sum = extractvalue { i64, i1 } %o, 0
  %t = icmp ult i64 %sum, 100
  call void @use(i1 %t)
  ret void

trap:
  ret void
}

; The extractvalue is in the same block as the intrinsic, so it is also
; evaluated when the add overflowed. It must stay opaque.
define void @neg_sadd_unguarded_same_block(i64 %a, i64 %b) {
; CHECK-LABEL: define void @neg_sadd_unguarded_same_block(
; CHECK-SAME: i64 [[A:%.*]], i64 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp sle i64 [[A]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C0]])
; CHECK-NEXT:    [[C1:%.*]] = icmp sle i64 [[B]], 20
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    [[O:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[A]], i64 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[O]], 1
; CHECK-NEXT:    [[SUM:%.*]] = extractvalue { i64, i1 } [[O]], 0
; CHECK-NEXT:    [[T:%.*]] = icmp slt i64 [[SUM]], 100
; CHECK-NEXT:    call void @use(i1 [[T]])
; CHECK-NEXT:    br i1 [[OV]], label %[[TRAP:.*]], label %[[CONT:.*]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp sle i64 %a, 10
  call void @llvm.assume(i1 %c0)
  %c1 = icmp sle i64 %b, 20
  call void @llvm.assume(i1 %c1)
  %o = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 %b)
  %ov = extractvalue { i64, i1 } %o, 1
  %sum = extractvalue { i64, i1 } %o, 0
  %t = icmp slt i64 %sum, 100
  call void @use(i1 %t)
  br i1 %ov, label %trap, label %cont

cont:
  ret void

trap:
  ret void
}

; The extractvalue is on the overflow edge, where the add did wrap.
define void @neg_sadd_on_overflow_edge(i64 %a, i64 %b) {
; CHECK-LABEL: define void @neg_sadd_on_overflow_edge(
; CHECK-SAME: i64 [[A:%.*]], i64 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp sle i64 [[A]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C0]])
; CHECK-NEXT:    [[C1:%.*]] = icmp sle i64 [[B]], 20
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    [[O:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[A]], i64 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[O]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[OVF:.*]], label %[[CONT:.*]]
; CHECK:       [[OVF]]:
; CHECK-NEXT:    [[SUM:%.*]] = extractvalue { i64, i1 } [[O]], 0
; CHECK-NEXT:    [[T:%.*]] = icmp slt i64 [[SUM]], 100
; CHECK-NEXT:    call void @use(i1 [[T]])
; CHECK-NEXT:    ret void
; CHECK:       [[CONT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp sle i64 %a, 10
  call void @llvm.assume(i1 %c0)
  %c1 = icmp sle i64 %b, 20
  call void @llvm.assume(i1 %c1)
  %o = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 %b)
  %ov = extractvalue { i64, i1 } %o, 1
  br i1 %ov, label %ovf, label %cont

ovf:
  %sum = extractvalue { i64, i1 } %o, 0
  %t = icmp slt i64 %sum, 100
  call void @use(i1 %t)
  ret void

cont:
  ret void
}

; The extractvalue sits in a join block reachable from both the overflow and the
; no-overflow edge, so no-overflow does not hold there.
define void @neg_sadd_in_join_block(i64 %a, i64 %b) {
; CHECK-LABEL: define void @neg_sadd_in_join_block(
; CHECK-SAME: i64 [[A:%.*]], i64 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp sle i64 [[A]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C0]])
; CHECK-NEXT:    [[C1:%.*]] = icmp sle i64 [[B]], 20
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    [[O:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[A]], i64 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[O]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[OVF:.*]], label %[[CONT:.*]]
; CHECK:       [[OVF]]:
; CHECK-NEXT:    br label %[[JOIN:.*]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[SUM:%.*]] = extractvalue { i64, i1 } [[O]], 0
; CHECK-NEXT:    [[T:%.*]] = icmp slt i64 [[SUM]], 100
; CHECK-NEXT:    call void @use(i1 [[T]])
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp sle i64 %a, 10
  call void @llvm.assume(i1 %c0)
  %c1 = icmp sle i64 %b, 20
  call void @llvm.assume(i1 %c1)
  %o = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 %b)
  %ov = extractvalue { i64, i1 } %o, 1
  br i1 %ov, label %ovf, label %cont

ovf:
  br label %join

cont:
  br label %join

join:
  %sum = extractvalue { i64, i1 } %o, 0
  %t = icmp slt i64 %sum, 100
  call void @use(i1 %t)
  ret void
}

; The no-overflow successor has a second predecessor that bypasses the overflow
; check, so the edge does not dominate the block.
define void @neg_sadd_no_overflow_succ_multi_pred(i64 %a, i64 %b, i1 %cc) {
; CHECK-LABEL: define void @neg_sadd_no_overflow_succ_multi_pred(
; CHECK-SAME: i64 [[A:%.*]], i64 [[B:%.*]], i1 [[CC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp sle i64 [[A]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C0]])
; CHECK-NEXT:    [[C1:%.*]] = icmp sle i64 [[B]], 20
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    [[O:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[A]], i64 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[O]], 1
; CHECK-NEXT:    br i1 [[CC]], label %[[CONT:.*]], label %[[CHECK:.*]]
; CHECK:       [[CHECK]]:
; CHECK-NEXT:    br i1 [[OV]], label %[[TRAP:.*]], label %[[CONT]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[SUM:%.*]] = extractvalue { i64, i1 } [[O]], 0
; CHECK-NEXT:    [[T:%.*]] = icmp slt i64 [[SUM]], 100
; CHECK-NEXT:    call void @use(i1 [[T]])
; CHECK-NEXT:    ret void
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp sle i64 %a, 10
  call void @llvm.assume(i1 %c0)
  %c1 = icmp sle i64 %b, 20
  call void @llvm.assume(i1 %c1)
  %o = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 %b)
  %ov = extractvalue { i64, i1 } %o, 1
  br i1 %cc, label %cont, label %check

check:
  br i1 %ov, label %trap, label %cont

cont:
  %sum = extractvalue { i64, i1 } %o, 0
  %t = icmp slt i64 %sum, 100
  call void @use(i1 %t)
  ret void

trap:
  ret void
}

; uadd.with.overflow is not handled: its no-overflow guarantee is about the
; *unsigned* sum, which says nothing in the signed system. For %a = 1,
; %b = SMAX the unsigned add does not overflow but the signed result is SMIN,
; so %sum s>= %a does not hold.
define void @neg_uadd_guarded_not_handled(i64 %a, i64 %b) {
; CHECK-LABEL: define void @neg_uadd_guarded_not_handled(
; CHECK-SAME: i64 [[A:%.*]], i64 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C1:%.*]] = icmp sge i64 [[B]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    [[O:%.*]] = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 [[A]], i64 [[B]])
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[O]], 1
; CHECK-NEXT:    br i1 [[OV]], label %[[TRAP:.*]], label %[[CONT:.*]]
; CHECK:       [[CONT]]:
; CHECK-NEXT:    [[SUM:%.*]] = extractvalue { i64, i1 } [[O]], 0
; CHECK-NEXT:    [[T:%.*]] = icmp sge i64 [[SUM]], [[A]]
; CHECK-NEXT:    call void @use(i1 [[T]])
; CHECK-NEXT:    ret void
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    ret void
;
entry:
  %c1 = icmp sge i64 %b, 0
  call void @llvm.assume(i1 %c1)
  %o = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 %a, i64 %b)
  %ov = extractvalue { i64, i1 } %o, 1
  br i1 %ov, label %trap, label %cont

cont:
  %sum = extractvalue { i64, i1 } %o, 0
  %t = icmp sge i64 %sum, %a
  call void @use(i1 %t)
  ret void

trap:
  ret void
}
