; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; sadd.with.overflow(A, C) with a constant C does not signed-overflow when A
; stays in range after adding C: for C s>= 0 that needs A s<= SMAX - C, for
; C s< 0 it needs A s>= SMIN - C. The bound on A is discharged either by the
; constraint solver (constant bound) or, as a fallback, by SCEV's signed range
; (variable bound on a loop induction).

declare { i8, i1 } @llvm.sadd.with.overflow.i8(i8, i8)
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare void @llvm.assume(i1)
declare void @use(i1)
declare void @use.agg({ i8, i1 })

; A is in [0, 100), so A + 1 does not overflow (A s<= SMAX - 1).
define i8 @sadd_no_overflow_pos_const(i8 %a) {
; CHECK-LABEL: define i8 @sadd_no_overflow_pos_const(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[LO]])
; CHECK-NEXT:    [[HI:%.*]] = icmp slt i8 [[A]], 100
; CHECK-NEXT:    [[OK:%.*]] = and i1 [[LO]], [[HI]]
; CHECK-NEXT:    br i1 [[OK]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[V:%.*]] = add nsw i8 [[A]], 1
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
  %lo = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %lo)
  %hi = icmp slt i8 %a, 100
  call void @llvm.assume(i1 %hi)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v
}

; A is in (-100, 0], so A + (-1) does not overflow (A s>= SMIN + 1).
define i8 @sadd_no_overflow_neg_const(i8 %a) {
; CHECK-LABEL: define i8 @sadd_no_overflow_neg_const(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:    [[LO:%.*]] = icmp sgt i8 [[A]], -100
; CHECK-NEXT:    call void @llvm.assume(i1 [[LO]])
; CHECK-NEXT:    [[HI:%.*]] = icmp sle i8 [[A]], 0
; CHECK-NEXT:    [[OK:%.*]] = and i1 [[LO]], [[HI]]
; CHECK-NEXT:    br i1 [[OK]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[V:%.*]] = add nsw i8 [[A]], -1
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[V]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    ret i8 0
;
  %lo = icmp sgt i8 %a, -100
  call void @llvm.assume(i1 %lo)
  %hi = icmp sle i8 %a, 0
  call void @llvm.assume(i1 %hi)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 -1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v
}

; C == SMIN: sadd(A, SMIN) does not overflow iff A s>= SMIN - C == 0.
define i8 @sadd_c_smin(i8 %a) {
; CHECK-LABEL: define i8 @sadd_c_smin(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[LO]])
; CHECK-NEXT:    [[HI:%.*]] = icmp slt i8 [[A]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[HI]])
; CHECK-NEXT:    [[TMP1:%.*]] = add nsw i8 [[A]], -128
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[TMP1]]
;
  %lo = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %lo)
  %hi = icmp slt i8 %a, 100
  call void @llvm.assume(i1 %hi)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 -128)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v
}

; C == SMAX: sadd(A, SMAX) does not overflow iff A s<= SMAX - C == 0.
define i8 @sadd_c_smax(i8 %a) {
; CHECK-LABEL: define i8 @sadd_c_smax(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:    [[LO:%.*]] = icmp sgt i8 [[A]], -100
; CHECK-NEXT:    call void @llvm.assume(i1 [[LO]])
; CHECK-NEXT:    [[HI:%.*]] = icmp sle i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[HI]])
; CHECK-NEXT:    [[TMP1:%.*]] = add nsw i8 [[A]], 127
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[TMP1]]
;
  %lo = icmp sgt i8 %a, -100
  call void @llvm.assume(i1 %lo)
  %hi = icmp sle i8 %a, 0
  call void @llvm.assume(i1 %hi)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 127)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v
}

; An unsigned bound A u< 100 puts A in [0, 100), which is also a non-negative
; signed range, so the signed fold for A + 1 is discharged.
define i8 @sadd_unsigned_bound(i8 %a) {
; CHECK-LABEL: define i8 @sadd_unsigned_bound(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:    [[HI:%.*]] = icmp ult i8 [[A]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[HI]])
; CHECK-NEXT:    [[TMP1:%.*]] = add nsw i8 [[A]], 1
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[TMP1]]
;
  %hi = icmp ult i8 %a, 100
  call void @llvm.assume(i1 %hi)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v
}

; Wide (i64) constant-bounded case: a constant bound needs no SCEV fallback
; even for the widest type, where the SMAX/SMIN limit is unrepresentable.
define i64 @sadd_no_overflow_i64_const(i64 %a) {
; CHECK-LABEL: define i64 @sadd_no_overflow_i64_const(
; CHECK-SAME: i64 [[A:%.*]]) {
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i64 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[LO]])
; CHECK-NEXT:    [[HI:%.*]] = icmp slt i64 [[A]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[HI]])
; CHECK-NEXT:    [[TMP1:%.*]] = add nsw i64 [[A]], 1
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i64 [[TMP1]]
;
  %lo = icmp sge i64 %a, 0
  call void @llvm.assume(i1 %lo)
  %hi = icmp slt i64 %a, 100
  call void @llvm.assume(i1 %hi)
  %s = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %a, i64 1)
  %v = extractvalue { i64, i1 } %s, 0
  %o = extractvalue { i64, i1 } %s, 1
  call void @use(i1 %o)
  ret i64 %v
}

; The aggregate also feeds a non-extractvalue use, so the intrinsic must be
; preserved even though the extractvalues are rewritten.
define i8 @sadd_aggregate_escapes(i8 %a) {
; CHECK-LABEL: define i8 @sadd_aggregate_escapes(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[LO]])
; CHECK-NEXT:    [[HI:%.*]] = icmp slt i8 [[A]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[HI]])
; CHECK-NEXT:    [[TMP1:%.*]] = add nsw i8 [[A]], 1
; CHECK-NEXT:    [[S:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 1)
; CHECK-NEXT:    call void @use.agg({ i8, i1 } [[S]])
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    ret i8 [[TMP1]]
;
  %lo = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %lo)
  %hi = icmp slt i8 %a, 100
  call void @llvm.assume(i1 %hi)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use.agg({ i8, i1 } %s)
  call void @use(i1 %o)
  ret i8 %v
}

; A is only known non-negative, with no upper bound, so A + 1 may overflow.
define i8 @neg_sadd_may_overflow(i8 %a) {
; CHECK-LABEL: define i8 @neg_sadd_may_overflow(
; CHECK-SAME: i8 [[A:%.*]]) {
; CHECK-NEXT:    [[LO:%.*]] = icmp sge i8 [[A]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[LO]])
; CHECK-NEXT:    [[S:%.*]] = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 [[A]], i8 1)
; CHECK-NEXT:    [[V:%.*]] = extractvalue { i8, i1 } [[S]], 0
; CHECK-NEXT:    [[O:%.*]] = extractvalue { i8, i1 } [[S]], 1
; CHECK-NEXT:    call void @use(i1 [[O]])
; CHECK-NEXT:    ret i8 [[V]]
;
  %lo = icmp sge i8 %a, 0
  call void @llvm.assume(i1 %lo)
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %a, i8 1)
  %v = extractvalue { i8, i1 } %s, 0
  %o = extractvalue { i8, i1 } %s, 1
  call void @use(i1 %o)
  ret i8 %v
}

; The bound is a variable, so the solver cannot prove A s<= SMAX - 1. But A is
; an induction {0,+,1} with exit bound %count - 1, so SCEV's signed range for A
; excludes SMAX and A + 1 cannot overflow.
define i1 @sadd_var_bound_induction(i64 %count) {
; CHECK-LABEL: define i1 @sadd_var_bound_induction(
; CHECK-SAME: i64 [[COUNT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i64 [[COUNT]], 1
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP_PREHEADER:.*]], label %[[DONE:.*]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i64 [[COUNT]], -1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[LOOP_PREHEADER]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[I_NEXT]] = add nsw i64 [[I]], 1
; CHECK-NEXT:    br i1 false, label %[[TRAP:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i64 [[I_NEXT]], [[SUB]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[DONE]]
; CHECK:       [[DONE]]:
; CHECK-NEXT:    ret i1 true
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sgt i64 %count, 1
  br i1 %cmp, label %loop.preheader, label %done

loop.preheader:
  %sub = add nsw i64 %count, -1
  br label %loop

loop:
  %i = phi i64 [ 0, %loop.preheader ], [ %i.next, %loop.latch ]
  %s = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %i, i64 1)
  %i.next = extractvalue { i64, i1 } %s, 0
  %ov = extractvalue { i64, i1 } %s, 1
  br i1 %ov, label %trap, label %loop.latch

loop.latch:
  %cond = icmp slt i64 %i.next, %sub
  br i1 %cond, label %loop, label %done

done:
  ret i1 true

trap:
  ret i1 false
}

; Same for a sub-i64 width, where the solver's signed-range seeding could in
; principle help but the bound is still a variable.
define i1 @sadd_var_bound_induction_i8(i8 %count) {
; CHECK-LABEL: define i1 @sadd_var_bound_induction_i8(
; CHECK-SAME: i8 [[COUNT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i8 [[COUNT]], 1
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP_PREHEADER:.*]], label %[[DONE:.*]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i8 [[COUNT]], -1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i8 [ 0, %[[LOOP_PREHEADER]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[I_NEXT]] = add nsw i8 [[I]], 1
; CHECK-NEXT:    br i1 false, label %[[TRAP:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i8 [[I_NEXT]], [[SUB]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP]], label %[[DONE]]
; CHECK:       [[DONE]]:
; CHECK-NEXT:    ret i1 true
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sgt i8 %count, 1
  br i1 %cmp, label %loop.preheader, label %done

loop.preheader:
  %sub = add nsw i8 %count, -1
  br label %loop

loop:
  %i = phi i8 [ 0, %loop.preheader ], [ %i.next, %loop.latch ]
  %s = call { i8, i1 } @llvm.sadd.with.overflow.i8(i8 %i, i8 1)
  %i.next = extractvalue { i8, i1 } %s, 0
  %ov = extractvalue { i8, i1 } %s, 1
  br i1 %ov, label %trap, label %loop.latch

loop.latch:
  %cond = icmp slt i8 %i.next, %sub
  br i1 %cond, label %loop, label %done

done:
  ret i1 true

trap:
  ret i1 false
}

; The induction {0,+,1} has no computable exit bound, so SCEV's signed range for
; %i is the full range including SMAX and %i + 1 may overflow.
define void @neg_sadd_unbounded_induction(ptr %p) {
; CHECK-LABEL: define void @neg_sadd_unbounded_induction(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[S:%.*]] = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 [[I]], i64 1)
; CHECK-NEXT:    [[I_NEXT]] = extractvalue { i64, i1 } [[S]], 0
; CHECK-NEXT:    [[OV:%.*]] = extractvalue { i64, i1 } [[S]], 1
; CHECK-NEXT:    store i64 [[I]], ptr [[P]], align 4
; CHECK-NEXT:    br i1 [[OV]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %s = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %i, i64 1)
  %i.next = extractvalue { i64, i1 } %s, 0
  %ov = extractvalue { i64, i1 } %s, 1
  store i64 %i, ptr %p
  br i1 %ov, label %exit, label %loop

exit:
  ret void
}
