; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; Select with condition implied true by dominating branch.
define i32 @select_cond_implied_true(i32 %x, i32 %y, i32 %a, i32 %b) {
; CHECK-LABEL: @select_cond_implied_true(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    ret i32 [[A:%.*]]
; CHECK:       else:
; CHECK-NEXT:    ret i32 0
;
entry:
  %cmp1 = icmp ult i32 %x, %y
  br i1 %cmp1, label %then, label %else

then:
  %cmp2 = icmp ult i32 %x, %y
  %sel = select i1 %cmp2, i32 %a, i32 %b
  ret i32 %sel

else:
  ret i32 0
}

; Select with condition implied false by dominating branch.
define i32 @select_cond_implied_false(i32 %x, i32 %y, i32 %a, i32 %b) {
; CHECK-LABEL: @select_cond_implied_false(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp uge i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    ret i32 [[B:%.*]]
; CHECK:       else:
; CHECK-NEXT:    ret i32 0
;
entry:
  %cmp1 = icmp uge i32 %x, %y
  br i1 %cmp1, label %then, label %else

then:
  %cmp2 = icmp ult i32 %x, %y
  %sel = select i1 %cmp2, i32 %a, i32 %b
  ret i32 %sel

else:
  ret i32 0
}

; Select with weaker condition implied by dominating stricter condition.
define i32 @select_weaker_cond_implied(i32 %x, i32 %y, i32 %a, i32 %b) {
; CHECK-LABEL: @select_weaker_cond_implied(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i32 [[X:%.*]], 10
; CHECK-NEXT:    br i1 [[CMP1]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    ret i32 [[A:%.*]]
; CHECK:       else:
; CHECK-NEXT:    ret i32 0
;
entry:
  %cmp1 = icmp ult i32 %x, 10
  br i1 %cmp1, label %then, label %else

then:
  %cmp2 = icmp ult i32 %x, 20
  %sel = select i1 %cmp2, i32 %a, i32 %b
  ret i32 %sel

else:
  ret i32 0
}

; Select where condition is already a constant true (e.g. from prior simplification).
define i32 @select_const_true(i32 %a, i32 %b) {
; CHECK-LABEL: @select_const_true(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SEL:%.*]] = select i1 true, i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    ret i32 [[SEL]]
;
entry:
  %sel = select i1 true, i32 %a, i32 %b
  ret i32 %sel
}

; Select where condition is already a constant false.
define i32 @select_const_false(i32 %a, i32 %b) {
; CHECK-LABEL: @select_const_false(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SEL:%.*]] = select i1 false, i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    ret i32 [[SEL]]
;
entry:
  %sel = select i1 false, i32 %a, i32 %b
  ret i32 %sel
}

; Select with same icmp condition as the dominating branch (different ICmpInst).
define i32 @select_same_cond_different_inst(i32 %x, i32 %n, i32 %a, i32 %b) {
; CHECK-LABEL: @select_same_cond_different_inst(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_BR:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_BR]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    ret i32 [[A:%.*]]
; CHECK:       else:
; CHECK-NEXT:    ret i32 0
;
entry:
  %cmp.br = icmp sge i32 %x, 0
  br i1 %cmp.br, label %then, label %else

then:
  %cmp.sel = icmp sge i32 %x, 0
  %sel = select i1 %cmp.sel, i32 %a, i32 %b
  ret i32 %sel

else:
  ret i32 0
}

; Select with signed predicate implied by dominating unsigned + non-negative.
define i32 @select_signed_from_unsigned(i32 %x, i32 %y, i32 %a, i32 %b) {
; CHECK-LABEL: @select_signed_from_unsigned(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[CMP2:%.*]] = icmp slt i32 [[X]], [[Y]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP2]], i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    ret i32 [[SEL]]
; CHECK:       else:
; CHECK-NEXT:    ret i32 0
;
entry:
  %cmp1 = icmp ult i32 %x, %y
  br i1 %cmp1, label %then, label %else

then:
  ; x < y unsigned, but we don't necessarily know x < y signed
  %cmp2 = icmp slt i32 %x, %y
  %sel = select i1 %cmp2, i32 %a, i32 %b
  ret i32 %sel

else:
  ret i32 0
}

; NEGATIVE: Select condition not implied by dominating constraints.
define i32 @select_cond_not_implied(i32 %x, i32 %y, i32 %a, i32 %b) {
; CHECK-LABEL: @select_cond_not_implied(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i32 [[X:%.*]], 10
; CHECK-NEXT:    br i1 [[CMP1]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[CMP2:%.*]] = icmp ult i32 [[Y:%.*]], 10
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP2]], i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    ret i32 [[SEL]]
; CHECK:       else:
; CHECK-NEXT:    ret i32 0
;
entry:
  %cmp1 = icmp ult i32 %x, 10
  br i1 %cmp1, label %then, label %else

then:
  %cmp2 = icmp ult i32 %y, 10
  %sel = select i1 %cmp2, i32 %a, i32 %b
  ret i32 %sel

else:
  ret i32 0
}

; NEGATIVE: No dominating constraints at all.
define i32 @select_no_constraints(i32 %x, i32 %y, i32 %a, i32 %b) {
; CHECK-LABEL: @select_no_constraints(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    ret i32 [[SEL]]
;
entry:
  %cmp = icmp ult i32 %x, %y
  %sel = select i1 %cmp, i32 %a, i32 %b
  ret i32 %sel
}

; Select in loop body with loop invariant condition.
define i32 @select_in_loop(i32 %n, i32 %a, i32 %b) {
; CHECK-LABEL: @select_in_loop(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_ENTRY:%.*]] = icmp sgt i32 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_ENTRY]], label [[LOOP:%.*]], label [[EXIT:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[CMP_LOOP:%.*]] = icmp slt i32 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP_LOOP]], label [[LOOP]], label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[RES:%.*]] = phi i32 [ 0, [[ENTRY]] ], [ [[A:%.*]], [[LOOP]] ]
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  %cmp.entry = icmp sgt i32 %n, 0
  br i1 %cmp.entry, label %loop, label %exit

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %cmp.sel = icmp sgt i32 %n, 0
  %sel = select i1 %cmp.sel, i32 %a, i32 %b
  %i.next = add i32 %i, 1
  %cmp.loop = icmp slt i32 %i.next, %n
  br i1 %cmp.loop, label %loop, label %exit

exit:
  %res = phi i32 [ 0, %entry ], [ %sel, %loop ]
  ret i32 %res
}

; Select with pointer type operands.
define ptr @select_ptr_type(i32 %x, i32 %y, ptr %p, ptr %q) {
; CHECK-LABEL: @select_ptr_type(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    ret ptr [[P:%.*]]
; CHECK:       else:
; CHECK-NEXT:    ret ptr null
;
entry:
  %cmp1 = icmp ult i32 %x, %y
  br i1 %cmp1, label %then, label %else

then:
  %cmp2 = icmp ult i32 %x, %y
  %sel = select i1 %cmp2, ptr %p, ptr %q
  ret ptr %sel

else:
  ret ptr null
}

; Multiple selects with the same implied condition.
define i32 @select_multiple_same_cond(i32 %x, i32 %y, i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: @select_multiple_same_cond(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[THEN:%.*]], label [[ELSE:%.*]]
; CHECK:       then:
; CHECK-NEXT:    [[RES:%.*]] = add i32 [[A:%.*]], [[C:%.*]]
; CHECK-NEXT:    ret i32 [[RES]]
; CHECK:       else:
; CHECK-NEXT:    ret i32 0
;
entry:
  %cmp1 = icmp ult i32 %x, %y
  br i1 %cmp1, label %then, label %else

then:
  %cmp2 = icmp ult i32 %x, %y
  %sel1 = select i1 %cmp2, i32 %a, i32 %b
  %sel2 = select i1 %cmp2, i32 %c, i32 %d
  %res = add i32 %sel1, %sel2
  ret i32 %res

else:
  ret i32 0
}
