; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; srem with non-negative dividend and constant divisor: result >= 0.
define i1 @srem_nonneg_dividend_sge_zero(i32 noundef %x) {
; CHECK-LABEL: @srem_nonneg_dividend_sge_zero(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 7
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sge i32 %x, 0
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i32 %x, 7
  %v = icmp sge i32 %r, 0
  ret i1 %v

else:
  ret i1 false
}

; srem with non-negative dividend and constant divisor: result <= x.
define i1 @srem_nonneg_dividend_sle_dividend(i32 noundef %x) {
; CHECK-LABEL: @srem_nonneg_dividend_sle_dividend(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 7
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sge i32 %x, 0
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i32 %x, 7
  %v = icmp sle i32 %r, %x
  ret i1 %v

else:
  ret i1 false
}

; srem with non-negative dividend, constant divisor, and bound:
; result < bound when x < bound.
define i1 @srem_nonneg_dividend_slt_bound(i32 noundef %x, i32 noundef %bound) {
; CHECK-LABEL: @srem_nonneg_dividend_slt_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    [[CMP2:%.*]] = icmp slt i32 [[X]], [[BOUND:%.*]]
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[CMP1]], [[CMP2]]
; CHECK-NEXT:    br i1 [[AND]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 7
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp1 = icmp sge i32 %x, 0
  %cmp2 = icmp slt i32 %x, %bound
  %and = and i1 %cmp1, %cmp2
  br i1 %and, label %mid, label %else

mid:
  %r = srem i32 %x, 7
  %v = icmp slt i32 %r, %bound
  ret i1 %v

else:
  ret i1 false
}

; srem with constant divisor: result slt |n|.
define i1 @srem_const_divisor_slt(i32 noundef %x) {
; CHECK-LABEL: @srem_const_divisor_slt(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X:%.*]], 10
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = srem i32 %x, 10
  %v = icmp slt i32 %r, 10
  ret i1 %v
}

; srem with constant divisor: result sgt -|n|.
define i1 @srem_const_divisor_sgt_neg(i32 noundef %x) {
; CHECK-LABEL: @srem_const_divisor_sgt_neg(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X:%.*]], 10
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = srem i32 %x, 10
  %v = icmp sgt i32 %r, -10
  ret i1 %v
}

; srem with negative constant divisor: result bounded by |n|.
define i1 @srem_neg_const_divisor_slt(i32 noundef %x) {
; CHECK-LABEL: @srem_neg_const_divisor_slt(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X:%.*]], -7
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = srem i32 %x, -7
  %v = icmp slt i32 %r, 7
  ret i1 %v
}

; srem with negative constant divisor: result sgt -|n|.
define i1 @srem_neg_const_divisor_sgt_neg(i32 noundef %x) {
; CHECK-LABEL: @srem_neg_const_divisor_sgt_neg(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X:%.*]], -7
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = srem i32 %x, -7
  %v = icmp sgt i32 %r, -7
  ret i1 %v
}

; sdiv with non-negative dividend and constant positive divisor: result >= 0.
define i1 @sdiv_nonneg_both_sge_zero(i32 noundef %x) {
; CHECK-LABEL: @sdiv_nonneg_both_sge_zero(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP1]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = sdiv i32 [[X]], 3
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp1 = icmp sge i32 %x, 0
  br i1 %cmp1, label %mid, label %else

mid:
  %r = sdiv i32 %x, 3
  %v = icmp sge i32 %r, 0
  ret i1 %v

else:
  ret i1 false
}

; sdiv with non-negative dividend and constant positive divisor: result <= x.
define i1 @sdiv_nonneg_both_sle_dividend(i32 noundef %x) {
; CHECK-LABEL: @sdiv_nonneg_both_sle_dividend(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP1]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = sdiv i32 [[X]], 3
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp1 = icmp sge i32 %x, 0
  br i1 %cmp1, label %mid, label %else

mid:
  %r = sdiv i32 %x, 3
  %v = icmp sle i32 %r, %x
  ret i1 %v

else:
  ret i1 false
}

; sdiv with non-negative dividend and constant positive divisor, and bound:
; result < bound when x < bound.
define i1 @sdiv_nonneg_slt_bound(i32 noundef %x, i32 noundef %bound) {
; CHECK-LABEL: @sdiv_nonneg_slt_bound(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    [[CMP3:%.*]] = icmp slt i32 [[X]], [[BOUND:%.*]]
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[CMP1]], [[CMP3]]
; CHECK-NEXT:    br i1 [[AND]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = sdiv i32 [[X]], 3
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp1 = icmp sge i32 %x, 0
  %cmp3 = icmp slt i32 %x, %bound
  %and = and i1 %cmp1, %cmp3
  br i1 %and, label %mid, label %else

mid:
  %r = sdiv i32 %x, 3
  %v = icmp slt i32 %r, %bound
  ret i1 %v

else:
  ret i1 false
}

; NEGATIVE: srem with unknown dividend sign.
define i1 @srem_unknown_sign_cannot_prove_nonneg(i32 noundef %x, i32 noundef %n) {
; CHECK-LABEL: @srem_unknown_sign_cannot_prove_nonneg(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X:%.*]], [[N:%.*]]
; CHECK-NEXT:    [[V:%.*]] = icmp sge i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[V]]
;
entry:
  %r = srem i32 %x, %n
  %v = icmp sge i32 %r, 0
  ret i1 %v
}

; NEGATIVE: sdiv only dividend non-negative, divisor unknown.
define i1 @sdiv_only_dividend_nonneg(i32 noundef %x, i32 noundef %n) {
; CHECK-LABEL: @sdiv_only_dividend_nonneg(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sge i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = sdiv i32 [[X]], [[N:%.*]]
; CHECK-NEXT:    [[V:%.*]] = icmp sge i32 [[R]], 0
; CHECK-NEXT:    ret i1 [[V]]
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sge i32 %x, 0
  br i1 %cmp, label %mid, label %else

mid:
  %r = sdiv i32 %x, %n
  %v = icmp sge i32 %r, 0
  ret i1 %v

else:
  ret i1 false
}

; NEGATIVE: srem constant divisor, checking result >= divisor (always false for positive results).
define i1 @srem_const_divisor_not_sge(i32 noundef %x) {
; CHECK-LABEL: @srem_const_divisor_not_sge(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X:%.*]], 10
; CHECK-NEXT:    ret i1 false
;
entry:
  %r = srem i32 %x, 10
  %v = icmp sge i32 %r, 10
  ret i1 %v
}
