; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @llvm.trap()

; `xor X, -1` is `-1 - X` in the signed system, so `count + ~i` decomposes as
; `count - 1 - i`. With `0 <=s i <s count` that is `<s count`, so the check
; folds. InstCombine canonicalizes `sub (count - 1), i` into this shape, so it
; is the form reverse-iterating index expressions actually reach us in.
define void @not_decomposed_signed(i64 %count, i64 %i) {
; CHECK-LABEL: define void @not_decomposed_signed(
; CHECK-SAME: i64 [[COUNT:%.*]], i64 [[I:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[NN:%.*]] = icmp sgt i64 [[COUNT]], -1
; CHECK-NEXT:    br i1 [[NN]], label %[[C1:.*]], label %[[OUT:.*]]
; CHECK:       [[C1]]:
; CHECK-NEXT:    [[INN:%.*]] = icmp sgt i64 [[I]], -1
; CHECK-NEXT:    br i1 [[INN]], label %[[C2:.*]], label %[[OUT]]
; CHECK:       [[C2]]:
; CHECK-NEXT:    [[LT:%.*]] = icmp slt i64 [[I]], [[COUNT]]
; CHECK-NEXT:    br i1 [[LT]], label %[[C3:.*]], label %[[OUT]]
; CHECK:       [[C3]]:
; CHECK-NEXT:    [[NEG:%.*]] = xor i64 [[I]], -1
; CHECK-NEXT:    [[IDX:%.*]] = add nsw i64 [[COUNT]], [[NEG]]
; CHECK-NEXT:    br i1 true, label %[[OUT]], label %[[TRAP:.*]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       [[OUT]]:
; CHECK-NEXT:    ret void
;
entry:
  %nn = icmp sgt i64 %count, -1
  br i1 %nn, label %c1, label %out

c1:
  %inn = icmp sgt i64 %i, -1
  br i1 %inn, label %c2, label %out

c2:
  %lt = icmp slt i64 %i, %count
  br i1 %lt, label %c3, label %out

c3:
  %neg = xor i64 %i, -1
  %idx = add nsw i64 %count, %neg
  %ok = icmp slt i64 %idx, %count
  br i1 %ok, label %out, label %trap

trap:
  call void @llvm.trap()
  unreachable

out:
  ret void
}

; Negative test: the decomposition is only valid in the signed system. Read as
; an unsigned value the complement is `2^bw - 1 - X`, so with %x == 0 we have
; `~%x == 0xFFFFFFFFFFFFFFFF`, which is not `u< 5`. This must not fold.
define void @not_decomposed_unsigned(i64 %x) {
; CHECK-LABEL: define void @not_decomposed_unsigned(
; CHECK-SAME: i64 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[Z:%.*]] = icmp eq i64 [[X]], 0
; CHECK-NEXT:    br i1 [[Z]], label %[[C:.*]], label %[[OUT:.*]]
; CHECK:       [[C]]:
; CHECK-NEXT:    [[N:%.*]] = xor i64 [[X]], -1
; CHECK-NEXT:    [[OK:%.*]] = icmp ult i64 [[N]], 5
; CHECK-NEXT:    br i1 [[OK]], label %[[BAD:.*]], label %[[OUT]]
; CHECK:       [[BAD]]:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       [[OUT]]:
; CHECK-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %x, 0
  br i1 %z, label %c, label %out

c:
  %n = xor i64 %x, -1
  %ok = icmp ult i64 %n, 5
  br i1 %ok, label %bad, label %out

bad:
  call void @llvm.trap()
  unreachable

out:
  ret void
}
