; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=indvars %s | FileCheck %s

; ScalarEvolution uses @llvm.assume on a function Argument to tighten the
; range of the corresponding SCEVUnknown (see
; test/Analysis/ScalarEvolution/range-from-assume-on-argument.ll). As a knock-on
; effect, IndVarSimplify can emit <nuw><nsw> on %iv.next and 'samesign' on the
; latch icmp for both @count_sum_arg and @count_sum_load.

declare void @llvm.assume(i1)

define i64 @count_sum_arg(i32 %n, ptr %p) {
; CHECK-LABEL: define i64 @count_sum_arg(
; CHECK-SAME: i32 [[N:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[N]], 16
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[SUM:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[SUM_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_EXT:%.*]] = zext i32 [[IV]] to i64
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i64, ptr [[P]], i64 [[IV_EXT]]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[GEP]], align 4
; CHECK-NEXT:    [[SUM_NEXT]] = add i64 [[SUM]], [[V]]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SUM_NEXT_LCSSA:%.*]] = phi i64 [ [[SUM_NEXT]], %[[LOOP]] ]
; CHECK-NEXT:    ret i64 [[SUM_NEXT_LCSSA]]
;
entry:
  %c = icmp ult i32 %n, 16
  call void @llvm.assume(i1 %c)
  br label %loop

loop:
  %iv = phi i32 [0, %entry], [%iv.next, %loop]
  %sum = phi i64 [0, %entry], [%sum.next, %loop]
  %iv.ext = zext i32 %iv to i64
  %gep = getelementptr i64, ptr %p, i64 %iv.ext
  %v = load i64, ptr %gep
  %sum.next = add i64 %sum, %v
  %iv.next = add i32 %iv, 1
  %cmp = icmp ult i32 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret i64 %sum.next
}

define i64 @count_sum_load(ptr %np, ptr %p) {
; CHECK-LABEL: define i64 @count_sum_load(
; CHECK-SAME: ptr [[NP:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[N:%.*]] = load i32, ptr [[NP]], align 4
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[N]], 16
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[SUM:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[SUM_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_EXT:%.*]] = zext i32 [[IV]] to i64
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i64, ptr [[P]], i64 [[IV_EXT]]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[GEP]], align 4
; CHECK-NEXT:    [[SUM_NEXT]] = add i64 [[SUM]], [[V]]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SUM_NEXT_LCSSA:%.*]] = phi i64 [ [[SUM_NEXT]], %[[LOOP]] ]
; CHECK-NEXT:    ret i64 [[SUM_NEXT_LCSSA]]
;
entry:
  %n = load i32, ptr %np
  %c = icmp ult i32 %n, 16
  call void @llvm.assume(i1 %c)
  br label %loop

loop:
  %iv = phi i32 [0, %entry], [%iv.next, %loop]
  %sum = phi i64 [0, %entry], [%sum.next, %loop]
  %iv.ext = zext i32 %iv to i64
  %gep = getelementptr i64, ptr %p, i64 %iv.ext
  %v = load i64, ptr %gep
  %sum.next = add i64 %sum, %v
  %iv.next = add i32 %iv, 1
  %cmp = icmp ult i32 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret i64 %sum.next
}
