; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes='loop-mssa(indvars)' < %s | FileCheck %s --check-prefixes=INDVARS
; RUN: opt -S -passes='loop-mssa(indvars,simple-loop-unswitch<no-nontrivial;trivial>)' < %s | FileCheck %s --check-prefixes=UNSWITCH

; makeIVComparisonInvariant rewrites %neg to a loop-invariant compare and asks
; for an extra SimpleLoopUnswitch run. That run only unswitches conditions
; defined outside the loop, so the compare has to be left in the preheader for
; the request to have any effect.

declare void @llvm.trap() cold noreturn nounwind

define i64 @scan(ptr readonly %data, i64 %count, i64 %start) {
; INDVARS-LABEL: @scan(
; INDVARS-NEXT:  entry:
; INDVARS-NEXT:    [[ENTRY_COND:%.*]] = icmp slt i64 [[START:%.*]], [[COUNT:%.*]]
; INDVARS-NEXT:    br i1 [[ENTRY_COND]], label [[PH:%.*]], label [[EXIT:%.*]]
; INDVARS:       ph:
; INDVARS-NEXT:    [[NEG:%.*]] = icmp slt i64 [[START]], 0
; INDVARS-NEXT:    br label [[LOOP:%.*]]
; INDVARS:       loop:
; INDVARS-NEXT:    [[IV:%.*]] = phi i64 [ [[START]], [[PH]] ], [ [[IV_NEXT:%.*]], [[LATCH:%.*]] ]
; INDVARS-NEXT:    br i1 [[NEG]], label [[TRAP:%.*]], label [[BODY:%.*]]
; INDVARS:       trap:
; INDVARS-NEXT:    call void @llvm.trap()
; INDVARS-NEXT:    unreachable
; INDVARS:       body:
; INDVARS-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i8, ptr [[DATA:%.*]], i64 [[IV]]
; INDVARS-NEXT:    [[LD:%.*]] = load i8, ptr [[GEP]], align 1
; INDVARS-NEXT:    [[FOUND:%.*]] = icmp eq i8 [[LD]], 60
; INDVARS-NEXT:    br i1 [[FOUND]], label [[EXIT_LOOPEXIT:%.*]], label [[LATCH]]
; INDVARS:       latch:
; INDVARS-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 1
; INDVARS-NEXT:    [[CONT:%.*]] = icmp ne i64 [[IV_NEXT]], [[COUNT]]
; INDVARS-NEXT:    br i1 [[CONT]], label [[LOOP]], label [[EXIT_LOOPEXIT]]
; INDVARS:       exit.loopexit:
; INDVARS-NEXT:    [[LCSSA:%.*]] = phi i64 [ [[IV]], [[BODY]] ], [ [[COUNT]], [[LATCH]] ]
; INDVARS-NEXT:    br label [[EXIT]]
; INDVARS:       exit:
; INDVARS-NEXT:    [[RES:%.*]] = phi i64 [ [[START]], [[ENTRY:%.*]] ], [ [[LCSSA]], [[EXIT_LOOPEXIT]] ]
; INDVARS-NEXT:    ret i64 [[RES]]
;
; UNSWITCH-LABEL: @scan(
; UNSWITCH-NEXT:  entry:
; UNSWITCH-NEXT:    [[ENTRY_COND:%.*]] = icmp slt i64 [[START:%.*]], [[COUNT:%.*]]
; UNSWITCH-NEXT:    br i1 [[ENTRY_COND]], label [[PH:%.*]], label [[EXIT:%.*]]
; UNSWITCH:       ph:
; UNSWITCH-NEXT:    [[NEG:%.*]] = icmp slt i64 [[START]], 0
; UNSWITCH-NEXT:    br i1 [[NEG]], label [[TRAP:%.*]], label [[PH_SPLIT:%.*]]
; UNSWITCH:       ph.split:
; UNSWITCH-NEXT:    br label [[LOOP:%.*]]
; UNSWITCH:       loop:
; UNSWITCH-NEXT:    [[IV:%.*]] = phi i64 [ [[START]], [[PH_SPLIT]] ], [ [[IV_NEXT:%.*]], [[LATCH:%.*]] ]
; UNSWITCH-NEXT:    br label [[BODY:%.*]]
; UNSWITCH:       trap:
; UNSWITCH-NEXT:    call void @llvm.trap()
; UNSWITCH-NEXT:    unreachable
; UNSWITCH:       body:
; UNSWITCH-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i8, ptr [[DATA:%.*]], i64 [[IV]]
; UNSWITCH-NEXT:    [[LD:%.*]] = load i8, ptr [[GEP]], align 1
; UNSWITCH-NEXT:    [[FOUND:%.*]] = icmp eq i8 [[LD]], 60
; UNSWITCH-NEXT:    br i1 [[FOUND]], label [[EXIT_LOOPEXIT:%.*]], label [[LATCH]]
; UNSWITCH:       latch:
; UNSWITCH-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 1
; UNSWITCH-NEXT:    [[CONT:%.*]] = icmp ne i64 [[IV_NEXT]], [[COUNT]]
; UNSWITCH-NEXT:    br i1 [[CONT]], label [[LOOP]], label [[EXIT_LOOPEXIT]]
; UNSWITCH:       exit.loopexit:
; UNSWITCH-NEXT:    [[LCSSA:%.*]] = phi i64 [ [[IV]], [[BODY]] ], [ [[COUNT]], [[LATCH]] ]
; UNSWITCH-NEXT:    br label [[EXIT]]
; UNSWITCH:       exit:
; UNSWITCH-NEXT:    [[RES:%.*]] = phi i64 [ [[START]], [[ENTRY:%.*]] ], [ [[LCSSA]], [[EXIT_LOOPEXIT]] ]
; UNSWITCH-NEXT:    ret i64 [[RES]]
;
entry:
  %entry.cond = icmp slt i64 %start, %count
  br i1 %entry.cond, label %ph, label %exit

ph:
  br label %loop

loop:
  %iv = phi i64 [ %start, %ph ], [ %iv.next, %latch ]
  %neg = icmp slt i64 %iv, 0
  br i1 %neg, label %trap, label %body

trap:
  call void @llvm.trap()
  unreachable

body:
  %gep = getelementptr inbounds nuw i8, ptr %data, i64 %iv
  %ld = load i8, ptr %gep, align 1
  %found = icmp eq i8 %ld, 60
  br i1 %found, label %exit.loopexit, label %latch

latch:
  %iv.next = add nsw i64 %iv, 1
  %cont = icmp ne i64 %iv.next, %count
  br i1 %cont, label %loop, label %exit.loopexit

exit.loopexit:
  %lcssa = phi i64 [ %iv, %body ], [ %count, %latch ]
  br label %exit

exit:
  %res = phi i64 [ %start, %entry ], [ %lcssa, %exit.loopexit ]
  ret i64 %res
}
