; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='loop(loop-unroll-full,indvars)' < %s 2>/dev/null | FileCheck %s
;
; Regression test: fully unrolling (and deleting) %inner leaves the outer-loop
; addrec for %idx = {{0,+,1}<%outer>,+,1}<%inner> referencing the deleted loop.
; When %outer's backedge-taken count is computed, re-inferring nowrap flags for
; its addrecs must not analyze the deleted %inner loop.

@g = constant [8 x i32] zeroinitializer

declare void @use(i32)

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    br i1 false, label %[[INNER]], label %[[OUTER_LATCH:.*]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[OUTER_LATCH]]:
; CHECK-NEXT:    call void @use(i32 0)
; CHECK-NEXT:    br label %[[INNER_1:.*]]
; CHECK:       [[INNER_1]]:
; CHECK-NEXT:    br i1 false, label %[[INNER_1]], label %[[OUTER_LATCH_1:.*]], !llvm.loop [[LOOP0]]
; CHECK:       [[OUTER_LATCH_1]]:
; CHECK-NEXT:    call void @use(i32 0)
; CHECK-NEXT:    ret void
;
entry:
  br label %outer

outer:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %outer.latch ]
  %iv.next = add i64 %iv, 1
  br label %inner

inner:
  %iv2 = phi i64 [ 0, %outer ], [ %iv2.next, %inner ]
  %iv2.next = add i64 %iv2, 1
  %idx = add i64 %iv, %iv2
  %gep = getelementptr i32, ptr @g, i64 %idx
  %load = load i32, ptr %gep
  %cmp2 = icmp ne i64 %iv2, 3
  br i1 %cmp2, label %inner, label %outer.latch, !llvm.loop !0

outer.latch:
  call void @use(i32 %load)
  %cmp = icmp ne i64 %iv, 1
  br i1 %cmp, label %outer, label %exit

exit:
  ret void
}

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.unroll.disable", i1 true}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.unroll.disable", i1 true}
;.
