; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -enable-cost-based-tail-folding -S %s | FileCheck %s
;
; Test that cost-based tail folding does not crash when loops have interleave
; groups with gaps that require a scalar epilogue.
;
; Reviewer C identified a potential assertion in materializeVectorTripCount:
;   assert(!TailByMasking && "requiring scalar epilogue is not supported
;          with tail folding")
; This could trigger if a tail-folded plan is selected AND the primary CM's
; interleave groups have gaps requiring a scalar epilogue. The scenario:
;   1. useMaskedInterleavedAccesses(TTI) returns true (AArch64+SVE)
;   2. Interleave groups with gaps are NOT invalidated
;   3. CanBuildTailFoldedPlans is true (due to useMaskedInterleavedAccesses)
;   4. InterleaveInfo.requiresScalarEpilogue() is true (load group, last member missing)
;   5. If the tail-folded plan were selected, executePlan would pass
;      IsTailFolded=true AND CM.requiresScalarEpilogue()=true to
;      materializeVectorTripCount, hitting the assertion.
;
; Currently, the tail-folded plan's cost is always higher for loops with
; interleave group gaps (due to masking overhead), so the assertion is not
; triggered. This test verifies the code path works without crashing and
; serves as a regression test if cost numbers ever change.

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-linux-gnu"

; Stride-4 LOADS using [4 x i32] GEP, reading members 0 and 1.
; Gap at members 2 and 3. The LAST member (3) is missing, so
; InterleaveGroup::requiresScalarEpilogue() returns true.
; With SVE, useMaskedInterleavedAccesses returns true, so the groups are NOT
; invalidated and CanBuildTailFoldedPlans can be true.
; Trip count 100 is large enough for epilogue vectorization to be allowed.
;
define void @interleave_load_gap_tc100(ptr noalias %dst, ptr noalias %src) #0 {
; CHECK-LABEL: define void @interleave_load_gap_tc100(
; CHECK-SAME: ptr noalias [[DST:%.*]], ptr noalias [[SRC:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 100, [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[N_MOD_VF]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = select i1 [[TMP2]], i64 [[TMP1]], i64 [[N_MOD_VF]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 100, [[TMP3]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [4 x i32], ptr [[SRC]], i64 [[INDEX]], i64 0
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <vscale x 16 x i32>, ptr [[TMP4]], align 4
; CHECK-NEXT:    [[STRIDED_VEC:%.*]] = call { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32> } @llvm.vector.deinterleave4.nxv16i32(<vscale x 16 x i32> [[WIDE_VEC]])
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32> } [[STRIDED_VEC]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32> } [[STRIDED_VEC]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = add <vscale x 4 x i32> [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 4 x i32> [[TMP7]], ptr [[TMP8]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP1]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP9]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[N_VEC]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds [4 x i32], ptr [[SRC]], i64 [[IV]], i64 0
; CHECK-NEXT:    [[LD0:%.*]] = load i32, ptr [[GEP0]], align 4
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [4 x i32], ptr [[SRC]], i64 [[IV]], i64 1
; CHECK-NEXT:    [[LD1:%.*]] = load i32, ptr [[GEP1]], align 4
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[LD0]], [[LD1]]
; CHECK-NEXT:    [[GEP_DST:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[IV]]
; CHECK-NEXT:    store i32 [[ADD]], ptr [[GEP_DST]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[IV_NEXT]], 100
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep0 = getelementptr inbounds [4 x i32], ptr %src, i64 %iv, i64 0
  %ld0 = load i32, ptr %gep0, align 4
  %gep1 = getelementptr inbounds [4 x i32], ptr %src, i64 %iv, i64 1
  %ld1 = load i32, ptr %gep1, align 4
  %add = add i32 %ld0, %ld1
  %gep.dst = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 %add, ptr %gep.dst, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 100
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

attributes #0 = { "target-features"="+sve" vscale_range(1,16) }
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
