; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -S %s | FileCheck --check-prefix=DEFAULT %s
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -enable-cost-based-tail-folding -S %s | FileCheck --check-prefix=COST-BASED %s

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-linux-gnu"

; Test that with -enable-cost-based-tail-folding, the vectorizer builds VPlans
; for both tail-folding and scalar epilogue, then picks the best based on cost.
; With a known trip count of 19 that does not divide evenly by VF, the cost of
; handling the scalar remainder makes tail folding cheaper, so the cost model
; selects tail folding with active lane masks.

define void @memset_tc19(ptr noalias %dst) #0 {
; DEFAULT-LABEL: define void @memset_tc19(
; DEFAULT-SAME: ptr noalias [[DST:%.*]]) #[[ATTR0:[0-9]+]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP1:%.*]] = shl nuw nsw i64 [[TMP0]], 2
; DEFAULT-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 19, [[TMP1]]
; DEFAULT-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; DEFAULT:       [[VECTOR_PH]]:
; DEFAULT-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 2
; DEFAULT-NEXT:    [[N_MOD_VF:%.*]] = urem i64 19, [[TMP3]]
; DEFAULT-NEXT:    [[N_VEC:%.*]] = sub i64 19, [[N_MOD_VF]]
; DEFAULT-NEXT:    br label %[[VECTOR_BODY:.*]]
; DEFAULT:       [[VECTOR_BODY]]:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; DEFAULT-NEXT:    store <vscale x 4 x i32> splat (i32 42), ptr [[TMP4]], align 4
; DEFAULT-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; DEFAULT-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; DEFAULT-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; DEFAULT:       [[MIDDLE_BLOCK]]:
; DEFAULT-NEXT:    [[CMP_N:%.*]] = icmp eq i64 19, [[N_VEC]]
; DEFAULT-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; DEFAULT:       [[SCALAR_PH]]:
; DEFAULT-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[IV]]
; DEFAULT-NEXT:    store i32 42, ptr [[GEP]], align 4
; DEFAULT-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; DEFAULT-NEXT:    [[CMP:%.*]] = icmp ult i64 [[IV_NEXT]], 19
; DEFAULT-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP3:![0-9]+]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; COST-BASED-LABEL: define void @memset_tc19(
; COST-BASED-SAME: ptr noalias [[DST:%.*]]) #[[ATTR0:[0-9]+]] {
; COST-BASED-NEXT:  [[ENTRY:.*:]]
; COST-BASED-NEXT:    br label %[[VECTOR_PH:.*]]
; COST-BASED:       [[VECTOR_PH]]:
; COST-BASED-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; COST-BASED-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; COST-BASED-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 19)
; COST-BASED-NEXT:    br label %[[VECTOR_BODY:.*]]
; COST-BASED:       [[VECTOR_BODY]]:
; COST-BASED-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; COST-BASED-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> splat (i32 42), ptr align 4 [[TMP2]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; COST-BASED-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; COST-BASED-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX_NEXT]], i64 19)
; COST-BASED-NEXT:    [[TMP3:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i32 0
; COST-BASED-NEXT:    [[TMP4:%.*]] = xor i1 [[TMP3]], true
; COST-BASED-NEXT:    br i1 [[TMP4]], label %[[SCALAR_PH:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; COST-BASED:       [[SCALAR_PH]]:
; COST-BASED-NEXT:    br label %[[LOOP:.*]]
; COST-BASED:       [[LOOP]]:
; COST-BASED-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 42, ptr %gep, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 19
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; With a variable trip count, tail folding is more expensive due to masking
; overhead, so the cost model correctly rejects it. DEFAULT and COST-BASED
; produce the same output.

define void @memset_variable_tc(ptr noalias %dst, i64 %n) #0 {
; DEFAULT-LABEL: define void @memset_variable_tc(
; DEFAULT-SAME: ptr noalias [[DST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP1:%.*]] = shl nuw nsw i64 [[TMP0]], 2
; DEFAULT-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMAX]], [[TMP1]]
; DEFAULT-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; DEFAULT:       [[VECTOR_PH]]:
; DEFAULT-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 2
; DEFAULT-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMAX]], [[TMP3]]
; DEFAULT-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMAX]], [[N_MOD_VF]]
; DEFAULT-NEXT:    br label %[[VECTOR_BODY:.*]]
; DEFAULT:       [[VECTOR_BODY]]:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; DEFAULT-NEXT:    store <vscale x 4 x i32> splat (i32 42), ptr [[TMP4]], align 4
; DEFAULT-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; DEFAULT-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; DEFAULT-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; DEFAULT:       [[MIDDLE_BLOCK]]:
; DEFAULT-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[UMAX]], [[N_VEC]]
; DEFAULT-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; DEFAULT:       [[SCALAR_PH]]:
; DEFAULT-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[IV]]
; DEFAULT-NEXT:    store i32 42, ptr [[GEP]], align 4
; DEFAULT-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; DEFAULT-NEXT:    [[CMP:%.*]] = icmp ult i64 [[IV_NEXT]], [[N]]
; DEFAULT-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP5:![0-9]+]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; COST-BASED-LABEL: define void @memset_variable_tc(
; COST-BASED-SAME: ptr noalias [[DST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; COST-BASED-NEXT:  [[ENTRY:.*]]:
; COST-BASED-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; COST-BASED-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; COST-BASED-NEXT:    [[TMP1:%.*]] = shl nuw nsw i64 [[TMP0]], 2
; COST-BASED-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[UMAX]], [[TMP1]]
; COST-BASED-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; COST-BASED:       [[VECTOR_PH]]:
; COST-BASED-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; COST-BASED-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 2
; COST-BASED-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[UMAX]], [[TMP3]]
; COST-BASED-NEXT:    [[N_VEC:%.*]] = sub i64 [[UMAX]], [[N_MOD_VF]]
; COST-BASED-NEXT:    br label %[[VECTOR_BODY:.*]]
; COST-BASED:       [[VECTOR_BODY]]:
; COST-BASED-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; COST-BASED-NEXT:    store <vscale x 4 x i32> splat (i32 42), ptr [[TMP4]], align 4
; COST-BASED-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; COST-BASED-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; COST-BASED-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; COST-BASED:       [[MIDDLE_BLOCK]]:
; COST-BASED-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[UMAX]], [[N_VEC]]
; COST-BASED-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; COST-BASED:       [[SCALAR_PH]]:
; COST-BASED-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; COST-BASED-NEXT:    br label %[[LOOP:.*]]
; COST-BASED:       [[LOOP]]:
; COST-BASED-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; COST-BASED-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[IV]]
; COST-BASED-NEXT:    store i32 42, ptr [[GEP]], align 4
; COST-BASED-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; COST-BASED-NEXT:    [[CMP:%.*]] = icmp ult i64 [[IV_NEXT]], [[N]]
; COST-BASED-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP4:![0-9]+]]
; COST-BASED:       [[EXIT]]:
; COST-BASED-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 42, ptr %gep, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Reduction with known trip count 17. The masking overhead for the reduction
; makes tail folding more expensive than a scalar epilogue, so both DEFAULT
; and COST-BASED use a scalar epilogue.
define i32 @reduction_tc17(ptr noalias %src) #0 {
; DEFAULT-LABEL: define i32 @reduction_tc17(
; DEFAULT-SAME: ptr noalias [[SRC:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP1:%.*]] = shl nuw nsw i64 [[TMP0]], 2
; DEFAULT-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 17, [[TMP1]]
; DEFAULT-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; DEFAULT:       [[VECTOR_PH]]:
; DEFAULT-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 2
; DEFAULT-NEXT:    [[N_MOD_VF:%.*]] = urem i64 17, [[TMP3]]
; DEFAULT-NEXT:    [[N_VEC:%.*]] = sub i64 17, [[N_MOD_VF]]
; DEFAULT-NEXT:    br label %[[VECTOR_BODY:.*]]
; DEFAULT:       [[VECTOR_BODY]]:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP5:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[INDEX]]
; DEFAULT-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP4]], align 4
; DEFAULT-NEXT:    [[TMP5]] = add <vscale x 4 x i32> [[VEC_PHI]], [[WIDE_LOAD]]
; DEFAULT-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; DEFAULT-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; DEFAULT-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; DEFAULT:       [[MIDDLE_BLOCK]]:
; DEFAULT-NEXT:    [[TMP7:%.*]] = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> [[TMP5]])
; DEFAULT-NEXT:    [[CMP_N:%.*]] = icmp eq i64 17, [[N_VEC]]
; DEFAULT-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; DEFAULT:       [[SCALAR_PH]]:
; DEFAULT-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; DEFAULT-NEXT:    [[BC_MERGE_RDX:%.*]] = phi i32 [ [[TMP7]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[SUM:%.*]] = phi i32 [ [[BC_MERGE_RDX]], %[[SCALAR_PH]] ], [ [[ADD:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[IV]]
; DEFAULT-NEXT:    [[LD:%.*]] = load i32, ptr [[GEP]], align 4
; DEFAULT-NEXT:    [[ADD]] = add nsw i32 [[SUM]], [[LD]]
; DEFAULT-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; DEFAULT-NEXT:    [[CMP:%.*]] = icmp ult i64 [[IV_NEXT]], 17
; DEFAULT-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP7:![0-9]+]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD]], %[[LOOP]] ], [ [[TMP7]], %[[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    ret i32 [[ADD_LCSSA]]
;
; COST-BASED-LABEL: define i32 @reduction_tc17(
; COST-BASED-SAME: ptr noalias [[SRC:%.*]]) #[[ATTR0]] {
; COST-BASED-NEXT:  [[ENTRY:.*]]:
; COST-BASED-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; COST-BASED-NEXT:    [[TMP1:%.*]] = shl nuw nsw i64 [[TMP0]], 2
; COST-BASED-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 17, [[TMP1]]
; COST-BASED-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; COST-BASED:       [[VECTOR_PH]]:
; COST-BASED-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; COST-BASED-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 2
; COST-BASED-NEXT:    [[N_MOD_VF:%.*]] = urem i64 17, [[TMP3]]
; COST-BASED-NEXT:    [[N_VEC:%.*]] = sub i64 17, [[N_MOD_VF]]
; COST-BASED-NEXT:    br label %[[VECTOR_BODY:.*]]
; COST-BASED:       [[VECTOR_BODY]]:
; COST-BASED-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP5:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[INDEX]]
; COST-BASED-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP4]], align 4
; COST-BASED-NEXT:    [[TMP5]] = add <vscale x 4 x i32> [[VEC_PHI]], [[WIDE_LOAD]]
; COST-BASED-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; COST-BASED-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; COST-BASED-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; COST-BASED:       [[MIDDLE_BLOCK]]:
; COST-BASED-NEXT:    [[TMP7:%.*]] = call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> [[TMP5]])
; COST-BASED-NEXT:    [[CMP_N:%.*]] = icmp eq i64 17, [[N_VEC]]
; COST-BASED-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; COST-BASED:       [[SCALAR_PH]]:
; COST-BASED-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; COST-BASED-NEXT:    [[BC_MERGE_RDX:%.*]] = phi i32 [ [[TMP7]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; COST-BASED-NEXT:    br label %[[LOOP:.*]]
; COST-BASED:       [[LOOP]]:
; COST-BASED-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; COST-BASED-NEXT:    [[SUM:%.*]] = phi i32 [ [[BC_MERGE_RDX]], %[[SCALAR_PH]] ], [ [[ADD:%.*]], %[[LOOP]] ]
; COST-BASED-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[IV]]
; COST-BASED-NEXT:    [[LD:%.*]] = load i32, ptr [[GEP]], align 4
; COST-BASED-NEXT:    [[ADD]] = add nsw i32 [[SUM]], [[LD]]
; COST-BASED-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; COST-BASED-NEXT:    [[CMP:%.*]] = icmp ult i64 [[IV_NEXT]], 17
; COST-BASED-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP6:![0-9]+]]
; COST-BASED:       [[EXIT]]:
; COST-BASED-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD]], %[[LOOP]] ], [ [[TMP7]], %[[MIDDLE_BLOCK]] ]
; COST-BASED-NEXT:    ret i32 [[ADD_LCSSA]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %sum = phi i32 [ 0, %entry ], [ %add, %loop ]
  %gep = getelementptr inbounds i32, ptr %src, i64 %iv
  %ld = load i32, ptr %gep, align 4
  %add = add nsw i32 %sum, %ld
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 17
  br i1 %cmp, label %loop, label %exit

exit:
  ret i32 %add
}

; Trip count known to be a multiple of typical VFs (64). Both DEFAULT and
; COST-BASED use a scalar epilogue; tail folding adds unnecessary masking when
; there is no remainder.
define void @memset_tc64(ptr noalias %dst) #0 {
; DEFAULT-LABEL: define void @memset_tc64(
; DEFAULT-SAME: ptr noalias [[DST:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[VECTOR_PH:.*]]
; DEFAULT:       [[VECTOR_PH]]:
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; DEFAULT-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP1]]
; DEFAULT-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; DEFAULT-NEXT:    br label %[[VECTOR_BODY:.*]]
; DEFAULT:       [[VECTOR_BODY]]:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; DEFAULT-NEXT:    store <vscale x 4 x i32> splat (i32 42), ptr [[TMP2]], align 4
; DEFAULT-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP1]]
; DEFAULT-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; DEFAULT-NEXT:    br i1 [[TMP3]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; DEFAULT:       [[MIDDLE_BLOCK]]:
; DEFAULT-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; DEFAULT-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH:.*]]
; DEFAULT:       [[SCALAR_PH]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[IV:%.*]] = phi i64 [ [[N_VEC]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[IV]]
; DEFAULT-NEXT:    store i32 42, ptr [[GEP]], align 4
; DEFAULT-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; DEFAULT-NEXT:    [[CMP:%.*]] = icmp ult i64 [[IV_NEXT]], 64
; DEFAULT-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP9:![0-9]+]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; COST-BASED-LABEL: define void @memset_tc64(
; COST-BASED-SAME: ptr noalias [[DST:%.*]]) #[[ATTR0]] {
; COST-BASED-NEXT:  [[ENTRY:.*:]]
; COST-BASED-NEXT:    br label %[[VECTOR_PH:.*]]
; COST-BASED:       [[VECTOR_PH]]:
; COST-BASED-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; COST-BASED-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; COST-BASED-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP1]]
; COST-BASED-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; COST-BASED-NEXT:    br label %[[VECTOR_BODY:.*]]
; COST-BASED:       [[VECTOR_BODY]]:
; COST-BASED-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; COST-BASED-NEXT:    store <vscale x 4 x i32> splat (i32 42), ptr [[TMP2]], align 4
; COST-BASED-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP1]]
; COST-BASED-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; COST-BASED-NEXT:    br i1 [[TMP3]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; COST-BASED:       [[MIDDLE_BLOCK]]:
; COST-BASED-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; COST-BASED-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH:.*]]
; COST-BASED:       [[SCALAR_PH]]:
; COST-BASED-NEXT:    br label %[[LOOP:.*]]
; COST-BASED:       [[LOOP]]:
; COST-BASED-NEXT:    [[IV:%.*]] = phi i64 [ [[N_VEC]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; COST-BASED-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[IV]]
; COST-BASED-NEXT:    store i32 42, ptr [[GEP]], align 4
; COST-BASED-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; COST-BASED-NEXT:    [[CMP:%.*]] = icmp ult i64 [[IV_NEXT]], 64
; COST-BASED-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP8:![0-9]+]]
; COST-BASED:       [[EXIT]]:
; COST-BASED-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 42, ptr %gep, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 64
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Loop with both a load and a store and trip count 13. The default SVE
; configuration already selects tail folding with active lane masks for this
; pattern, so COST-BASED produces the same result.
define void @load_store_tc13(ptr noalias %dst, ptr noalias %src) #0 {
; DEFAULT-LABEL: define void @load_store_tc13(
; DEFAULT-SAME: ptr noalias [[DST:%.*]], ptr noalias [[SRC:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[VECTOR_PH:.*]]
; DEFAULT:       [[VECTOR_PH]]:
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; DEFAULT-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 13)
; DEFAULT-NEXT:    br label %[[VECTOR_BODY:.*]]
; DEFAULT:       [[VECTOR_BODY]]:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[INDEX]]
; DEFAULT-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP2]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i32> poison)
; DEFAULT-NEXT:    [[TMP3:%.*]] = mul nsw <vscale x 4 x i32> [[WIDE_MASKED_LOAD]], splat (i32 3)
; DEFAULT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; DEFAULT-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP3]], ptr align 4 [[TMP4]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; DEFAULT-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; DEFAULT-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX_NEXT]], i64 13)
; DEFAULT-NEXT:    [[TMP5:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i32 0
; DEFAULT-NEXT:    [[TMP6:%.*]] = xor i1 [[TMP5]], true
; DEFAULT-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
; DEFAULT:       [[MIDDLE_BLOCK]]:
; DEFAULT-NEXT:    br label %[[EXIT:.*]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; COST-BASED-LABEL: define void @load_store_tc13(
; COST-BASED-SAME: ptr noalias [[DST:%.*]], ptr noalias [[SRC:%.*]]) #[[ATTR0]] {
; COST-BASED-NEXT:  [[ENTRY:.*:]]
; COST-BASED-NEXT:    br label %[[VECTOR_PH:.*]]
; COST-BASED:       [[VECTOR_PH]]:
; COST-BASED-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; COST-BASED-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; COST-BASED-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 13)
; COST-BASED-NEXT:    br label %[[VECTOR_BODY:.*]]
; COST-BASED:       [[VECTOR_BODY]]:
; COST-BASED-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[INDEX]]
; COST-BASED-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP2]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i32> poison)
; COST-BASED-NEXT:    [[TMP3:%.*]] = mul nsw <vscale x 4 x i32> [[WIDE_MASKED_LOAD]], splat (i32 3)
; COST-BASED-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; COST-BASED-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP3]], ptr align 4 [[TMP4]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; COST-BASED-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; COST-BASED-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX_NEXT]], i64 13)
; COST-BASED-NEXT:    [[TMP5:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i32 0
; COST-BASED-NEXT:    [[TMP6:%.*]] = xor i1 [[TMP5]], true
; COST-BASED-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; COST-BASED:       [[MIDDLE_BLOCK]]:
; COST-BASED-NEXT:    br label %[[EXIT:.*]]
; COST-BASED:       [[EXIT]]:
; COST-BASED-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.src = getelementptr inbounds i32, ptr %src, i64 %iv
  %ld = load i32, ptr %gep.src, align 4
  %mul = mul nsw i32 %ld, 3
  %gep.dst = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 %mul, ptr %gep.dst, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 13
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

attributes #0 = { "target-features"="+sve" vscale_range(1,16) }
;.
; DEFAULT: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; DEFAULT: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; DEFAULT: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; DEFAULT: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
; DEFAULT: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; DEFAULT: [[LOOP5]] = distinct !{[[LOOP5]], [[META2]], [[META1]]}
; DEFAULT: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]]}
; DEFAULT: [[LOOP7]] = distinct !{[[LOOP7]], [[META2]], [[META1]]}
; DEFAULT: [[LOOP8]] = distinct !{[[LOOP8]], [[META1]], [[META2]]}
; DEFAULT: [[LOOP9]] = distinct !{[[LOOP9]], [[META2]], [[META1]]}
; DEFAULT: [[LOOP10]] = distinct !{[[LOOP10]], [[META1]], [[META2]]}
;.
; COST-BASED: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; COST-BASED: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; COST-BASED: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; COST-BASED: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
; COST-BASED: [[LOOP4]] = distinct !{[[LOOP4]], [[META2]], [[META1]]}
; COST-BASED: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]], [[META2]]}
; COST-BASED: [[LOOP6]] = distinct !{[[LOOP6]], [[META2]], [[META1]]}
; COST-BASED: [[LOOP7]] = distinct !{[[LOOP7]], [[META1]], [[META2]]}
; COST-BASED: [[LOOP8]] = distinct !{[[LOOP8]], [[META2]], [[META1]]}
; COST-BASED: [[LOOP9]] = distinct !{[[LOOP9]], [[META1]], [[META2]]}
;.
