; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -S %s | FileCheck --check-prefix=DEFAULT %s
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -prefer-predicate-over-epilogue=scalar-epilogue -enable-cost-based-tail-folding -S %s | FileCheck --check-prefix=COST-BASED %s

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"
target triple = "riscv64-unknown-linux-gnu"

; Test that with -enable-cost-based-tail-folding on RISC-V (which prefers
; DataWithEVL by default), the vectorizer uses DataWithoutLaneMask for
; cost-based tail folding, never EVL. The DEFAULT run shows RISC-V's natural
; EVL-based tail folding; the COST-BASED run forces a scalar-epilogue baseline
; and enables cost-based selection, which should pick active lane masks.

define void @memset_tc19(ptr noalias %dst) #0 {
; DEFAULT-LABEL: define void @memset_tc19(
; DEFAULT-SAME: ptr noalias [[DST:%.*]]) #[[ATTR0:[0-9]+]] {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[VECTOR_PH:.*]]
; DEFAULT:       [[VECTOR_PH]]:
; DEFAULT-NEXT:    br label %[[VECTOR_BODY:.*]]
; DEFAULT:       [[VECTOR_BODY]]:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[CURRENT_ITERATION_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[AVL:%.*]] = phi i64 [ 19, %[[VECTOR_PH]] ], [ [[AVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 4, i1 true)
; DEFAULT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; DEFAULT-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> splat (i32 42), ptr align 4 [[TMP4]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP0]] to i64
; DEFAULT-NEXT:    [[CURRENT_ITERATION_NEXT]] = add nuw i64 [[TMP2]], [[INDEX]]
; DEFAULT-NEXT:    [[AVL_NEXT]] = sub nuw i64 [[AVL]], [[TMP2]]
; DEFAULT-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[AVL_NEXT]], 0
; DEFAULT-NEXT:    br i1 [[TMP3]], label %[[SCALAR_PH:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; DEFAULT:       [[SCALAR_PH]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    ret void
;
; COST-BASED-LABEL: define void @memset_tc19(
; COST-BASED-SAME: ptr noalias [[DST:%.*]]) #[[ATTR0:[0-9]+]] {
; COST-BASED-NEXT:  [[ENTRY:.*:]]
; COST-BASED-NEXT:    br label %[[VECTOR_PH:.*]]
; COST-BASED:       [[VECTOR_PH]]:
; COST-BASED-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; COST-BASED-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; COST-BASED-NEXT:    [[TMP2:%.*]] = sub i64 [[TMP1]], 1
; COST-BASED-NEXT:    [[N_RND_UP:%.*]] = add i64 19, [[TMP2]]
; COST-BASED-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N_RND_UP]], [[TMP1]]
; COST-BASED-NEXT:    [[N_VEC:%.*]] = sub i64 [[N_RND_UP]], [[N_MOD_VF]]
; COST-BASED-NEXT:    br label %[[VECTOR_BODY:.*]]
; COST-BASED:       [[VECTOR_BODY]]:
; COST-BASED-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[INDEX]], i64 0
; COST-BASED-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; COST-BASED-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; COST-BASED-NEXT:    [[TMP4:%.*]] = add <vscale x 4 x i64> zeroinitializer, [[TMP3]]
; COST-BASED-NEXT:    [[VEC_IV:%.*]] = add <vscale x 4 x i64> [[BROADCAST_SPLAT]], [[TMP4]]
; COST-BASED-NEXT:    [[TMP5:%.*]] = icmp ule <vscale x 4 x i64> [[VEC_IV]], splat (i64 18)
; COST-BASED-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; COST-BASED-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> splat (i32 42), ptr align 4 [[TMP6]], <vscale x 4 x i1> [[TMP5]])
; COST-BASED-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP1]]
; COST-BASED-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; COST-BASED-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; COST-BASED:       [[MIDDLE_BLOCK]]:
; COST-BASED-NEXT:    br label %[[EXIT:.*]]
; COST-BASED:       [[EXIT]]:
; COST-BASED-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 42, ptr %gep, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, 19
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Variable trip count: DEFAULT uses EVL tail folding; COST-BASED uses
; DataWithoutLaneMask tail folding (lane masks, not EVL).

define void @memset_variable_tc(ptr noalias %dst, i64 %n) #0 {
; DEFAULT-LABEL: define void @memset_variable_tc(
; DEFAULT-SAME: ptr noalias [[DST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; DEFAULT-NEXT:    br label %[[VECTOR_PH:.*]]
; DEFAULT:       [[VECTOR_PH]]:
; DEFAULT-NEXT:    br label %[[VECTOR_BODY:.*]]
; DEFAULT:       [[VECTOR_BODY]]:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[CURRENT_ITERATION_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[AVL:%.*]] = phi i64 [ [[UMAX]], %[[VECTOR_PH]] ], [ [[AVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 4, i1 true)
; DEFAULT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; DEFAULT-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> splat (i32 42), ptr align 4 [[TMP4]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP0]] to i64
; DEFAULT-NEXT:    [[CURRENT_ITERATION_NEXT]] = add i64 [[TMP2]], [[INDEX]]
; DEFAULT-NEXT:    [[AVL_NEXT]] = sub nuw i64 [[AVL]], [[TMP2]]
; DEFAULT-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[AVL_NEXT]], 0
; DEFAULT-NEXT:    br i1 [[TMP3]], label %[[SCALAR_PH:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; DEFAULT:       [[SCALAR_PH]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    ret void
;
; COST-BASED-LABEL: define void @memset_variable_tc(
; COST-BASED-SAME: ptr noalias [[DST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; COST-BASED-NEXT:  [[ENTRY:.*:]]
; COST-BASED-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[N]], i64 1)
; COST-BASED-NEXT:    br label %[[VECTOR_PH:.*]]
; COST-BASED:       [[VECTOR_PH]]:
; COST-BASED-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; COST-BASED-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; COST-BASED-NEXT:    [[TMP2:%.*]] = sub i64 [[TMP1]], 1
; COST-BASED-NEXT:    [[N_RND_UP:%.*]] = add i64 [[UMAX]], [[TMP2]]
; COST-BASED-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N_RND_UP]], [[TMP1]]
; COST-BASED-NEXT:    [[N_VEC:%.*]] = sub i64 [[N_RND_UP]], [[N_MOD_VF]]
; COST-BASED-NEXT:    [[TRIP_COUNT_MINUS_1:%.*]] = sub i64 [[UMAX]], 1
; COST-BASED-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TRIP_COUNT_MINUS_1]], i64 0
; COST-BASED-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; COST-BASED-NEXT:    br label %[[VECTOR_BODY:.*]]
; COST-BASED:       [[VECTOR_BODY]]:
; COST-BASED-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; COST-BASED-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[INDEX]], i64 0
; COST-BASED-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT1]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; COST-BASED-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; COST-BASED-NEXT:    [[TMP4:%.*]] = add <vscale x 4 x i64> zeroinitializer, [[TMP3]]
; COST-BASED-NEXT:    [[VEC_IV:%.*]] = add <vscale x 4 x i64> [[BROADCAST_SPLAT2]], [[TMP4]]
; COST-BASED-NEXT:    [[TMP5:%.*]] = icmp ule <vscale x 4 x i64> [[VEC_IV]], [[BROADCAST_SPLAT]]
; COST-BASED-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; COST-BASED-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> splat (i32 42), ptr align 4 [[TMP6]], <vscale x 4 x i1> [[TMP5]])
; COST-BASED-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; COST-BASED-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; COST-BASED-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; COST-BASED:       [[MIDDLE_BLOCK]]:
; COST-BASED-NEXT:    br label %[[EXIT:.*]]
; COST-BASED:       [[EXIT]]:
; COST-BASED-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 42, ptr %gep, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %cmp = icmp ult i64 %iv.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

attributes #0 = { "target-features"="+v" vscale_range(2,1024) }
;.
; DEFAULT: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; DEFAULT: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; DEFAULT: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; DEFAULT: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
;.
; COST-BASED: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; COST-BASED: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; COST-BASED: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; COST-BASED: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
;.
